# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/build_repo_mirror.R
# build_repo_mirror.R — assemble WKBD_repo/, the GitHub-shaped mirror of Chapter 2 and Chapter 3.
#
# PJ, 17 Aug: "need to get to a set of files that mirror github - word doc, r scripts, data,
# figure and table. Needs a sep folder in WKBD - then a well ordered archive on folder and
# clear subfolders."
#
# ⭐ EXTENDED 14 Sep 2026: Chapter 3 finalized at v22 ("v22 is the final version, upload to git
# hub"). PJ confirmed (via AskUserQuestion) this means the data/code/appendix replication mirror,
# NOT the manuscript text — chapters/ stays gitignored, the repo is public. Chapter 3's SCRIPTS
# list is built dynamically (list.files) rather than hand-typed like Chapter 2's, because it has
# ~74 live scripts (vs Ch2's ~23) and hand-typing that many names is itself an error source; the
# dynamic list is filtered to exclude scripts/_superseded_12sep/ (dead scripts, same convention as
# the figures/_superseded_*/ folders already excluded by only ever pointing FIGS at current
# filenames).
#
# ⛔ COPIES ONLY. Nothing in the working tree is moved, renamed or deleted by this script.
#    Re-run it after any rebuild; it overwrites its own outputs and touches nothing else.
#
# ⚠ SCRIPTS ARE COPIED AS-IS and still carry the ABSOLUTE working-tree paths they were written
#   with. They therefore reproduce the figures on PJ's machine but not on a stranger's. Making
#   them path-portable is a separate job — see the "NOT YET DONE" section of WKBD_repo/README.md.
#   Do not let the tidy folder shape imply a portability that has not been built.

P    <- "/Users/pjair2026/Library/CloudStorage/Dropbox/Documents/Who Killed British Democracy?"
WS   <- file.path(P, "data_workspace_2026-07")
REPO <- file.path(P, "WKBD_repo")

for (d in c("manuscript","figures","tables","scripts","scripts/_helpers","data",
            "data/executive","data/electoral","data/public_opinion","data/parliament",
            "data/policy","data/nao","data/composite",
            "data/ch3_raw","data/ch3_processed","data/ch3_sources_raw",
            "tables/ch3_appendix","tables/ch2_appendix","tables/ch2_appendix/figures"))
  dir.create(file.path(REPO, d), recursive = TRUE, showWarnings = FALSE)

copied <- 0; missing <- character(0)
put <- function(src, dest_dir, rename = NULL) {
  if (!file.exists(src)) { missing <<- c(missing, src); return(invisible(FALSE)) }
  dst <- file.path(REPO, dest_dir, if (is.null(rename)) basename(src) else rename)
  file.copy(src, dst, overwrite = TRUE)
  copied <<- copied + 1; invisible(TRUE)
}

# ---------------------------------------------------------------- 1. FIGURES
# number, source path, repo filename. Source names were corrected 17 Aug, so these now agree.
FIGS <- list(
  c("2.1", "figures/fig_2_1_pm_tenure.png",                                            "Figure_2.1_pm_tenure_and_departure.png"),
  c("2.2", "figures/fig_2_2_great_officers_combined.png",                              "Figure_2.2_great_offices.png"),
  c("2.3", "figures/fig_2_3_cabinet_turnover.png",                                     "Figure_2.3_cabinet_turnover.png"),
  c("2.4", "figures/fig_2_4_executive_instability.png",                                "Figure_2.4_executive_instability.png"),
  c("2.5", "figures/fig_2_5_comparative_tenure.png",                                   "Figure_2.5_comparative_tenure.png"),
  c("2.6", "data_workspace_2026-07/allparty_review/figures/fig_2_6_electoral_volatility.png",   "Figure_2.6_electoral_volatility.png"),
  c("2.7", "data_workspace_2026-07/allparty_review/figures/fig_2_7_comparative_volatility.png", "Figure_2.7_comparative_volatility.png"),
  c("2.8", "data_workspace_2026-07/ch2_public_opinion/fig_2_8_public_agenda.png",       "Figure_2.8_public_agenda.png"),
  c("2.9", "data_workspace_2026-07/ch2_public_opinion/fig_2_9_unexpected_movements.png","Figure_2.9_unexpected_movements.png"),
  c("2.10","data_workspace_2026-07/parliamentary_dislocation/fig_2_10_parliamentary_instability.png","Figure_2.10_parliamentary_instability.png"),
  c("2.11","data_workspace_2026-07/policy_instability/figures/fig_2_11_policy_agenda.png","Figure_2.11_policy_agenda.png"),
  c("2.12","data_workspace_2026-07/machinery_churn/figures/fig_2_12_machinery_churn_1979_2025.png","Figure_2.12_machinery_churn.png"),
  c("2.13","figures/fig_2_13_nao_delivery_failure_1984_2025.png",                       "Figure_2.13_nao_delivery_failure.png"),
  c("2.14","figures/fig_2_14_external_validation.png",                                  "Figure_2.14_external_validation.png"),
  c("2.15","figures/fig_2_15_uturns_1979_2025.png",                                     "Figure_2.15_uturns.png"),
  c("2.16","data_workspace_2026-07/composite_canonical/figures/fig_2_16_turbulence_index_1979_2025.png","Figure_2.16_turbulence_index.png"),
  c("2.17","data_workspace_2026-07/ch2_public_opinion/fig_2_17_attribution_slopes.png","Figure_2.17_attribution_slopes.png")
)
for (f in FIGS) put(file.path(P, f[2]), "figures", f[3])

# ---------------------------------------------------------------- 2. SCRIPTS
# ⚠ Filenames are kept EXACTLY as in the working tree, deliberately. Renaming them here would
#   create a third naming system on top of the two we have just finished reconciling. MANIFEST.csv
#   is what maps figure number -> script.
SCRIPTS <- c(
  "scripts/01_pm_turnover.R",
  # "scripts/02_great_officers.R" — REMOVED 29 Aug 2026: the with-Chow original superseded by
  # 02b below on 17 Aug, but left uncopied here until now (finding #3 of the reorg plan — the
  # live "two scripts per figure" problem). Archived to _ARCHIVE/scripts/, see RESTORE_MAP.csv.
  "scripts/02b_great_officers_combined_figure.R",
  "scripts/03_cabinet_turnover.R",
  "scripts/04_executive_instability.R",
  "scripts/05_comparative_turnover.R",
  "scripts/01e_table_2_1.R",
  "data_workspace_2026-07/allparty_review/build_fig_2_6_electoral_volatility.R",
  "data_workspace_2026-07/allparty_review/build_fig_2_7_comparative_volatility.R",
  "data_workspace_2026-07/ch2_public_opinion/29_fig_agenda_no_pca.R",
  "data_workspace_2026-07/ch2_public_opinion/35_fig_expected_movements.R",
  "data_workspace_2026-07/parliamentary_dislocation/10_three_panel_summary.R",
  "data_workspace_2026-07/parliamentary_dislocation/17_lords_official_rebuild.R",
  "data_workspace_2026-07/policy_instability/diagnostics/build_divergence_punctuation.R",
  "data_workspace_2026-07/machinery_churn/build_fig_2_12_machinery_churn.R",
  "data_workspace_2026-07/nao_extension/diagnostics/build_fig_2_13_nao.R",
  "data_workspace_2026-07/policy_failure/vdem_wgi/build_fig_2_14_external_validation.R",
  "data_workspace_2026-07/policy_instability/uturns/build_fig_2_15_uturns.R",
  "data_workspace_2026-07/composite_canonical/build_fig_2_16_turbulence_index.R",
  "data_workspace_2026-07/ch2_public_opinion/40_fig_attribution_slopes.R",
  "data_workspace_2026-07/composite_canonical/build_canonical_composite.R",
  "data_workspace_2026-07/nonlinear_modelling/chapter_wide_race.R",
  "data_workspace_2026-07/nonlinear_modelling/horse_race.R",
  "data_workspace_2026-07/nonlinear_modelling/full_model_comparison.R"
)
for (s in SCRIPTS) put(file.path(P, s), "scripts")

HELPERS <- c("data_workspace_2026-07/chow_standardized/chow_test.R",
             "data_workspace_2026-07/figure_house_theme.R",
             "data_workspace_2026-07/collect_ch2_figures.R",
             "data_workspace_2026-07/build_repo_mirror.R")
for (h in HELPERS) put(file.path(P, h), "scripts/_helpers")

# ---------------------------------------------------------------- 2b. BANNERS
# Stamps every mirrored script with a one-line header so it is unmistakable, even read out of
# context, that this file is a COPY and where the real working copy lives. Wired in here (not
# applied once by hand) so the banner survives every regeneration automatically, and re-stamps
# in place rather than duplicating if a banner from a prior run is already there. 29 Aug 2026,
# part of the live/exploratory reorg — see 00_LIVE_VS_EXPLORATORY.md.
banner_stamp <- function(rel_src, dest_dir) {
  dst <- file.path(REPO, dest_dir, basename(rel_src))
  if (!file.exists(dst)) return(invisible(FALSE))
  txt <- readLines(dst, warn = FALSE)
  banner <- sprintf("# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: %s", rel_src)
  if (length(txt) > 0 && startsWith(txt[1], "# COPY — generated by build_repo_mirror.R")) {
    txt[1] <- banner
  } else {
    txt <- c(banner, txt)
  }
  writeLines(txt, dst)
}
for (s in SCRIPTS) banner_stamp(s, "scripts")
for (h in HELPERS) banner_stamp(h, "scripts/_helpers")

# ---------------------------------------------------------------- 2c. PRUNE STALE COPIES
# ⚠ file.copy(overwrite=TRUE) only ever ADDS or UPDATES — a script dropped from SCRIPTS/HELPERS
#   (e.g. an archived original) is never removed from a prior run's WKBD_repo/ output, and sits
#   there as an orphan indefinitely. Caught 29 Aug 2026 when scripts/02_great_officers.R was
#   archived but its stale mirror copy kept reappearing after every rebuild. Safe to prune: this
#   only ever deletes inside WKBD_repo/, which is 100% regenerated copies, never the working tree.
prune_stale <- function(dest_dir, expected_srcs) {
  expected <- basename(expected_srcs)
  present  <- list.files(file.path(REPO, dest_dir), pattern = "\\.R$")
  stale    <- setdiff(present, expected)
  for (f in stale) {
    file.remove(file.path(REPO, dest_dir, f))
    cat(sprintf("⚠ pruned stale mirror copy: %s/%s (no longer in SCRIPTS/HELPERS)\n", dest_dir, f))
  }
}
# ⚠ 14 Sep 2026: prune_stale("scripts", ...) moved to AFTER the Chapter 3 section below (it now
#   prunes against SCRIPTS ∪ SCRIPTS3) — calling it here, before Ch3's ~74 scripts are copied in,
#   would flag every one of them as "stale" and delete-then-recreate them on every single run
#   (harmless to the end state, since section 3.2 re-adds them, but noisy and misleading output).
prune_stale("scripts/_helpers", HELPERS)

# ---------------------------------------------------------------- 3. DATA
D <- list(
  executive = c("data/processed/pm_tenure.csv",
                "data/processed/great_officers.csv",
                "data/processed/great_officers_annual_departures.csv",
                "data/processed/cabinet_annual_departures.csv",
                "data/raw/ifg_ministers/appointment.csv",
                "data/raw/ifg_ministers/person.csv",
                "data/raw/ifg_ministers/post.csv",
                "data/raw/ifg_ministers/appointment_characteristics.csv"),
  electoral = c("data_workspace_2026-07/allparty_review/marss/aggregate_volatility_index.csv",
                "data_workspace_2026-07/allparty_review/marss/volatility_index_pca_input.csv",
                "data_workspace_2026-07/allparty_review/marss/marss_ge_pedersen.csv",
                "data_workspace_2026-07/allparty_review/marss/marss_poll_volatility.csv",
                "data_workspace_2026-07/allparty_review/marss/marss_local_pedersen.csv",
                "data_workspace_2026-07/switching_series/switching_recall_1979_2024.csv",
                "data_workspace_2026-07/max_burn_2607/comparative/electoral_volatility/data/emanuele_tv_western_europe_1945_2025.csv",
                "data_workspace_2026-07/max_burn_2607/comparative/electoral_volatility/data/canada_volatility_computed.csv",
                "data_workspace_2026-07/max_burn_2607/comparative/electoral_volatility/data/australia_volatility_computed.csv",
                "data_workspace_2026-07/easy_win_proposals/robust_ge_pedersen_8v4_FIXED.csv",
                "data_workspace_2026-07/checks/data/uk_ge_voteshare_1945_1979.csv"),
  public_opinion = c("data_workspace_2026-07/ch2_public_opinion/agenda_indices_annual.csv",
                "data_workspace_2026-07/ch2_public_opinion/ipsos_issues_index_monthly_1974_2026_mapped.csv",
                "data_workspace_2026-07/ch2_public_opinion/all_items_expected.csv",
                "data_workspace_2026-07/ch2_public_opinion/all_items_tracking_stats.csv",
                "data_workspace_2026-07/ch2_public_opinion/composite_unexpected_index.csv",
                "data_workspace_2026-07/ch2_public_opinion/composite_item_residuals.csv"),
  parliament = c("data_workspace_2026-07/parliamentary_dislocation/parliamentary_dislocation_index.csv",
                "data_workspace_2026-07/parliamentary_dislocation/lords_defeats_annual.csv",
                "data_workspace_2026-07/parliamentary_dislocation/three_way_pca.csv",
                "data_workspace_2026-07/parliamentary_dislocation/sources_raw/lords_defeats_by_session_official.csv",
                "data_workspace_2026-07/ch3_pipeline_restored/data/processed/rebellions_annual.csv"),
  policy    = c("data_workspace_2026-07/machinery_churn/data/departmental_churn_1979_2025.csv",
                "data_workspace_2026-07/machinery_churn/data/departmental_events.csv",
                "data_workspace_2026-07/policy_instability/uturns/series/uturns_series.csv"),
  nao       = c("data_workspace_2026-07/nao_extension/pdf_era/nao_final.csv",
                "data_workspace_2026-07/nao_extension/pdf_era/nao_counts.csv",
                "data_workspace_2026-07/nao_extension/diagnostics/fig213_computed_values.csv",
                "data_workspace_2026-07/policy_failure/vdem_wgi/wgi_goveff_uk.csv"),
  composite = c("data_workspace_2026-07/composite_canonical/canonical_pc1_1979_2025.csv",
                "data_workspace_2026-07/nonlinear_modelling/chapter_wide_shapes.csv")
)
for (grp in names(D)) for (f in D[[grp]]) put(file.path(P, f), file.path("data", grp))

# Prune stale data/ copies the same way scripts/ is pruned above — same root cause (file.copy
# only ever adds/updates). Only touches folders actually listed in D; data/processed/ predates
# the category scheme and isn't one of them, so it's reported but left for a human decision
# rather than auto-deleted.
for (grp in names(D)) {
  expected <- basename(D[[grp]])
  dest_dir <- file.path("data", grp)
  present  <- list.files(file.path(REPO, dest_dir))
  stale    <- setdiff(present, expected)
  for (f in stale) {
    file.remove(file.path(REPO, dest_dir, f))
    cat(sprintf("⚠ pruned stale mirror copy: %s/%s (no longer in D$%s)\n", dest_dir, f, grp))
  }
}
if (dir.exists(file.path(REPO, "data", "processed"))) {
  cat("⚠ data/processed/ exists in the mirror but isn't produced by any current D category —\n",
      "  predates the data/<category> scheme (see WKBD_repo/README.md). Not auto-removed;\n",
      "  needs a human decision (delete, or fold its files into a real category).\n")
}

# ---------------------------------------------------------------- 4. TABLES
put(file.path(P, "figures/table_2_1_transition.png"), "tables")
put(file.path(WS, "nonlinear_modelling/ch2_shapes_table.tex"), "tables")

# ---------------------------------------------------------------- 5. MANUSCRIPT
# newest "Chapter Two vNN.docx" only. ⛔ Word lock files (~$...) are skipped.
# ⚠ BUG FOUND AND FIXED 14 Sep 2026: put()'s overwrite=TRUE only replaces a file with the SAME
#   destination name — since each version has a different "vNN" filename, every rebuild left the
#   previous run's older version sitting alongside the new one instead of replacing it. Found 17
#   accumulated versions (v24 through v72) never pruned. Now explicitly removes every other
#   "Chapter Two v*.docx" in the mirror before copying the current newest one in.
ch <- list.files(file.path(P, "chapters"), pattern = "^Chapter Two v[0-9]+\\.docx$", full.names = TRUE)
if (length(ch)) {
  v  <- as.integer(sub(".*v([0-9]+)\\.docx$", "\\1", ch))
  newest <- ch[which.max(v)]
  old_mirror_copies <- list.files(file.path(REPO, "manuscript"),
                                   pattern = "^Chapter Two v[0-9]+\\.docx$", full.names = TRUE)
  stale <- setdiff(old_mirror_copies, file.path(REPO, "manuscript", basename(newest)))
  for (f in stale) { file.remove(f); cat(sprintf("⚠ pruned stale manuscript version: %s\n", basename(f))) }
  put(newest, "manuscript")
  cat(sprintf("manuscript: %s\n", basename(newest)))
}
# ⛔ Chapter 3's manuscript (currently v22) is deliberately NOT copied here — the whole
#   chapters/ folder is gitignored and this repo is public. Only Chapter 2's manuscript was ever
#   mirrored (PJ's original 17 Aug ask); Chapter 3 gets the code/data/appendix replication
#   package only. Do not add a Ch3 "put(ch...)" call here without checking with PJ first.

# ================================================================== CHAPTER 3
CH3 <- file.path(WS, "ch3_pipeline_restored")

# ---------------------------------------------------------- 3.1 FIGURES
# One canonical PNG per figure number, confirmed against each build_fig_3_N_*.R script's own
# ggsave() target (NOT guessed from filename — figures/fig_3_1_professionalisation_composite.png
# is a stale orphan from before the chapter's figure-reorder and is deliberately excluded; no
# current script produces it).
FIGS3 <- list(
  c("3.1", "figures/fig_3_1_path_diagram.png",                 "Figure_3.1_path_diagram.png"),
  c("3.2", "figures/fig_3_2_hansard_self_regarding.png",       "Figure_3.2_hansard_self_regarding.png"),
  c("3.3", "figures/fig_3_3_mp_misconduct.png",                "Figure_3.3_mp_misconduct.png"),
  c("3.4", "figures/fig_3_4_ministerial_departures.png",       "Figure_3.4_ministerial_departures.png"),
  c("3.5", "figures/fig_3_5_professionalisation_composite.png","Figure_3.5_professionalisation_composite.png"),
  c("3.6", "figures/fig_3_6_three_series.png",                 "Figure_3.6_three_series.png"),
  c("3.7", "figures/fig_3_7_mediation.png",                    "Figure_3.7_mediation.png")
)
for (f in FIGS3) put(file.path(CH3, f[2]), "figures", f[3])

# Appendix figures (cited in the online appendix, not the main chapter figure sequence).
FIGS3_APPENDIX <- list(
  c("figures/ch3_aggregate_self_regarding_APPENDIX.png", "Figure_A3_aggregate_self_regarding.png"),
  c("figures/ch3_backbench_frontbench_split.png",        "Figure_A3_backbench_frontbench_split.png")
)
for (f in FIGS3_APPENDIX) put(file.path(CH3, f[1]), "figures", f[2])

# ---------------------------------------------------------- 3.2 SCRIPTS
# Dynamically listed (unlike Ch2's hand-typed SCRIPTS above) — Ch3 has ~74 live scripts, and
# hand-typing that many names is itself an error source. Excludes scripts/_superseded_12sep/
# (dead scripts — currently just 41h_causal_path_diagram.R, the archived causal-path diagram
# superseded by the current fig_3_1 path diagram).
SCRIPTS3 <- list.files(file.path(CH3, "scripts"), pattern = "\\.R$", full.names = FALSE)
SCRIPTS3 <- file.path("data_workspace_2026-07/ch3_pipeline_restored/scripts", SCRIPTS3)
for (s in SCRIPTS3) put(file.path(P, s), "scripts")
for (s in SCRIPTS3) banner_stamp(s, "scripts")

# Combined prune, now that both Ch2's SCRIPTS and Ch3's SCRIPTS3 have been copied in.
prune_stale("scripts", c(SCRIPTS, SCRIPTS3))

# ---------------------------------------------------------- 3.3 DATA
# Whole data/raw/ and data/processed/ folders, not a per-script grep match — Ch3's scripts
# frequently read each other's outputs back in (e.g. 64s reads 64q's/64r's own outputs), so a
# strict per-script dependency list would still end up needing almost every file anyway. Judgment
# call: whole-folder copy here, flagged explicitly rather than silently done.
D3_RAW       <- list.files(file.path(CH3, "data/raw"),       pattern = "\\.csv$", full.names = FALSE)
D3_PROCESSED <- list.files(file.path(CH3, "data/processed"), pattern = "\\.csv$", full.names = FALSE)
for (f in D3_RAW)       put(file.path(CH3, "data/raw", f),       "data/ch3_raw")
for (f in D3_PROCESSED) put(file.path(CH3, "data/processed", f), "data/ch3_processed")
prune_stale2 <- function(dest_dir, expected) {
  # only.files, not.dirs — a subfolder (e.g. tables/ch2_appendix/figures/) living inside a
  # pruned dest_dir is not a stale FILE and must not be passed to file.remove(). Caught 14 Sep
  # 2026 when ch2_appendix/figures/ (added same session) tripped this on its parent dir's prune.
  present <- list.files(file.path(REPO, dest_dir))
  present <- present[!file.info(file.path(REPO, dest_dir, present))$isdir]
  stale   <- setdiff(present, basename(expected))
  for (f in stale) {
    file.remove(file.path(REPO, dest_dir, f))
    cat(sprintf("⚠ pruned stale mirror copy: %s/%s\n", dest_dir, f))
  }
}
prune_stale2("data/ch3_raw", D3_RAW)
prune_stale2("data/ch3_processed", D3_PROCESSED)

# Cross-chapter dependency: several Ch3 scripts read Chapter 2's turbulence composite
# (../composite_canonical/canonical_pc1_1979_2025.csv). Already mirrored under data/composite/
# by the Chapter 2 section above (D$composite) — not duplicated here, just noted so the
# dependency is documented rather than silently assumed.

# Small, directly-cited primary-source files ONLY (not the full sources_raw/ tree — several
# subfolders there, e.g. sources_raw/hansard_api_pull_2020_2025/, are 1GB+ raw API scrape dumps
# unsuitable for a git repo; replicators can re-pull Hansard via the API directly, as the
# scripts' own headers describe). Judgment call: include the two small, citable primary-source
# CSVs actually read by name in the scripts; exclude the large scrape dumps and the PDF-heavy
# sourcing folders (lords_gender_composition/, local_govt_scandals_web_compiled/ are SOURCE_NOTE.md
# + PDFs, not machine-readable data, and belong in the manuscript's own sourcing trail, not a code
# replication package).
SOURCES3_RAW <- c(
  "sources_raw/ipsos_veracity_index/ipsos_veracity_trust_1983_2023.csv",
  "sources_raw/butler_butler_2011_mp_allowances/mp_office_expenses_allowance_max_1969_2016.csv"
)
for (f in SOURCES3_RAW) put(file.path(P, f), "data/ch3_sources_raw")
prune_stale2("data/ch3_sources_raw", SOURCES3_RAW)

# ---------------------------------------------------------- 3.4 ONLINE APPENDIX TABLES
# The four live Chapter 3 appendix table files (LaTeX) plus the data CSVs they cite in their own
# tablenotes. online_appendix/appendix_chapters/ch03.tex is DELIBERATELY EXCLUDED — it is stale
# content predating the four-appendix restructuring (references a since-renumbered "Figure 3.14"
# and an RC01-RC04 scheme superseded by robustness_chapters/ch03.tex's RC13-RC18); it was never
# retired and should not be perpetuated into the public mirror.
APPENDIX3_TEX <- c(
  "online_appendix/additional_tables_chapters/ch03.tex",
  "online_appendix/additional_tables_chapters/ch03_local_govt_scandals_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch03_gender_timing_tests_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch03_spads_sources_GENERATED.tex",
  "online_appendix/robustness_chapters/ch03.tex"
)
for (f in APPENDIX3_TEX) put(file.path(P, f), "tables/ch3_appendix")

APPENDIX3_DATA <- c(
  "online_appendix/ch3_local_government_scandals_by_decade.csv",
  "online_appendix/ch3_fig34_misconduct_robustness.csv",
  "online_appendix/ch3_fig35_threshold_robustness.csv",
  "online_appendix/ch3_fig35_window_robustness.csv",
  "online_appendix/ch3_fig35_scandal_borderline_robustness.csv",
  "online_appendix/ch3_fig35_scandal_exact_tests.csv",
  "online_appendix/ch3_fig36_mediation_trend_robustness.csv",
  "online_appendix/ch3_backbench_frontbench_2020_2025.csv",
  "online_appendix/ch3_backbench_frontbench_full_1979_2025.csv",
  "online_appendix/ch3_backbench_frontbench_split.csv",
  "online_appendix/ch3_career_orientation_full_1979_2025.csv",
  "online_appendix/ch3_career_orientation_rolling5yr_1979_2025.csv",
  "online_appendix/ch3_career_orientation_split_1979_2019.csv",
  "online_appendix/ch3_career_orientation_split_2020_2025.csv"
)
for (f in APPENDIX3_DATA) put(file.path(P, f), "tables/ch3_appendix")
prune_stale2("tables/ch3_appendix", c(APPENDIX3_TEX, APPENDIX3_DATA))

cat(sprintf("\nChapter 3: %d figures, %d scripts, %d+%d data files, %d appendix files\n",
            length(FIGS3) + length(FIGS3_APPENDIX), length(SCRIPTS3),
            length(D3_RAW), length(D3_PROCESSED), length(APPENDIX3_TEX) + length(APPENDIX3_DATA)))

# ---------------------------------------------------------- 3.5 CHAPTER 2 ONLINE APPENDIX TABLES
# ⭐ ADDED 14 Sep 2026, same decision as Ch3's appendix inclusion above (superseding the 29 Aug
# "appendices stay out for now" call). Mirrors ONLY the "A" (robustness) and "C" (additional
# tables) appendix content, matching what was included for Ch3 -- not Appendix B (cross-checking)
# or the older appendix_chapters/ch02.tex, which predates the four-appendix restructuring the same
# way appendix_chapters/ch03.tex does (superseded, never retired -- see Ch3's own exclusion note
# above). Unlike Ch3's tables, these GENERATED sub-files embed their numbers directly (no separate
# underlying CSV cited in their own tablenotes) -- checked by grep, not assumed -- so only the
# .tex files and the figures they \includegraphics are mirrored, no data/ch2_appendix needed.
APPENDIX2_TEX <- c(
  "online_appendix/additional_tables_chapters/ch02.tex",
  "online_appendix/additional_tables_chapters/ch02_alternative_measures_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch02_nao_output_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch02_rebellion_comparative_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch02_mip_comparative_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch02_wgi_comparative_GENERATED.tex",
  "online_appendix/additional_tables_chapters/ch02_agenda_speeches_GENERATED.tex",
  "online_appendix/robustness_chapters/ch02.tex",
  "online_appendix/robustness_chapters/ch02_nao_breaks_GENERATED.tex",
  "online_appendix/robustness_chapters/ch02_nao_quantification_GENERATED.tex",
  "online_appendix/robustness_chapters/ch02_uturns_cuts_GENERATED.tex",
  "online_appendix/robustness_chapters/ch02_attribution_GENERATED.tex"
)
for (f in APPENDIX2_TEX) put(file.path(P, f), "tables/ch2_appendix")

# Figures the two master .tex files actually \includegraphics (confirmed by grep, not guessed) --
# both sourced from their own figures_ch02/ subfolder, one per appendix (additional_tables_chapters
# and robustness_chapters each have their own).
APPENDIX2_FIGS <- c(
  "online_appendix/additional_tables_chapters/figures_ch02/piecewise_trend_unexpected_attention.png",
  "online_appendix/additional_tables_chapters/figures_ch02/fig_2_21_wgi_gov_effectiveness.png",
  "online_appendix/additional_tables_chapters/figures_ch02/fig_agenda_speech_eni.png",
  "online_appendix/robustness_chapters/figures_ch02/fig_a2_14_nao_specifications_not_chosen.png"
)
for (f in APPENDIX2_FIGS) put(file.path(P, f), "tables/ch2_appendix/figures")
prune_stale2("tables/ch2_appendix", APPENDIX2_TEX)
prune_stale2("tables/ch2_appendix/figures", APPENDIX2_FIGS)

cat(sprintf("Chapter 2 appendix: %d tex files, %d figures\n", length(APPENDIX2_TEX), length(APPENDIX2_FIGS)))

# ---------------------------------------------------------------- 6. MANIFEST
BUILDER <- c("01_pm_turnover.R","02b_great_officers_combined_figure.R","03_cabinet_turnover.R",
  "04_executive_instability.R","05_comparative_turnover.R","build_fig_2_6_electoral_volatility.R",
  "build_fig_2_7_comparative_volatility.R","29_fig_agenda_no_pca.R","35_fig_expected_movements.R",
  "10_three_panel_summary.R","build_divergence_punctuation.R","build_fig_2_12_machinery_churn.R",
  "build_fig_2_13_nao.R","build_fig_2_14_external_validation.R","build_fig_2_15_uturns.R",
  "build_fig_2_16_turbulence_index.R","40_fig_attribution_slopes.R")
man2 <- data.frame(
  figure   = sapply(FIGS, `[`, 1),
  file     = sapply(FIGS, `[`, 3),
  script   = BUILDER,
  worktree = sapply(FIGS, `[`, 2),
  stringsAsFactors = FALSE)

# Chapter 3 manifest rows — script mapped from each figure's own build_fig_3_N_*.R filename
# (each figure has exactly one dedicated builder, unlike Ch2's occasional many-figures-per-script
# scripts, so this can be derived directly rather than hand-listed like Ch2's BUILDER above).
BUILDER3 <- sprintf("build_fig_3_%s.R", c(
  "1_path_diagram", "2_hansard_self_regarding", "3_mp_misconduct", "4_ministerial_departures",
  "5_professionalisation_composite", "6_three_series", "7_mediation"))
man3 <- data.frame(
  figure   = sapply(FIGS3, `[`, 1),
  file     = sapply(FIGS3, `[`, 3),
  script   = BUILDER3,
  worktree = sapply(FIGS3, `[`, 2),
  stringsAsFactors = FALSE)

man <- rbind(man2, man3)
write.csv(man, file.path(REPO, "MANIFEST.csv"), row.names = FALSE)

cat(sprintf("\ncopied %d files into WKBD_repo/\n", copied))
if (length(missing)) {
  cat("\n⛔ MISSING — listed in the manifest but not on disk:\n")
  for (m in missing) cat("   ", sub(paste0(P,"/"), "", m, fixed = TRUE), "\n")
} else cat("✅ every manifest entry found\n")
