# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/collect_ch2_figures.R
# collect_ch2_figures.R — gather the CURRENT Chapter 2 figures into one place.
#
# PJ, 17 Aug: "I can't find 2.12. Organising of files in WKBD looking increasingly messy!"
# He is right. The numbered figures are spread across SIX directories, and worse, the root
# figures/ folder still holds files under numbers 2.8, 2.9, 2.10 and 2.12 that are the OLD
# figures — the ones those numbers used to mean before the 17 Aug renumbering. Anyone assembling
# the chapter from figures/ would pick up the wrong image under the right name.
#
# ⛔ THIS SCRIPT DOES NOT MOVE OR DELETE ANYTHING. It COPIES the current figure for each number
# into figures_ch2/, which becomes the one place to look. Re-run it after any figure rebuild;
# because it copies rather than syncs, a stale figures_ch2/ is impossible to create by accident —
# but it IS possible to leave one behind, so re-run before any hand-off.
#
# ⚠ The manifest is explicit ON PURPOSE. A glob would have silently picked up the collided files.

DEST <- "/Users/pjair2026/Library/CloudStorage/Dropbox/Documents/Who Killed British Democracy?/figures_ch2"
P    <- "/Users/pjair2026/Library/CloudStorage/Dropbox/Documents/Who Killed British Democracy?"
WS   <- file.path(P, "data_workspace_2026-07")
dir.create(DEST, showWarnings = FALSE)

# number, source path, short name, whether the SOURCE filename still carries the OLD number
MANIFEST <- list(
  # SECOND RENUMBERING, 17 Aug: old Figure 2.2 (PM departures) MERGED INTO 2.1 as panel B.
  # PJ: "ok rebuild - it will mean renumbering all the others but less figures so better."
  # The chapter now has SIXTEEN figures, not seventeen.
  # THE SOURCE FILES STILL CARRY THE PREVIOUS NUMBERS, deliberately: this is the third
  # renumbering cascade in two days, the first of which broke four NAO scripts for a day, and
  # further merges may follow. The source rename happens ONCE, at the end. Until then THIS FILE
  # is the mapping and figures_ch2/ is the only place the numbers are right.
  list("2.1", file.path(P,"figures/fig_2_1_pm_tenure.png"), "pm_tenure_and_departure", FALSE),
  list("2.2", file.path(P,"figures/fig_2_2_great_officers_combined.png"), "great_offices", TRUE),
  list("2.3", file.path(P,"figures/fig_2_3_cabinet_turnover.png"), "cabinet_turnover", TRUE),
  list("2.4", file.path(P,"figures/fig_2_4_executive_instability.png"), "executive_instability", TRUE),
  list("2.5", file.path(P,"figures/fig_2_5_comparative_tenure.png"), "comparative_tenure", TRUE),
  list("2.6", file.path(WS,"allparty_review/figures/fig_2_6_electoral_volatility.png"), "electoral_volatility", TRUE),
  list("2.7", file.path(WS,"allparty_review/figures/fig_2_7_comparative_volatility.png"), "comparative_volatility", TRUE),
  list("2.8", file.path(WS,"ch2_public_opinion/fig_2_8_public_agenda.png"), "public_agenda", TRUE),
  list("2.9", file.path(WS,"ch2_public_opinion/fig_2_9_unexpected_movements.png"), "unexpected_movements", TRUE),
  list("2.10", file.path(WS,"parliamentary_dislocation/fig_2_10_parliamentary_instability.png"), "parliamentary", TRUE),
  list("2.11", file.path(WS,"policy_instability/figures/fig_2_11_policy_agenda.png"), "policy_agenda", TRUE),
  list("2.12", file.path(WS,"machinery_churn/figures/fig_2_12_machinery_churn_1979_2024.png"), "machinery_churn", TRUE),
  list("2.13", file.path(P,"figures/fig_2_13_nao_delivery_failure_1984_2025.png"), "nao_delivery_failure", TRUE),
  list("2.14", file.path(P,"figures/fig_2_14_external_validation.png"), "external_validation", TRUE),
  list("2.15", file.path(P,"figures/fig_2_15_uturns_1979_2025.png"), "uturns", TRUE),
  list("2.16", file.path(WS,"composite_canonical/figures/fig_2_16_turbulence_index_1979_2024.png"), "turbulence_index", TRUE)
)

ok <- 0; missing <- character(0); pending <- character(0)
for (m in MANIFEST) {
  num <- m[[1]]; src <- m[[2]]; nm <- m[[3]]; old <- m[[4]]
  dst <- file.path(DEST, sprintf("Figure_%s_%s.png", num, nm))
  if (!file.exists(src)) { missing <- c(missing, sprintf("%s  <- %s", num, src)); next }
  file.copy(src, dst, overwrite = TRUE)
  ok <- ok + 1
  if (old) pending <- c(pending, num)
}

cat(sprintf("\ncopied %d of %d figures -> figures_ch2/\n", ok, length(MANIFEST)))
if (length(pending))
  cat(sprintf("⏭ still numbered OLD at source (renumbering pass not yet reached them): %s\n",
              paste(pending, collapse = ", ")))
if (length(missing)) {
  cat("\n⛔ MISSING — a figure in the manifest does not exist:\n")
  for (x in missing) cat("   ", x, "\n")
}

# ⛔ The collided files: same number, OLD content, still sitting in the root figures/ folder.
COLLIDED <- c("fig_2_8_electoral_volatility.png",            # old 2.8, now 2.7 and rebuilt elsewhere
              "fig_2_9_electoral_volatility_comparative.png",# old 2.9, now 2.8
              "fig_2_10_most_important_issue_1979_2023.png", # old 2.10, now 2.9
              "fig_2_12_parliamentary_instability_1979_2026.png") # old 2.12, now 2.11
hits <- COLLIDED[file.exists(file.path(P, "figures", COLLIDED))]
if (length(hits)) {
  cat("\n⛔ NUMBER COLLISIONS still live in figures/ — these carry a number that now means a\n")
  cat("   DIFFERENT figure. Assembling the chapter from figures/ would pick up the wrong image:\n")
  for (h in hits) cat("   ", h, "\n")
  cat("   -> move to _ARCHIVE/figures/figures_superseded_17aug/ once PJ confirms. NOT done automatically.\n")
}

# ---------------------------------------------------------------------------
# ⛔ SELF-CLEAN. A renumbering leaves the PREVIOUS numbering behind in this folder, and then two
# files both claim to be "Figure 2.10". That is the same collision that was found in figures/ and
# it is worse here, because this folder is the one PJ reads from.
# Anything in figures_ch2/ that this manifest did not just write is stale by definition.
# ⛔ It is MOVED, never deleted (PJ's standing rule).
# ---------------------------------------------------------------------------
written <- vapply(MANIFEST, function(m) sprintf("Figure_%s_%s.png", m[[1]], m[[3]]), character(1))
present <- list.files(DEST, pattern = "\\.png$")
stale   <- setdiff(present, written)
if (length(stale)) {
  # PJ, 17 Aug: "have one folder for completed figures - too many folders."
  # Stale copies go to the ONE archive that already exists, NOT a nested folder inside
  # the completed set. figures_ch2/ holds the finished figures and nothing else.
  OLD <- file.path(P, "figures", "_superseded_17aug")
  dir.create(OLD, showWarnings = FALSE, recursive = TRUE)
  file.rename(file.path(DEST, stale), file.path(OLD, stale))
  cat(sprintf("\n⛔ %d stale file(s) from a previous numbering MOVED to _ARCHIVE/figures/figures_superseded_17aug/:\n",
              length(stale)))
  for (s in stale) cat("   ", s, "\n")
}
cat(sprintf("\n✅ figures_ch2/ now holds exactly %d figures, numbered 2.1-2.%d\n",
            length(written), length(written)))
