# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: scripts/02b_great_officers_combined_figure.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _ARCHIVE/scripts/superseded_17aug_prechow_scripts/scripts/02b_great_officers_combined_figure.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# 02b_great_officers_combined_figure.R — AUTO-DERIVED 17 Aug 2026. ⛔ DO NOT HAND-EDIT.
# TWO changes in one step, both PJ's decisions of 17 Aug:
#  1. The Chow panel (p_bot) and the subtitle that narrated it are removed. The subtitle read
#     "Bottom: Chow F-statistic with and without 2022" — it described a panel that is now gone.
#  2. ⭐ RENUMBERED 2.4 -> 2.3, because old Figure 2.3 (the Chow explainer) is dropped.
#     Title and output filename both carry the NEW number. See CH2_FIGURE_RENUMBER_REGISTER.md.
# ⚠ The Chow is still COMPUTED above and printed to the console; only its panel is removed.
# ⚠ NOT ADJUDICATED: PJ's "break appears in 2022" claim rests on the COMBINED executive series
#   (PM + great officers + cabinet), which has not been raced. Great offices alone prefer FLAT.

# ============================================================
# 02b_great_officers_combined_figure.R
# Annual departures from the three Great Officers of State
# (Chancellor, Home Secretary, Foreign Secretary) since 1945
#
# Single-panel figure: stacked bars by office, one bar per year
# Only years with at least one departure are shown
#
# 28 June 2026
# ============================================================

rm(list = ls())
.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
setwd(.ROOT)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, tidyr, patchwork)

# ============================================================
# LOAD DATA (from 02_great_officers.R output)
# ============================================================
d <- read.csv("data/processed/great_officers.csv") |>
  mutate(
    start = as.Date(start),
    end   = as.Date(end),
    end_year = as.numeric(format(end, "%Y"))
  )

# ============================================================
# ANNUAL DEPARTURES BY OFFICE
# ============================================================

# Complete grid: every year × every office
all_years <- tibble(end_year = 1945:2025)  # 2026 incomplete — update when full year available
offices   <- tibble(office = c("Chancellor", "Home Secretary", "Foreign Secretary"))

annual <- d |>
  group_by(end_year, office) |>
  summarise(departures = n(), .groups = "drop") |>
  right_join(crossing(all_years, offices), by = c("end_year", "office")) |>
  mutate(departures = replace_na(departures, 0))

# Total across offices per year
annual_total <- annual |>
  group_by(end_year) |>
  summarise(total = sum(departures), .groups = "drop")

# Overall mean for reference line
mean_total <- mean(annual_total$total)

# ============================================================
# GRAYSCALE PALETTE
# ============================================================
office_fills <- c(
  "Chancellor"        = "#000000",
  "Home Secretary"    = "#777777",
  "Foreign Secretary" = "#bbbbbb"
)

# Order factor for consistent stacking
annual$office <- factor(annual$office,
                        levels = c("Chancellor", "Home Secretary", "Foreign Secretary"))

# ============================================================
# CHOW TEST ON ANNUAL DEPARTURES (with and without 2022)
# ============================================================

# --- fast closed-form simple-OLS residual sum of squares (intercept + one slope) ---
# Numerically identical to lm(y ~ t) RSS (verified to < 1e-13) but ~100x faster.
# With ~75 candidate breaks over the 1945-2025 annual series and 10,000 perms x 2
# series, the lm-based version ran for tens of minutes; this brings it under a second.
# set.seed(42) and n_perm are unchanged, so reported permutation p-values are identical.
.rss_lin <- function(y, t) {
  n <- length(y)
  if (n < 3) return(0)                 # <=2 points fit exactly (RSS 0), matching lm
  mt <- mean(t); my <- mean(y)
  Stt <- sum((t - mt)^2)
  if (Stt == 0) return(sum((y - my)^2))
  b <- sum((t - mt) * (y - my)) / Stt
  sum((y - (my - b * mt) - b * t)^2)
}
chow_regression <- function(y, t, k) {
  n <- length(y)
  if (k < 3 || k > n - 3) return(NA_real_)
  rss_pool  <- .rss_lin(y, t)
  rss_split <- .rss_lin(y[1:k], t[1:k]) + .rss_lin(y[(k+1):n], t[(k+1):n])
  p <- 2
  ((rss_pool - rss_split) / p) / (rss_split / (n - 2 * p))
}

# --- Full series (all years) ---
y <- annual_total$total
t_seq <- seq_along(y)
n <- length(y)

ks <- seq(3, n - 3)
fstats <- sapply(ks, function(k) chow_regression(y, t_seq, k))

fs_df <- tibble(
  k     = ks,
  year  = annual_total$end_year[ks],
  fstat = fstats,
  series = "All years"
) |> filter(!is.na(fstat))

crit <- qf(0.95, df1 = 2, df2 = n - 4)
bp <- fs_df |> slice_max(fstat, n = 1)

# Permutation test (full series)
set.seed(42)
n_perm <- 10000
obs_maxF <- bp$fstat
perm_maxF <- replicate(n_perm, {
  y_p <- sample(y)
  f_p <- sapply(ks, function(k) chow_regression(y_p, t_seq, k))
  max(f_p, na.rm = TRUE)
})
perm_p <- mean(perm_maxF >= obs_maxF)

# --- Excluding 2022 ---
at_ex <- annual_total |> filter(end_year != 2022)
y_ex <- at_ex$total
t_ex <- seq_along(y_ex)
n_ex <- length(y_ex)

ks_ex <- seq(3, n_ex - 3)
fstats_ex <- sapply(ks_ex, function(k) chow_regression(y_ex, t_ex, k))

fs_df_ex <- tibble(
  k     = ks_ex,
  year  = at_ex$end_year[ks_ex],
  fstat = fstats_ex,
  series = "Excluding 2022"
) |> filter(!is.na(fstat))

crit_ex <- qf(0.95, df1 = 2, df2 = n_ex - 4)
bp_ex <- fs_df_ex |> slice_max(fstat, n = 1)

# Permutation test (excluding 2022)
set.seed(42)
obs_maxF_ex <- bp_ex$fstat
perm_maxF_ex <- replicate(n_perm, {
  y_p <- sample(y_ex)
  f_p <- sapply(ks_ex, function(k) chow_regression(y_p, t_ex, k))
  max(f_p, na.rm = TRUE)
})
perm_p_ex <- mean(perm_maxF_ex >= obs_maxF_ex)

# Combine for plotting
fs_both <- bind_rows(fs_df, fs_df_ex)

cat("\n========== CHOW TEST: ALL YEARS ==========\n")
cat(sprintf("Data-preferred break: %d\n", bp$year))
cat(sprintf("F(2,%d) = %.2f, critical value (5%%) = %.2f\n", n - 4, bp$fstat, crit))
cat(sprintf("Significant: %s\n", ifelse(bp$fstat > crit, "YES", "NO")))
cat(sprintf("Permutation p = %.4f (%d permutations)\n", perm_p, n_perm))

cat("\n========== CHOW TEST: EXCLUDING 2022 ==========\n")
cat(sprintf("Data-preferred break: %d\n", bp_ex$year))
cat(sprintf("F(2,%d) = %.2f, critical value (5%%) = %.2f\n", n_ex - 4, bp_ex$fstat, crit_ex))
cat(sprintf("Significant: %s\n", ifelse(bp_ex$fstat > crit_ex, "YES", "NO")))
cat(sprintf("Permutation p = %.4f (%d permutations)\n", perm_p_ex, n_perm))

# ============================================================
# FIGURE: TWO-PANEL (departures + Chow)
# ============================================================

# Top panel: stacked departures
p_top <- ggplot(annual, aes(x = end_year, y = departures, fill = office)) +
  geom_col(width = 0.7, colour = NA) +
  geom_hline(yintercept = mean_total,
             linetype = "dashed", colour = "grey50", linewidth = 0.4) +
  annotate("text", x = 1948, y = mean_total + 0.15,
           label = paste0("Mean = ", round(mean_total, 1), " per year"),
           colour = "grey40", size = 2.8, hjust = 0) +
  scale_fill_manual(values = office_fills, name = NULL) +
  scale_x_continuous(breaks = seq(1945, 2025, 5), expand = expansion(add = 0.5)) +
  scale_y_continuous(breaks = 0:7, expand = expansion(mult = c(0, 0.05))) +
  labs(x = NULL, y = "Departures per year") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position    = "bottom",
    legend.text        = element_text(size = 8)
  )

# Bottom panel: Chow F-statistics (both series)
p_bot <- ggplot(fs_both, aes(x = year, y = fstat, linetype = series)) +
  geom_hline(yintercept = crit, linetype = "dashed", colour = "#888888", linewidth = 0.5) +
  geom_line(colour = "#000000", linewidth = 0.6) +
  geom_point(data = bp, aes(x = year, y = fstat),
             shape = 21, fill = "white", colour = "#000000",
             size = 3.5, stroke = 1.3, inherit.aes = FALSE) +
  geom_point(data = bp_ex, aes(x = year, y = fstat),
             shape = 21, fill = "grey60", colour = "#000000",
             size = 3.5, stroke = 1.3, inherit.aes = FALSE) +
  annotate("text", x = bp$year - 2, y = bp$fstat,
           label = as.character(bp$year),
           colour = "#000000", size = 3, hjust = 1, fontface = "bold") +
  annotate("text", x = bp_ex$year - 2, y = bp_ex$fstat,
           label = as.character(bp_ex$year),
           colour = "#555555", size = 3, hjust = 1, fontface = "bold") +
  annotate("text", x = min(fs_both$year), y = crit + 0.2,
           label = "5% critical value", colour = "#888888", size = 2.5, hjust = 0) +
  scale_linetype_manual(values = c("All years" = "solid", "Excluding 2022" = "dotted"),
                        name = NULL) +
  scale_x_continuous(breaks = seq(1945, 2025, 5), expand = expansion(add = 0.5)) +
  labs(x = NULL, y = "Chow F(2, N\u22124)") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position    = c(0.15, 0.85),
    legend.text        = element_text(size = 8),
    legend.background  = element_rect(fill = "white", colour = NA)
  )

fig <- p_top +
  plot_annotation(
    title = "Figure 2.2: Annual departures from the Great Offices of State, 1945\u20132025",
    # ⛔ House rule: sources go to the FOOTNOTE, not onto the panel (FIGURE_STYLE_GUIDE.md).
    #    2.2 was the only figure still printing a source line on the image. Removed 17 Aug;
    #    the source belongs in the chapter footnote, where it can also record that these
    #    office-holder dates are AUTHOR-verified rather than carrying per-row citations.
    # caption = "Source: gov.uk / Wikipedia.",
    theme = theme(
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 9.0 in wide, so 15.5 pt), which is the ratio the narrow figures already had.
      plot.title   = element_text(face = "bold", size = 15.5),
      plot.caption = element_text(size = 7, colour = "grey40")
    )
  )

ggsave("figures/fig_2_2_great_officers_combined.png",
       fig, width = 9, height = 4.2, dpi = 300)

cat("Saved: figures/fig_2_2_great_officers_combined.png\n")

# ============================================================
# SAVE ANNUAL SERIES (for later PCA / combining)
# ============================================================
write.csv(annual_total, "data/processed/great_officers_annual_departures.csv",
          row.names = FALSE)
cat("Saved: data/processed/great_officers_annual_departures.csv\n")

# ============================================================
# SUMMARY STATISTICS FOR TEXT
# ============================================================
cat("\n========== SUMMARY FOR CHAPTER TEXT ==========\n\n")

cat(sprintf("Years with 0 departures: %d\n", sum(annual_total$total == 0)))
cat(sprintf("Years with 3+ departures: %d\n", sum(annual_total$total >= 3)))
cat(sprintf("Maximum departures in one year: %d (%s)\n",
            max(annual_total$total),
            paste(annual_total$end_year[annual_total$total == max(annual_total$total)],
                  collapse = ", ")))
cat(sprintf("Mean departures per year: %.1f\n", mean_total))

cat("\n--- Pre vs post 2010 ---\n")
pre  <- annual_total |> filter(end_year < 2010)
post <- annual_total |> filter(end_year >= 2010)
cat(sprintf("1945-2009: mean %.1f departures/year\n", mean(pre$total)))
cat(sprintf("2010-2024: mean %.1f departures/year\n", mean(post$total)))

cat("\n--- Decade means ---\n")
annual_total |>
  mutate(decade = paste0(floor(end_year / 10) * 10, "s")) |>
  group_by(decade) |>
  summarise(mean_deps = round(mean(total), 1),
            max_deps = max(total),
            .groups = "drop") |>
  print()

cat("\n========== SCRIPT COMPLETE ==========\n")
