# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: scripts/04_executive_instability.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _ARCHIVE/scripts/superseded_17aug_prechow_scripts/scripts/04_executive_instability.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# 04_executive_instability.R — AUTO-DERIVED from 04_executive_instability.R, 17 Aug 2026.
# ⛔ DO NOT EDIT BY HAND. PJ, 17 Aug: drop the Chow panels from the Ch2 figures; each series' shape
# is carried instead by one summary table (nonlinear_modelling/ch2_shapes_table.tex).
# ⚠ RENUMBERED 2.6 -> 2.5 (old Fig 2.3 dropped). ⭐ The subtitle was edited SURGICALLY, not deleted:
# the Chow sentence ("Bottom: Chow F-statistic on total departures...") is gone, but the LOESS and
# PCA eigenvalue/variance lines are kept, because they describe what is still drawn.
# ⚠ This variant drops a PURE TEST panel. No data panel is removed.

# ============================================================
# 04_executive_instability.R
# Composite measure of executive instability
# Combines: PM departures, great officer departures,
#           cabinet departures (excl. great officers)
#
# Method: PCA on standardised (z-score) annual series
# Overlap period: 1979–2026
# ============================================================

rm(list = ls())
.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
setwd(.ROOT)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, tidyr, readr, patchwork)

# ============================================================
# LOAD THE THREE SERIES
# ============================================================

# 1. PM departures: convert tenure data to annual 0/1
pm <- read_csv("data/processed/pm_tenure.csv", show_col_types = FALSE) |>
  mutate(end_year = as.numeric(format(as.Date(end), "%Y"))) |>
  filter(end_year >= 1979, end_year <= 2025)

pm_annual <- tibble(year = 1979:2025) |>
  left_join(
    pm |> group_by(end_year) |> summarise(pm_departures = n(), .groups = "drop"),
    by = c("year" = "end_year")
  ) |>
  mutate(pm_departures = replace_na(pm_departures, 0))

# 2. Great officers (already annual)
go <- read_csv("data/processed/great_officers_annual_departures.csv",
               show_col_types = FALSE) |>
  filter(end_year >= 1979, end_year <= 2025) |>
  rename(year = end_year, go_departures = total)

# 3. Cabinet (excl. great officers, already annual)
cab <- read_csv("data/processed/cabinet_annual_departures.csv",
                show_col_types = FALSE) |>
  rename(cab_departures = departures)

# ============================================================
# COMBINE INTO SINGLE DATAFRAME
# ============================================================
combined <- pm_annual |>
  left_join(go, by = "year") |>
  left_join(cab, by = "year") |>
  mutate(across(c(go_departures, cab_departures),
                ~replace_na(.x, 0)))  # All series truncated at 2025 — 2026 incomplete

cat("========== COMBINED SERIES ==========\n")
cat(sprintf("Years: %d–%d (n = %d)\n",
            min(combined$year), max(combined$year), nrow(combined)))
cat(sprintf("PM departures: %d total\n", sum(combined$pm_departures)))
cat(sprintf("Great officer departures: %d total\n", sum(combined$go_departures)))
cat(sprintf("Cabinet departures: %d total\n", sum(combined$cab_departures)))

# ============================================================
# CORRELATIONS
# ============================================================
cat("\n========== CORRELATIONS ==========\n")
cor_mat <- cor(combined |> select(pm_departures, go_departures, cab_departures))
print(round(cor_mat, 3))

# ============================================================
# PCA ON STANDARDISED SERIES
# ============================================================
z <- combined |>
  select(pm_departures, go_departures, cab_departures) |>
  scale()

pca <- prcomp(z, center = FALSE, scale. = FALSE)

cat("\n========== PCA RESULTS ==========\n")
cat("\nStandard deviations:\n")
print(round(pca$sdev, 3))
cat("\nVariance explained:\n")
ve <- pca$sdev^2 / sum(pca$sdev^2)
print(round(ve, 3))
cat(sprintf("\nPC1 explains %.1f%% of variance\n", ve[1] * 100))

cat("\nLoadings (rotation):\n")
print(round(pca$rotation, 3))

# Total departures = simple sum (justified by equal PCA loadings)
combined$total_departures <- combined$pm_departures +
                             combined$go_departures +
                             combined$cab_departures
mean_total <- mean(combined$total_departures)

# ============================================================
# CHOW TEST ON PC1 (with and without 2022)
# ============================================================

# --- fast closed-form simple-OLS residual sum of squares (intercept + one slope) ---
# Numerically identical to lm(y ~ t) RSS (verified to < 1e-13) but ~100x faster.
# Removes the permutation-loop bottleneck (10,000 perms x every break x 3 lm fits,
# run twice) that pushed this script past the 200s road-test cap. set.seed(42) and
# n_perm are unchanged, so reported permutation p-values are identical.
.rss_lin <- function(y, t) {
  n <- length(y)
  if (n < 3) return(0)                 # <=2 points fit exactly (RSS 0), matching lm
  mt <- mean(t); my <- mean(y)
  Stt <- sum((t - mt)^2)
  if (Stt == 0) return(sum((y - my)^2))
  b <- sum((t - mt) * (y - my)) / Stt
  sum((y - (my - b * mt) - b * t)^2)
}
chow_regression <- function(y, t, k) {
  n <- length(y)
  if (k < 3 || k > n - 3) return(NA_real_)
  rss_pool  <- .rss_lin(y, t)
  rss_split <- .rss_lin(y[1:k], t[1:k]) + .rss_lin(y[(k+1):n], t[(k+1):n])
  p <- 2
  ((rss_pool - rss_split) / p) / (rss_split / (n - 2 * p))
}

run_chow <- function(df, y_col, label) {
  y <- df[[y_col]]
  t_seq <- seq_along(y)
  n <- length(y)
  ks <- seq(3, n - 3)
  fstats <- sapply(ks, function(k) chow_regression(y, t_seq, k))

  fs <- tibble(
    k     = ks,
    year  = df$year[ks],
    fstat = fstats,
    series = label
  ) |> filter(!is.na(fstat))

  crit <- qf(0.95, df1 = 2, df2 = n - 4)
  bp <- fs |> slice_max(fstat, n = 1)

  set.seed(42)
  n_perm <- 10000
  perm_maxF <- replicate(n_perm, {
    y_p <- sample(y)
    f_p <- sapply(ks, function(k) chow_regression(y_p, t_seq, k))
    max(f_p, na.rm = TRUE)
  })
  perm_p <- mean(perm_maxF >= bp$fstat)

  list(fs = fs, bp = bp, crit = crit, perm_p = perm_p, n = n)
}

res_all <- run_chow(combined, "total_departures", "All years")
res_ex  <- run_chow(combined |> filter(year != 2022), "total_departures", "Excluding 2022")

fs_both <- bind_rows(res_all$fs, res_ex$fs)

cat(sprintf("\n========== CHOW TEST ON PC1: ALL YEARS ==========\n"))
cat(sprintf("Break: %d, F(2,%d) = %.2f, perm p = %.4f\n",
            res_all$bp$year, res_all$n - 4, res_all$bp$fstat, res_all$perm_p))

cat(sprintf("\n========== CHOW TEST ON PC1: EXCLUDING 2022 ==========\n"))
cat(sprintf("Break: %d, F(2,%d) = %.2f, perm p = %.4f\n",
            res_ex$bp$year, res_ex$n - 4, res_ex$bp$fstat, res_ex$perm_p))

# ============================================================
# FIGURE: TWO PANELS (smoothed z-scores + Chow)
# ============================================================

# Prepare z-scored long data for LOESS panel
z_df <- combined |>
  mutate(
    z_pm  = as.numeric(scale(pm_departures)),
    z_go  = as.numeric(scale(go_departures)),
    z_cab = as.numeric(scale(cab_departures)),
    z_composite = (z_pm + z_go + z_cab) / 3
  )

z_long <- z_df |>
  select(year, PM = z_pm, `Great Officers` = z_go, Cabinet = z_cab) |>
  pivot_longer(-year, names_to = "series", values_to = "z")

# Compute LOESS endpoints for labels, then space them out
end_yr <- max(z_df$year)
lbl_series <- z_long |>
  group_by(series) |>
  summarise(y = predict(loess(z ~ year, span = 0.3),
                        newdata = data.frame(year = end_yr)),
            .groups = "drop") |>
  mutate(colour = "grey50", face = "plain", sz = 2.5)
comp_y <- predict(loess(z_composite ~ year, data = z_df, span = 0.3),
                  newdata = data.frame(year = end_yr))
lbl_all <- bind_rows(lbl_series,
                     tibble(series = "Composite", y = comp_y,
                            colour = "#000000", face = "bold", sz = 2.8)) |>
  arrange(y)
min_gap <- 0.12
for (i in 2:nrow(lbl_all)) {
  if (lbl_all$y[i] - lbl_all$y[i-1] < min_gap) {
    lbl_all$y[i] <- lbl_all$y[i-1] + min_gap
  }
}

# Top panel: LOESS-smoothed z-scores
p_top <- ggplot() +
  geom_smooth(data = z_long, aes(x = year, y = z, group = series),
              method = "loess", span = 0.3, se = FALSE,
              colour = "grey70", linewidth = 0.5, linetype = "dashed") +
  geom_smooth(data = z_df, aes(x = year, y = z_composite),
              method = "loess", span = 0.3, se = FALSE,
              colour = "#000000", linewidth = 1.2) +
  geom_text(data = lbl_all,
            aes(x = end_yr + 0.5, y = y, label = series),
            colour = lbl_all$colour, size = lbl_all$sz,
            fontface = lbl_all$face, hjust = 0) +
  scale_x_continuous(breaks = seq(1980, 2025, 5),
                     expand = expansion(add = c(0.5, 6))) +
  labs(x = NULL, y = "Standardised departures (z-score)\nLOESS-smoothed, span = 0.3") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank()
  )

# Bottom panel: dual Chow
p_bot <- ggplot(fs_both, aes(x = year, y = fstat, linetype = series)) +
  geom_hline(yintercept = res_all$crit, linetype = "dashed",
             colour = "#888888", linewidth = 0.5) +
  geom_line(colour = "#000000", linewidth = 0.6) +
  geom_point(data = res_all$bp, aes(x = year, y = fstat),
             shape = 21, fill = "white", colour = "#000000",
             size = 3.5, stroke = 1.3, inherit.aes = FALSE) +
  geom_point(data = res_ex$bp, aes(x = year, y = fstat),
             shape = 21, fill = "grey60", colour = "#000000",
             size = 3.5, stroke = 1.3, inherit.aes = FALSE) +
  annotate("text", x = res_all$bp$year - 2, y = res_all$bp$fstat,
           label = as.character(res_all$bp$year),
           colour = "#000000", size = 3, hjust = 1, fontface = "bold") +
  annotate("text", x = res_ex$bp$year - 2, y = res_ex$bp$fstat,
           label = as.character(res_ex$bp$year),
           colour = "#555555", size = 3, hjust = 1, fontface = "bold") +
  annotate("text", x = min(fs_both$year), y = res_all$crit + 0.2,
           label = "5% critical value", colour = "#888888", size = 2.5, hjust = 0) +
  scale_linetype_manual(values = c("All years" = "solid",
                                   "Excluding 2022" = "dotted"),
                        name = NULL) +
  scale_x_continuous(breaks = seq(1980, 2025, 5), expand = expansion(add = 0.5)) +
  labs(x = NULL, y = "Chow F(2, N\u22124)") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position    = c(0.15, 0.85),
    legend.text        = element_text(size = 8),
    legend.background  = element_rect(fill = "white", colour = NA)
  )

fig <- p_top +
  plot_annotation(
    title = "Figure 2.4: Executive instability, 1979\u20132025",
    subtitle = paste0(
      "LOESS-smoothed z-scores (span = 0.3). Dashed grey = PM, Great Officers, Cabinet. Bold black = composite mean.\n",
      "PCA: eigenvalue = ", round(pca$sdev[1]^2, 2),
      ", ", round(ve[1] * 100, 1), "% variance."
    ),
    caption = "Source: hand-coded (PM, Great Officers) / IfG (Cabinet). PCA loadings near-equal across all three series.",
    theme = theme(
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 9.0 in wide, so 15.5 pt), which is the ratio the narrow figures already had.
      plot.title    = element_text(face = "bold", size = 15.5),
      plot.subtitle = element_text(size = 8.5, colour = "grey30", lineheight = 1.2),
      plot.caption  = element_text(size = 7, colour = "grey40")
    )
  )

ggsave("figures/fig_2_4_executive_instability.png",
       fig, width = 9, height = 4.2, dpi = 300)
cat("\nSaved: figures/fig_2_4_executive_instability.png\n")

# ============================================================
# SAVE DATA
# ============================================================
write_csv(combined, "data/processed/executive_instability_annual.csv")
cat("Saved: data/processed/executive_instability_annual.csv\n")

cat("\n========== SCRIPT COMPLETE ==========\n")
