# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: scripts/05_comparative_turnover.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _ARCHIVE/scripts/superseded_17aug_prechow_scripts/scripts/05_comparative_turnover.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# 05_comparative_turnover.R — AUTO-DERIVED 17 Aug 2026. ⛔ DO NOT HAND-EDIT.
# ⭐ RENUMBERED 2.7 -> 2.6 (old Fig 2.3 dropped, everything shifts down one).
# ⚠ THIS FIGURE HAS NO CHOW PANEL. What it did carry was RESULTS IN THE SUBTITLE: a
#   difference-in-differences BREAK DATE, and a UK-acceleration coefficient with a
#   permutation p. Both are removed from the panel per house style (figures inform, text
#   concludes; subtitles describe rather than comment). The subtitle now says only what is
#   drawn. ⚠ Both statistics are still COMPUTED and printed to the console — they belong in
#   the footnote notes, not on the figure.
# ⭐ WORTH KEEPING IN THE TEXT: the UK-acceleration term (UK x time-squared) is a SHAPE claim,
#   and it is the same shape the turbulence index shows — flat then rising. That is a better
#   fit with the chapter's new framing than the DiD break date is.

# ============================================================
# 05_comparative_turnover.R
# Head of government turnover: UK vs comparable democracies
# UK, Australia, Canada, Japan (parliamentary PMs, 1945-2026)
# Germany (Chancellors, 1949-2026)
#
# Sources: gov.uk, bundeskanzler.de, kantei.go.jp, pm.gc.ca,
#          Australian Parliament Handbook, Britannica
# All records verified — see validation_checks/
# ============================================================

rm(list = ls())
.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
setwd(.ROOT)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, tidyr, patchwork, zoo)

# ============================================================
# DATA: ALL HEADS OF GOVERNMENT, 1945-2026
# ============================================================

uk <- tribble(
  ~name,                ~start,        ~end,
  "Attlee",             "1945-07-26",  "1951-10-26",
  "Churchill",          "1951-10-26",  "1955-04-05",
  "Eden",               "1955-04-06",  "1957-01-09",
  "Macmillan",          "1957-01-10",  "1963-10-18",
  "Douglas-Home",       "1963-10-19",  "1964-10-16",
  "Wilson (1st)",       "1964-10-16",  "1970-06-19",
  "Heath",              "1970-06-19",  "1974-03-04",
  "Wilson (2nd)",       "1974-03-04",  "1976-04-05",
  "Callaghan",          "1976-04-05",  "1979-05-04",
  "Thatcher",           "1979-05-04",  "1990-11-28",
  "Major",              "1990-11-28",  "1997-05-02",
  "Blair",              "1997-05-02",  "2007-06-27",
  "Brown",              "2007-06-27",  "2010-05-11",
  "Cameron",            "2010-05-11",  "2016-07-13",
  "May",                "2016-07-13",  "2019-07-24",
  "Johnson",            "2019-07-24",  "2022-09-06",
  "Truss",              "2022-09-06",  "2022-10-25",
  "Sunak",              "2022-10-25",  "2024-07-05",
  "Starmer",            "2024-07-05",  "2026-07-20",   # handover to Burnham verified 20 Jul 2026 (was 07-17)
  "Burnham",            "2026-07-20",  "2026-07-31"    # Burnham appointed PM 20 Jul 2026; 07-31 = shared censor date
) |> mutate(country = "UK")

germany <- tribble(
  ~name,                ~start,        ~end,
  "Adenauer",           "1949-09-20",  "1963-10-16",
  "Erhard",             "1963-10-16",  "1966-12-01",
  "Kiesinger",          "1966-12-01",  "1969-10-21",
  "Brandt",             "1969-10-21",  "1974-05-16",
  "Schmidt",            "1974-05-16",  "1982-10-01",
  "Kohl",               "1982-10-01",  "1998-10-27",
  "Schroeder",          "1998-10-27",  "2005-11-22",
  "Merkel",             "2005-11-22",  "2021-12-08",
  "Scholz",             "2021-12-08",  "2025-05-06",
  "Merz",               "2025-05-06",  "2026-07-31"
) |> mutate(country = "Germany")

canada <- tribble(
  ~name,                ~start,        ~end,
  "Mackenzie King",     "1945-01-01",  "1948-11-15",
  "St Laurent",         "1948-11-15",  "1957-06-21",
  "Diefenbaker",        "1957-06-21",  "1963-04-22",
  "Pearson",            "1963-04-22",  "1968-04-20",
  "Trudeau P (1st)",    "1968-04-20",  "1979-06-04",
  "Clark",              "1979-06-04",  "1980-03-03",
  "Trudeau P (2nd)",    "1980-03-03",  "1984-06-30",
  "Turner",             "1984-06-30",  "1984-09-17",
  "Mulroney",           "1984-09-17",  "1993-06-25",
  "Campbell",           "1993-06-25",  "1993-11-04",
  "Chretien",           "1993-11-04",  "2003-12-12",
  "Martin",             "2003-12-12",  "2006-02-06",
  "Harper",             "2006-02-06",  "2015-11-04",
  "Trudeau J",          "2015-11-04",  "2025-03-14",
  "Carney",             "2025-03-14",  "2026-07-31"
) |> mutate(country = "Canada")

australia <- tribble(
  ~name,                ~start,        ~end,
  "Curtin",             "1945-01-01",  "1945-07-05",
  "Forde",              "1945-07-06",  "1945-07-13",
  "Chifley",            "1945-07-13",  "1949-12-19",
  "Menzies",            "1949-12-19",  "1966-01-26",
  "Holt",               "1966-01-26",  "1967-12-19",
  "McEwen",             "1967-12-19",  "1968-01-10",
  "Gorton",             "1968-01-10",  "1971-03-10",
  "McMahon",            "1971-03-10",  "1972-12-05",
  "Whitlam",            "1972-12-05",  "1975-11-11",
  "Fraser",             "1975-11-11",  "1983-03-11",
  "Hawke",              "1983-03-11",  "1991-12-20",
  "Keating",            "1991-12-20",  "1996-03-11",
  "Howard",             "1996-03-11",  "2007-12-03",
  "Rudd (1st)",         "2007-12-03",  "2010-06-24",
  "Gillard",            "2010-06-24",  "2013-06-27",
  "Rudd (2nd)",         "2013-06-27",  "2013-09-18",
  "Abbott",             "2013-09-18",  "2015-09-15",
  "Turnbull",           "2015-09-15",  "2018-08-24",
  "Morrison",           "2018-08-24",  "2022-05-23",
  "Albanese",           "2022-05-23",  "2026-07-31"
) |> mutate(country = "Australia")

japan <- tribble(
  ~name,                ~start,        ~end,
  "Higashikuni",        "1945-08-17",  "1945-10-09",
  "Shidehara",          "1945-10-09",  "1946-05-22",
  "Yoshida (1st)",      "1946-05-22",  "1947-05-24",
  "Katayama",           "1947-05-24",  "1948-03-10",
  "Ashida",             "1948-03-10",  "1948-10-15",
  "Yoshida (2nd)",      "1948-10-15",  "1954-12-10",
  "Hatoyama I",         "1954-12-10",  "1956-12-23",
  "Ishibashi",          "1956-12-23",  "1957-02-25",
  "Kishi",              "1957-02-25",  "1960-07-19",
  "Ikeda",              "1960-07-19",  "1964-11-09",
  "Sato",               "1964-11-09",  "1972-07-07",
  "Tanaka",             "1972-07-07",  "1974-12-09",
  "Miki",               "1974-12-09",  "1976-12-24",
  "Fukuda T",           "1976-12-24",  "1978-12-07",
  "Ohira",              "1978-12-07",  "1980-06-12",
  "Suzuki",             "1980-07-17",  "1982-11-27",
  "Nakasone",           "1982-11-27",  "1987-11-06",
  "Takeshita",          "1987-11-06",  "1989-06-03",
  "Uno",                "1989-06-03",  "1989-08-10",
  "Kaifu",              "1989-08-10",  "1991-11-05",
  "Miyazawa",           "1991-11-05",  "1993-08-09",
  "Hosokawa",           "1993-08-09",  "1994-04-28",
  "Hata",               "1994-04-28",  "1994-06-30",
  "Murayama",           "1994-06-30",  "1996-01-11",
  "Hashimoto",          "1996-01-11",  "1998-07-30",
  "Obuchi",             "1998-07-30",  "2000-04-05",
  "Mori",               "2000-04-05",  "2001-04-26",
  "Koizumi",            "2001-04-26",  "2006-09-26",
  "Abe (1st)",          "2006-09-26",  "2007-09-26",
  "Fukuda Y",           "2007-09-26",  "2008-09-24",
  "Aso",                "2008-09-24",  "2009-09-16",
  "Hatoyama Y",         "2009-09-16",  "2010-06-08",
  "Kan",                "2010-06-08",  "2011-09-02",
  "Noda",               "2011-09-02",  "2012-12-26",
  "Abe (2nd)",          "2012-12-26",  "2020-09-16",
  "Suga",               "2020-09-16",  "2021-10-04",
  "Kishida",            "2021-10-04",  "2024-10-01",
  "Ishiba",             "2024-10-01",  "2025-10-21",
  "Takaichi",           "2025-10-21",  "2026-07-31"
) |> mutate(country = "Japan")

# ============================================================
# COMBINE AND COMPUTE TENURE
# ============================================================
all_leaders <- bind_rows(uk, germany, canada, australia, japan) |>
  mutate(
    start = as.Date(start),
    end   = as.Date(end),
    tenure_years = as.numeric(end - start) / 365.25
  )

cat("========== LEADERS BY COUNTRY ==========\n")
all_leaders |>
  group_by(country) |>
  summarise(
    n_leaders = n(),
    mean_tenure = round(mean(tenure_years), 2),
    median_tenure = round(median(tenure_years), 2),
    .groups = "drop"
  ) |>
  arrange(mean_tenure) |>
  print()

# ============================================================
# ROLLING AVERAGE OF LEADERSHIP CHANGES
# ============================================================

# Annual changes per country
changes <- all_leaders |>
  filter(start > as.Date("1945-01-01") | country == "Germany") |>
  mutate(change_year = as.numeric(format(start, "%Y")))

# Germany starts 1949
min_year <- 1946
max_year <- 2026

annual <- expand_grid(
  country = unique(all_leaders$country),
  year = min_year:max_year
) |>
  # Germany only from 1949
  filter(!(country == "Germany" & year < 1949)) |>
  left_join(
    changes |>
      group_by(country, change_year) |>
      summarise(n = n(), .groups = "drop"),
    by = c("country", "year" = "change_year")
  ) |>
  mutate(n = replace_na(n, 0)) |>
  arrange(country, year) |>
  group_by(country) |>
  mutate(rolling = zoo::rollmean(n, k = 5, fill = NA, align = "right")) |>
  ungroup() |>
  filter(!is.na(rolling)) |>
  mutate(country = factor(country,
    levels = c("UK", "Australia", "Japan", "Canada", "Germany")))

# Others average
others_avg <- annual |>
  filter(country != "UK") |>
  group_by(year) |>
  summarise(rolling = mean(rolling, na.rm = TRUE), .groups = "drop") |>
  mutate(country = "Other 4 (mean)")

uk_data <- annual |> filter(country == "UK")

# ============================================================
# STATISTICAL TESTS (on annual counts, full series)
# ============================================================

annual_raw <- expand_grid(
  country = unique(all_leaders$country),
  year = 1950:2026
) |>
  filter(!(country == "Germany" & year < 1950)) |>
  left_join(
    changes |>
      group_by(country, change_year) |>
      summarise(n = n(), .groups = "drop"),
    by = c("country", "year" = "change_year")
  ) |>
  mutate(
    n = replace_na(n, 0),
    uk = as.integer(country == "UK"),
    t = year - 1950
  )

# Test 1: UK vs others overall
m1 <- lm(n ~ uk, data = annual_raw)
cat("\n========== TEST 1: UK vs OTHERS (level) ==========\n")
cat(sprintf("UK mean: %.3f changes/yr\n", mean(annual_raw$n[annual_raw$uk == 1])))
cat(sprintf("Others mean: %.3f changes/yr\n", mean(annual_raw$n[annual_raw$uk == 0])))
cat(sprintf("Difference: %.3f, p = %.4f\n",
            coef(m1)["uk"], summary(m1)$coefficients["uk", "Pr(>|t|)"]))

# Test 2: Divergence over time
m2 <- lm(n ~ uk * t, data = annual_raw)
cat("\n========== TEST 2: UK DIVERGENCE OVER TIME ==========\n")
print(round(coef(summary(m2)), 4))
cat(sprintf("\nUK*time interaction: %.4f (p = %.4f)\n",
            coef(m2)["uk:t"], summary(m2)$coefficients["uk:t", "Pr(>|t|)"]))

# Permutation test (linear)
set.seed(42)
n_perm <- 10000
obs_interact <- coef(m2)["uk:t"]
perm_interact <- replicate(n_perm, {
  d_perm <- annual_raw
  d_perm$uk <- sample(d_perm$uk)
  coef(lm(n ~ uk * t, data = d_perm))["uk:t"]
})
perm_p <- mean(abs(perm_interact) >= abs(obs_interact))
cat(sprintf("Permutation p (two-sided, %d perms): %.4f\n", n_perm, perm_p))

# Test 3: Quadratic interaction — does UK ACCELERATE relative to others?
annual_raw$t2 <- annual_raw$t^2
m3 <- lm(n ~ uk * (t + t2), data = annual_raw)
cat("\n========== TEST 3: UK ACCELERATION (quadratic interaction) ==========\n")
cat("Model: changes ~ UK + time + time² + UK*time + UK*time²\n")
print(round(coef(summary(m3)), 4))
obs_quad <- coef(m3)["uk:t2"]
cat(sprintf("\nUK*time² interaction: %.6f (p = %.4f)\n",
            obs_quad, summary(m3)$coefficients["uk:t2", "Pr(>|t|)"]))

# Permutation test on quadratic interaction
set.seed(42)
perm_quad <- replicate(n_perm, {
  d_perm <- annual_raw
  d_perm$uk <- sample(d_perm$uk)
  coef(lm(n ~ uk * (t + t2), data = d_perm))["uk:t2"]
})
perm_p_quad <- mean(abs(perm_quad) >= abs(obs_quad))
cat(sprintf("Permutation p (two-sided, %d perms): %.4f\n", n_perm, perm_p_quad))

# Test 4: Piecewise DiD — scan for breakpoint in UK-others divergence
cat("\n========== TEST 4: PIECEWISE DiD (breakpoint scan) ==========\n")

# For each candidate break year, fit:
# n ~ uk + post + uk*post (where post = year >= break)
break_years <- 1970:2020
did_results <- sapply(break_years, function(by) {
  annual_raw$post <- as.integer(annual_raw$year >= by)
  m <- lm(n ~ uk * post, data = annual_raw)
  c(year = by,
    did_coef = coef(m)["uk:post"],
    did_p = summary(m)$coefficients["uk:post", "Pr(>|t|)"])
})
did_df <- as.data.frame(t(did_results))
names(did_df) <- c("year", "did_coef", "did_p")

# Best breakpoint = largest absolute DiD coefficient
best_break <- did_df[which.max(abs(did_df$did_coef)), ]
cat(sprintf("Best breakpoint: %d\n", best_break$year))
cat(sprintf("DiD coefficient: %.4f (UK changes %.4f more per year post-break)\n",
            best_break$did_coef, best_break$did_coef))
cat(sprintf("Parametric p: %.4f\n", best_break$did_p))

# Permutation test on best-break DiD
set.seed(42)
obs_did <- best_break$did_coef
perm_did <- replicate(n_perm, {
  d_perm <- annual_raw
  d_perm$uk <- sample(d_perm$uk)
  d_perm$post <- as.integer(d_perm$year >= best_break$year)
  coef(lm(n ~ uk * post, data = d_perm))["uk:post"]
})
perm_p_did <- mean(abs(perm_did) >= abs(obs_did))
cat(sprintf("Permutation p (two-sided, %d perms): %.4f\n", n_perm, perm_p_did))

# Pre/post means for the best break
pre_uk  <- mean(annual_raw$n[annual_raw$uk == 1 & annual_raw$year < best_break$year])
post_uk <- mean(annual_raw$n[annual_raw$uk == 1 & annual_raw$year >= best_break$year])
pre_oth <- mean(annual_raw$n[annual_raw$uk == 0 & annual_raw$year < best_break$year])
post_oth <- mean(annual_raw$n[annual_raw$uk == 0 & annual_raw$year >= best_break$year])
cat(sprintf("\nPre-%d:  UK = %.3f, Others = %.3f (UK - Others = %.3f)\n",
            best_break$year, pre_uk, pre_oth, pre_uk - pre_oth))
cat(sprintf("Post-%d: UK = %.3f, Others = %.3f (UK - Others = %.3f)\n",
            best_break$year, post_uk, post_oth, post_uk - post_oth))

# ============================================================
# FIGURE
# ============================================================

# ============================================================
# LOESS-SMOOTHED FIGURE
# ============================================================

# Annual counts for all countries (for smoothing)
annual_all <- expand_grid(
  country = unique(all_leaders$country),
  year = min_year:max_year
) |>
  filter(!(country == "Germany" & year < 1949)) |>
  left_join(
    changes |>
      group_by(country, change_year) |>
      summarise(n = n(), .groups = "drop"),
    by = c("country", "year" = "change_year")
  ) |>
  mutate(
    n = replace_na(n, 0),
    country = factor(country,
      levels = c("UK", "Australia", "Japan", "Canada", "Germany"))
  )

# Others average per year (unsmoothed, then smooth)
others_annual <- annual_all |>
  filter(country != "UK") |>
  group_by(year) |>
  summarise(n = mean(n, na.rm = TRUE), .groups = "drop")

uk_annual <- annual_all |> filter(country == "UK")

# LOESS span — 0.3 gives a good balance of smooth and responsive
loess_span <- 0.3

# Predict smooth curves
uk_loess <- loess(n ~ year, data = uk_annual, span = loess_span)
uk_smooth <- tibble(
  year = uk_annual$year,
  smooth = pmax(predict(uk_loess), 0)  # floor at 0
)

others_loess <- loess(n ~ year, data = others_annual, span = loess_span)
others_smooth <- tibble(
  year = others_annual$year,
  smooth = pmax(predict(others_loess), 0)
)

# Individual country smooths
indiv_smooth <- annual_all |>
  filter(country != "UK") |>
  group_by(country) |>
  group_modify(~ {
    lo <- loess(n ~ year, data = .x, span = loess_span)
    tibble(year = .x$year, smooth = pmax(predict(lo), 0))
  }) |>
  ungroup()

country_lines <- c(
  "UK"        = "solid",
  "Australia" = "dashed",
  "Japan"     = "dotted",
  "Canada"    = "longdash",
  "Germany"   = "dotdash"
)

fig <- ggplot() +
  # Individual country smooths (thin, light grey)
  geom_line(data = indiv_smooth,
            aes(x = year, y = smooth, linetype = country),
            linewidth = 0.4, colour = "#bbbbbb") +
  # Others average smooth (thick grey)
  geom_line(data = others_smooth,
            aes(x = year, y = smooth),
            linewidth = 1.2, colour = "#888888") +
  # UK smooth (thick black)
  geom_line(data = uk_smooth,
            aes(x = year, y = smooth),
            linewidth = 1.2, colour = "#000000") +
  # Labels — UK and Others (bold lines)
  annotate("text", x = 2027, y = tail(uk_smooth$smooth, 1),
           label = "UK", fontface = "bold", size = 3.5, hjust = 0) +
  annotate("text", x = 2027, y = tail(others_smooth$smooth, 1),
           label = "Others", colour = "#888888", fontface = "bold",
           size = 3.5, hjust = 0) +
  # Labels — individual countries (at end of each line)
  annotate("text", x = 2027,
           y = tail(indiv_smooth$smooth[indiv_smooth$country == "Japan"], 1),
           label = "Japan", colour = "#bbbbbb", size = 2.8, hjust = 0) +
  annotate("text", x = 2027,
           y = tail(indiv_smooth$smooth[indiv_smooth$country == "Australia"], 1),
           label = "Australia", colour = "#bbbbbb", size = 2.8, hjust = 0) +
  annotate("text", x = 2027,
           y = tail(indiv_smooth$smooth[indiv_smooth$country == "Canada"], 1),
           label = "Canada", colour = "#bbbbbb", size = 2.8, hjust = 0) +
  annotate("text", x = 2027,
           y = tail(indiv_smooth$smooth[indiv_smooth$country == "Germany"], 1),
           label = "Germany", colour = "#bbbbbb", size = 2.8, hjust = 0) +
  scale_linetype_manual(values = country_lines, name = NULL) +
  scale_x_continuous(breaks = seq(1950, 2025, 10),
                     expand = expansion(add = c(0.5, 4))) +
  scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1))) +
  labs(x = NULL, y = "Leadership changes per year\n(LOESS-smoothed)") +
  theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position    = "none"
  ) +
  plot_annotation(
    title = "Figure 2.5: Leadership turnover in five parliamentary democracies, 1945\u20132026",
    subtitle = paste0(
      "LOESS-smoothed (span = ", loess_span, "). Bold black = UK; bold grey = mean of Germany, Canada, Australia, Japan."
    ),
    caption = "Sources: gov.uk, bundeskanzler.de, kantei.go.jp, pm.gc.ca, Australian Parliament Handbook. Germany from 1949.",
    theme = theme(
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 10.0 in wide, so 17.5 pt), which is the ratio the narrow figures already had.
      plot.title    = element_text(face = "bold", size = 17.5),
      plot.subtitle = element_text(size = 8.5, colour = "grey30", lineheight = 1.2),
      plot.caption  = element_text(size = 7, colour = "grey40")
    )
  )

ggsave("figures/fig_2_5_comparative_tenure.png",
       fig, width = 10, height = 5, dpi = 300)
cat("\nSaved: figures/fig_2_5_comparative_tenure.png\n")

# ============================================================
# SAVE DATA
# ============================================================
write.csv(all_leaders, "data/processed/comparative_leaders.csv", row.names = FALSE)
cat("Saved: data/processed/comparative_leaders.csv\n")

cat("\n========== SCRIPT COMPLETE ==========\n")
