# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/parliamentary_dislocation/10_three_panel_summary.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _superseded_17aug/data_workspace_2026-07/parliamentary_dislocation/10_three_panel_summary.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# ⭐ RENUMBERED 2.12 -> 2.11, 17 Aug 2026 (old Fig 2.3 dropped; everything after shifts down one).
# ⚠ Output renamed to the PRINTED name — the old file was called "..._3panel_nochow.png", which
#   was wrong twice over: the figure has FOUR panels, and a printed figure must not be named
#   after a panel it does not contain.
# ⛔ Panel E (Chow F-sweep) was removed earlier; panels are A/B/C/D via labs(tag=), per
#   FIGURE_STYLE_GUIDE.md. ⚠ Panel E is still BUILT above but not drawn.

# 10_three_panel_summary.R — AUTO-DERIVED from 10_three_panel_summary.R, 17 Aug 2026.
# ⛔ DO NOT EDIT BY HAND. PJ, 17 Aug: drop the Chow panels from the Ch2 figures; each series' shape
# is carried instead by one summary table (nonlinear_modelling/ch2_shapes_table.tex).
# ⚠ EVERY ggsave in this file is redirected to a _nochow filename. The originals are never touched.
# ⚠ This variant drops a PURE TEST panel. No data panel is removed.

# 10_three_panel_summary.R — Figure 2.12, parliamentary instability (revised 3 Aug: now 5 panels,
# per PJ: "A cowley b. instability c. Lords, d. PCA and e. chow on PCA").
#   A = Cowley's rebellion rate (the one consistent series, corrected, 1979-2026)
#   B = the instability index (4-component Commons dislocation index, after excluding policy
#       reversals, abnormal prorogation/order-paper seizures, and the majority-adjusted residual —
#       see METHOD.md §8-13)
#   C = House of Lords defeats panel
#   D = the combined PCA (Cowley + instability + Lords, civility deliberately excluded — see
#       16_final_three_way_pca.R; civility reported separately, not in this combined index)
#   E = the Chow structural-break test on the combined PCA series
# Hard-boiled house style throughout: descriptive subtitles only, no stated findings, except the
# permutation p-value on the Chow panel (Figs 2.1-2.8 precedent).
# Non-destructive: reads existing project files read-only, writes ONLY into this folder (plus the
# already-agreed sync to figures/).
suppressMessages({library(dplyr); library(readr); library(ggplot2); library(patchwork)})
WS <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
setwd(file.path(WS, "parliamentary_dislocation"))
source(file.path(WS, "chow_standardized", "chow_test.R"))
START <- 1979; END <- 2026

house <- theme_minimal(base_size=10) +
  theme(panel.grid.minor=element_blank(), panel.grid.major.x=element_blank(), legend.position="none",
        plot.subtitle=element_text(face="italic", colour="grey30", size=9),
        axis.title=element_text(size=9, colour="grey20"), plot.tag=element_text(face="bold", size=11))
xaxis <- list(scale_x_continuous(breaks=seq(1980,END,5)), coord_cartesian(xlim=c(START,END)))

# ---- Panel A: Cowley's rebellion rate ----
reb <- read_csv(file.path(WS,"ch3_pipeline_restored","data","processed","rebellions_annual.csv"),
                 show_col_types=FALSE) |> filter(year>=START, year<=END)
pA <- ggplot(reb, aes(year, rebellion_pct)) +
  geom_step(direction="hv", linewidth=0.7, colour="black") +
  geom_point(size=1.2, colour="black") +
  xaxis + labs(tag="A", x=NULL, y="Backbench rebellion rate (%)",
    subtitle="Backbench rebellion rate, by Parliament (Cowley & Stuart)") +
  house

# ---- Panel B: the instability index (4-component Commons dislocation index) ----
idx <- read_csv("parliamentary_dislocation_index.csv", show_col_types=FALSE) |>
  filter(!is.na(dislocation_index))
pB <- ggplot(idx, aes(year, dislocation_index)) +
  geom_hline(yintercept=0, colour="grey70", linewidth=0.4) +
  geom_line(colour="black", linewidth=0.7) + geom_point(colour="black", size=1.2) +
  xaxis + labs(tag="B", x=NULL, y="Instability index (z)", subtitle="Instability index") +
  house

# ---- Panel C: House of Lords defeats, PER YEAR ----
# ⭐ CHANGED 17 Aug, PJ: "years for lords panel c".
# ⛔ WHY: the official parliament.uk series is BY SESSION, and the old panel step-carried each
# session's WHOLE total across every calendar year it spanned. Sessions are not equal lengths -
# 2010-12, 2017-19, 2019-21 and 2024-26 all run about two years - so long sessions were inflated
# and the 2024- session put 208 on 2024, 2025 AND 2026. Per year that session runs at 104, which
# is BELOW 2021 (128) and 2022 (125): the apparent record spike was a session-length artefact.
# ✅ The break year is 2016 on either measure (raw sup-F 22.86, per-year 19.79, both p=0.0002),
# and the per-year version gives slightly HIGHER PC1 variance and a higher Lords loading.
lords <- read_csv("lords_official_rebuild/lords_defeats_annual_official.csv", show_col_types=FALSE)
pC <- ggplot(lords, aes(year, rate)) +
  geom_line(colour="black", linewidth=0.7) + geom_point(colour="black", size=1.2) +
  xaxis + labs(tag="C", x=NULL, y="Government defeats per year",
    subtitle="House of Lords government defeats, per year of session") +
  house

# ---- Panel D: the combined PCA (Cowley + instability + Lords) ----
pcadat <- read_csv("three_way_pca.csv", show_col_types=FALSE)
pD <- ggplot(pcadat, aes(year, pc1)) +
  geom_hline(yintercept=0, colour="grey70", linewidth=0.4) +
  geom_line(colour="black", linewidth=0.7) + geom_point(colour="black", size=1.2) +
  xaxis + labs(tag="D", x=NULL, y="PC1 (z)",
    subtitle="Parliamentary instability, combined (first principal component)") +
  house

# ---- Panel E: the Chow structural-break test, on the combined PCA ----
sb <- chow_sweep(pcadat$year, pcadat$pc1)
cat(sprintf("=== PANEL E CHOW (combined 3-way PCA): peak %d, F(2,%d)=%.2f, perm p=%.4f ===\n",
            sb$peak_year, sb$n-4, sb$peak_F, sb$perm_p))
pE <- ggplot(sb$curve, aes(year, F)) +
  geom_hline(yintercept=sb$crit_5pct, linetype="dashed", colour="grey55", linewidth=0.5) +
  geom_line(colour="black", linewidth=0.6) +
  geom_point(data=sb$curve[which.max(sb$curve$F), , drop=FALSE],
             shape=21, fill="white", colour="black", size=3, stroke=1.2) +
  annotate("text", x=min(sb$curve$year), y=sb$crit_5pct,
           label="5% critical value", colour="grey50", size=2.5, hjust=0, vjust=-0.6) +
  xaxis + labs(tag="E", x="Year", y=sprintf("Chow F(2,%d)", sb$n-4),
    subtitle=sprintf("Structural break (perm. p = %.3f)", sb$perm_p)) +
  house

fig <- pA / pB / pC / pD +
  plot_layout(heights=c(1,1,1,1)) +
  # 17 Aug: colon + en dash, matching every other figure title in the chapter.
  plot_annotation(title=paste0("Figure 2.10: Parliamentary instability, ", START, "\u2013", END),
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 8.5 in wide, so 15 pt), which is the ratio the narrow figures already had.
    theme=theme(plot.title=element_text(face="bold", size=15)))
ggsave("fig_2_10_parliamentary_instability.png", fig, width=8.5, height=12.4, dpi=200, bg="white")
cat("\nwrote fig_parliamentary_instability_3panel.png (now 5 panels: A-E)\n")
