# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch2_public_opinion/29_fig_agenda_no_pca.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _superseded_17aug/data_workspace_2026-07/ch2_public_opinion/29_fig_agenda_no_pca.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# 29_fig_agenda_no_pca.R — AUTO-DERIVED from 29_fig_agenda_no_pca.R, 17 Aug 2026.
# ⛔ DO NOT EDIT BY HAND. PJ, 17 Aug: drop the Chow panels from the Ch2 figures; each series' shape
# is carried instead by one summary table (nonlinear_modelling/ch2_shapes_table.tex).
# ⭐ RENUMBERED 2.10 -> 2.9, 17 Aug 2026 (old Fig 2.3 dropped; everything after shifts down one).
# ⚠ Output now carries the PRINTED name (fig_2_8_public_agenda.png), not a _nochow suffix — a
#   printed figure must not be named after a panel it does not contain.
# ⚠ Panel letters resequenced A/B/C: the removed Chow panel had left a gap (they ran A, B, D).
# ⭐ 17 Aug: this figure was BRIEFLY normalised to an "A. " subtitle prefix, then REVERTED. It was
#   already correct: FIGURE_STYLE_GUIDE.md (25 Jul) specifies bold labs(tag=) letters and italic
#   grey30 subtitles. The guide is the standard; the other figures are being brought TO it.
# ⚠ This variant drops a PURE TEST panel. No data panel is removed.

# 29_fig_agenda_no_pca.R — Figure 2.10 WITHOUT the PCA composite.
#
# Decision (PJ, 28 Jul 2026): drop the PCA panel. Diversity (ENI) and volatility (KL) are very
# different measures and are only weakly correlated (r = -0.34); collapsing them into one axis
# produced a panel whose visible peaks were 60-85% KL while the step it existed to show was
# two-thirds ENI, and which DILUTED the break (composite F=73 vs ENI alone F=120).
# Replaced by: each measure keeps its own panel and gets its OWN Chow break.
#
# Supersedes 28_fig_camargo_diversity_pca.R (kept on disk, not deleted).
# Same locked basis as before: ANNUAL, UN-SMOOTHED, stable-CAP.
# CORRECTION (28 Jul): script 28's header said Camargo's "fully-smoothed replication lives in
# robustness_checks/RC_ch2_camargo_replication/". It does NOT. That folder's replication
# (build_fig_camargo_replication.R + camargo_replication_*.csv) is UN-smoothed. The 5-month
# running mean + ep=0.01 was run once as a 1985-2016 diagnostic and reported in prose in that
# folder's README; it was never saved as a series or a script. See 30_kl_smoothed_break_check.R.
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, ggplot2, patchwork, tibble, scales, ggrepel)
.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(dirname(sub("^--file=", "", m))) else getwd()
})
setwd(.ROOT)
START <- 1979; LABELPAD <- 7

house <- theme_minimal(base_size=10) +
  theme(panel.grid.minor=element_blank(), panel.grid.major.x=element_blank(), legend.position="none",
        plot.subtitle=element_text(face="italic", colour="grey30", size=9),
        axis.title=element_text(size=9, colour="grey20"), plot.tag=element_text(face="bold", size=11))

idx <- read_csv("agenda_indices_annual.csv", show_col_types=FALSE)
mon <- read_csv("ipsos_issues_index_monthly_1974_2026_mapped.csv", show_col_types=FALSE)
# endpoint rule: last year with >=6 months of data (excludes 2026, which has 3)
END <- max((mon |> group_by(year) |> summarise(nm=n_distinct(month)) |> filter(nm>=6))$year)
xaxis <- list(scale_x_continuous(breaks=seq(1980,END,5)), coord_cartesian(xlim=c(START, END+LABELPAD)))
idxf <- idx |> filter(year>=START, year<=END) |> mutate(sparse = year<=1983)

# ---- Chow: THE STANDARDISED HOUSE TEST ----------------------------------------------------------
# CORRECTED 28 Jul: this script originally rolled its own mean-shift Chow (df1=1, fixed 3-obs trim).
# That broke project convention — `chow_standardized/` (19 Jul) is the book's single implementation,
# already applied to fig 2.6, PM/cabinet turnover, government defeats and the MARSS latents. Fig 2.10
# now uses it, so breaks here are reported on the same basis as every other figure:
#   - REGRESSION-based Quandt–Andrews sup-F: intercept AND slope may break (df1 = 2)
#   - 15% trim each end, so endpoint spikes cannot be selected as the global break
#   - significance from a 10,000-draw permutation max-F null, seed 42 (honest, since k is searched)
#
# CONSEQUENCE, declared not hidden: on ENI this moves the preferred break from 1997 to 2014, and F
# from 120.1 to 7.25 (perm p = 0.028). Not a contradiction — the regression version fits a trend
# within each segment, so it absorbs the 1997 LEVEL step into the ongoing rise and instead selects
# where that rise ACCELERATES (slope 0.12/yr before vs 0.25/yr after). The two tests ask different
# questions; their F values are not comparable (different df and null).
source("../chow_standardized/chow_test.R")
# DECISION (PJ, 28 Jul): break-test DIVERSITY ONLY.
# KL is not a level series — it is the divergence between consecutive years, i.e. already a measure
# of CHANGE (year-on-year "surprise"). A Chow test looks for a shift in the mean of a level series,
# so applying it to a surprise measure is a category error, and the unstable date it returned
# (1983/1989/1993/1997 depending on spec) is the symptom of that mismatch rather than a fixable
# data problem. Panel C therefore shows the series with NO break line. This also keeps the
# reporting consistent with the other chapter figures: one break, on the level series.
dE <- idxf |> select(year, v=eni) |> na.omit()
bE <- chow_sweep(dE$year, dE$v)          # house defaults: trim .15, nperm 10000, seed 42

# panel; br=NULL draws NO turning-point line and adds no break statistics to the subtitle
line_panel <- function(col, tag, ylab, sub, br=NULL){
  d <- idxf |> select(year, v=all_of(col), sparse) |> na.omit()
  p <- ggplot(d, aes(year, v))
  if (!is.null(br)) p <- p +
    geom_vline(xintercept=br$peak_year, linetype="dashed", colour="grey45") +
    annotate("text", x=br$peak_year+0.6, y=max(d$v, na.rm=TRUE),
             label=paste0("turning point ", br$peak_year), hjust=0, size=3, colour="grey25")
  p + geom_line(colour="black", linewidth=0.75, na.rm=TRUE) +
    geom_point(data=subset(d,!sparse), colour="black", size=1.2, na.rm=TRUE) +
    geom_point(data=subset(d, sparse), shape=21, colour="black", fill="white", stroke=0.7, size=1.5, na.rm=TRUE) +
    xaxis + labs(tag=tag, x=NULL, y=ylab,
      subtitle=if (is.null(br)) sub else
        paste0(sub, ". Sup-F turning point ", br$peak_year,
               " (F=", round(br$peak_F,1), ", perm p=", format.pval(br$perm_p, digits=2, eps=1e-4), ")")) + house }

# ---- Panel A: leading issues' share (context; 1981 interpolated) ----
sh0 <- mon |> group_by(year, cap_code) |> summarise(pct=mean(percent_raw, na.rm=TRUE), .groups="drop") |>
  group_by(year) |> mutate(share=pct/sum(pct)) |> ungroup() |> filter(year>=START, year<=END) |> select(year, cap_code, share)
d80 <- sh0|>filter(year==1980)|>select(cap_code,s80=share); d82 <- sh0|>filter(year==1982)|>select(cap_code,s82=share)
imp81 <- full_join(d80,d82,by="cap_code")|>mutate(s80=coalesce(s80,0),s82=coalesce(s82,0),share=(s80+s82)/2)|>
  filter(share>0)|>mutate(year=1981L, share=share/sum(share))|>select(year,cap_code,share)
shares <- bind_rows(sh0, imp81)
topics <- c(`1`="Economy",`3`="Health/NHS",`5`="Unemployment",`6`="Education",`9`="Immigration",
            `12`="Crime",`13`="Welfare",`14`="Housing",`19`="Europe/int'l",`20`="Government")
top6 <- shares|>filter(cap_code!=99)|>group_by(cap_code)|>summarise(m=mean(share))|>slice_max(m,n=6)|>pull(cap_code)
greys <- c("grey15","grey35","grey50","grey58","grey66","grey72"); ltys <- c("solid","longdash","dashed","dotdash","dotted","twodash")
names(greys)<-names(ltys)<-as.character(top6)
labA <- shares|>filter(cap_code%in%top6, year==END)|>mutate(lab=topics[as.character(cap_code)])
pA <- shares|>filter(cap_code%in%top6)|>ggplot(aes(year,share,colour=factor(cap_code),linetype=factor(cap_code)))+
  geom_line(linewidth=0.6)+
  geom_text_repel(data=labA, aes(x=END,y=share,label=lab,colour=factor(cap_code)), hjust=0, size=2.5,
     direction="y", nudge_x=2, segment.size=0.2, segment.colour="grey80", min.segment.length=0, xlim=c(END+0.8, END+LABELPAD))+
  scale_colour_manual(values=greys)+scale_linetype_manual(values=ltys)+scale_y_continuous(labels=percent_format(accuracy=1))+
  xaxis+labs(tag="A", x=NULL, y="Share of mentions", subtitle="Most important issue mentions")+house
# PJ, 31 Jul: panel/figure text is descriptive only (what's shown), not commentary (no stats, no
# citations, no findings on the panel) — full spec/citations live in the script comments and
# FIG211_NOTES.md-equivalent for this figure, for the footnote/text.

pB <- line_panel("eni","B","Effective no. of issues", "Effective number of issues (ENI)")
# No break line/annotation on B any more — the break test gets its own dedicated panel (below,
# swapped to position C per PJ, 31 Jul), so B stays a plain descriptive level series.

pD_kl <- line_panel("kl_churn","C","KL divergence (bits)", "KL divergence")
# ---- Break-test panel (was D, now C — swapped per PJ, 31 Jul): F-sweep across candidate break
# years, 5% critical line, peak marked. The sweep legitimately stops short of both ends (15% trim),
# so the panel has an honest gap rather than being stretched to the full span.
fd <- bE$curve
pk <- fd[which.max(fd$F), ]
pC_break <- ggplot(fd, aes(year, F)) +
  geom_hline(yintercept=bE$crit_5pct, linetype="dashed", colour="grey65") +
  geom_line(colour="grey30", linewidth=0.7) + geom_point(colour="grey30", size=1.4) +
  geom_point(data=pk, colour="black", size=2.8) +
  annotate("text", x=pk$year+0.5, y=pk$F, label=pk$year, colour="black", hjust=0, size=3) +
  annotate("text", x=min(fd$year), y=bE$crit_5pct, label="5%", colour="grey55",
           vjust=-0.5, hjust=0, size=2.8) +
  xaxis + labs(tag="C", x="Candidate break year", y="Chow F(2, n-4)",
    subtitle="Structural break on diversity") + house

fig <- pA/pB/pD_kl + plot_layout(heights=c(1.15,1,1)) +
  plot_annotation(title=paste0("Figure 2.8: The British public agenda, ", START, "–", END),
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 9.0 in wide, so 15.5 pt), which is the ratio the narrow figures already had.
    theme=theme(plot.title=element_text(face="bold", size=15.5)))
# No figure-level subtitle (PJ, 31 Jul) — title only. Panel order swapped C<->D (break test now
# C, KL divergence now D) per PJ's steer same day.
ggsave("fig_2_8_public_agenda.png", fig, width=9, height=10.1, dpi=200)

# ---- declare the break statistics (DIVERSITY ONLY — see the decision note above) ----
brk <- tibble(
  series = "eni (diversity, Fig 2.10 panel B)", n = bE$n,
  coverage = paste0(START, "-", END),
  chow_peak_year = bE$peak_year, peak_F = round(bE$peak_F,2),
  crit_5pct = round(bE$crit_5pct,2), perm_p = bE$perm_p,
  slope_before = round(bE$slope_before,4), slope_after = round(bE$slope_after,4),
  test = "standardised regression-based Quandt-Andrews sup-F (chow_standardized/chow_test.R)",
  note = "KL deliberately NOT tested: a divergence (change) measure, not a level series")
write_csv(brk, "agenda_breaks_no_pca.csv")
print(as.data.frame(brk))
cat("\nsaved fig_ch2_agenda_diversity_volatility_1979_2025.png (", START, "-", END, ")\n")
