# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41_career_politicians.R
# 41_career_politicians.R
# Political professionals as % of MPs, 1974–2019
#
# Analytical purpose (Ch3 — The Political Class):
#   Shows the long-run growth in MPs with no substantial career outside
#   politics (university → researcher/SPAD/party worker → MP). The variable
#   of interest is career experience, NOT social class. Connects to the
#   experimental literature on risk appetite and evidence use.
#
#   KEY INTERPRETIVE NOTE: trend is long-run and substantially predates 2014.
#   The figure is NOT a post-2014 breakpoint argument. It establishes that
#   the modern political class is structurally different from its predecessors.
#   Consistent with causal plausibility framing: these structural features
#   amplify turbulence once started, but the figure cannot carry more weight.
#
# DATA SOURCES:
#   1974: Allen et al. (2020) EPSR — "political occupation only" MPs;
#         comparable but not identical to Criddle definition (open circle).
#   1983, 2010, 2015: Byron Criddle surveys in Butler/Cowley/Kavanagh British
#         General Election volumes; correct compiled citation is HC Library
#         CBP-7529 (CBP-7483 is wrong — that briefing covers gender/age/
#         ethnicity/education, not occupation). CBP-7529 Table 11a spot-check
#         (3 Sep 2026) confirms these figures against the primary Nuffield
#         data: 1983 3.18%, 2010 14.49%, 2015 17.09% (within rounding).
#   1979: NOT Criddle — Butler & Kavanagh's own chapter (Criddle's first
#         "Candidates" chapter was 1983). CBP-7529 spot-check: 3.45% vs coded
#         3.0%, a ~4pp gap flagged for physical-volume verification (4 Sep).
#   2019: NOT Criddle — Butler (C.)/Campbell/Hudson, "Political Recruitment
#         Under Pressure, Again," in British General Election of 2019.
#         Reported only as a range ("~20-22%"); no independent cross-check
#         available (CBP-7529's own 2017/2019 table uses a different,
#         non-comparable classification basis).
#   1987, 1992, 1997, 2001, 2005: Henn (2018) Table 6, "Politician/Pol
#         Organiser" row — his own narrower category, matching Criddle's
#         definition directly (distinct from his broader "Westminster Group"
#         row, which also includes journalists and lobbyists). No calibration
#         or adjustment needed — reported directly by election year. Values:
#         1987=5.4, 1992=7.3, 1997=9.5, 2001=10.5, 2005=14.1. Cross-checked
#         against CBP-7529's own equivalent row (1979=3.45, 1983=3.18,
#         2010=14.49) — the two independent compilations converge to within
#         0.05pp, both drawing on the same underlying BGE data. (Previous
#         version of this script used the broader Westminster Group row minus
#         a 6.7pp calibration adjustment; replaced 4 Sep 2026 — PJ: "keep to
#         Criddle throughout and use Henn to get there.")
#   Definition: MPs whose ONLY pre-parliamentary occupations were political
#   (party worker, researcher, SPAD, political lobbyist). Excludes MPs who
#   also held substantial non-political roles.
#
#   NOTE: Shown as points only; Henn interior points shown as triangles
#   (direct citation, no error bars — see 1987-2005 note above).
#
#   DATA FILE: data/raw/career_pols_DATA_ENTRY.csv
#
# OUTPUT:
#   figures/ch3_career_politicians.png

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, readr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})  # portable project root: works via Rscript from anywhere, or falls back to
    # getwd() when sourced interactively (assumes ch3_pipeline_restored/ as cwd)
PROJECT <- .ROOT
DATA_IN <- file.path(PROJECT, "data/raw/career_pols_DATA_ENTRY.csv")
FIG_OUT <- file.path(PROJECT, "figures/ch3_career_politicians.png")

COL_BLUE  <- "#2166ac"
COL_RED   <- "#d7191c"
COL_GREY  <- "#636363"

# ============================================================
# 1. LOAD AND VALIDATE
# ============================================================

cat("Loading data...\n")
d <- read_csv(DATA_IN,
              col_types = cols(year = "i", pct_pol_professionals = "d",
                               is_estimated = "l", source_note = "c"),
              show_col_types = FALSE)

bad <- d$year[d$pct_pol_professionals < 0 | d$pct_pol_professionals > 50]
if (length(bad) > 0) stop(paste("pct out of range for years:", paste(bad, collapse = ", ")))

cat("Data points:\n"); print(d |> select(year, pct_pol_professionals, is_estimated))

# ============================================================
# 1b. Henn interior points (direct, same definition as Criddle)
# ============================================================
# Henn (2018) Table 6, "Politician/Pol Organiser" row — reported directly for
# each election, no calibration needed (see header note).

henn <- tribble(
  ~year, ~pct_estimated,
  1987,  5.4,
  1992,  7.3,
  1997,  9.5,
  2001,  10.5,
  2005,  14.1
)

cat("\nHenn (2018) Table 6 'Politician/Pol Organiser' interior points:\n")
print(henn)

# ============================================================
# 2. FIGURE
# ============================================================

# PM shading (election-year-relevant range)
pm_bands <- tribble(
  ~start, ~end,   ~party,
  1979,   1997,   "Conservative",
  1997,   2010,   "Labour",
  2010,   2020,   "Conservative"
)

party_fill <- c("Conservative" = "#fff5f5", "Labour" = "#f5f5ff")

COL_HENN <- "#6baed6"   # lighter blue for Henn interior points

p <- ggplot() +
  # PM era shading
  geom_rect(data = pm_bands,
            aes(xmin = start, xmax = end, ymin = 0, ymax = Inf, fill = party),
            alpha = 0.35) +
  scale_fill_manual(values = party_fill, name = NULL, guide = "none") +
  # Henn interior points: triangles (direct, same definition — no error bars needed)
  geom_point(data = henn,
             aes(x = year, y = pct_estimated),
             colour = COL_HENN, size = 3, shape = 17) +
  # Solid circles for reported Criddle figures
  geom_point(data = d |> filter(!is_estimated),
             aes(x = year, y = pct_pol_professionals),
             colour = COL_BLUE, size = 3.5) +
  # Open circles for Criddle estimated figures (1979, 1983, 2019)
  geom_point(data = d |> filter(is_estimated, year != 1974),
             aes(x = year, y = pct_pol_professionals),
             colour = COL_BLUE, size = 3.5, shape = 1) +
  # Allen 1974: grey diamond — different source, not part of Criddle series
  geom_point(data = d |> filter(year == 1974),
             aes(x = year, y = pct_pol_professionals),
             colour = COL_GREY, size = 3.5, shape = 18) +
  annotate("text", x = 1974.5, y = 6.5,
           label = "Allen et al. (2020)\n(different measure)",
           hjust = 0, size = 2.4, colour = COL_GREY, lineheight = 0.9) +
  # Legend-style key annotations
  annotate("text", x = 1986, y = 22,
           label = "▲ Henn (2018), direct",
           hjust = 0, size = 2.5, colour = COL_HENN) +
  annotate("text", x = 1986, y = 20.5,
           label = "● Criddle / CBP-7529",
           hjust = 0, size = 2.5, colour = COL_BLUE) +
  scale_x_continuous(breaks = c(1974, 1979, 1983, 1987, 1992, 1997, 2001, 2005, 2010, 2015, 2019),
                     limits = c(1972, 2021)) +
  scale_y_continuous(limits = c(0, 25),
                     breaks = seq(0, 25, 5),
                     labels = function(x) paste0(x, "%"),
                     expand = c(0, 0)) +
  labs(
    title    = "MPs with no career outside Westminster have multiplied since 1979",
    subtitle = "Political professionals as % of all MPs. Triangles = Henn (2018) 'Politician/Pol Organiser' row, same definition as Criddle. Election years only.",
    x        = NULL,
    y        = "% of MPs",
    caption  = paste0(
      "Sources: Byron Criddle in BGE volumes (1983, 2010, 2015); Butler & Kavanagh (1979); Butler(C.)/\n",
      "Campbell/Hudson (2019) — all via HC Library CBP-7529. 1987-2005: Henn (2018) Table 6,\n",
      "'Politician/Pol Organiser' row — same narrow definition, reported directly, no calibration needed.\n",
      "1974: Allen et al. (2020) EPSR comparable but not identical measure."
    )
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    plot.title         = element_text(face = "bold", size = 11),
    plot.subtitle      = element_text(colour = COL_GREY, size = 8.5),
    plot.caption       = element_text(colour = COL_GREY, size = 7.5, hjust = 0),
    axis.text.x        = element_text(angle = 45, hjust = 1),
    plot.margin        = margin(t = 10, r = 10, b = 30, l = 10)
  )

ggsave(FIG_OUT, p, width = 10, height = 5.5, dpi = 300)
cat("\nFigure saved:", FIG_OUT, "\n")

# ============================================================
# 3. SUMMARY STATS
# ============================================================

cat("\n=== SUMMARY FOR CHAPTER TEXT ===\n")
cat(sprintf("1974: ~%.1f%% political professionals (Allen et al. 2020 — comparable measure)\n",
            d$pct_pol_professionals[d$year == 1974]))
cat(sprintf("1979: ~%.0f%% political professionals\n",
            d$pct_pol_professionals[d$year == 1979]))
cat(sprintf("1983: ~%.0f%% political professionals (reported as <5%%)\n",
            d$pct_pol_professionals[d$year == 1983]))
cat(sprintf("2010: %.0f%% political professionals\n",
            d$pct_pol_professionals[d$year == 2010]))
cat(sprintf("2015: %.0f%% political professionals\n",
            d$pct_pol_professionals[d$year == 2015]))
cat(sprintf("2019: ~%.0f%% political professionals (reported as ~20-22%%)\n",
            d$pct_pol_professionals[d$year == 2019]))
cat(sprintf("\nGrowth 1979-2019: %.0fx increase (%.0f%% to %.0f%%)\n",
            d$pct_pol_professionals[d$year == 2019] /
              d$pct_pol_professionals[d$year == 1979],
            d$pct_pol_professionals[d$year == 1979],
            d$pct_pol_professionals[d$year == 2019]))
cat("\nKey finding: political professionals multiplied sevenfold 1979-2019.\n")
cat("Trend is long-run and cross-party — not a post-2014 break.\n")
cat("Allen et al. (2020): 4.8% 'political occupation only' in 1974 — consistent.\n")
cat("Warncke (2024): insider route is empirically the path to Cabinet.\n")
cat("\nINTERPRETIVE LIMIT: figure illustrates structural change, not causal\n")
cat("mechanism. MPs without outside experience may amplify turbulence once\n")
cat("it starts; they did not cause the 2014 break.\n")

# ============================================================
# 4. CHOW STRUCTURAL BREAK — TALK FIGURE
# ============================================================
# NOTE: N = 10 election-year observations (Criddle + Henn direct; Allen 1974
# excluded as different measure). Power is very low. F-test uses standard
# Chow with p=2 (intercept + slope free to change). df = (2, n-4) = (2, 6).
# Critical F(2,6) at 5% = 5.14. Andrews (1993) bounds not appropriate at N=10.
# Candidate break years constrained to ≥ 3 obs each side.
# PURPOSE: methodological consistency with Ch2 figures, not strong inference.
# CAUSAL NOTE: if career politicians (IV) cause turbulence (DV, break ~2014),
# the IV break must precede the DV break — expect data-preferred break
# in the 1992–2005 window (pre-2014 by design).

pacman::p_load(patchwork)

NAVY  <- "#1F3864"
RED   <- "#d7191c"
GREY_BLUE <- "#607D8B"
HENN_COL  <- "#6baed6"

TALK_OUT <- file.path(PROJECT, "figures/ch3_career_politicians_chow_talk.png")

# --- Combined dataset for Chow (Criddle + Henn direct; no Allen 1974) ---
chow_data <- bind_rows(
  d |> filter(year != 1974) |>
    transmute(year, pct = pct_pol_professionals,
              source = if_else(!is_estimated, "Criddle (confirmed)",
                               "Criddle (approximate)")),
  henn |> transmute(year, pct = pct_estimated, source = "Henn (2018), direct")
) |> arrange(year) |>
  mutate(t = year - min(year))  # time index from series start

cat("\nChow dataset:\n"); print(chow_data |> select(year, pct, source))

n_chow <- nrow(chow_data)
p      <- 2  # intercept + slope

mod_r  <- lm(pct ~ t, data = chow_data)
RSS_r  <- sum(resid(mod_r)^2)

# Candidate break years: at least 3 obs on each side
years_sorted      <- sort(chow_data$year)
candidate_breaks  <- years_sorted[3:(length(years_sorted) - 3)]

cat("Candidate break years:", candidate_breaks, "\n")
cat("N =", n_chow, "| df_denominator =", n_chow - 2*p, "\n")

F_crit_05 <- qf(0.95, df1 = p, df2 = n_chow - 2*p)
cat(sprintf("Critical F(%d,%d) at 5%% = %.2f\n", p, n_chow - 2*p, F_crit_05))

chow_results <- do.call(rbind, lapply(candidate_breaks, function(k) {
  dat1 <- chow_data |> filter(year <= k)
  dat2 <- chow_data |> filter(year >  k)
  rss1 <- sum(resid(lm(pct ~ t, data = dat1))^2)
  rss2 <- sum(resid(lm(pct ~ t, data = dat2))^2)
  RSS_u <- rss1 + rss2
  F_stat <- ((RSS_r - RSS_u) / p) / (RSS_u / (n_chow - 2 * p))
  data.frame(break_year = k, F_stat = F_stat,
             n1 = nrow(dat1), n2 = nrow(dat2))
}))

cat("\nChow F-statistics:\n"); print(chow_results)
best_break <- chow_results$break_year[which.max(chow_results$F_stat)]
best_F     <- max(chow_results$F_stat)
cat(sprintf("Data-preferred break: %d (F = %.2f; critical = %.2f)\n",
            best_break, best_F, F_crit_05))

# --- Panel A: bar chart ---
source_cols <- c(
  "Criddle (confirmed)"      = NAVY,
  "Criddle (approximate)"    = GREY_BLUE,
  "Henn (2018), direct" = HENN_COL
)

p_bars <- ggplot(chow_data, aes(x = factor(year), y = pct, fill = source)) +
  geom_col(width = 0.7) +
  geom_vline(xintercept = which(years_sorted == best_break) + 0.5,
             linetype = "dashed", colour = RED, linewidth = 0.7) +
  annotate("text",
           x = which(years_sorted == best_break) + 0.65,
           y = max(chow_data$pct) * 0.92,
           label = paste0("Break: ", best_break),
           hjust = 0, size = 2.8, colour = RED) +
  scale_fill_manual(values = source_cols, name = NULL) +
  scale_y_continuous(limits = c(0, 25), breaks = seq(0, 25, 5),
                     labels = function(x) paste0(x, "%"), expand = c(0, 0)) +
  labs(
    title    = "A. Political professionals as % of MPs, 1979–2019",
    subtitle = "Criddle/CBP-7529 (navy/grey) + Henn (2018) direct interior points (light blue). Allen 1974 excluded from Chow.",
    x = NULL, y = "% of MPs"
  ) +
  theme_bw(base_size = 11) +
  theme(
    plot.title      = element_text(face = "bold", colour = NAVY, size = 11),
    plot.subtitle   = element_text(colour = "#888888", size = 7.5),
    legend.position = "bottom",
    legend.text     = element_text(size = 7.5),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x     = element_text(angle = 45, hjust = 1)
  )

# --- Panel B: Chow F-statistic ---
p_chow <- ggplot(chow_results, aes(x = factor(break_year), y = F_stat)) +
  geom_col(fill = NAVY, width = 0.6) +
  geom_hline(yintercept = F_crit_05, linetype = "dashed",
             colour = RED, linewidth = 0.7) +
  annotate("text",
           x = nrow(chow_results),
           y = F_crit_05 + 0.15,
           label = sprintf("F(%d,%d) critical = %.2f (5%%)", p, n_chow - 2*p, F_crit_05),
           hjust = 1, size = 2.5, colour = RED) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  labs(
    title    = "B. Chow structural break test",
    subtitle = sprintf(
      "N = %d election years. Low power — health warning: small-N Chow, not comparable to Ch2 annual series.\nData-preferred break: %d (F = %.2f). IV break must precede DV (turbulence) break at ~2014.",
      n_chow, best_break, best_F),
    x = "Candidate break year", y = "Chow F-statistic"
  ) +
  theme_bw(base_size = 11) +
  theme(
    plot.title    = element_text(face = "bold", colour = NAVY, size = 11),
    plot.subtitle = element_text(colour = "#888888", size = 7.5, lineheight = 1.2),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x   = element_text(angle = 45, hjust = 1)
  )

# --- Combine and save ---
p_talk <- p_bars / p_chow +
  plot_layout(heights = c(2, 1)) +
  plot_annotation(
    caption = paste0(
      "Sources: Byron Criddle (1983, 2010, 2015), Butler & Kavanagh (1979), Butler(C.)/Campbell/Hudson (2019) — all via HC Library CBP-7529;\n",
      "Henn (2018) Table 6 'Politician/Pol Organiser' row, direct (1987-2005); Allen et al. (2020) excluded from Chow.\n",
      "Chow health warnings: (1) N=10 election years, not annual — very low power;\n",
      "(2) standard F critical value used (Andrews bounds not appropriate at N=10); (3) treat break year as indicative only."
    ),
    theme = theme(plot.caption = element_text(size = 6.5, colour = "#888888",
                                               lineheight = 1.2))
  )

ggsave(TALK_OUT, p_talk, width = 10, height = 9, dpi = 300)
cat("\nTalk figure saved:", TALK_OUT, "\n")
