# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41e_professionalisation_pca.R
# 41e_professionalisation_pca.R
# Political professionalisation index — annual series + PCA
#
# Three components, 1979–2025:
#   1. Career politicians % (Criddle + Henn-adjusted; step function by parliament)
#   2. SPADs in post (observed + linearly interpolated)
#   3. Mean staffing spend per MP, real terms (Butler & Butler (2011)-calibrated
#      pre-2010, IPSA annual post-2011 — see 41m_staffing_calibrate_butler.R)
#
# ✅ 7 Sep 2026: pre-2010 staffing REPOINTED from the flat-85%-assumption
#   placeholder to a real, empirically-calibrated series (Butler & Butler
#   maxima x the true 2012-2016 IPSA overlap ratio). Every number below is
#   superseded relative to any report before this date.
#
# OUTPUTS:
#   figures/ch3_professionalisation_pca_talk.png

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, readr, patchwork, tidyr, tibble)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})  # portable project root: works via Rscript from anywhere, or falls back to
    # getwd() when sourced interactively (assumes ch3_pipeline_restored/ as cwd)
PROJECT  <- .ROOT
TALK_OUT <- file.path(PROJECT, "figures/ch3_professionalisation_pca_talk.png")

NAVY      <- "#1F3864"
RED       <- "#d7191c"
GREY_BLUE <- "#607D8B"
COL_CAR   <- "#2166ac"   # career politicians
COL_SPAD  <- "#d95f02"   # SPADs
COL_STAFF <- "#1b7837"   # staffing

YEARS <- 1979:2025

# ============================================================
# 1. CAREER POLITICIANS — step function by parliament
# ============================================================
# Confirmed Criddle values (from CSV, excluding 1974)
career_criddle <- tribble(
  ~year, ~pct,
  1979,  3.0,
  1983,  4.5,
  2010, 14.0,
  2015, 17.0,
  2019, 21.0
)

# Henn (2018) Table 6, "Politician/Pol Organiser" row — his own narrower
# category, same definition as Criddle's, reported directly by election year,
# no calibration needed. FIXED 5 Sep 2026: this tribble previously held wrong
# values (1.4/3.3/5.0/6.4/7.7 + 6.7pp calibration) that did not match Henn's
# actual Table 6 — traced during the CBP-7529/Cairney cross-check (see
# 41_career_politicians.R and build_fig_3_2_professionalisation_composite.R,
# fixed there 3-4 Sep; this script, and 41f/41g/41i/41j which copy its
# construction, were not caught until PJ asked "why not 47 obs" and a broader
# consistency check followed).
career_henn <- tribble(
  ~year, ~pct,
  1987,  5.4,
  1992,  7.3,
  1997,  9.5,
  2001,  10.5,
  2005,  14.1
)

career_obs <- bind_rows(career_criddle, career_henn) |> arrange(year)

# Step function: for each year use the most recent election-year observation
career_annual <- tibble(year = YEARS) |>
  mutate(
    obs_yr      = sapply(year, function(y)
      max(career_obs$year[career_obs$year <= y], na.rm = TRUE)),
    career_pct  = career_obs$pct[match(obs_yr, career_obs$year)],
    career_src  = if_else(obs_yr %in% career_criddle$year, "Criddle", "Henn-adjusted")
  )

cat("Career politicians series:\n")
print(career_annual |> filter(year %in% c(1979:1981, 1987:1989, 2009:2012, 2019:2021)))

# ============================================================
# 2. SPADs — linear interpolation between observations
# ============================================================
spads_data <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                       show_col_types = FALSE)

# Restrict to 1979–2023 for interpolation
spads_fit <- spads_data |> filter(year <= 2025)
spads_interp <- approx(spads_fit$year, spads_fit$n_spads,
                       xout = YEARS, method = "linear", rule = 2)
spads_annual <- tibble(year = YEARS, n_spads = spads_interp$y)

cat("\nSPADs series (sample):\n")
print(spads_annual |> filter(year %in% c(1979, 1985, 1992, 2000, 2010, 2019, 2023)))

# ============================================================
# 3. STAFFING — step function pre-2010, annual post-2011
# ============================================================
ipsa <- read_csv(file.path(PROJECT, "data/processed/ipsa_staffing_annual.csv"),
                 show_col_types = FALSE) |>
  select(cal_year, staffing_real = mean_staffing_real_2015)

# REPOINTED 7 Sep 2026: real Butler & Butler (2011) maxima, empirically
# calibrated against the IPSA 2012-2016 overlap (see 41m_staffing_calibrate_
# butler.R), replacing the old flat-85%-assumption placeholder. Headline spec
# = mean overlap ratio (0.854); min/max specs (0.769/0.910) are in the same
# output file for robustness. 1991 has no source figure (confirmed genuine
# gap in Butler & Butler, not cropped) and is dropped here so the step
# function below carries 1990's value forward to 1992, same as it already
# does across every other multi-year gap in this series.
pre10 <- read_csv(file.path(PROJECT, "data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types = FALSE) |>
  filter(!is.na(real_2015_mean)) |>
  select(cal_year = year, staffing_real = real_2015_mean)

staffing_obs <- bind_rows(pre10, ipsa) |>
  arrange(cal_year) |>
  filter(cal_year <= 2025)

# Step function: most recent staffing observation ≤ year
staffing_annual <- tibble(year = YEARS) |>
  mutate(
    obs_yr       = sapply(year, function(y)
      max(staffing_obs$cal_year[staffing_obs$cal_year <= y], na.rm = TRUE)),
    staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)]
  )

cat("\nStaffing series (sample):\n")
print(staffing_annual |> filter(year %in% c(1979, 1983, 2000, 2010, 2012, 2020, 2023)))

# ============================================================
# 4. COMBINE, NORMALISE, PCA
# ============================================================
norm01 <- function(x) (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))

d <- tibble(year = YEARS) |>
  left_join(career_annual  |> select(year, career_pct, career_src), by = "year") |>
  left_join(spads_annual   |> select(year, n_spads),                 by = "year") |>
  left_join(staffing_annual |> select(year, staffing_real),          by = "year") |>
  mutate(
    career_norm   = norm01(career_pct),
    spads_norm    = norm01(n_spads),
    staffing_norm = norm01(staffing_real)
  )

# Correlation matrix
cat("\n=== CORRELATION MATRIX (normalised) ===\n")
cor_mat <- cor(d[, c("career_norm", "spads_norm", "staffing_norm")], use = "complete.obs")
print(round(cor_mat, 3))

# PCA
pca_mat  <- d |> select(career_norm, spads_norm, staffing_norm) |> as.matrix()
pca_res  <- prcomp(pca_mat, scale. = TRUE, center = TRUE)
pca_summ <- summary(pca_res)

cat("\n=== PCA SUMMARY ===\n")
print(pca_summ)
cat("\nLoadings (rotation):\n")
print(round(pca_res$rotation, 3))

# PC1 scores
d <- d |>
  mutate(
    pc1    = pca_res$x[, 1],
    t      = year - min(year)
  )

pc1_var_pct <- round(pca_summ$importance[2, 1] * 100, 1)
cat(sprintf("\nPC1 explains %.1f%% of variance\n", pc1_var_pct))
cat(sprintf("Loadings: career=%.3f, spads=%.3f, staffing=%.3f\n",
            pca_res$rotation[1,1], pca_res$rotation[2,1], pca_res$rotation[3,1]))

# ============================================================
# 5. CHOW ON PC1
# ============================================================
n_chow <- nrow(d)
p_reg  <- 1   # intercept only in each segment (or intercept + slope)
p_reg2 <- 2

mod_r  <- lm(pc1 ~ t, data = d)
RSS_r  <- sum(resid(mod_r)^2)

years_sorted     <- sort(d$year)
candidate_breaks <- years_sorted[3:(length(years_sorted) - 3)]

chow_results <- do.call(rbind, lapply(candidate_breaks, function(k) {
  dat1 <- d |> filter(year <= k)
  dat2 <- d |> filter(year >  k)
  if (nrow(dat1) < 3 || nrow(dat2) < 3) return(NULL)
  rss1 <- tryCatch(sum(resid(lm(pc1 ~ t, data = dat1))^2), error = function(e) NA)
  rss2 <- tryCatch(sum(resid(lm(pc1 ~ t, data = dat2))^2), error = function(e) NA)
  if (is.na(rss1) || is.na(rss2)) return(NULL)
  RSS_u  <- rss1 + rss2
  F_stat <- ((RSS_r - RSS_u) / p_reg2) / (RSS_u / (n_chow - 2 * p_reg2 - 1))
  data.frame(break_year = k, F_stat = max(F_stat, 0))
}))

F_crit     <- qf(0.95, df1 = p_reg2, df2 = n_chow - 2 * p_reg2 - 1)
best_break <- chow_results$break_year[which.max(chow_results$F_stat)]
best_F     <- max(chow_results$F_stat)

cat(sprintf("\nChow on PC1: N=%d, critical F(%d,%d)=%.2f\n",
            n_chow, p_reg2, n_chow - 2*p_reg2 - 1, F_crit))
cat(sprintf("Data-preferred break: %d (F=%.2f)\n", best_break, best_F))
cat("\nTop 10 candidate breaks:\n")
print(chow_results |> arrange(desc(F_stat)) |> head(10))

# ============================================================
# 6. FIGURES
# ============================================================

# ============================================================
# 6. FIGURES — talk version
# ============================================================

# Correlation labels for annotation in Panel A
r_cs <- round(cor_mat["career_norm",   "spads_norm"],    2)
r_cf <- round(cor_mat["career_norm",   "staffing_norm"], 2)
r_sf <- round(cor_mat["spads_norm",    "staffing_norm"], 2)

cor_label <- sprintf(
  "Pairwise r:  career × SPADs = %.2f\n             career × staffing = %.2f\n             SPADs × staffing = %.2f",
  r_cs, r_cf, r_sf
)

long_d <- d |>
  select(year, career_norm, spads_norm, staffing_norm) |>
  pivot_longer(-year, names_to = "component", values_to = "value") |>
  mutate(component = recode(component,
    "career_norm"   = "Career politicians %",
    "spads_norm"    = "SPADs in post",
    "staffing_norm" = "MP staffing spend (real)"
  ))

# --- Panel A: three normalised series ---
p_components <- ggplot(long_d, aes(x = year, y = value, colour = component,
                                    linetype = component)) +
  geom_line(linewidth = 1.1) +
  annotate("label",
           x = 1982, y = 0.82,
           label    = cor_label,
           hjust    = 0, vjust = 1,
           size     = 3, colour = NAVY,
           fill     = "white", label.size = 0.3,
           fontface = "plain", lineheight = 1.4) +
  scale_colour_manual(values = c(
    "Career politicians %"     = COL_CAR,
    "SPADs in post"            = COL_SPAD,
    "MP staffing spend (real)" = COL_STAFF
  ), name = NULL) +
  scale_linetype_manual(values = c(
    "Career politicians %"     = "solid",
    "SPADs in post"            = "dashed",
    "MP staffing spend (real)" = "dotdash"
  ), name = NULL) +
  scale_x_continuous(breaks = seq(1980, 2020, 5)) +
  scale_y_continuous(limits = c(0, 1.02),
                     labels = scales::percent_format(accuracy = 1),
                     expand = c(0, 0)) +
  labs(
    title    = "A. Three independent measures of political professionalisation move in near-perfect lockstep",
    subtitle = sprintf(
      paste0("Career politicians %%: Criddle/Henn (step function by parliament, 9 election years). ",
             "SPADs: Cabinet Office/Yong & Hazell (observed + interpolated).\n",
             "MP staffing spend: modelled pre-2010 (HC allowance × 85%%), IPSA actual 2012–2023. ",
             "All three series from entirely independent data sources.")
    ),
    x = NULL, y = "Normalised value (0 = minimum, 1 = maximum)"
  ) +
  theme_bw(base_size = 11) +
  theme(
    plot.title         = element_text(face = "bold", colour = NAVY, size = 11),
    plot.subtitle      = element_text(colour = "#888888", size = 7.5, lineheight = 1.2),
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x        = element_text(angle = 45, hjust = 1),
    legend.position    = "top",
    legend.text        = element_text(size = 9),
    legend.key.width   = unit(1.5, "cm")
  )

# --- Panel B: PC1 composite time series ---
p_pc1 <- ggplot(d, aes(x = year, y = pc1)) +
  geom_line(colour = NAVY, linewidth = 1.1) +
  geom_point(colour = NAVY, size = 1.8) +
  annotate("text",
           x = 1982, y = 2.5,
           label    = sprintf("PC1 explains %.1f%% of variance\nLoadings: career = %.2f, SPADs = %.2f, staffing = %.2f\n(near-equal weighting — no single measure dominates)",
                              pc1_var_pct,
                              pca_res$rotation[1,1], pca_res$rotation[2,1], pca_res$rotation[3,1]),
           hjust = 0, vjust = 1, size = 2.8, colour = NAVY, lineheight = 1.4) +
  scale_x_continuous(breaks = seq(1980, 2020, 5)) +
  labs(
    title    = sprintf("B. Professionalisation composite (PC1): %.1f%% of variance explained by a single dimension", pc1_var_pct),
    subtitle = "Higher score = more professionalised political class. Structural break test (Panel C) shows acceleration predates turbulence DV by ~7 years.",
    x = NULL, y = "PC1 score (standardised)"
  ) +
  theme_bw(base_size = 11) +
  theme(
    plot.title         = element_text(face = "bold", colour = NAVY, size = 11),
    plot.subtitle      = element_text(colour = "#888888", size = 7.5, lineheight = 1.2),
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x        = element_text(angle = 45, hjust = 1)
  )

# --- Panel C: Chow on PC1 ---
p_chow <- ggplot(chow_results, aes(x = factor(break_year), y = F_stat)) +
  geom_col(fill = NAVY, width = 0.7) +
  geom_hline(yintercept = F_crit, linetype = "dashed", colour = RED, linewidth = 0.7) +
  annotate("text",
           x     = as.character(candidate_breaks[length(candidate_breaks)]),
           y     = F_crit + max(chow_results$F_stat) * 0.04,
           label = sprintf("Critical F(%d,%d) = %.2f (5%%)", p_reg2,
                           n_chow - 2*p_reg2 - 1, F_crit),
           hjust = 1, size = 2.5, colour = RED) +
  annotate("text",
           x     = as.character(best_break),
           y     = best_F + max(chow_results$F_stat) * 0.04,
           label = sprintf("Peak: %d\n(T−7 before\nturbulence break)", best_break),
           hjust = 0.5, vjust = 0, size = 2.5, colour = NAVY) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
  scale_x_discrete(breaks = as.character(seq(1982, 2020, 5))) +
  labs(
    title    = "C. Chow structural break test on PC1 composite",
    subtitle = sprintf(
      "Data-preferred break: %d (F = %.2f, critical = %.2f). Professionalisation acceleration predates turbulence DV (~2014) by ~7 years.\nNote: N=45. Pre-2010 data are modelled estimates — Chow will update after Butler & Butler calibration 30 Apr.",
      best_break, best_F, F_crit),
    x = "Candidate break year", y = "Chow F-statistic"
  ) +
  theme_bw(base_size = 11) +
  theme(
    plot.title         = element_text(face = "bold", colour = NAVY, size = 11),
    plot.subtitle      = element_text(colour = "#888888", size = 7.5, lineheight = 1.2),
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x        = element_text(angle = 45, hjust = 1)
  )

p_talk <- p_components / p_pc1 / p_chow +
  plot_layout(heights = c(2.2, 1.6, 1.2)) +
  plot_annotation(
    title   = "The professionalisation of British politics",
    caption = paste0(
      "Sources: Criddle in Cowley/Kavanagh British General Election volumes; Henn (2018) Table 6 Westminster Group + 6.7pp calibration adjustment; ",
      "Cabinet Office CSV releases + Yong & Hazell (2014) SPADs;\n",
      "IPSA Annual Total Spend 2011-12 to 2023-24; HC Members' Allowances modelled pre-2010 (to be calibrated Butler & Butler 2011)."
    ),
    theme = theme(
      plot.title   = element_text(face = "bold", colour = NAVY, size = 13, hjust = 0),
      plot.caption = element_text(size = 6.5, colour = "#888888", lineheight = 1.2)
    )
  )

ggsave(TALK_OUT, p_talk, width = 10, height = 13, dpi = 300)
cat("Figure saved:", TALK_OUT, "\n")

# ============================================================
# 7. SPEECH COVARIANCE CHECK
# — Does the self-regarding speech series covary with the index?
# — Coverage: 1979-2025 (Evan Odell + ParlSpeech V2 + official Hansard API,
#   see 64d/64e/64f); overlap with the professionalisation index (1979-2023)
#   is now 45 years, up from 32 (1988-2019 previously)
# ============================================================
SPEECH_IN <- file.path(PROJECT, "data/processed/speech_self_regarding_1979_2025.csv")

if (file.exists(SPEECH_IN)) {
  speech <- read_csv(SPEECH_IN, show_col_types = FALSE) |>
    select(year, speech_ratio = mean_self_ratio)

  d_speech <- d |>
    filter(year >= 1979, year <= 2023) |>
    left_join(speech, by = "year") |>
    mutate(speech_norm = norm01(speech_ratio))

  cat("\n=== SPEECH SERIES COVARIANCE CHECK (N=45, 1979-2023) ===\n")
  cat("Mean self-regarding ratio by period:\n")
  d_speech |>
    mutate(period = case_when(
      year <= 1988 ~ "1979-88 (Thatcher/Major-early)",
      year <= 1997 ~ "1989-97 (Major)",
      year <= 2009 ~ "1998-09 (Blair/Brown)",
      year <= 2019 ~ "2010-19 (Coalition+)",
      TRUE         ~ "2020-23 (Johnson/Truss/Sunak)"
    )) |>
    group_by(period) |>
    summarise(mean_ratio = mean(speech_ratio, na.rm = TRUE),
              .groups = "drop") |>
    print()

  # Correlations with the three index components and PC1
  cat("\nCorrelations with speech self-regarding ratio:\n")
  cor_speech <- cor(
    d_speech[, c("career_norm", "spads_norm", "staffing_norm", "pc1", "speech_norm")],
    use = "complete.obs"
  )
  print(round(cor_speech["speech_norm", c("career_norm", "spads_norm",
                                           "staffing_norm", "pc1")], 3))

  # Four-component PCA (1988-2019 only)
  pca4_data <- d_speech |>
    select(career_norm, spads_norm, staffing_norm, speech_norm) |>
    na.omit()
  pca4_res  <- prcomp(pca4_data, scale. = TRUE, center = TRUE)
  pca4_summ <- summary(pca4_res)
  cat("\n4-component PCA (1988-2019):\n")
  print(pca4_summ$importance[, 1:4])
  cat("\nLoadings:\n")
  print(round(pca4_res$rotation, 3))

  # Quick comparison figure
  COL_SPEECH <- "#7b2d8b"
  long_speech <- d_speech |>
    select(year, career_norm, spads_norm, staffing_norm, speech_norm) |>
    pivot_longer(-year, names_to = "series", values_to = "value") |>
    mutate(series = recode(series,
      "career_norm"   = "Career politicians %",
      "spads_norm"    = "SPADs in post",
      "staffing_norm" = "MP staffing spend (real)",
      "speech_norm"   = "Self-regarding speech ratio"
    ))

  p_speech_check <- ggplot(long_speech, aes(x = year, y = value,
                                             colour = series, linetype = series)) +
    geom_line(linewidth = 1.0) +
    scale_colour_manual(values = c(
      "Career politicians %"          = COL_CAR,
      "SPADs in post"                 = COL_SPAD,
      "MP staffing spend (real)"      = COL_STAFF,
      "Self-regarding speech ratio"   = COL_SPEECH
    ), name = NULL) +
    scale_linetype_manual(values = c(
      "Career politicians %"          = "solid",
      "SPADs in post"                 = "dashed",
      "MP staffing spend (real)"      = "dotdash",
      "Self-regarding speech ratio"   = "twodash"
    ), name = NULL) +
    scale_x_continuous(breaks = seq(1980, 2020, 5)) +
    scale_y_continuous(limits = c(0, 1.02),
                       labels = scales::percent_format(accuracy = 1)) +
    labs(
      title    = "Speech self-regard vs professionalisation index components, 1979–2023",
      subtitle = sprintf(
        "Correlations with PC1: r = %.3f. Speech series is flat-to-declining across the full span vs monotonic rise in index.\nFour-component PCA: PC1 = %.1f%% (1979-2023, N=45); speech adds a distinct second dimension.",
        cor_speech["speech_norm", "pc1"],
        pca4_summ$importance[2, 1] * 100
      ),
      x = NULL, y = "Normalised value (0 = min, 1 = max)"
    ) +
    theme_bw(base_size = 11) +
    theme(
      plot.title         = element_text(face = "bold", colour = NAVY, size = 11),
      plot.subtitle      = element_text(colour = "#888888", size = 8, lineheight = 1.3),
      panel.grid.minor   = element_blank(),
      panel.grid.major.x = element_blank(),
      axis.text.x        = element_text(angle = 45, hjust = 1),
      legend.position    = "top",
      legend.text        = element_text(size = 8.5)
    )

  speech_out <- file.path(PROJECT, "figures/ch3_speech_vs_index_check.png")
  ggsave(speech_out, p_speech_check, width = 10, height = 5.5, dpi = 300)
  cat("\nSpeech check figure saved:", speech_out, "\n")

  # ============================================================
  # OVERLAY FIGURE: PC1 composite vs self-regarding speech
  # Both Z-scored so they sit on the same axis.
  # Shows divergence (Blair era) then convergence (post-2010).
  # ============================================================
  OVERLAY_OUT <- file.path(PROJECT, "figures/ch3_profess_speech_overlay_talk.png")
  COL_PC1    <- NAVY
  COL_SPEECH <- "#7b2d8b"

  zscore <- function(x) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)

  d_overlay <- d_speech |>
    mutate(
      pc1_z    = zscore(pc1),
      speech_z = zscore(speech_ratio)
    )

  # NOTE: this figure previously (1988-2019 window) carried hand-built period
  # shading and "divergence then convergence" annotations describing that
  # specific shorter shape. Removed here rather than stretched to the new
  # 1979-2023 range — those were claims about the old window, not verified
  # against the extended series. See console period-means table (Section 7
  # above) for the actual shape before adding new descriptive annotations.
  p_overlay <- ggplot() +
    # Zero line
    geom_hline(yintercept = 0, linetype = "dotted", colour = "#aaaaaa", linewidth = 0.5) +
    # PC1 composite
    geom_line(data = d_overlay, aes(x = year, y = pc1_z, colour = "Professionalisation\nPC1 composite"),
              linewidth = 1.2) +
    # Speech series
    geom_line(data = d_overlay, aes(x = year, y = speech_z, colour = "Self-regarding\nspeech ratio"),
              linewidth = 1.2, linetype = "dashed") +
    scale_colour_manual(
      values = c("Professionalisation\nPC1 composite" = COL_PC1,
                 "Self-regarding\nspeech ratio"      = COL_SPEECH),
      name = NULL
    ) +
    scale_x_continuous(breaks = seq(1980, 2020, 5), limits = c(1979, 2023.5)) +
    scale_y_continuous(breaks = seq(-2, 2, 1),
                       labels = function(x) sprintf("%+.0f SD", x)) +
    labs(
      title    = "Professionalisation index vs self-regarding speech ratio, 1979–2023",
      subtitle = sprintf(
        paste0(
          "Both series Z-scored (mean 0, SD 1). Professionalisation PC1 = structural index (career politicians, SPADs, staffing).\n",
          "Self-regarding speech = career/position references as share of career+policy hits ",
          "(1979-88 Evan Odell, 1989-2019 ParlSpeech V2, 2020-23 official Hansard API).\n",
          "Correlation, full overlap: r = %.3f."
        ),
        cor_speech["speech_norm", "pc1"]
      ),
      x = NULL, y = "Standardised score (Z)"
    ) +
    theme_bw(base_size = 11) +
    theme(
      plot.title       = element_text(face = "bold", colour = NAVY, size = 11),
      plot.subtitle    = element_text(colour = "#888888", size = 7.5, lineheight = 1.3),
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank(),
      axis.text.x      = element_text(angle = 45, hjust = 1),
      legend.position  = c(0.08, 0.82),
      legend.background = element_rect(fill = "white", colour = "#cccccc", linewidth = 0.3),
      legend.text      = element_text(size = 8.5),
      legend.key.width = unit(1.2, "cm")
    )

  ggsave(OVERLAY_OUT, p_overlay, width = 10, height = 6.5, dpi = 300)
  cat("Overlay figure saved:", OVERLAY_OUT, "\n")

} else {
  cat("\nSpeech data not found — run 64b_hansard_annual.R first.\n")
}
