# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41f_profess_turb_lag.R
# 41f_profess_turb_lag.R
# Lagged correlation: professionalisation IV vs turbulence DV
#
# Figure 1: time series overlay (IV ahead of DV)
# Figure 2: three scatter plots, lag 0/1/2 with r and p values
#
# OUTPUTS:
#   figures/ch3_profess_turb_timeseries_talk.png
#   figures/ch3_profess_turb_scatter_talk.png

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, readr, patchwork, tibble, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})  # portable project root: works via Rscript from anywhere, or falls back to
    # getwd() when sourced interactively (assumes ch3_pipeline_restored/ as cwd)
PROJECT <- .ROOT
OUT1 <- file.path(PROJECT, "figures/ch3_profess_turb_timeseries_talk.png")
OUT2 <- file.path(PROJECT, "figures/ch3_profess_turb_scatter_talk.png")

NAVY <- "#1F3864"; RED <- "#d7191c"; GREY <- "#607D8B"

# ============================================================
# 1. REBUILD PROFESSIONALISATION PC1 (same as 41e)
# ============================================================
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
zscore <- function(x) (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
YEARS  <- 1979:2025

career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)

career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr     = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                  show_col_types = FALSE) |> filter(year <= 2025)
spads_annual <- tibble(year = YEARS,
  n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),
                  show_col_types=FALSE) |> select(cal_year, staffing_real=mean_staffing_real_2015)
# REPOINTED 7 Sep 2026: Butler & Butler-calibrated real series, see 41m_staffing_calibrate_butler.R
pre10 <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types=FALSE) |> filter(!is.na(real_2015_mean)) |>
  select(cal_year=year, staffing_real=real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr       = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual  |> select(year, career_pct), by="year") |>
  left_join(spads_annual   |> select(year, n_spads),    by="year") |>
  left_join(staffing_annual|> select(year, staffing_real), by="year") |>
  mutate(career_norm   = norm01(career_pct),
         spads_norm    = norm01(n_spads),
         staffing_norm = norm01(staffing_real))

pca_res  <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm),
                   scale. = TRUE, center = TRUE)
d_prof   <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

# ============================================================
# 2. LOAD TURBULENCE DV
# ============================================================
turb <- read_csv(file.path(PROJECT, "../composite_canonical/canonical_pc1_1979_2025.csv"),
                 show_col_types = FALSE) |> select(year, turb_pc1 = PC1_index)
# repointed 2 Sep 2026: was reading a stale local turbulence_pca.csv (2005-2023,
# 5-component pm_churn spec) — now reads the canonical composite (1979-2025,
# 6-component exec_instab spec). See wkbd-composite-stale-canonical memory.

# ============================================================
# 3. MERGE WITH LAGS
# ============================================================
merged <- turb |>
  left_join(d_prof |> select(year, prof_pc1),                          by="year") |>
  left_join(d_prof |> select(year, prof_lag1=prof_pc1) |> mutate(year=year+1), by="year") |>
  left_join(d_prof |> select(year, prof_lag2=prof_pc1) |> mutate(year=year+2), by="year")

r_stats <- function(x, y) {
  cc  <- complete.cases(cbind(x, y))
  r   <- cor(x[cc], y[cc])
  n   <- sum(cc)
  tst <- r * sqrt((n-2)/(1-r^2))
  p   <- 2 * pt(-abs(tst), df=n-2)
  list(r=r, n=n, t=tst, p=p)
}

s0 <- r_stats(merged$turb_pc1, merged$prof_pc1)
s1 <- r_stats(merged$turb_pc1, merged$prof_lag1)
s2 <- r_stats(merged$turb_pc1, merged$prof_lag2)

cat(sprintf("Lag 0: r=%.3f, N=%d, p=%.3f\n", s0$r, s0$n, s0$p))
cat(sprintf("Lag 1: r=%.3f, N=%d, p=%.3f\n", s1$r, s1$n, s1$p))
cat(sprintf("Lag 2: r=%.3f, N=%d, p=%.3f\n", s2$r, s2$n, s2$p))

# ============================================================
# FIGURE 1: TIME SERIES OVERLAY
# ============================================================
ts_long <- bind_rows(
  d_prof |> select(year, val=prof_pc1) |>
    mutate(series="Professionalisation PC1 (IV)", val_z=zscore(val)),
  turb   |> select(year, val=turb_pc1) |>
    mutate(series="Turbulence PC1 (DV)",          val_z=zscore(val))
) |> filter(year >= 2000)

# Shade the "IV elevated, DV still low" gap period
p_ts <- ggplot(ts_long, aes(x=year, y=val_z, colour=series, linetype=series)) +
  geom_line(linewidth=1.3) +
  geom_point(size=2) +
  scale_colour_manual(
    values   = c("Professionalisation PC1 (IV)" = NAVY,
                 "Turbulence PC1 (DV)"          = RED),
    name     = NULL
  ) +
  scale_linetype_manual(
    values   = c("Professionalisation PC1 (IV)" = "solid",
                 "Turbulence PC1 (DV)"          = "dashed"),
    name     = NULL
  ) +
  scale_x_continuous(breaks=seq(2000, 2025, 2)) +
  scale_y_continuous(breaks=seq(-2, 2, 1),
                     labels=function(x) sprintf("%+.0f SD", x)) +
  labs(
    title    = "Professionalisation index (IV) elevated from ~2007; turbulence composite (DV) rises after 2014",
    subtitle = paste0(
      "Both series Z-scored. Professionalisation IV (career politicians, SPADs, staffing) ",
      "elevated from ~2007.\n",
      "Turbulence DV (PM churn, Pedersen, defeats, NAO, spending churn) jumps after 2014. ",
      sprintf("Lagged r (lag 2) = %.3f, p < .001.", s2$r)
    ),
    x = NULL, y = "Standardised score (Z)"
  ) +
  theme_bw(base_size=12) +
  theme(
    plot.title         = element_text(face="bold", colour=NAVY, size=12),
    plot.subtitle      = element_text(colour=GREY, size=8.5, lineheight=1.3),
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x        = element_text(angle=45, hjust=1),
    legend.position    = "top",
    legend.text        = element_text(size=10),
    legend.key.width   = unit(1.5, "cm")
  )

# Standalone version with title
ggsave(OUT1, p_ts, width=10, height=6.5, dpi=300)
cat("Figure 1 saved:", OUT1, "\n")

# Version for combined figure — drop title/subtitle to avoid duplication
p_ts_compact <- p_ts + labs(title = NULL, subtitle = NULL)

# ============================================================
# FIGURE 2: THREE SCATTER PLOTS
# ============================================================
make_scatter <- function(x_vec, y_vec, stats, lag_label, x_label, highlight=FALSE) {
  df <- data.frame(x=x_vec, y=y_vec) |> na.omit()
  p_str  <- if(stats$p < 0.001) "p < .001" else sprintf("p = %.3f", stats$p)
  annot  <- sprintf("r = %.3f\n%s\nN = %d", stats$r, p_str, stats$n)

  # Stronger visual treatment for the best-fitting lag
  line_col  <- if(highlight) RED   else "#888888"
  fill_col  <- if(highlight) "#ffd5d5" else "#e0e0e0"
  line_w    <- if(highlight) 1.4   else 0.8
  point_a   <- if(highlight) 0.9   else 0.5
  annot_col <- if(highlight) RED   else GREY
  title_col <- if(highlight) RED   else NAVY
  border_col <- if(highlight) RED  else "grey80"

  ggplot(df, aes(x=x, y=y)) +
    geom_smooth(method="lm", se=TRUE, colour=line_col, fill=fill_col,
                linewidth=line_w, alpha=0.35) +
    geom_point(colour=NAVY, size=3, alpha=point_a) +
    annotate("label", x=-Inf, y=Inf,
             label    = annot,
             hjust    = -0.1, vjust=1.15,
             size     = 4.0, colour=annot_col, fill="white",
             fontface = "bold", lineheight=1.4) +
    labs(
      title    = lag_label,
      x        = x_label,
      y        = "Turbulence PC1"
    ) +
    theme_bw(base_size=11) +
    theme(
      plot.title         = element_text(face="bold", colour=title_col, size=11),
      panel.grid.minor   = element_blank(),
      panel.border       = element_rect(colour=border_col, linewidth=if(highlight) 1.5 else 0.5)
    )
}

p_s0 <- make_scatter(merged$prof_pc1,  merged$turb_pc1, s0,
  "Lag 0 — same year", "Professionalisation PC1 (year t)", highlight=FALSE)
p_s1 <- make_scatter(merged$prof_lag1, merged$turb_pc1, s1,
  "Lag 1 — leads by 1 year", "Professionalisation PC1 (year t\u22121)", highlight=FALSE)
p_s2 <- make_scatter(merged$prof_lag2, merged$turb_pc1, s2,
  "Lag 2 — leads by 2 years  \u2605", "Professionalisation PC1 (year t\u22122)", highlight=TRUE)

p_scatter <- (p_s0 | p_s1 | p_s2)

# --- Combined figure: scatters on top (prominent), time series below ---
OUT3 <- file.path(PROJECT, "figures/ch3_profess_turb_combined_talk.png")

p_combined <- (p_scatter / p_ts_compact) +
  plot_layout(heights = c(3, 2.5)) +
  plot_annotation(
    title    = "Professionalisation and turbulence: lagged correlations, 1979\u20132025",
    subtitle = sprintf(
      "Top: correlation strengthens with lag (r = %.2f \u2192 %.2f \u2192 %.2f). Bottom: both series over time (Z-scored).",
      s0$r, s1$r, s2$r
    ),
    caption  = sprintf(
      "N = %d annual observations (1979\u20132025). PCA composites, 1 SD units. Health warning: small N, time-trended series.",
      s2$n
    ),
    theme = theme(
      plot.title    = element_text(face="bold", colour=NAVY, size=14),
      plot.subtitle = element_text(colour=GREY,  size=9.5,  lineheight=1.3),
      plot.caption  = element_text(colour=GREY,  size=7,    lineheight=1.2)
    )
  )

ggsave(OUT3, p_combined, width=12, height=10, dpi=300)
cat("Combined figure saved:", OUT3, "\n")

# Also save individual panels
ggsave(OUT2, p_scatter +
  plot_annotation(
    title = "Professionalisation and turbulence: lagged correlations, 2005\u20132023",
    subtitle = sprintf("Correlation strengthens with lag (r = %.2f \u2192 %.2f \u2192 %.2f).", s0$r, s1$r, s2$r),
    theme = theme(
      plot.title    = element_text(face="bold", colour=NAVY, size=14),
      plot.subtitle = element_text(colour=GREY, size=9.5)
    )
  ), width=12, height=5.5, dpi=300)
cat("Scatter-only figure saved:", OUT2, "\n")
