# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41g_profess_trust_lag.R
# 41g_profess_trust_lag.R
# Lagged correlation: professionalisation IV vs political trust
#
# Trust DV: BSA "trust govt just about always/most of time", extended
#   1979-2025 via TrustGov/Ipsos calibration for BSA gap years
#   (trust_extended_1979_2025.csv — see 41k/41l, sources_raw/trustgov_dataset/,
#   sources_raw/ipsos_veracity_index/). ~24 years genuinely BSA-observed,
#   ~23 years calibrated (TrustGov 1979-2020 gaps, Ipsos 2021/22/25) — figures
#   below distinguish observed vs. calibrated points, do not blend them silently.
# IV: professionalisation PC1 from 41e (career politicians, SPADs, staffing)
#   1979-2023
#
# Figure 1: time series overlay (both Z-scored, 1990-2023)
# Figure 2: scatter plots at lag 0, 1, 2
#
# NOTE: both series are time-trended (prof up, trust down) — correlations
# are informative about association but not causal identification.
# Caution: trust is a Ch4 (political culture) variable; this script explores
# the cross-chapter link professionalisation → trust, not the Ch4 main analysis.
#
# OUTPUTS:
#   figures/ch3_profess_trust_timeseries_talk.png
#   figures/ch3_profess_trust_scatter_talk.png

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, readr, patchwork, tibble, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})  # portable project root: works via Rscript from anywhere, or falls back to
    # getwd() when sourced interactively (assumes ch3_pipeline_restored/ as cwd)
PROJECT <- .ROOT
OUT1 <- file.path(PROJECT, "figures/ch3_profess_trust_timeseries_talk.png")
OUT2 <- file.path(PROJECT, "figures/ch3_profess_trust_scatter_talk.png")

NAVY <- "#1F3864"; RED <- "#d7191c"; GREY <- "#607D8B"

# ============================================================
# 1. REBUILD PROFESSIONALISATION PC1 (same as 41e/41f)
# ============================================================
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
zscore <- function(x) (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
YEARS  <- 1979:2025

career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)

career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr     = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                  show_col_types = FALSE) |> filter(year <= 2025)
spads_annual <- tibble(year = YEARS,
  n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),
                  show_col_types=FALSE) |> select(cal_year, staffing_real=mean_staffing_real_2015)
# REPOINTED 7 Sep 2026: Butler & Butler-calibrated real series, see 41m_staffing_calibrate_butler.R
pre10 <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types=FALSE) |> filter(!is.na(real_2015_mean)) |>
  select(cal_year=year, staffing_real=real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr        = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual   |> select(year, career_pct),    by="year") |>
  left_join(spads_annual    |> select(year, n_spads),        by="year") |>
  left_join(staffing_annual |> select(year, staffing_real),  by="year") |>
  mutate(career_norm   = norm01(career_pct),
         spads_norm    = norm01(n_spads),
         staffing_norm = norm01(staffing_real))

pca_res <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm),
                  scale. = TRUE, center = TRUE)
d_prof  <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

cat("PC1 variance explained:", round(summary(pca_res)$importance[2,1]*100, 1), "%\n")

# ============================================================
# 2. LOAD TRUST DV
# ============================================================
trust <- read_csv(file.path(PROJECT, "data/processed/trust_extended_1979_2025.csv"),
                  show_col_types = FALSE) |>
  select(year, trust_pct, data_source, note) |>
  mutate(observed = !grepl("INTERPOLATED", data_source, fixed = TRUE))

cat("Trust series: N =", nrow(trust), "  range", min(trust$year), "-", max(trust$year), "\n")
cat("  of which observed (BSA):", sum(trust$observed),
    " calibrated (TrustGov/Ipsos):", sum(!trust$observed), "\n")

# ============================================================
# 3. MERGE WITH LAGS
# ============================================================
# Lag: professionalisation at year t-k paired with trust at year t
merged <- trust |>
  left_join(d_prof |> select(year, prof_pc1),                            by="year") |>
  left_join(d_prof |> select(year, prof_lag1=prof_pc1) |> mutate(year=year+1), by="year") |>
  left_join(d_prof |> select(year, prof_lag2=prof_pc1) |> mutate(year=year+2), by="year")

# Observed-only robustness check (BSA years only, drops calibrated years)
merged_obs <- merged |> filter(observed)

r_stats <- function(x, y) {
  cc  <- complete.cases(cbind(x, y))
  r   <- cor(x[cc], y[cc])
  n   <- sum(cc)
  tst <- r * sqrt((n-2)/(1-r^2))
  p   <- 2 * pt(-abs(tst), df=n-2)
  list(r=r, n=n, t=tst, p=p)
}

s0 <- r_stats(merged$trust_pct, merged$prof_pc1)
s1 <- r_stats(merged$trust_pct, merged$prof_lag1)
s2 <- r_stats(merged$trust_pct, merged$prof_lag2)

cat(sprintf("Lag 0: r=%.3f, N=%d, p=%.3f\n", s0$r, s0$n, s0$p))
cat(sprintf("Lag 1: r=%.3f, N=%d, p=%.3f\n", s1$r, s1$n, s1$p))
cat(sprintf("Lag 2: r=%.3f, N=%d, p=%.3f\n", s2$r, s2$n, s2$p))

s0_obs <- r_stats(merged_obs$trust_pct, merged_obs$prof_pc1)
s1_obs <- r_stats(merged_obs$trust_pct, merged_obs$prof_lag1)
s2_obs <- r_stats(merged_obs$trust_pct, merged_obs$prof_lag2)
cat("\n--- Robustness: BSA-observed years only (drops calibrated years) ---\n")
cat(sprintf("Lag 0: r=%.3f, N=%d, p=%.3f\n", s0_obs$r, s0_obs$n, s0_obs$p))
cat(sprintf("Lag 1: r=%.3f, N=%d, p=%.3f\n", s1_obs$r, s1_obs$n, s1_obs$p))
cat(sprintf("Lag 2: r=%.3f, N=%d, p=%.3f\n", s2_obs$r, s2_obs$n, s2_obs$p))

# ============================================================
# FIGURE 1: TIME SERIES OVERLAY
# ============================================================
ts_long <- bind_rows(
  d_prof |> select(year, val=prof_pc1) |>
    mutate(series="Professionalisation PC1 (IV)", val_z=zscore(val), observed=TRUE),
  trust  |> select(year, val=trust_pct, observed) |>
    mutate(series="Political trust % (DV)",       val_z=zscore(val))
) |> filter(year >= 1979)

p_ts <- ggplot(ts_long, aes(x=year, y=val_z, colour=series, linetype=series)) +
  geom_vline(xintercept=2014, linetype="dotted", colour=RED, linewidth=0.7) +
  annotate("text", x=2014.2, y=2.2,
           label="2014\n(turbulence\nbreakpoint)",
           colour=RED, size=2.6, hjust=0, lineheight=1.1) +
  geom_line(linewidth=1.2) +
  geom_point(aes(shape=observed), size=1.8) +
  scale_colour_manual(
    values = c("Professionalisation PC1 (IV)" = NAVY,
               "Political trust % (DV)"        = RED),
    name = NULL
  ) +
  scale_linetype_manual(
    values = c("Professionalisation PC1 (IV)" = "solid",
               "Political trust % (DV)"        = "dashed"),
    name = NULL
  ) +
  scale_shape_manual(
    values = c("TRUE" = 16, "FALSE" = 1),
    labels = c("TRUE" = "Observed", "FALSE" = "Calibrated (TrustGov/Ipsos)"),
    name = NULL
  ) +
  scale_x_continuous(breaks=seq(1980, 2025, 5)) +
  scale_y_continuous(breaks=seq(-2, 2, 1),
                     labels=function(x) sprintf("%+.0f SD", x)) +
  labs(
    title    = "Professionalisation index rising as public trust falls, 1979–2025",
    subtitle = paste0(
      "Both series Z-scored. Professionalisation IV (career politicians, SPADs, staffing) rises steadily.\n",
      "Political trust (BSA: % trusting govt just about always/most of time, extended via TrustGov/Ipsos ",
      "calibration for BSA gap years — hollow points) falls broadly over same period. ",
      sprintf("Contemporaneous r = %.3f (p = %.3f, N = %d).", s0$r, s0$p, s0$n),
      "\nCaution: both series are time-trended; correlation does not establish causation. ",
      "~Half of trust points are calibrated, not observed — see BSA-only robustness stats in console output."
    ),
    x = NULL, y = "Standardised score (Z)"
  ) +
  theme_bw(base_size=12) +
  theme(
    plot.title         = element_text(face="bold", colour=NAVY, size=12),
    plot.subtitle      = element_text(colour=GREY, size=8, lineheight=1.3),
    panel.grid.minor   = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x        = element_text(angle=45, hjust=1),
    legend.position    = "top",
    legend.text        = element_text(size=9),
    legend.key.width   = unit(1.5, "cm")
  )

ggsave(OUT1, p_ts, width=10, height=6.5, dpi=300)
cat("Figure 1 saved:", OUT1, "\n")

# ============================================================
# FIGURE 2: THREE SCATTER PLOTS
# ============================================================
make_scatter <- function(x_vec, y_vec, obs_vec, stats, lag_label, x_label) {
  df     <- data.frame(x=x_vec, y=y_vec, observed=obs_vec) |> na.omit()
  p_str  <- if(stats$p < 0.001) "p < .001" else sprintf("p = %.3f", stats$p)
  annot  <- sprintf("r = %.3f\n%s\nN = %d", stats$r, p_str, stats$n)

  ggplot(df, aes(x=x, y=y)) +
    geom_smooth(method="lm", se=TRUE, colour=RED, fill="#ffd5d5",
                linewidth=1.0, alpha=0.35) +
    geom_point(aes(shape=observed), colour=NAVY, size=3, alpha=0.85) +
    scale_shape_manual(values = c("TRUE" = 16, "FALSE" = 1), guide = "none") +
    annotate("label", x=-Inf, y=Inf,
             label    = annot,
             hjust    = -0.1, vjust=1.15,
             size     = 3.5, colour=NAVY, fill="white",
             fontface = "bold", lineheight=1.4) +
    labs(
      title = lag_label,
      x     = x_label,
      y     = "Political trust %"
    ) +
    theme_bw(base_size=11) +
    theme(
      plot.title       = element_text(face="bold", colour=NAVY, size=11),
      panel.grid.minor = element_blank()
    )
}

p_s0 <- make_scatter(merged$prof_pc1,  merged$trust_pct, merged$observed, s0,
  "Lag 0 — same year", "Professionalisation PC1 (year t)")
p_s1 <- make_scatter(merged$prof_lag1, merged$trust_pct, merged$observed, s1,
  "Lag 1 — IV leads by 1 year", "Professionalisation PC1 (year t-1)")
p_s2 <- make_scatter(merged$prof_lag2, merged$trust_pct, merged$observed, s2,
  "Lag 2 — IV leads by 2 years", "Professionalisation PC1 (year t-2)")

best_lag <- which.max(abs(c(s0$r, s1$r, s2$r))) - 1
best_r   <- c(s0$r, s1$r, s2$r)[best_lag + 1]
best_p   <- c(s0$p, s1$p, s2$p)[best_lag + 1]
best_n   <- c(s0$n, s1$n, s2$n)[best_lag + 1]

p_scatter <- (p_s0 | p_s1 | p_s2) +
  plot_annotation(
    title    = "Professionalisation and political trust: lagged correlations",
    subtitle = paste0(
      sprintf("Each point = one year, 1979-2025 (N = %d to %d across lags). Filled = BSA-observed; ", min(s0$n, s1$n, s2$n), max(s0$n, s1$n, s2$n)),
      "hollow = calibrated (TrustGov/Ipsos).\n",
      sprintf("Strongest lag: %d (r = %.3f, p = %.3f). BSA-only robustness: lag %d r = %.3f (N = %d, p = %.3f).\n",
              best_lag, best_r, best_p, best_lag,
              c(s0_obs$r, s1_obs$r, s2_obs$r)[best_lag + 1],
              c(s0_obs$n, s1_obs$n, s2_obs$n)[best_lag + 1],
              c(s0_obs$p, s1_obs$p, s2_obs$p)[best_lag + 1]),
      "Health warnings: both series time-trended (common trend may inflate r); ",
      "BSA question wording varies slightly across years; ",
      "trust is the Ch4 political culture variable — this is a cross-chapter exploratory correlation."
    ),
    caption = paste0(
      "Trust DV: BSA 'trust govt just about always/most of time' (NatCen/BSA), extended 1979-2025 via ",
      "TrustGov/Ipsos calibration for BSA gap years (see 41k/41l).\n",
      "Professionalisation IV: career politicians % (Criddle/Henn), SPADs (Cabinet Office/Yong & Hazell), ",
      "MP staffing real terms (IPSA/modelled). PCA composite, 1 SD units."
    ),
    theme = theme(
      plot.title    = element_text(face="bold", colour=NAVY, size=12),
      plot.subtitle = element_text(colour=GREY,  size=8.5,  lineheight=1.3),
      plot.caption  = element_text(colour=GREY,  size=6.5,  lineheight=1.2)
    )
  )

ggsave(OUT2, p_scatter, width=12, height=5.5, dpi=300)
cat("Figure 2 saved:", OUT2, "\n")

cat("\n=== SUMMARY ===\n")
cat(sprintf("Lag 0: r = %.3f (N=%d, p=%.3f)\n", s0$r, s0$n, s0$p))
cat(sprintf("Lag 1: r = %.3f (N=%d, p=%.3f)\n", s1$r, s1$n, s1$p))
cat(sprintf("Lag 2: r = %.3f (N=%d, p=%.3f)\n", s2$r, s2$n, s2$p))
cat(sprintf("Strongest lag: %d\n", best_lag))
cat("Both series time-trended — interpret as association, not causation.\n")
cat("Trust is Ch4 variable; this explores the Ch3->Ch4 cross-chapter link.\n")
