# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41l_trust_extend_2021_2025.R
# 41l_trust_extend_2021_2025.R
# Extend the Ch3 political-trust series to cover 2021, 2022, 2025 (2026
# deliberately left NA - see below), using Ipsos Veracity ("politicians
# generally", % trust to tell the truth) as a calibrated bridge onto BSA's
# scale, same method as 41k_trust_extend_1979.R (linear calibration on
# overlap years, multiple robustness specs, LOO-CV, explicit health warnings).
#
# WHY IPSOS ONLY, NOT OECD: PJ's brief for this pass also flagged the OECD
# "Drivers of Trust in Public Institutions" 2026 report (UK readings at 2021/
# 2023/2025) as a second candidate bridge. Checked directly: oecd.org blocks
# automated access (Cloudflare bot challenge, confirmed via curl - same wall
# hit earlier this session on GESIS/ICPSR). The UK 2021/2023/2025 figures
# quoted in web-search summaries were NEVER verified against the primary OECD
# report and are NOT used here. Separately: even if verified, OECD only
# overlaps BSA at a single year (2023) in the whole window - one point cannot
# support a real regression (0 degrees of freedom), so it would not have
# passed this project's own robustness bar regardless. OECD is left as a
# flagged, unconfirmed, not-yet-usable lead for a future session with
# non-blocked access - see project_wkbd_chapter3_prep.md.
#
# 2026 LEFT NA throughout: no primary source found for any calendar-2026 UK
# trust reading in any tracker (BSA/Ipsos/OECD) - expected, not a search
# failure, since annual waves for 2026 have not yet been fielded/published as
# of this session (Sept 2026). Forcing a number here would mean extrapolating
# past the last real anchor with nothing on the other side - a materially
# weaker move than the gap-filling already done, so it isn't done.
#
# OUTPUTS:
#   data/processed/trust_extend_2021_2025_robustness.csv (all specs' coefs + predictions)
#   data/processed/trust_extended_1979_2025.csv   (FULL merged series, 1979-2025, 2026 excluded)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, tibble, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
IPSOS_IN  <- file.path(PROJECT, "../../sources_raw/ipsos_veracity_index/ipsos_veracity_trust_1983_2023.csv")
BSA_IN    <- file.path(PROJECT, "data/processed/trust_v2.csv")
K_OUT_CSV <- file.path(PROJECT, "data/processed/trust_extended_1979_2024.csv")  # 41k's output, read back in
OUT_ROB   <- file.path(PROJECT, "data/processed/trust_extend_2021_2025_robustness.csv")
OUT_FULL  <- file.path(PROJECT, "data/processed/trust_extended_1979_2025.csv")

# ============================================================
# 1. LOAD
# ============================================================
ipsos <- read_csv(IPSOS_IN, show_col_types = FALSE) |>
  filter(!is.na(politicians_pct)) |>
  select(year, politicians_pct, ipsos_tier = notes) |>
  mutate(is_tier1 = !grepl("TIER 2", ipsos_tier, fixed = TRUE))

bsa <- read_csv(BSA_IN, show_col_types = FALSE) |> select(year, trust_pct)

overlap <- inner_join(bsa, ipsos, by = "year") |> arrange(year)
cat(sprintf("Ipsos-BSA overlap years: N = %d (%s)\n",
            nrow(overlap), paste(overlap$year, collapse = ", ")))
print(overlap)

# ============================================================
# 2. CALIBRATION ROBUSTNESS
# ============================================================
specs <- list(
  "A. All overlap years (incl. Tier-2 2016)" = overlap,
  "B. Tier-1 only (excl. 2016)"               = overlap |> filter(is_tier1),
  "C. Post-2015 only"                         = overlap |> filter(year >= 2016),
  "D. Excl. 2020 (COVID)"                     = overlap |> filter(year != 2020)
)

target_years <- c(2021, 2022, 2025)  # 2026 deliberately excluded, see header

fit_and_predict <- function(d, spec_label) {
  m <- lm(trust_pct ~ politicians_pct, data = d)
  pred <- ipsos |> filter(year %in% target_years) |>
    mutate(trust_pct_pred = predict(m, newdata = tibble(politicians_pct = politicians_pct)),
           spec = spec_label, n_anchor = nrow(d), r2 = summary(m)$r.squared,
           intercept = coef(m)[1], slope = coef(m)[2])
  pred
}

robustness <- bind_rows(lapply(names(specs), function(nm) fit_and_predict(specs[[nm]], nm)))

loo <- do.call(rbind, lapply(seq_len(nrow(overlap)), function(i) {
  train <- overlap[-i, ]; test <- overlap[i, ]
  m <- lm(trust_pct ~ politicians_pct, data = train)
  pred <- predict(m, newdata = test)
  data.frame(year = test$year, observed = test$trust_pct, predicted = pred, error = pred - test$trust_pct)
}))
loo_rmse <- sqrt(mean(loo$error^2))
cat(sprintf("\nSpec A (all overlap years) LOO-CV RMSE: %.2f trust-pct points (N=%d)\n", loo_rmse, nrow(overlap)))
print(loo)

write_csv(robustness, OUT_ROB)
cat(sprintf("\nRobustness table written: %s\n", OUT_ROB))
cat("\n=== Predicted 2021/2022/2025 trust_pct under each calibration spec ===\n")
wide <- robustness |> select(spec, year, trust_pct_pred, n_anchor, r2) |>
  pivot_wider(names_from = spec, values_from = trust_pct_pred)
print(wide)

# ============================================================
# 3. HEADLINE for 2021/2022/2025 — spec B (Tier-1 only) as default: excludes
#    the one unconfirmed Ipsos year (2016) from the calibration itself, most
#    defensible on the same "don't calibrate off shaky anchors" logic as 41k's
#    spec D. All four specs kept as columns so the choice isn't hidden.
# ============================================================
headline_model <- lm(trust_pct ~ politicians_pct, data = specs[["B. Tier-1 only (excl. 2016)"]])
new_years <- ipsos |> filter(year %in% target_years) |>
  mutate(trust_pct = predict(headline_model, newdata = tibble(politicians_pct = politicians_pct)),
         data_source = "Ipsos-calibrated (INTERPOLATED)",
         note = "HEALTH WARNING: not an observed BSA reading — calibrated from Ipsos Veracity via spec B (Tier-1 overlap years, see trust_extend_2021_2025_robustness.csv)")

cat(sprintf("\n=== Headline (spec B) values for 2021/2022/2025 ===\n"))
print(new_years |> select(year, trust_pct, politicians_pct))

# ============================================================
# 4. MERGE with 41k's 1979-2020+2023-2024 output into the FULL 1979-2025 series
# ============================================================
k_series <- read_csv(K_OUT_CSV, show_col_types = FALSE) |>
  select(year, trust_pct, data_source, note)

full <- bind_rows(
  k_series,
  new_years |> select(year, trust_pct, data_source, note)
) |> arrange(year) |> distinct(year, .keep_all = TRUE)

all_target <- 1979:2025
missing <- setdiff(all_target, full$year)
cat(sprintf("\nFULL series: N=%d rows, years %d-%d. Still missing within 1979-2025: %s\n",
            nrow(full), min(full$year), max(full$year),
            if (length(missing) == 0) "none" else paste(missing, collapse = ", ")))

write_csv(full, OUT_FULL)
cat(sprintf("Full 1979-2025 series written: %s\n", OUT_FULL))
cat("2026: deliberately not included — no primary source found for any calendar-2026 UK trust reading yet.\n")
