# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/41n_profess_turb_gam_check.R
# 41n_profess_turb_gam_check.R
#
# Non-linearity check for the profess -> turbulence relationship (standard
# technique across Ch3-9, see [[wkbd-gam-nonlinearity-check]]): OLS linear vs
# quadratic polynomial vs GAM (smooth term, k=5), at each lag (0/1/2 years).
# Rerun 7 Sep 2026 because the underlying professionalisation IV changed
# (Butler & Butler-calibrated staffing series, see 41m/41e) — every number in
# this check is superseded relative to any report before that date.
#
# Same IV/DV construction as 41f_profess_turb_lag.R (duplicated here
# deliberately, matching that script's own pattern of each analysis script
# rebuilding its inputs independently rather than sourcing a shared object).
#
# OUTPUT: console only — this is a footnote-numbers check, not a figure.

suppressMessages({library(dplyr); library(readr); library(tibble); library(mgcv)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT <- .ROOT

norm01 <- function(x) (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
YEARS  <- 1979:2025

career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)
career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"), show_col_types = FALSE) |>
  filter(year <= 2025)
spads_annual <- tibble(year = YEARS, n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT, "data/processed/ipsa_staffing_annual.csv"), show_col_types = FALSE) |>
  select(cal_year, staffing_real = mean_staffing_real_2015)
pre10 <- read_csv(file.path(PROJECT, "data/processed/staffing_pre2010_calibrated_butler.csv"), show_col_types = FALSE) |>
  filter(!is.na(real_2015_mean)) |> select(cal_year = year, staffing_real = real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual  |> select(year, career_pct), by = "year") |>
  left_join(spads_annual   |> select(year, n_spads), by = "year") |>
  left_join(staffing_annual |> select(year, staffing_real), by = "year") |>
  mutate(career_norm = norm01(career_pct), spads_norm = norm01(n_spads), staffing_norm = norm01(staffing_real))
pca_res <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm), scale. = TRUE, center = TRUE)
d_prof  <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

turb <- read_csv(file.path(PROJECT, "../composite_canonical/canonical_pc1_1979_2025.csv"), show_col_types = FALSE) |>
  select(year, turb_pc1 = PC1_index)

merged <- turb |>
  left_join(d_prof |> select(year, prof_pc1), by = "year") |>
  left_join(d_prof |> select(year, prof_lag1 = prof_pc1) |> mutate(year = year + 1), by = "year") |>
  left_join(d_prof |> select(year, prof_lag2 = prof_pc1) |> mutate(year = year + 2), by = "year")

check_lag <- function(iv, dv, label) {
  d <- data.frame(iv = iv, dv = dv) |> na.omit()
  ols  <- lm(dv ~ iv, data = d)
  quad <- lm(dv ~ poly(iv, 2, raw = TRUE), data = d)
  g    <- gam(dv ~ s(iv, k = 5), data = d)
  r2_lin  <- summary(ols)$r.squared
  r2_quad <- summary(quad)$r.squared
  r2_gam  <- summary(g)$r.sq
  quad_p  <- summary(quad)$coefficients[3, 4]
  edf     <- summary(g)$edf[1]
  cat(sprintf("\n%s (N=%d):\n", label, nrow(d)))
  cat(sprintf("  Linear R²=%.3f | Quadratic R²=%.3f (quad term p=%.4g) | GAM R²=%.3f, edf=%.2f\n",
              r2_lin, r2_quad, quad_p, r2_gam, edf))
  invisible(list(r2_lin = r2_lin, r2_quad = r2_quad, r2_gam = r2_gam, quad_p = quad_p, edf = edf, n = nrow(d)))
}

cat("=== Profess -> Turbulence non-linearity check, rerun 7 Sep on calibrated staffing IV ===\n")
r0 <- check_lag(merged$prof_pc1,  merged$turb_pc1, "Lag 0")
r1 <- check_lag(merged$prof_lag1, merged$turb_pc1, "Lag 1")
r2 <- check_lag(merged$prof_lag2, merged$turb_pc1, "Lag 2")

cat(sprintf("\nFootnote summary:\nLinear R² approx doubles/triples vs GAM at each lag (lag0: %.3f→%.3f; lag1: %.3f→%.3f; lag2: %.3f→%.3f).\n",
            r0$r2_lin, r0$r2_gam, r1$r2_lin, r1$r2_gam, r2$r2_lin, r2$r2_gam))
cat(sprintf("Quadratic term p-values: lag0=%.4g, lag1=%.4g, lag2=%.4g\n", r0$quad_p, r1$quad_p, r2$quad_p))
cat(sprintf("GAM effective degrees of freedom: lag0=%.2f, lag1=%.2f, lag2=%.2f\n", r0$edf, r1$edf, r2$edf))
