# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/49_mediation_breakpoint_test.R
# 49_mediation_breakpoint_test.R
# Structural-break test on the DIRECT RELATIONSHIP itself (professionalisation
# -> turbulence, Figure 3.6's c' path), PJ 10 Sep: "is there any change point
# such as the expenses scandal [2009]?"
#
# Distinct from what's already been tested:
# - 41e_professionalisation_pca.R's own break test on prof_pc1 alone: break
#   clustered 1988-1996, not 2009.
# - The canonical composite's own break (turb_pc1 alone): 2015.
# - 45_ministerial_departures_break_test.R (built for exactly the 2009
#   question, but on DEPARTURES not the mediation variables): found 2015-16,
#   not 2009, as the significant break for both total and standalone rates.
# None of those tests the RELATIONSHIP between prof_pc1 and turb_pc1 itself -
# i.e. whether the SLOPE of turbulence-on-professionalisation changes at some
# point, which is what Figure 3.6's direct effect (c') actually is.
#
# METHOD: classic Chow test for a two-parameter regression (intercept + slope
# of turb_pc1 ~ prof_pc1), not the mean-shift version used in 45/47 (which
# only tests a shift in the MEAN of a single series). Same sup-statistic +
# permutation architecture as those scripts, extended to 2 parameters
# (df1=2 instead of 1).
#
# DATA: same merge as 41i_mediation_test.R (canonical_pc1 turbulence,
# professionalisation PC1, full overlap years - trust itself not needed here,
# this tests JUST the direct prof->turb relationship, not the mediation).
# OUTPUT: console only - diagnostic.

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, tibble)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT <- .ROOT

# Rebuild professionalisation PC1 - IDENTICAL construction to 41e-41i (no
# saved CSV exists for this; every mediation-pipeline script rebuilds it
# inline from the same three inputs, so this does too rather than inventing
# a second construction path).
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
YEARS  <- 1979:2025

career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)
career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr     = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                  show_col_types = FALSE) |> filter(year <= 2025)
spads_annual <- tibble(year = YEARS,
  n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),
                  show_col_types=FALSE) |> select(cal_year, staffing_real=mean_staffing_real_2015)
pre10 <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types=FALSE) |> filter(!is.na(real_2015_mean)) |>
  select(cal_year=year, staffing_real=real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr        = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual   |> select(year, career_pct),    by="year") |>
  left_join(spads_annual    |> select(year, n_spads),        by="year") |>
  left_join(staffing_annual |> select(year, staffing_real),  by="year") |>
  mutate(career_norm   = norm01(career_pct),
         spads_norm    = norm01(n_spads),
         staffing_norm = norm01(staffing_real))

pca_res <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm),
                  scale. = TRUE, center = TRUE)
d_prof  <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

turb <- read_csv(file.path(PROJECT, "../composite_canonical/canonical_pc1_1979_2025.csv"),
                  show_col_types = FALSE) |>
  select(year, turb_pc1 = PC1_index)

d <- turb |> inner_join(d_prof |> select(year, prof_pc1), by = "year") |>
  filter(!is.na(turb_pc1), !is.na(prof_pc1)) |> arrange(year)
cat(sprintf("N = %d, years %d-%d\n", nrow(d), min(d$year), max(d$year)))

set.seed(42)
NPERM <- 10000

chow_F_regression <- function(y, x, k, min_seg = 5) {
  n <- length(y); if (k < min_seg || k > n - min_seg) return(NA_real_)
  m_pool <- lm(y ~ x)
  m1 <- lm(y[1:k] ~ x[1:k])
  m2 <- lm(y[(k+1):n] ~ x[(k+1):n])
  rss_pool <- sum(residuals(m_pool)^2)
  rss_split <- sum(residuals(m1)^2) + sum(residuals(m2)^2)
  df1 <- 2  # intercept + slope
  df2 <- n - 2 * df1
  if (rss_split <= 0 || df2 <= 0) return(NA_real_)
  ((rss_pool - rss_split) / df1) / (rss_split / df2)
}
.ks_interior <- function(n, trim = 0.15, min_seg = 5) {
  lo <- max(min_seg, floor(trim * n)); hi <- min(n - min_seg, n - floor(trim * n)); lo:hi
}
supF_regression <- function(y, x, year, trim = 0.15, min_seg = 5) {
  n <- length(y); ks <- .ks_interior(n, trim, min_seg)
  f <- vapply(ks, function(k) chow_F_regression(y, x, k, min_seg), numeric(1))
  list(peak_year = year[ks[which.max(f)]], peak_F = max(f, na.rm = TRUE),
       curve = data.frame(year = year[ks], F = f))
}
perm_pvalue <- function(y, x, year, observed_F, trim = 0.15, min_seg = 5, nperm = NPERM) {
  perm_max <- replicate(nperm, {
    idx <- sample(length(y))
    supF_regression(y[idx], x[idx], year, trim, min_seg)$peak_F
  })
  mean(perm_max >= observed_F, na.rm = TRUE)
}

res <- supF_regression(d$turb_pc1, d$prof_pc1, d$year)
pval <- perm_pvalue(d$turb_pc1, d$prof_pc1, d$year, res$peak_F)

cat(sprintf("\n=== Chow test: structural break in turb_pc1 ~ prof_pc1 (the c' relationship) ===\n"))
cat(sprintf("Peak break year: %d, F = %.2f, permutation p = %.4f (%d draws)\n",
            res$peak_year, res$peak_F, pval, NPERM))
cat("Top 5 candidate years by F:\n")
print(res$curve |> arrange(desc(F)) |> head(5))

# Specifically report what the Chow F looks like right around 2009, since
# that's the exact year PJ asked about - not just the overall peak.
cat("\nF-statistic in the window around 2009 (expenses scandal), for direct comparison:\n")
print(res$curve |> filter(year >= 2005, year <= 2013))

# Slope before/after the peak break year, so a "yes there's a break" answer
# comes with what actually changed (steeper/shallower/sign-flipped).
k <- which(d$year == res$peak_year)
m1 <- lm(turb_pc1 ~ prof_pc1, data = d[1:k, ])
m2 <- lm(turb_pc1 ~ prof_pc1, data = d[(k+1):nrow(d), ])
cat(sprintf("\nSlope before %d: %.3f (n=%d)\n", res$peak_year, coef(m1)[2], k))
cat(sprintf("Slope from %d:  %.3f (n=%d)\n", res$peak_year, coef(m2)[2], nrow(d)-k))
