# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/51c_mediation_firstdiff_diagnostics.R
# 51c_mediation_firstdiff_diagnostics.R
#
# PJ, 14 Sep 2026: the lagged first-differenced check (51b) flipped sign
# (negative, vs positive in levels) and turned marginal-to-significant only
# under HAC correction (p=0.099 OLS, p=0.034 HAC) - PJ: "dig into what's
# driving the sign flip - I'd rather a n/s result", i.e. work out whether
# this is a real (if fragile) finding or an artefact of a few influential
# years / the specific HAC lag choice, rather than assume either answer.
#
# CHECKS: (1) influence diagnostics (Cook's D, DFBETAS) on the first-diff
# direct-effect model: which years are driving it, and does dropping them
# flip the result back to null; (2) sensitivity of the HAC p-value to the
# Newey-West lag order (1 was hardcoded in 51/51b - is p=0.034 fragile to
# that choice?); (3) a plain look at the differenced series itself.
#
# OUTPUT: console only - diagnostic, feeds the footnote 22 rewrite decision.

if (!require("pacman")) install.packages("pacman")
pacman::p_load(readr, dplyr, tibble, sandwich, lmtest)

PROJECT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
YEARS <- 1979:2025
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE)-min(x, na.rm=TRUE))

career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)
career <- tibble(year=YEARS) |> mutate(obs=sapply(year, function(y) max(career_obs$year[career_obs$year<=y])),
  career_pct=career_obs$pct[match(obs, career_obs$year)])
sp <- read_csv(file.path(PROJECT,"data/raw/spads_DATA_ENTRY.csv"),show_col_types=FALSE) |> filter(year<=2025)
spads <- tibble(year=YEARS,n_spads=approx(sp$year,sp$n_spads,xout=YEARS,rule=2)$y)
ip <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),show_col_types=FALSE) |>
  select(year=cal_year,staffing=mean_staffing_real_2015)
pre <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),show_col_types=FALSE) |>
  filter(!is.na(real_2015_mean)) |> select(year,staffing=real_2015_mean)
st <- bind_rows(pre,ip) |> arrange(year)
staff <- tibble(year=YEARS) |> mutate(obs=sapply(year,function(y) max(st$year[st$year<=y])),
  staffing=st$staffing[match(obs,st$year)])
prof <- tibble(year=YEARS) |> left_join(career |> select(year,career_pct),by="year") |>
  left_join(spads,by="year") |> left_join(staff |> select(year,staffing),by="year") |>
  mutate(career=norm01(career_pct),spads=norm01(n_spads),staffing=norm01(staffing))
pca <- prcomp(prof |> select(career,spads,staffing),scale.=TRUE,center=TRUE)
prof$prof_pc1 <- pca$x[,1]
trust <- read_csv(file.path(PROJECT,"data/processed/trust_extended_1979_2025.csv"),show_col_types=FALSE) |> select(year,trust_pct)
turb <- read_csv(file.path(PROJECT,"../composite_canonical/canonical_pc1_1979_2025.csv"),show_col_types=FALSE) |> select(year,turb_pc1=PC1_index)

d_all <- tibble(year = YEARS) |>
  left_join(prof |> select(year, prof_pc1), by = "year") |>
  left_join(trust, by = "year") |>
  left_join(turb,  by = "year") |>
  arrange(year) |>
  mutate(d_prof  = prof_pc1 - lag(prof_pc1),
         d_trust = trust_pct - lag(trust_pct),
         d_turb  = turb_pc1 - lag(turb_pc1))
dd <- d_all |>
  mutate(d_prof_lag2  = lag(d_prof, 2),
         d_trust_lag1 = lag(d_trust, 1)) |>
  filter(!is.na(d_prof_lag2), !is.na(d_trust_lag1), !is.na(d_turb))

cat(sprintf("N = %d, years %d-%d\n\n", nrow(dd), min(dd$year), max(dd$year)))

# ---- (1) Influence diagnostics on the TOTAL-effect first-diff model (simpler, same story as direct) ----
tt <- lm(d_turb ~ d_prof_lag2, data = dd)
cat("=== First-diff total effect model: d_turb ~ d_prof_lag2 ===\n")
print(summary(tt)$coefficients)

infl <- influence.measures(tt)
cooks <- cooks.distance(tt)
dfb   <- dfbetas(tt)[, "d_prof_lag2"]
diag_tbl <- dd |> mutate(cooks_d = cooks, dfbeta_prof = dfb, resid = residuals(tt)) |>
  select(year, d_prof_lag2, d_trust_lag1, d_turb, resid, cooks_d, dfbeta_prof) |>
  arrange(desc(cooks_d))
cat("\nTop 8 years by Cook's distance:\n")
print(head(diag_tbl, 8))

top3_years <- head(diag_tbl$year, 3)
cat(sprintf("\n=== Refit EXCLUDING top-3 Cook's D years (%s) ===\n", paste(top3_years, collapse=", ")))
dd_trim <- dd |> filter(!year %in% top3_years)
tt_trim <- lm(d_turb ~ d_prof_lag2, data = dd_trim)
print(summary(tt_trim)$coefficients)
cat(sprintf("HAC (lag=1) on trimmed data:\n"))
print(coeftest(tt_trim, vcov = NeweyWest(tt_trim, lag=1, prewhite=FALSE)))

# same for the DIRECT-effect model (with trust in it)
yy <- lm(d_turb ~ d_prof_lag2 + d_trust_lag1, data = dd)
cooks_y <- cooks.distance(yy)
diag_y <- dd |> mutate(cooks_d = cooks_y) |> select(year, cooks_d) |> arrange(desc(cooks_d))
top3_y <- head(diag_y$year, 3)
cat(sprintf("\n=== Direct-effect model: top-3 Cook's D years (%s); refit excluding them ===\n", paste(top3_y, collapse=", ")))
yy_trim <- lm(d_turb ~ d_prof_lag2 + d_trust_lag1, data = dd |> filter(!year %in% top3_y))
print(summary(yy_trim)$coefficients)
cat("HAC (lag=1) on trimmed direct-effect data:\n")
print(coeftest(yy_trim, vcov = NeweyWest(yy_trim, lag=1, prewhite=FALSE)))

# ---- (2) Sensitivity of the HAC p-value to the Newey-West lag order ----
cat("\n=== HAC p-value for d_prof_lag2 (direct effect), by Newey-West lag order ===\n")
for (L in 0:4) {
  ct <- coeftest(yy, vcov = NeweyWest(yy, lag = L, prewhite = FALSE))
  cat(sprintf("NW lag=%d: estimate=%.3f, p=%.4f\n", L, ct["d_prof_lag2","Estimate"], ct["d_prof_lag2","Pr(>|t|)"]))
}
cat("\n(lag=1 was the value hardcoded in 51/51b - checking it wasn't a favourable-by-chance pick)\n")

# ---- (3) Plain look at the differenced series ----
cat("\n=== The differenced series itself (sorted by year) ===\n")
print(dd |> select(year, d_prof_lag2, d_trust_lag1, d_turb) |> arrange(year), n = 50)
