# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64d_hansard_annual_extend_1979.R
# 64d_hansard_annual_extend_1979.R
# Self-regarding speech ratio, 1979-1988 — extends speech_self_regarding_annual.csv
# backward using the Evan Odell Hansard Speeches dataset (parlparse-derived,
# CC-BY 4.0, DOI 10.5281/zenodo.4066772), which covers 1979-05-09 to 2020-07-22.
#
# IDENTICAL dictionaries and scoring method to 64b_hansard_annual.R (archived,
# see _ARCHIVE/scripts/scripts_from_archive_may2026/), which produced the
# existing 1988-2019 series from ParlSpeech V2. Recomputes 1988 fresh from this
# source too: ParlSpeech "hard-starts" 22 Nov 1988, so the existing 1988 row in
# speech_self_regarding_annual.csv is built from only ~6 weeks of that year, not
# a full year. Evan Odell's data covers all of 1988, so this replaces that row
# with a full-year figure rather than just prepending 1979-1987.
#
# OUTPUT: data/processed/speech_self_regarding_1979_1988.csv (new years only,
#         1979-1988 inclusive; merge with the existing 1989-2019 file done in
#         a follow-up step once the 2020-2025 API-pull extension is also ready)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, stringr, purrr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
DATA_IN   <- file.path(WKBD_ROOT, "sources_raw/hansard_speeches_evanodell_1979_2020/hansard-speeches-v301.rds")
DATA_OUT  <- file.path(PROJECT, "data/processed/speech_self_regarding_1979_1988.csv")

# ============================================================
# 1. LOAD
# ============================================================
cat("Loading Evan Odell Hansard speeches...\n")
raw <- readRDS(DATA_IN)
cat(sprintf("Loaded: %d rows\n", nrow(raw)))
cat("speech_class breakdown:\n")
print(table(raw$speech_class))

# ============================================================
# 2. FILTER — actual spoken content, 1979-1988 inclusive
# ============================================================
filtered <- raw |>
  mutate(
    date = as.Date(date),
    year = as.integer(format(date, "%Y")),
    text = speech
  ) |>
  filter(
    speech_class == "Speech",
    year >= 1979, year <= 1988,
    nchar(text) > 300
  )

cat(sprintf("After filter: %d speeches, %d years (%d to %d)\n",
            nrow(filtered), n_distinct(filtered$year),
            min(filtered$year), max(filtered$year)))
cat("Speeches per year:\n")
print(as.data.frame(count(filtered, year)), row.names = FALSE)

# Flag: 1979 is a partial year (data starts 9 May 1979 — post-election)
cat("\nNOTE: 1979 covers only 9 May onward (post-1979-election Parliament),",
    "not the full calendar year — same partial-year caveat structure as the",
    "existing 1988 row in the old series (which this script replaces).\n")

# ============================================================
# 3. SAMPLE — up to 1,500 per year, same seed, same method as 64b
# ============================================================
set.seed(42)
sample_df <- filtered |>
  group_by(year) |>
  group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |>
  ungroup()

cat(sprintf("\nSample: %d speeches across %d years\n",
            nrow(sample_df), n_distinct(sample_df$year)))

# ============================================================
# 4. DICTIONARIES — identical to 64b_hansard_annual.R
# ============================================================
career_terms <- c(
  "my role", "my position", "my appointment", "my department",
  "my portfolio", "my responsibilities", "my tenure", "my office",
  "my capacity", "my ministerial", "my shadow", "my career",
  "as minister", "as secretary of state", "as chancellor",
  "as home secretary", "as foreign secretary", "as prime minister",
  "in my view", "i believe", "i think", "i feel"
)

policy_terms <- c(
  "my constituents", "my constituency", "people in my",
  "the evidence", "the research shows", "the data",
  "the public", "communities", "families",
  "workers", "businesses", "this policy", "the policy",
  "the bill", "the legislation", "the government must",
  "we must", "we should", "we need to"
)

# ============================================================
# 5. SCORE — identical method to 64b
# ============================================================
score_speech <- function(text, terms) {
  text_lower <- tolower(text)
  sum(str_count(text_lower, fixed(terms)))
}

cat("\nScoring speeches...\n")
t0 <- Sys.time()

scored <- sample_df |>
  mutate(
    n_words    = str_count(text, "\\S+"),
    n_career   = map_int(text, score_speech, career_terms),
    n_policy   = map_int(text, score_speech, policy_terms),
    self_ratio = (n_career + 0.5) / (n_career + n_policy + 1)
  ) |>
  filter(n_words >= 50)

cat(sprintf("Scoring done in %.1f minutes\n", as.numeric(Sys.time() - t0, units = "mins")))
cat(sprintf("Scored: %d speeches\n", nrow(scored)))

# ============================================================
# 6. ANNUAL AGGREGATION — identical schema to speech_self_regarding_annual.csv
# ============================================================
annual <- scored |>
  group_by(year) |>
  summarise(
    n_speeches      = n(),
    mean_self_ratio = mean(self_ratio),
    se_self_ratio   = sd(self_ratio) / sqrt(n()),
    .groups = "drop"
  ) |>
  arrange(year)

cat("\n=== ANNUAL SELF-REGARDING RATIO, 1979-1988 ===\n")
print(annual, n = 15)

write_csv(annual, DATA_OUT)
cat("\nSaved:", DATA_OUT, "\n")
