# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64f_hansard_annual_merge_1979_2025.R
# 64f_hansard_annual_merge_1979_2025.R
# Merges the three self-regarding-speech annual pieces into one 1979-2025 series:
#   - speech_self_regarding_1979_1988.csv   (64d, Evan Odell dataset)   — 1979-1988
#   - speech_self_regarding_annual.csv      (64b archived, ParlSpeech V2) — 1988-2019
#   - speech_self_regarding_2020_2025.csv   (64e, live Hansard API pull) — 2020-2025
#
# The 1988 row exists in BOTH the first two files. ParlSpeech's 1988 row is built
# from only ~6 weeks of that year (hard-starts 22 Nov 1988) — 64d's full-year 1988
# from Evan Odell's dataset supersedes it. Kept the ParlSpeech 1988 value alongside
# for the record (see console output / SOURCE_NOTE), not written to the merged file.
#
# OUTPUT: data/processed/speech_self_regarding_1979_2025.csv

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT <- .ROOT
DATA_DIR <- file.path(PROJECT, "data/processed")

hist   <- read_csv(file.path(DATA_DIR, "speech_self_regarding_1979_1988.csv"), show_col_types = FALSE)
mid    <- read_csv(file.path(DATA_DIR, "speech_self_regarding_annual.csv"), show_col_types = FALSE)
recent <- read_csv(file.path(DATA_DIR, "speech_self_regarding_2020_2025.csv"), show_col_types = FALSE)

cat(sprintf("1979-1988 (Evan Odell): %d rows, years %d-%d\n", nrow(hist), min(hist$year), max(hist$year)))
cat(sprintf("1988-2019 (ParlSpeech): %d rows, years %d-%d\n", nrow(mid), min(mid$year), max(mid$year)))
cat(sprintf("2020-2025 (Hansard API): %d rows, years %d-%d\n", nrow(recent), min(recent$year), max(recent$year)))

old_1988 <- mid |> filter(year == 1988)
cat(sprintf("\nSuperseded: old partial-year 1988 (ParlSpeech, ~6 weeks) mean_self_ratio=%.4f (n=%d)\n",
            old_1988$mean_self_ratio, old_1988$n_speeches))
new_1988 <- hist |> filter(year == 1988)
cat(sprintf("Replacing with: full-year 1988 (Evan Odell) mean_self_ratio=%.4f (n=%d)\n",
            new_1988$mean_self_ratio, new_1988$n_speeches))

merged <- bind_rows(
  hist,                          # 1979-1988 inclusive (full-year 1988)
  mid |> filter(year >= 1989),   # 1989-2019 (drop old partial 1988)
  recent                         # 2020-2025
) |>
  arrange(year) |>
  mutate(source = case_when(
    year <= 1988 ~ "Evan Odell dataset (parlparse)",
    year <= 2019 ~ "ParlSpeech V2",
    TRUE         ~ "Official Hansard API (live pull)"
  ))

stopifnot(nrow(merged) == 47, min(merged$year) == 1979, max(merged$year) == 2025,
          n_distinct(merged$year) == 47)

cat(sprintf("\n=== MERGED SERIES: %d years, %d-%d ===\n", nrow(merged), min(merged$year), max(merged$year)))
print(merged, n = 47)

OUT <- file.path(DATA_DIR, "speech_self_regarding_1979_2025.csv")
write_csv(merged, OUT)
cat("\nSaved:", OUT, "\n")
