# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64g_hansard_annual_figure_1979_2025.R
# 64g_hansard_annual_figure_1979_2025.R
# Figure: self-regarding speech ratio, full 1979-2025 annual series.
# Source data: speech_self_regarding_1979_2025.csv (built by 64d/64e/64f — see
# those scripts and sources_raw/hansard_speeches_evanodell_1979_2020/,
# sources_raw/hansard_api_pull_2020_2025/ for provenance of each segment).
#
# Same "talk" style as the existing pilot figure (64_hansard_self_regarding_
# pilot.R) — exploratory/working figure, not final book styling.
#
# OUTPUT: figures/ch3_hansard_annual_1979_2025_talk.png

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, ggplot2, scales)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT <- .ROOT
OUT_DIR <- file.path(PROJECT, "figures")
DATA_IN <- file.path(PROJECT, "data/processed/speech_self_regarding_1979_2025.csv")

NAVY <- "#1F3864"; GREY <- "#888888"

d <- read_csv(DATA_IN, show_col_types = FALSE) |>
  mutate(
    lo = mean_self_ratio - 1.96 * se_self_ratio,
    hi = mean_self_ratio + 1.96 * se_self_ratio
  )

# PM-era markers, for context only (matches the book's chapter-2 DV framing) —
# not drawn as a conclusion, just axis orientation
era_lines <- tibble::tibble(
  year  = c(1990, 1997, 2007, 2010, 2016, 2019, 2022),
  label = c("Major", "Blair", "Brown", "Cameron", "May", "Johnson", "Sunak")
)

p <- ggplot(d, aes(x = year, y = mean_self_ratio)) +
  geom_ribbon(aes(ymin = lo, ymax = hi), fill = NAVY, alpha = 0.12) +
  geom_vline(data = era_lines, aes(xintercept = year),
             colour = "grey85", linewidth = 0.3) +
  geom_line(colour = NAVY, linewidth = 0.8) +
  geom_point(colour = NAVY, size = 1.4) +
  geom_hline(yintercept = mean(d$mean_self_ratio),
             linetype = "dashed", colour = GREY, linewidth = 0.4) +
  scale_x_continuous(breaks = seq(1980, 2025, 5)) +
  scale_y_continuous(labels = percent_format(accuracy = 0.1)) +
  labs(
    title    = "Self-regarding speech ratio in the House of Commons, 1979–2025",
    subtitle = paste0(
      "Self-regarding ratio = career/position references as share of (career + constituency/policy)\n",
      "references. Annual means, up to 1,500 sampled speeches/year, 95% CI shown. ",
      "Dashed line = 47-year mean."
    ),
    x       = NULL,
    y       = "Self-regarding ratio (mean, 95% CI)",
    caption = paste0(
      "Sources: 1979–88 Evan Odell Hansard Speeches (parlparse, CC-BY, doi:10.5281/zenodo.4066772); ",
      "1989–2019 ParlSpeech V2 (Rauh & Schwalbach 2020, doi:10.7910/DVN/L4OAKN); ",
      "2020–25 official Hansard API (hansard-api.parliament.uk, live pull, Open Parliament Licence v3.0).\n",
      "Same dictionary and scoring method across all three segments (22 career/position terms, ",
      "18 constituency/policy terms, Laplace-smoothed ratio). Exploratory — dictionary not yet ",
      "validated against a gold standard; three independent source pipelines not yet cross-validated ",
      "against each other on overlapping dates."
    )
  ) +
  theme_minimal(base_size = 11) +
  theme(
    plot.title       = element_text(face = "bold", size = 12, colour = NAVY),
    plot.subtitle    = element_text(size = 9, colour = GREY, lineheight = 1.3),
    plot.caption     = element_text(size = 7, colour = GREY, hjust = 0, lineheight = 1.3),
    panel.grid.minor = element_blank(),
    axis.line        = element_line(colour = "grey80", linewidth = 0.3)
  )

out_path <- file.path(OUT_DIR, "ch3_hansard_annual_1979_2025_talk.png")
ggsave(out_path, p, width = 10, height = 5.5, dpi = 300)
cat("Figure saved:", out_path, "\n")

cat("\nPeriod means (for reference):\n")
d |>
  mutate(period = case_when(
    year <= 1988 ~ "1979-88",
    year <= 1997 ~ "1989-97",
    year <= 2009 ~ "1998-2009",
    year <= 2019 ~ "2010-19",
    TRUE         ~ "2020-25"
  )) |>
  group_by(period) |>
  summarise(mean_ratio = mean(mean_self_ratio), .groups = "drop") |>
  print()
