# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64j_hansard_odell_full_1979_2019.R
# 64j_hansard_odell_full_1979_2019.R
#
# Rebuild the 1979-2019 self-regarding speech series ENTIRELY from the Evan
# Odell Hansard Speeches dataset (Chamber-only, parlparse-derived), replacing
# BOTH the old ParlSpeech V2-based 1989-2019 segment AND the separate
# 1979-1988 Odell extension (64d) with one consistent source and method.
#
# WHY: 64i_overlap_check_multiday.R (7 Sep) found ParlSpeech V2 silently
# starts including Westminster Hall debates (a second, parallel Commons
# chamber, opened Nov 1999) from year 2000 onward, while Odell and the
# 2020-2025 live Hansard API pull are BOTH Chamber-only throughout. That
# gave the spliced series a hidden scope discontinuity: Chamber-only
# (1979-99) -> Chamber+WestHall (2000-19) -> Chamber-only (2020-25).
# PJ, 7 Sep: chose option (a) — make the whole series Chamber-only, since
# Odell/the API already agree closely on Chamber-only content wherever
# tested (1979 test day: 481=481 rows; 2019 test day: 325=325 rows between
# Odell and a live API pull).
#
# Odell's own raw file already spans 1979-05-09 to 2020-07-22 (confirmed in
# 64d's header) — so this single source covers the WHOLE 1979-2019 span
# needed here, at consistent Chamber-only scope, without any splice at all
# inside this range. IDENTICAL dictionaries/scoring/sampling method to
# 64d/64b (same seed, same 1500/year cap, same >300-char / >=50-word filters).
#
# OUTPUT: data/processed/speech_self_regarding_1979_2019_odell.csv
# (to be merged with the existing 2020-2025 API segment in a follow-up step,
# same pattern as the original 64f merge)

suppressMessages({library(dplyr); library(readr); library(stringr); library(purrr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
DATA_IN   <- file.path(WKBD_ROOT, "sources_raw/hansard_speeches_evanodell_1979_2020/hansard-speeches-v301.rds")
DATA_OUT  <- file.path(PROJECT, "data/processed/speech_self_regarding_1979_2019_odell.csv")

cat("Loading Evan Odell Hansard speeches (full range)...\n")
raw <- readRDS(DATA_IN)
cat(sprintf("Loaded: %d rows\n", nrow(raw)))

filtered <- raw |>
  mutate(date = as.Date(date), year = as.integer(format(date, "%Y")), text = speech) |>
  filter(speech_class == "Speech", year >= 1979, year <= 2019, nchar(text) > 300)

cat(sprintf("After filter (Speech class, 1979-2019, >300 chars): %d speeches, %d years\n",
            nrow(filtered), n_distinct(filtered$year)))

set.seed(42)
sample_df <- filtered |>
  group_by(year) |>
  group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |>
  ungroup()
cat(sprintf("Sample: %d speeches across %d years\n", nrow(sample_df), n_distinct(sample_df$year)))

career_terms <- c(
  "my role", "my position", "my appointment", "my department",
  "my portfolio", "my responsibilities", "my tenure", "my office",
  "my capacity", "my ministerial", "my shadow", "my career",
  "as minister", "as secretary of state", "as chancellor",
  "as home secretary", "as foreign secretary", "as prime minister"
)
policy_terms <- c(
  "my constituents", "my constituency", "people in my",
  "the evidence", "the research shows", "the data",
  "the public", "communities", "families",
  "workers", "businesses", "this policy", "the policy",
  "the bill", "the legislation", "the government must",
  "we must", "we should", "we need to"
)
score_speech <- function(text, terms) {
  text_lower <- tolower(text)
  sum(str_count(text_lower, fixed(terms)))
}

cat("\nScoring speeches (this will take a while for 40 years of data)...\n")
t0 <- Sys.time()
scored <- sample_df |>
  mutate(
    n_words    = str_count(text, "\\S+"),
    n_career   = map_int(text, score_speech, career_terms),
    n_policy   = map_int(text, score_speech, policy_terms),
    self_ratio = (n_career + 0.5) / (n_career + n_policy + 1)
  ) |>
  filter(n_words >= 50)
cat(sprintf("Scoring done in %.1f minutes. Scored: %d speeches\n",
            as.numeric(Sys.time() - t0, units = "mins"), nrow(scored)))

annual <- scored |>
  group_by(year) |>
  summarise(n_speeches = n(), mean_self_ratio = mean(self_ratio),
            se_self_ratio = sd(self_ratio) / sqrt(n()), .groups = "drop") |>
  arrange(year) |>
  mutate(source = "Evan Odell dataset (parlparse), Chamber-only")

cat("\n=== ANNUAL SELF-REGARDING RATIO, 1979-2019 (Odell, Chamber-only) ===\n")
print(annual, n = 50)

write_csv(annual, DATA_OUT)
cat("\nSaved:", DATA_OUT, "\n")
