# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64l_constituency_keyword_crosscheck.R
# 64l_constituency_keyword_crosscheck.R
#
# Independent cross-check against Blumenau & Damiani (UCL), "Parliamentary
# Debate in the UK House of Commons" — they measure "constituency-oriented
# language" as the proportion of speeches containing "constituency" or
# "constituent", 1979-2019, finding it roughly DOUBLES (~6% in 1979-83 to
# ~15% in the most recent parliament they observe). This script applies the
# same simple measure to our own corpus (same Odell sample used for the
# self-regarding series, 64j) as an independent check on the direction of
# our own finding (declining self-regarding ratio = rising relative policy/
# constituency language).
#
# NOTE on replication fidelity: their paper states the literal words
# "constituency" or "constituent" (singular). Implemented here as the STEM
# "constituen" (case-insensitive substring), which also catches "constituents"
# and "constituencies" — a defensible extension of an under-specified detail,
# not a literal replication of unstated code. Flagged, not hidden.
#
# Uses the SAME sample as 64j (same filter, same seed=42) for 1979-2019, and
# the same raw pulled text as 64e for 2020-2025, so this is directly
# comparable to the existing self-regarding series, not a fresh sample.
#
# OUTPUT: console only.

suppressMessages({library(dplyr); library(readr); library(stringr); library(purrr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))

# ============================================================
# 1979-2019: reproduce the EXACT same Odell sample as 64j (same seed)
# ============================================================
cat("Loading Odell (reproducing 64j's exact sample)...\n")
raw <- readRDS(file.path(WKBD_ROOT, "sources_raw/hansard_speeches_evanodell_1979_2020/hansard-speeches-v301.rds"))
filtered <- raw |>
  mutate(date = as.Date(date), year = as.integer(format(date, "%Y")), text = speech) |>
  filter(speech_class == "Speech", year >= 1979, year <= 2019, nchar(text) > 300)
set.seed(42)
sample_df <- filtered |>
  group_by(year) |>
  group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |>
  ungroup()

has_constituen <- function(x) str_detect(tolower(x), "constituen")

odell_annual <- sample_df |>
  mutate(n_words = str_count(text, "\\S+"), has_con = has_constituen(text)) |>
  filter(n_words >= 50) |>
  group_by(year) |>
  summarise(n = n(), pct_constituency = round(100 * mean(has_con), 1), .groups = "drop")

# ============================================================
# 2020-2025: same raw pulled text as 64e, same 1500/year sampling logic
# ============================================================
cat("Loading 2020-2025 Hansard API raw text...\n")
api_raw <- read_csv(
  file.path(WKBD_ROOT, "sources_raw/hansard_api_pull_2020_2025/hansard_contributions_2020_2025_dedup.csv"),
  show_col_types = FALSE
) |>
  mutate(date = as.Date(date), year = as.integer(format(date, "%Y"))) |>
  filter(nchar(text) > 300)

set.seed(42)
api_sample <- api_raw |>
  group_by(year) |>
  group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |>
  ungroup()

api_annual <- api_sample |>
  mutate(n_words = str_count(text, "\\S+"), has_con = has_constituen(text)) |>
  filter(n_words >= 50) |>
  group_by(year) |>
  summarise(n = n(), pct_constituency = round(100 * mean(has_con), 1), .groups = "drop")

annual <- bind_rows(odell_annual, api_annual) |> arrange(year)

cat("\n=== Constituency-keyword share by year, 1979-2025 (our corpus) ===\n")
print(as.data.frame(annual), row.names = FALSE)

period <- function(y0, y1) annual |> filter(year >= y0, year <= y1) |>
  summarise(pct = round(100 * weighted.mean(pct_constituency / 100, n), 1)) |> pull(pct)

cat("\n=== Period comparison ===\n")
cat(sprintf("1979-83 (our data):  %.1f%%   (Blumenau & Damiani report ~6%% for this period)\n", period(1979, 1983)))
cat(sprintf("2015-19 (our data):  %.1f%%   (Blumenau & Damiani report ~15%% for their most recent parliament)\n", period(2015, 2019)))
cat(sprintf("2020-25 (our data):  %.1f%%   (outside their study period, no comparator)\n", period(2020, 2025)))
r <- period(2015, 2019) / period(1979, 1983)
cat(sprintf("\nImplied multiplier, our data 1979-83 -> 2015-19: %.2fx (theirs: ~2.5x, 6%% -> 15%%)\n", r))
