# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64m_westhall_appendix_table.R
# 64m_westhall_appendix_table.R
#
# REBUILT 7 Sep 2026 — Appendix robustness table: self-regarding speech
# ratio, headline (Chamber+Westminster Hall) vs alternative (Chamber-only),
# full 1979-2025 span, both sides a single consistent construction now.
# PJ: "we could have some extra tables in the appendix with the westminster
# hall data in or out" -> then "decide chamber-only vs chamber+WH for the
# headline series - keep [chamber+WH] as that is the standard."
#
# Chamber+WH (HEADLINE) = speech_self_regarding_1979_2025.csv — Blumenau &
# Damiani (UCL) 1979-2019 + Hansard API (Chamber+WH pull) 2020-25 (64p).
# Chamber-only (ALTERNATIVE) = speech_self_regarding_1979_2025_chamber_only_
# ALT.csv — Odell 1979-2019 + Hansard API (Chamber-only pull) 2020-25 (64k),
# archived when the headline switched, not deleted.
#
# Earlier version of this table only compared 2000-2019 using the old,
# patchier ParlSpeech-based WH series against Odell — this version compares
# the full 1979-2025 span using two properly-matched, single-method series
# on each side.
#
# Bare comparison table, no interpretive tablenotes, per house convention for
# appendix tables — the interpretation belongs in the chapter text/footnote.
#
# OUTPUT: online_appendix/ch3_westhall_robustness_table.csv

suppressMessages({library(dplyr); library(readr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
DATA_DIR  <- file.path(PROJECT, "data/processed")
OUT_DIR   <- file.path(WKBD_ROOT, "online_appendix")

chamber_wh <- read_csv(file.path(DATA_DIR, "speech_self_regarding_1979_2025.csv"), show_col_types = FALSE) |>
  select(year, chamber_plus_westhall = mean_self_ratio)
chamber_only <- read_csv(file.path(DATA_DIR, "speech_self_regarding_1979_2025_chamber_only_ALT.csv"), show_col_types = FALSE) |>
  select(year, chamber_only = mean_self_ratio)

tbl <- chamber_wh |>
  left_join(chamber_only, by = "year") |>
  mutate(diff = round(chamber_plus_westhall - chamber_only, 4)) |>
  arrange(year)

cat("=== HEADLINE (Chamber+WestHall) vs ALTERNATIVE (Chamber-only), self-regarding ratio ===\n")
print(as.data.frame(tbl), row.names = FALSE)

period <- function(d, y0, y1, col) d |> filter(year >= y0, year <= y1) |> summarise(m = mean({{col}}, na.rm = TRUE)) |> pull(m)
cat("\n=== Period means ===\n")
for (rng in list(c(1979, 1988), c(1989, 1999), c(2000, 2009), c(2010, 2019), c(2020, 2025))) {
  wh <- period(tbl, rng[1], rng[2], chamber_plus_westhall)
  co <- period(tbl, rng[1], rng[2], chamber_only)
  cat(sprintf("%d-%d: Chamber+WestHall (headline) %.1f%%  |  Chamber-only (alt) %.1f%%  |  diff %+.1fpp\n",
              rng[1], rng[2], wh*100, co*100, (wh - co) * 100))
}

dir.create(OUT_DIR, showWarnings = FALSE)
OUT <- file.path(OUT_DIR, "ch3_westhall_robustness_table.csv")
write_csv(tbl, OUT)
cat("\nSaved:", OUT, "\n")
