# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64n_hansard_blumenau_full_1979_2019.R
# 64n_hansard_blumenau_full_1979_2019.R
#
# Rebuild the 1979-2019 self-regarding speech series from the Blumenau &
# Damiani (UCL) House of Commons Speech Database (TheyWorkForYou-derived,
# CC BY 4.0, UK Data Service ReShare DOI 10.5255/UKDA-SN-854292), replacing
# BOTH the ParlSpeech-based series AND the Chamber-only Odell rebuild (64j)
# with a single consistent Chamber+Westminster Hall source.
#
# PJ, 7 Sep: "decide chamber-only vs chamber+WH for the headline series -
# keep as that is the standard" — chosen Chamber+WH, matching the closest
# published comparator (Blumenau & Damiani deliberately include Westminster
# Hall throughout, confirmed against their actual deposited data, not just
# their paper's stated method) and ParlSpeech V2's own construction.
# Chamber-only (Odell-based) is retained as the alternative in the
# robustness appendix table (64m), not deleted.
#
# Using Blumenau's dataset directly (rather than reverting to the old
# ParlSpeech-based series) because it is ONE consistent source across the
# whole 1979-2019 span, at the scope we now want, rather than two spliced
# sources (Odell 1979-88 + ParlSpeech 1989-2019) with different pipelines.
#
# IDENTICAL dictionaries/scoring/sampling method to 64j/64d/64b (same seed,
# 1500/year cap, >300-char / >=50-word filters). Source column is `body`
# (speech text) per speeches_codebook.pdf.
#
# OUTPUT: data/processed/speech_self_regarding_1979_2019_blumenau.csv

suppressMessages({library(dplyr); library(readr); library(stringr); library(purrr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
DATA_IN   <- file.path(WKBD_ROOT, "sources_raw/blumenau_damiani_commons_speeches_1979_2019/extracted/out")
DATA_OUT  <- file.path(PROJECT, "data/processed/speech_self_regarding_1979_2019_blumenau.csv")

career_terms <- c(
  "my role", "my position", "my appointment", "my department",
  "my portfolio", "my responsibilities", "my tenure", "my office",
  "my capacity", "my ministerial", "my shadow", "my career",
  "as minister", "as secretary of state", "as chancellor",
  "as home secretary", "as foreign secretary", "as prime minister"
)
policy_terms <- c(
  "my constituents", "my constituency", "people in my",
  "the evidence", "the research shows", "the data",
  "the public", "communities", "families",
  "workers", "businesses", "this policy", "the policy",
  "the bill", "the legislation", "the government must",
  "we must", "we should", "we need to"
)
score_speech <- function(text, terms) {
  text_lower <- tolower(text)
  sum(str_count(text_lower, fixed(terms)))
}

years <- 1979:2019
results <- vector("list", length(years))
t0_all <- Sys.time()

for (i in seq_along(years)) {
  yr <- years[i]
  f <- file.path(DATA_IN, sprintf("%d.csv", yr))
  if (!file.exists(f)) { cat(sprintf("MISSING: %s\n", f)); next }

  d <- read_csv(f, show_col_types = FALSE, progress = FALSE,
                col_select = c(hdate, body, n_words)) |>
    filter(!is.na(body), nchar(body) > 300)

  set.seed(42)
  samp <- d |> slice_sample(n = min(1500, nrow(d)))

  scored <- samp |>
    mutate(
      n_words_calc = str_count(body, "\\S+"),
      n_career   = map_int(body, score_speech, career_terms),
      n_policy   = map_int(body, score_speech, policy_terms),
      self_ratio = (n_career + 0.5) / (n_career + n_policy + 1)
    ) |>
    filter(n_words_calc >= 50)

  results[[i]] <- tibble(
    year = yr, n_speeches = nrow(scored),
    mean_self_ratio = mean(scored$self_ratio),
    se_self_ratio = sd(scored$self_ratio) / sqrt(nrow(scored)),
    source = "Blumenau & Damiani (UCL/TheyWorkForYou), Chamber+Westminster Hall"
  )
  cat(sprintf("%d: %d speeches, ratio=%.4f (%.1f min elapsed)\n",
              yr, nrow(scored), mean(scored$self_ratio),
              as.numeric(Sys.time() - t0_all, units = "mins")))
}

annual <- bind_rows(results) |> arrange(year)
cat(sprintf("\nTotal: %.1f minutes\n", as.numeric(Sys.time() - t0_all, units = "mins")))
print(annual, n = 50)
write_csv(annual, DATA_OUT)
cat("\nSaved:", DATA_OUT, "\n")
