# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64o_hansard_annual_extend_2025_chamber_wh.R
# 64o_hansard_annual_extend_2025_chamber_wh.R
#
# REPLACES 64e — Self-regarding speech ratio, 2020-2025, now Chamber+
# Westminster Hall (was Chamber-only). PJ, 7 Sep: headline series is
# Chamber+WH throughout, matching Blumenau & Damiani / ParlSpeech V2. WH
# pulled separately (pull_hansard_api_westhall.py, completed 7 Sep: 573
# sitting days, 49,359 contributions) and combined with the existing Chamber
# pull here. IDENTICAL dictionaries/scoring/sampling method to 64e/64d/64j.
#
# OUTPUT: data/processed/speech_self_regarding_2020_2025_chamber_wh.csv

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, stringr, purrr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
CHAMBER_IN <- file.path(WKBD_ROOT, "sources_raw/hansard_api_pull_2020_2025/hansard_contributions_2020_2025_dedup.csv")
WH_IN      <- file.path(WKBD_ROOT, "sources_raw/hansard_api_pull_2020_2025/hansard_contributions_westhall_2020_2025.csv")
DATA_OUT   <- file.path(PROJECT, "data/processed/speech_self_regarding_2020_2025_chamber_wh.csv")

cat("Loading Chamber pull...\n")
chamber <- read_csv(CHAMBER_IN, show_col_types = FALSE)
cat(sprintf("Chamber: %d rows\n", nrow(chamber)))
cat("Loading Westminster Hall pull...\n")
wh <- read_csv(WH_IN, show_col_types = FALSE)
cat(sprintf("Westminster Hall: %d rows\n", nrow(wh)))

combined <- bind_rows(chamber, wh)
cat(sprintf("Combined: %d rows\n", nrow(combined)))

filtered <- combined |>
  mutate(date = as.Date(date), year = as.integer(format(date, "%Y"))) |>
  filter(year >= 2020, year <= 2025, !is.na(text), nchar(text) > 300)

cat(sprintf("After filter: %d speeches, %d years\n", nrow(filtered), n_distinct(filtered$year)))
print(as.data.frame(count(filtered, year)), row.names = FALSE)

set.seed(42)
sample_df <- filtered |>
  group_by(year) |>
  group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |>
  ungroup()
cat(sprintf("Sample: %d speeches\n", nrow(sample_df)))

career_terms <- c(
  "my role", "my position", "my appointment", "my department",
  "my portfolio", "my responsibilities", "my tenure", "my office",
  "my capacity", "my ministerial", "my shadow", "my career",
  "as minister", "as secretary of state", "as chancellor",
  "as home secretary", "as foreign secretary", "as prime minister"
)
policy_terms <- c(
  "my constituents", "my constituency", "people in my",
  "the evidence", "the research shows", "the data",
  "the public", "communities", "families",
  "workers", "businesses", "this policy", "the policy",
  "the bill", "the legislation", "the government must",
  "we must", "we should", "we need to"
)
score_speech <- function(text, terms) {
  text_lower <- tolower(text)
  sum(str_count(text_lower, fixed(terms)))
}

cat("\nScoring...\n")
scored <- sample_df |>
  mutate(
    n_words    = str_count(text, "\\S+"),
    n_career   = map_int(text, score_speech, career_terms),
    n_policy   = map_int(text, score_speech, policy_terms),
    self_ratio = (n_career + 0.5) / (n_career + n_policy + 1)
  ) |>
  filter(n_words >= 50)

annual <- scored |>
  group_by(year) |>
  summarise(n_speeches = n(), mean_self_ratio = mean(self_ratio),
            se_self_ratio = sd(self_ratio) / sqrt(n()), .groups = "drop") |>
  arrange(year) |>
  mutate(source = "Official Hansard API (live pull), Chamber+Westminster Hall")

cat("\n=== ANNUAL SELF-REGARDING RATIO, 2020-2025 (Chamber+WH) ===\n")
print(annual, n = 10)
write_csv(annual, DATA_OUT)
cat("\nSaved:", DATA_OUT, "\n")
