# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64p_hansard_annual_merge_chamber_wh_headline.R
# 64p_hansard_annual_merge_chamber_wh_headline.R
#
# REPLACES 64k. Builds the NEW HEADLINE series — Chamber+Westminster Hall
# throughout, 1979-2025, PJ's decision 7 Sep 2026: "decide chamber-only vs
# chamber+WH for the headline series - keep as that is the standard"
# (matching Blumenau & Damiani / ParlSpeech V2's construction, the closest
# published comparator).
#
#   - speech_self_regarding_1979_2019_blumenau.csv (64n, Blumenau & Damiani/
#     UCL, TheyWorkForYou-derived, Chamber+WH)                — 1979-2019
#   - speech_self_regarding_2020_2025_chamber_wh.csv (64o, live Hansard API,
#     Chamber pull + separately-pulled Westminster Hall combined) — 2020-2025
#
# The Chamber-only rebuild (64j/64k, Odell-based) is NOT deleted — archived
# at data/processed/speech_self_regarding_1979_2025_chamber_only_ALT.csv,
# used as the alternative spec in the robustness appendix table (64m).
#
# OUTPUT: data/processed/speech_self_regarding_1979_2025.csv (headline,
# overwrites the Chamber-only version that briefly held this filename)

suppressMessages({library(dplyr); library(readr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT  <- .ROOT
DATA_DIR <- file.path(PROJECT, "data/processed")

blumenau <- read_csv(file.path(DATA_DIR, "speech_self_regarding_1979_2019_blumenau.csv"), show_col_types = FALSE)
recent   <- read_csv(file.path(DATA_DIR, "speech_self_regarding_2020_2025_chamber_wh.csv"), show_col_types = FALSE)

cat(sprintf("1979-2019 (Blumenau & Damiani, Chamber+WH): %d rows, years %d-%d\n",
            nrow(blumenau), min(blumenau$year), max(blumenau$year)))
cat(sprintf("2020-2025 (Hansard API, Chamber+WH): %d rows, years %d-%d\n",
            nrow(recent), min(recent$year), max(recent$year)))

merged <- bind_rows(blumenau, recent) |> arrange(year)

stopifnot(nrow(merged) == 47, min(merged$year) == 1979, max(merged$year) == 2025,
          n_distinct(merged$year) == 47)

cat(sprintf("\n=== NEW HEADLINE SERIES (Chamber+WH throughout): %d years, %d-%d ===\n",
            nrow(merged), min(merged$year), max(merged$year)))
print(merged, n = 47)

# ---- Compare against the Chamber-only alternative ----
alt <- read_csv(file.path(DATA_DIR, "speech_self_regarding_1979_2025_chamber_only_ALT.csv"), show_col_types = FALSE)
comp <- merged |> select(year, chamber_wh = mean_self_ratio) |>
  left_join(alt |> select(year, chamber_only = mean_self_ratio), by = "year") |>
  mutate(diff = round(chamber_wh - chamber_only, 4))
cat("\n=== Chamber+WH (new headline) vs Chamber-only (alternative), 2000-2025 ===\n")
print(comp |> filter(year >= 2000), n = 26)

OUT <- file.path(DATA_DIR, "speech_self_regarding_1979_2025.csv")
write_csv(merged, OUT)
cat("\nSaved (new headline):", OUT, "\n")
