# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64v_career_orientation_split_2020_2025.R
# 64v_career_orientation_split_2020_2025.R
#
# Extends 64u's redesigned career-orientation split (1979-2019) to
# 2020-2025, mirroring exactly how 64r extended 64q. Same sample, same
# cached member biographies (sources_raw/members_api_biography_cache/,
# already fetched by 64r - no new network calls needed here), same
# frontbench-flagging logic. Only the dictionary changes (see 64u's header
# for the full 5-round pilot history behind it).
#
# OUTPUT: online_appendix/ch3_career_orientation_split_2020_2025.csv

suppressMessages({library(dplyr); library(readr); library(stringr); library(purrr); library(jsonlite)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
CACHE_DIR <- file.path(WKBD_ROOT, "sources_raw/members_api_biography_cache")
dir.create(CACHE_DIR, showWarnings = FALSE, recursive = TRUE)

# ============================================================
# 1. REPRODUCE the exact 2020-2025 sample (same as 64o/64r)
# ============================================================
chamber <- read_csv(file.path(WKBD_ROOT, "sources_raw/hansard_api_pull_2020_2025/hansard_contributions_2020_2025_dedup.csv"), show_col_types = FALSE)
wh <- read_csv(file.path(WKBD_ROOT, "sources_raw/hansard_api_pull_2020_2025/hansard_contributions_westhall_2020_2025.csv"), show_col_types = FALSE)
combined <- bind_rows(chamber, wh) |>
  mutate(date = as.Date(date), year = as.integer(format(date, "%Y"))) |>
  filter(year >= 2020, year <= 2025, !is.na(text), nchar(text) > 300)

set.seed(42)
samp <- combined |> group_by(year) |> group_modify(~ slice_sample(.x, n = min(1500, nrow(.x)))) |> ungroup()
cat(sprintf("Sample: %d speeches, %d unique speakers\n", nrow(samp), n_distinct(samp$member_id)))

# ============================================================
# 2. FETCH POST HISTORY per unique member (cached - reuses 64r's cache)
# ============================================================
ids <- unique(samp$member_id[!is.na(samp$member_id)])
cat(sprintf("Loading biography for %d members (cached)...\n", length(ids)))

get_bio <- function(id) {
  cache_f <- file.path(CACHE_DIR, sprintf("%s.json", id))
  if (file.exists(cache_f)) return(fromJSON(cache_f, simplifyVector = FALSE))
  url <- sprintf("https://members-api.parliament.uk/api/Members/%s/Biography", id)
  res <- tryCatch({
    r <- httr::GET(url, httr::timeout(20))
    if (httr::status_code(r) != 200) return(NULL)
    j <- httr::content(r, as = "text", encoding = "UTF-8")
    write(j, cache_f)
    fromJSON(j, simplifyVector = FALSE)
  }, error = function(e) NULL)
  Sys.sleep(0.15)
  res
}

bios <- vector("list", length(ids))
names(bios) <- as.character(ids)
for (i in seq_along(ids)) bios[[i]] <- get_bio(ids[i])
cat("Done loading biographies\n")

# ============================================================
# 3. BUILD interval table: member_id, start, end (any govt/opposition post)
# ============================================================
intervals <- map_dfr(names(bios), function(id) {
  b <- bios[[id]]
  if (is.null(b) || is.null(b$value)) return(NULL)
  posts <- c(b$value$governmentPosts, b$value$oppositionPosts)
  if (length(posts) == 0) return(NULL)
  map_dfr(posts, function(p) {
    tibble(member_id = as.numeric(id),
           start = as.Date(substr(p$startDate, 1, 10)),
           end = if (is.null(p$endDate)) as.Date("2030-01-01") else as.Date(substr(p$endDate, 1, 10)))
  })
})
cat(sprintf("Post intervals: %d rows across %d members\n", nrow(intervals), n_distinct(intervals$member_id)))

intervals_by_member <- split(intervals[, c("start", "end")], intervals$member_id)

is_frontbench_on <- function(mid, dt) {
  key <- as.character(mid)
  if (is.na(mid) || is.null(intervals_by_member[[key]])) return(FALSE)
  iv <- intervals_by_member[[key]]
  any(iv$start <= dt & iv$end >= dt)
}

samp <- samp |> mutate(is_frontbench = map2_lgl(member_id, date, is_frontbench_on))
cat(sprintf("Frontbench share of sample: %.1f%%\n", 100*mean(samp$is_frontbench)))

# ============================================================
# 4. SCORE - FINAL career-orientation dictionary (identical to 64u, see
#    that script's header for the 5-round pilot history)
# ============================================================
career_terms <- c(
  "i am determined to", "i am determined that", "i am committed to", "i will continue to fight",
  "i want to see", "i would like to see", "i wish to see", "i hope to see", "i want the government to",
  "history will judge",
  "i will vote against", "i fundamentally disagree", "i cannot vote for", "i part company with",
  "i make no apology", "i am not prepared to", "i speak for myself", "i stand by what i have said",
  "no one will tell me",
  "hold ministers to account"
)
policy_terms <- c(
  "my constituents", "my constituency", "people in my",
  "the evidence", "the research shows", "the data",
  "the public", "communities", "families",
  "workers", "businesses", "this policy", "the policy",
  "the bill", "the legislation", "the government must",
  "we must", "we should", "we need to"
)
score_speech <- function(text, terms) sum(str_count(tolower(text), fixed(terms)))

scored <- samp |>
  mutate(
    n_words = str_count(text, "\\S+"),
    n_career = map_int(text, score_speech, career_terms),
    n_policy = map_int(text, score_speech, policy_terms)
  ) |>
  filter(n_words >= 50)

# AGGREGATE-THEN-RATIO (see 64u's header note, 11 Sep, for why - the
# per-speech-average method silently reduces to a policy-term-only measure
# once n_career is this sparse).
annual <- scored |>
  group_by(year, is_frontbench) |>
  summarise(n = n(), n_career_sum = sum(n_career), n_policy_sum = sum(n_policy),
            ratio = (sum(n_career) + 0.5) / (sum(n_career) + sum(n_policy) + 1), .groups = "drop") |>
  # BUG FIX 11 Sep: n_career_sum/n_policy_sum must be in values_from too -
  # leaving them out made pivot_wider treat them as extra id columns, which
  # (since they differ by is_frontbench) produced TWO rows per year instead
  # of one, each half-NA. Caught via reading the raw CSV, not the console
  # print (which wraps wide tables and looked fine at a glance).
  tidyr::pivot_wider(names_from = is_frontbench, values_from = c(n, ratio, n_career_sum, n_policy_sum),
                     names_glue = "{ifelse(is_frontbench=='TRUE','frontbench','backbench')}_{.value}") |>
  rename(n_backbench = backbench_n, backbench_ratio = backbench_ratio,
         n_frontbench = frontbench_n, frontbench_ratio = frontbench_ratio) |>
  mutate(fb_share = n_frontbench / (n_frontbench + n_backbench)) |>
  arrange(year)

cat("\n=== 2020-2025 career-orientation split ===\n")
print(as.data.frame(annual), row.names = FALSE)
cat("\nTotal career-term hits, 2020-2025 sample:", sum(scored$n_career), "\n")

OUT <- file.path(WKBD_ROOT, "online_appendix/ch3_career_orientation_split_2020_2025.csv")
write_csv(annual, OUT)
cat("\nSaved:", OUT, "\n")
