# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/64w_career_orientation_merge_full.R
# 64w_career_orientation_merge_full.R
#
# Merges 64u (1979-2019) and 64v (2020-2025) career-orientation splits into
# one full 47-year table, mirroring 64s's merge of 64q/64r.
#
# OUTPUT: online_appendix/ch3_career_orientation_full_1979_2025.csv

suppressMessages({library(dplyr); library(readr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
OUT_DIR   <- file.path(WKBD_ROOT, "online_appendix")

cols <- c("year", "n_backbench", "backbench_ratio", "n_frontbench", "frontbench_ratio",
          "backbench_n_career_sum", "frontbench_n_career_sum",
          "backbench_n_policy_sum", "frontbench_n_policy_sum")
early <- read_csv(file.path(OUT_DIR, "ch3_career_orientation_split_1979_2019.csv"), show_col_types = FALSE) |>
  select(all_of(cols))
recent <- read_csv(file.path(OUT_DIR, "ch3_career_orientation_split_2020_2025.csv"), show_col_types = FALSE) |>
  select(all_of(cols))

merged <- bind_rows(early, recent) |> arrange(year) |>
  mutate(fb_share = n_frontbench / (n_frontbench + n_backbench))

cat(sprintf("Merged: %d years, %d-%d\n", nrow(merged), min(merged$year), max(merged$year)))

period <- function(d, y0, y1, col) d |> filter(year >= y0, year <= y1) |> summarise(m = mean({{col}}, na.rm = TRUE)) |> pull(m)
cat("\n=== PERIOD MEANS, full 47-year career-orientation series ===\n")
for (rng in list(c(1979,1988), c(1989,1997), c(1998,2009), c(2010,2019), c(2020,2025))) {
  bb <- period(merged, rng[1], rng[2], backbench_ratio)
  fb <- period(merged, rng[1], rng[2], frontbench_ratio)
  cat(sprintf("%d-%d: Backbench %.2f%%  |  Frontbench %.2f%%  |  Frontbench premium %+.2fpp\n",
              rng[1], rng[2], bb*100, fb*100, (fb-bb)*100))
}

cat("\n=== Full annual series ===\n")
print(as.data.frame(merged |> mutate(across(c(backbench_ratio, frontbench_ratio), ~round(.*100, 2)))), row.names = FALSE)

OUT <- file.path(OUT_DIR, "ch3_career_orientation_full_1979_2025.csv")
write_csv(merged, OUT)
cat("\nSaved:", OUT, "\n")
