# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/67_mp_misconduct_robustness.R
# 67_mp_misconduct_robustness.R
#
# Robustness table for Figure 3.4 (MP misconduct — seats forfeited).
# PJ, 11 Sep 2026: "why not get going on these 3.4 and 3.5" (robustness pass
# across Ch3 figures' coding decisions).
#
# THREE CHECKS:
#   A. Regime-shift sensitivity: does the "0 events 1979-2008, 8 events
#      2009-2025" pattern survive excluding the 2 events (Illsley 2011,
#      MacShane 2012) that sit inside the Parliamentary Standards Act 2009
#      s.10 / R v Chaytor [2010] legal-change window? (42_...R's header
#      already argued yes verbally; this quantifies it.)
#   B. Alternative-source comparison: HC Library SN04594 ("imprisoned
#      members") was checked and rejected 8 Sep 2026 as a standalone series
#      (sources_raw/hc_library_sn04594_imprisoned_members/SOURCE_NOTE.md) —
#      documented here as the robustness-by-comparison record.
#   C. ✅ APPLIED, 11 Sep 2026: SN04594's own rejection note surfaced two
#      in-window events that were missing from Mortimore & Blick's list —
#      Fiona Onasanya (2019) and Mike Amesbury (2025). Both verified
#      independently (UK Parliament's own recall-petition record for
#      Onasanya; CPS press release for Amesbury) and added to
#      data/raw/mp_misconduct_seats_forfeited_DATA_ENTRY.csv — this was a
#      CORRECTION (N: 8 -> 10), not a robustness variant, so the base figure
#      now reflects it (PJ: "ok so we need a new figure"). This script's
#      "baseline" below therefore now IS the 10-event series; the historical
#      8-event version is kept as a labelled comparison row only.
#
# OUTPUT: online_appendix/ch3_fig34_misconduct_robustness.csv (+ console)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))

events <- read_csv(file.path(PROJECT, "data/raw/mp_misconduct_seats_forfeited_DATA_ENTRY.csv"),
                    show_col_types = FALSE) |>
  filter(year >= 1979, year <= 2025)

cat("=== BASELINE (Fig 3.4 as built, post-11-Sep correction): N =", nrow(events), "===\n")
cat("Pre-2009:", sum(events$year < 2009), "| 2009+:", sum(events$year >= 2009), "\n")
cat("(Historical pre-correction baseline was N=8, before Onasanya/Amesbury were added.)\n\n")

# ============================================================
# A. REGIME-SHIFT SENSITIVITY — exclude Illsley (2011) & MacShane (2012)
# ============================================================
regime_shift_names <- c("Eric Illsley", "Denis MacShane")
events_excl <- events |> filter(!member %in% regime_shift_names)

cat("=== A. Excluding the 2 PSA-2009/Chaytor-window events (Illsley, MacShane) ===\n")
cat("N =", nrow(events_excl), "| Pre-2009:", sum(events_excl$year < 2009),
    "| 2009+:", sum(events_excl$year >= 2009), "\n")
cat("Remaining events:\n")
print(events_excl |> select(year, member, category, reason))
cat("\n-> Pattern (all events cluster 2009+, none 1979-2008) is UNCHANGED by\n")
cat("   excluding the 2 regime-shift-confounded events. The clustering is not\n")
cat("   an artefact of just those two cases.\n\n")

# ============================================================
# B. ALTERNATIVE SOURCE — HC Library SN04594, documented comparison
# ============================================================
cat("=== B. Alternative source: HC Library SN04594 'Sitting Members imprisoned since 1945' ===\n")
cat("Checked and rejected 8 Sep 2026 as a standalone series — see\n")
cat("sources_raw/hc_library_sn04594_imprisoned_members/SOURCE_NOTE.md.\n")
cat("Reason: 25 rows 1947-2024, but 12/25 (1986-91) are a single clustered\n")
cat("Northern Ireland Troubles-era protest-fine episode (several repeat\n")
cat("notifications of the same 3-4 MPs), unrelated to the personal/financial-\n")
cat("misconduct construct; after 1991 the list is nearly empty (2 events in\n")
cat("33 years pre-2019). 'Imprisonment' alone is too narrow a filter for this\n")
cat("chapter's construct — Mortimore & Blick's broader criminal-conviction +\n")
cat("censure-resignation list remains the better-fitting source.\n\n")

# ============================================================
# C. HISTORICAL COMPARISON — pre-correction 8-event series (Onasanya,
#    Amesbury excluded), kept as a labelled row so the correction's effect
#    on the headline pattern is visible, not just asserted
# ============================================================
added_names <- c("Fiona Onasanya", "Mike Amesbury")
events_pre_correction <- events |> filter(!member %in% added_names)

cat("=== C. Historical (pre-11-Sep-correction) series, for comparison ===\n")
cat("N =", nrow(events_pre_correction), "| Pre-2009:", sum(events_pre_correction$year < 2009),
    "| 2009+:", sum(events_pre_correction$year >= 2009), "\n")
cat("-> The 2 added events both fall in 2009+, so the correction reinforces\n")
cat("   the 'clustered post-2009' pattern rather than disrupting it.\n\n")

# ============================================================
# OUTPUT TABLE
# ============================================================
out_tbl <- tibble(
  check = c("Baseline (corrected, 11 Sep 2026 — as built)",
            "A. Exclude regime-shift events (Illsley, MacShane)",
            "C. Historical pre-correction series (Onasanya, Amesbury excluded)"),
  n_events    = c(nrow(events), nrow(events_excl), nrow(events_pre_correction)),
  n_pre_2009  = c(sum(events$year < 2009), sum(events_excl$year < 2009), sum(events_pre_correction$year < 2009)),
  n_2009_plus = c(sum(events$year >= 2009), sum(events_excl$year >= 2009), sum(events_pre_correction$year >= 2009))
)

OUT <- file.path(WKBD_ROOT, "online_appendix/ch3_fig34_misconduct_robustness.csv")
write_csv(out_tbl, OUT)
cat("Saved:", OUT, "\n")
print(out_tbl)
