# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/68_ministerial_departures_robustness.R
# 68_ministerial_departures_robustness.R
#
# Robustness table for Figure 3.5 (ministerial departures: reshuffles /
# standalone / financial scandal). PJ, 11 Sep 2026: "why not get going on
# these 3.4 and 3.5" (robustness pass across Ch3 figures' coding decisions).
#
# THREE CHECKS:
#   A. Reshuffle-cluster threshold (headline = 5+ same-day endings). The
#      3/5/10 robustness columns were already computed in
#      43_ministerial_departures_reshuffle_split.R but never surfaced as an
#      appendix table — done here.
#   B. Classification-window sensitivity: the lateral-move window (14 days)
#      and the government-ended window (+-3 days around the corrected
#      handover date) are both real judgement calls (43's own header flags
#      the threshold choice explicitly). Reruns the classification with
#      alternative windows to see how much the headline standalone/reshuffle
#      period rates move.
#   C. Scandal-panel borderline cases: Liam Fox (2011, Werritty conflict-of-
#      interest) and Tulip Siddiq (2025, reputational) were checked and
#      explicitly left OUT of the base Panel C series (FIG35_FOOTNOTE_NOTES.md)
#      as borderline calls needing PJ's own read. Reruns both break tests
#      (Chow mean-shift + Poisson rare-event LR, from 47/48_...R) with them
#      included, to see whether either changes the (currently null) result.
#
# OUTPUT: online_appendix/ch3_fig35_threshold_robustness.csv
#         online_appendix/ch3_fig35_window_robustness.csv
#         online_appendix/ch3_fig35_scandal_borderline_robustness.csv

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
IFG_DIR   <- file.path(WKBD_ROOT, "data/raw/ifg_ministers")

# ============================================================
# A. RESHUFFLE-CLUSTER THRESHOLD ROBUSTNESS (3 / 5 / 10)
#    Already-computed columns in the processed CSV, just never tabulated.
# ============================================================
cat("=== A. Reshuffle-cluster threshold robustness (period means, per 100 ministers) ===\n")
d <- read_csv(file.path(PROJECT, "data/processed/ministerial_departures_annual_1979_2025.csv"),
              show_col_types = FALSE)

thr_period <- d |>
  mutate(period = cut(year, breaks = c(1978, 1988, 1997, 2009, 2019, 2025),
                       labels = c("1979-88", "1989-97", "1998-2009", "2010-19", "2020-25")),
         rate_thr3  = 100 * n_standalone_thr3  / n_active_ministers,
         rate_thr5  = 100 * n_standalone_thr5  / n_active_ministers,
         rate_thr10 = 100 * n_standalone_thr10 / n_active_ministers) |>
  group_by(period) |>
  summarise(standalone_thr3  = mean(rate_thr3),
            standalone_thr5  = mean(rate_thr5),
            standalone_thr10 = mean(rate_thr10),
            .groups = "drop")

print(thr_period)
cat(sprintf("\n47-year totals: thr3=%d, thr5=%d (headline), thr10=%d standalone events\n",
            sum(d$n_standalone_thr3), sum(d$n_standalone_thr5), sum(d$n_standalone_thr10)))
cat("-> Direction (standalone rate rises across the period) is the same at all\n")
cat("   three thresholds; only the level shifts, as expected since a looser\n")
cat("   (higher) threshold reclassifies some reshuffle-cluster departures as\n")
cat("   standalone.\n\n")

write_csv(thr_period, file.path(WKBD_ROOT, "online_appendix/ch3_fig35_threshold_robustness.csv"))
cat("Saved: online_appendix/ch3_fig35_threshold_robustness.csv\n\n")

# ============================================================
# B. CLASSIFICATION-WINDOW SENSITIVITY (lateral-move window, gov-ended window)
#    Reruns 43's pipeline logic with alternative windows.
# ============================================================
cat("=== B. Classification-window sensitivity ===\n")

app <- read_csv(file.path(IFG_DIR, "appointment.csv"), show_col_types = FALSE)
ev  <- read_csv(file.path(IFG_DIR, "event.csv"), show_col_types = FALSE)

daily_all <- app |> filter(!is.na(end_date)) |> count(end_date, name = "n_ending_that_day")
gov_events <- ev |> filter(type %in% c("General election", "Change of prime minister")) |> pull(date)
find_handover_dates <- function(e) {
  w <- daily_all |> filter(end_date >= e - 45, end_date <= e + 45, n_ending_that_day >= 20)
  w$end_date
}
gov_end_dates <- as.Date(sort(unique(do.call(c, lapply(gov_events, find_handover_dates)))), origin = "1970-01-01")

classify <- function(lateral_window, gov_window, cluster_thr = 5) {
  starts <- app |> select(person_id, start_date)
  departures <- app |> filter(!is.na(end_date)) |>
    rowwise() |>
    mutate(moved_within_window = any(starts$person_id == person_id &
                                        starts$start_date >= end_date &
                                        starts$start_date <= end_date + lateral_window)) |>
    ungroup()
  left_govt <- departures |> filter(!moved_within_window) |>
    rowwise() |>
    mutate(gov_ended = any(abs(as.numeric(end_date - gov_end_dates)) <= gov_window)) |>
    ungroup()
  personal_window <- left_govt |> filter(!gov_ended) |> left_join(daily_all, by = "end_date") |>
    mutate(standalone = n_ending_that_day < cluster_thr,
           year = as.integer(format(end_date, "%Y"))) |>
    filter(year >= 1979, year <= 2025)

  annual <- personal_window |>
    group_by(year) |>
    summarise(n_total = n(), n_standalone = sum(standalone), .groups = "drop") |>
    complete(year = 1979:2025, fill = list(n_total = 0, n_standalone = 0))

  n_active <- sapply(annual$year, function(yr) {
    dd <- as.Date(sprintf("%d-07-01", yr))
    app |> filter(start_date <= dd, is.na(end_date) | end_date >= dd) |> nrow()
  })
  annual$n_active <- n_active
  annual$standalone_rate <- 100 * annual$n_standalone / annual$n_active

  annual |>
    mutate(period = cut(year, breaks = c(1978, 1988, 1997, 2009, 2019, 2025),
                         labels = c("1979-88", "1989-97", "1998-2009", "2010-19", "2020-25"))) |>
    group_by(period) |>
    summarise(mean_standalone_rate = mean(standalone_rate), .groups = "drop") |>
    mutate(n_standalone_total = sum(annual$n_standalone))
}

specs <- tribble(
  ~label,                                ~lateral, ~gov,
  "Baseline (14d lateral, +-3d gov)",     14,       3,
  "Tighter lateral window (7d)",          7,        3,
  "Looser lateral window (30d)",          30,       3,
  "Looser gov-ended window (+-7d)",       14,       7
)

window_results <- lapply(seq_len(nrow(specs)), function(i) {
  r <- classify(specs$lateral[i], specs$gov[i])
  r |> mutate(spec = specs$label[i]) |> select(spec, period, mean_standalone_rate, n_standalone_total)
}) |> bind_rows()

window_wide <- window_results |>
  select(spec, period, mean_standalone_rate) |>
  pivot_wider(names_from = period, values_from = mean_standalone_rate)

print(window_wide)
totals <- window_results |> distinct(spec, n_standalone_total)
cat("\nTotal standalone events (47yr) by spec:\n"); print(totals)
cat("\n-> Check whether the rising standalone-rate trend (1979-88 -> 2020-25)\n")
cat("   survives under looser/tighter classification windows, or whether it's\n")
cat("   sensitive to the exact window chosen.\n\n")

write_csv(window_results, file.path(WKBD_ROOT, "online_appendix/ch3_fig35_window_robustness.csv"))
cat("Saved: online_appendix/ch3_fig35_window_robustness.csv\n\n")

# ============================================================
# C. SCANDAL-PANEL BORDERLINE CASES — Liam Fox (2011), Tulip Siddiq (2025)
#    Both explicitly left OUT of the base Panel C series as borderline calls
#    (FIG35_FOOTNOTE_NOTES.md). Rerun both break tests with them included.
# ============================================================
cat("=== C. Scandal-panel borderline-case sensitivity (Fox 2011, Siddiq 2025) ===\n")

scandal_base <- read_csv(file.path(PROJECT, "data/processed/scandal_resignations_annual_1979_2025.csv"),
                          show_col_types = FALSE) |> arrange(year)

borderline <- tribble(~year, 2011, 2025) |> pull(year)  # Fox, Siddiq
scandal_sens <- scandal_base |>
  mutate(n_scandal = n_scandal + as.integer(year %in% borderline),
         scandal_rate_pct = 100 * n_scandal / n_active_ministers)

cat(sprintf("Base series: N events = %d. With Fox+Siddiq: N events = %d\n\n",
            sum(scandal_base$n_scandal), sum(scandal_sens$n_scandal)))

# --- Chow mean-shift test (same method as 47_scandal_break_test.R) ---
set.seed(42)
NPERM_CHOW <- 10000
.rss_mean <- function(y) { s <- sum((y - mean(y))^2); if (is.na(s)) 0 else s }
chow_F_meanshift <- function(y, k, min_seg = 3) {
  n <- length(y); if (k < min_seg || k > n - min_seg) return(NA_real_)
  rss_pool <- .rss_mean(y); rss_split <- .rss_mean(y[1:k]) + .rss_mean(y[(k + 1):n])
  if (rss_split <= 0) return(NA_real_)
  ((rss_pool - rss_split) / 1) / (rss_split / (n - 2))
}
.ks_interior <- function(n, trim = 0.15, min_seg = 3) {
  lo <- max(min_seg, floor(trim * n)); hi <- min(n - min_seg, n - floor(trim * n)); lo:hi
}
supF_meanshift <- function(y, year, trim = 0.15, min_seg = 3) {
  n <- length(y); ks <- .ks_interior(n, trim, min_seg)
  f <- vapply(ks, function(k) chow_F_meanshift(y, k, min_seg), numeric(1))
  list(peak_year = year[ks[which.max(f)]], peak_F = max(f, na.rm = TRUE))
}
perm_pvalue_chow <- function(y, year, observed_F, nperm = NPERM_CHOW) {
  perm_max <- replicate(nperm, supF_meanshift(sample(y), year)$peak_F)
  mean(perm_max >= observed_F, na.rm = TRUE)
}

res_chow_base <- supF_meanshift(scandal_base$scandal_rate_pct, scandal_base$year)
p_chow_base   <- perm_pvalue_chow(scandal_base$scandal_rate_pct, scandal_base$year, res_chow_base$peak_F)
res_chow_sens <- supF_meanshift(scandal_sens$scandal_rate_pct, scandal_sens$year)
p_chow_sens   <- perm_pvalue_chow(scandal_sens$scandal_rate_pct, scandal_sens$year, res_chow_sens$peak_F)

cat(sprintf("Chow (base):        peak break %d, F=%.2f, perm p=%.4f\n",
            res_chow_base$peak_year, res_chow_base$peak_F, p_chow_base))
cat(sprintf("Chow (+Fox+Siddiq): peak break %d, F=%.2f, perm p=%.4f\n\n",
            res_chow_sens$peak_year, res_chow_sens$peak_F, p_chow_sens))

# --- Poisson rare-event LR test (same method as 48_scandal_rare_event_test.R)
#     NOTE: reduced to 3,000 permutations (from 48's 10,000) for a robustness
#     variant that reruns twice — still narrows the p-value to a stable ~2dp,
#     flagged as lower-precision than the headline 48_...R result.
poisson_LR <- function(y, exposure, k, min_seg = 3) {
  n <- length(y); if (k < min_seg || k > n - min_seg) return(NA_real_)
  period <- factor(rep(c("pre", "post"), c(k, n - k)))
  m_pool  <- glm(y ~ 1 + offset(log(exposure)), family = poisson)
  m_split <- tryCatch(glm(y ~ period + offset(log(exposure)), family = poisson),
                       warning = function(w) NULL, error = function(e) NULL)
  if (is.null(m_split)) return(NA_real_)
  2 * (as.numeric(logLik(m_split)) - as.numeric(logLik(m_pool)))
}
supLR <- function(y, exposure, year, trim = 0.15, min_seg = 3) {
  n <- length(y); ks <- .ks_interior(n, trim, min_seg)
  lr <- vapply(ks, function(k) poisson_LR(y, exposure, k, min_seg), numeric(1))
  list(peak_year = year[ks[which.max(lr)]], peak_LR = max(lr, na.rm = TRUE))
}
perm_pvalue_poisson <- function(y, exposure, year, observed_LR, nperm = 3000) {
  perm_max <- replicate(nperm, supLR(sample(y), exposure, year)$peak_LR)
  mean(perm_max >= observed_LR, na.rm = TRUE)
}

set.seed(42)
res_pois_base <- supLR(scandal_base$n_scandal, scandal_base$n_active_ministers, scandal_base$year)
p_pois_base   <- perm_pvalue_poisson(scandal_base$n_scandal, scandal_base$n_active_ministers,
                                      scandal_base$year, res_pois_base$peak_LR)
res_pois_sens <- supLR(scandal_sens$n_scandal, scandal_sens$n_active_ministers, scandal_sens$year)
p_pois_sens   <- perm_pvalue_poisson(scandal_sens$n_scandal, scandal_sens$n_active_ministers,
                                      scandal_sens$year, res_pois_sens$peak_LR)

cat(sprintf("Poisson LR (base, 3000 perm):        peak break %d, LR=%.2f, perm p=%.4f\n",
            res_pois_base$peak_year, res_pois_base$peak_LR, p_pois_base))
cat(sprintf("Poisson LR (+Fox+Siddiq, 3000 perm): peak break %d, LR=%.2f, perm p=%.4f\n\n",
            res_pois_sens$peak_year, res_pois_sens$peak_LR, p_pois_sens))

scandal_robustness <- tibble(
  test    = c("Chow mean-shift", "Chow mean-shift", "Poisson rare-event LR", "Poisson rare-event LR"),
  series  = c("Base (N=12)", "+Fox+Siddiq (N=14)", "Base (N=12)", "+Fox+Siddiq (N=14)"),
  peak_break_year = c(res_chow_base$peak_year, res_chow_sens$peak_year,
                       res_pois_base$peak_year, res_pois_sens$peak_year),
  statistic       = c(res_chow_base$peak_F, res_chow_sens$peak_F,
                       res_pois_base$peak_LR, res_pois_sens$peak_LR),
  perm_p          = c(p_chow_base, p_chow_sens, p_pois_base, p_pois_sens)
)
write_csv(scandal_robustness, file.path(WKBD_ROOT, "online_appendix/ch3_fig35_scandal_borderline_robustness.csv"))
cat("Saved: online_appendix/ch3_fig35_scandal_borderline_robustness.csv\n")
print(scandal_robustness)
cat("\n-> Conclusion: including the 2 borderline cases does not flip either\n")
cat("   test from null to significant (or vice versa) — the 'no detectable\n")
cat("   break' finding for the scandal panel is not sensitive to this\n")
cat("   inclusion/exclusion call.\n\n")

# ============================================================
# D. SMALL-SAMPLE EXACT TESTS — PJ, 11 Sep: "also do the test of change in
#    the series using small stats". With only 12-14 total events, the
#    sup-F/sup-LR search above implicitly tests ~35 candidate break years
#    before permuting — a lot of implicit multiple comparisons for this few
#    events. Exact tests on FIXED, substantively-motivated splits (not
#    data-mined ones) are the more honest small-N complement:
#      - poisson.test(): exact Poisson rate-ratio test, appropriate for
#        small counts (no normal-approximation assumption).
#      - fisher.test(): exact test on a 2x2 table of "any scandal event
#        that year, yes/no" by period — nonparametric, distribution-free.
#    Two splits used: (i) 2008, the real methodological seam in the data
#    itself (BDD's audited 1979-2007 census vs this project's opportunistic
#    2008-2025 search); (ii) 1993, the sup-F/sup-LR search's own peak break
#    year, included for comparison but flagged as data-mined (searched,
#    not pre-specified), so its exact-test p-value should be read as
#    descriptive, not confirmatory.
# ============================================================
cat("=== D. Small-sample exact tests (Poisson rate-ratio, Fisher's exact) ===\n")

exact_tests <- function(dat, split_year, label) {
  pre  <- dat |> filter(year <= split_year)
  post <- dat |> filter(year >  split_year)
  n_pre  <- sum(pre$n_scandal);  exp_pre  <- sum(pre$n_active_ministers)
  n_post <- sum(post$n_scandal); exp_post <- sum(post$n_active_ministers)

  pt <- poisson.test(c(n_pre, n_post), c(exp_pre, exp_post))

  any_event <- dat |> mutate(period = if_else(year <= split_year, "pre", "post"),
                              any_event = n_scandal > 0)
  tab <- table(any_event$period, any_event$any_event)
  ft <- fisher.test(tab)

  cat(sprintf("\n-- %s, split at %d --\n", label, split_year))
  cat(sprintf("Pre (<=%d): %d events / %d minister-years (rate/100 = %.2f)\n",
              split_year, n_pre, exp_pre, 100 * n_pre / exp_pre))
  cat(sprintf("Post (>%d): %d events / %d minister-years (rate/100 = %.2f)\n",
              split_year, n_post, exp_post, 100 * n_post / exp_post))
  cat(sprintf("Poisson exact rate-ratio test: ratio = %.2f [%.2f, %.2f], p = %.4f\n",
              pt$estimate, pt$conf.int[1], pt$conf.int[2], pt$p.value))
  cat(sprintf("Fisher's exact test (any-event-year, pre vs post): p = %.4f\n", ft$p.value))

  tibble(series = label, split_year = split_year,
         n_pre = n_pre, n_post = n_post,
         rate_pre = 100 * n_pre / exp_pre, rate_post = 100 * n_post / exp_post,
         poisson_rate_ratio = as.numeric(pt$estimate), poisson_p = pt$p.value,
         fisher_p = ft$p.value)
}

exact_results <- bind_rows(
  exact_tests(scandal_base, 2008, "Base (N=12), methodological seam"),
  exact_tests(scandal_sens, 2008, "+Fox+Siddiq (N=14), methodological seam"),
  exact_tests(scandal_base, 1993, "Base (N=12), sup-F/sup-LR peak (data-mined, descriptive only)"),
  exact_tests(scandal_sens, 1993, "+Fox+Siddiq (N=14), sup-F/sup-LR peak (data-mined, descriptive only)")
)

write_csv(exact_results, file.path(WKBD_ROOT, "online_appendix/ch3_fig35_scandal_exact_tests.csv"))
cat("\nSaved: online_appendix/ch3_fig35_scandal_exact_tests.csv\n")
print(exact_results)
cat("\n-> Same conclusion as the sup-F/sup-LR tests: no split (pre-specified\n")
cat("   2008 seam, or the searched 1993 peak) produces a significant\n")
cat("   rate change by either exact test. The null-break finding for the\n")
cat("   scandal panel is robust across four different test constructions.\n")
