# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/72_combined_scandals_vs_professionalisation.R
# 72_combined_scandals_vs_professionalisation.R
#
# Does the professionalisation index (Figure 3.5 panel D) predict the
# COMBINED bad-behaviour count across Commons + Lords + local government
# (devolved excluded, PJ 14 Sep: "not devolved")? PJ: "need to model for zero
# cases" - correct instinct, a plain correlation on sparse annual counts
# (most years are zero) would be the wrong tool; this uses Poisson
# regression (log-linear on counts), the same family of method as the
# change-point tests elsewhere in this chapter, not OLS/correlation.
#
# ⭐ EXTENDED then REVERTED, 14 Sep 2026. PJ asked to pool in the Figure 3.4
# Panel C ministerial scandal-resignation series too (n=12) - tried it
# (checked for double-counting first: zero individual overlap with the
# Commons misconduct list, different construct - loss of seat vs.
# resignation from office). Result: fit was WORSE on every single test with
# ministerial resignations included (McFadden/R2 lower across the board),
# and for the test that matters most - scandal vs. the actual Ch2 turbulence
# DV - it pushed the raw result from significant (p=0.007-0.027) to
# non-significant (p=0.075-0.078) even before detrending. PJ's call, given
# "the worry about the DV and PCA": drop ministerial resignations, keep the
# THREE-list version (Commons + Lords + local government) as the primary
# specification - it fits better and is the cleaner test against the actual
# book DV. The ministerial-inclusive code is left in below (commented out
# of the main combination) rather than deleted, in case it's wanted again
# as an explicit robustness comparison.
#
# CONSTRUCT CAVEAT, stated once: combining three lists of very different
# rigor. Commons misconduct (n=11) is the systematic Mortimore & Blick
# census. Lords (n=12, using the FINAL list PJ settled on 14 Sep - Rennard
# and Steel dropped as unresolved/unassignable case-years, Lester added) and
# local government (n=18, from the appendix Table C3.1 research) are both
# web-compiled, illustrative, not censuses - see their SOURCE_NOTE.md files.
# Local government's within-year event dates for the 2018-23 section 114
# notice cluster are approximate (Croydon's exact middle-notice date was
# never pinned down) - the annual PATTERN is right, individual year
# assignments in that cluster carry real uncertainty.
#
# Professionalisation PC1 rebuilt identically to 41e/41f/69 (no saved output
# file exists to read).
#
# OUTPUT: console only - diagnostic.

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readr, tidyr)

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))

# ============================================================
# 1. PROFESSIONALISATION PC1 — rebuilt identically to 41e/41f/69
# ============================================================
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
YEARS  <- 1979:2025

career_obs <- bind_rows(
  tibble::tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tibble::tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)
career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr     = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                  show_col_types = FALSE) |> filter(year <= 2025)
spads_annual <- tibble(year = YEARS,
  n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),
                  show_col_types=FALSE) |> select(cal_year, staffing_real=mean_staffing_real_2015)
pre10 <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types=FALSE) |> filter(!is.na(real_2015_mean)) |>
  select(cal_year=year, staffing_real=real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr        = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual  |> select(year, career_pct),    by="year") |>
  left_join(spads_annual   |> select(year, n_spads),       by="year") |>
  left_join(staffing_annual|> select(year, staffing_real), by="year") |>
  mutate(career_norm   = norm01(career_pct),
         spads_norm    = norm01(n_spads),
         staffing_norm = norm01(staffing_real))
pca_res <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm), scale.=TRUE, center=TRUE)
d_prof  <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

# ============================================================
# 2. THREE CASE LISTS, COMBINED INTO ONE ANNUAL COUNT (devolved excluded)
# ============================================================
commons <- read_csv(file.path(PROJECT, "data/processed/mp_misconduct_annual_1979_2025.csv"),
                     show_col_types = FALSE) |> select(year, n_commons = n_total)

ministerial <- read_csv(file.path(PROJECT, "data/processed/scandal_resignations_annual_1979_2025.csv"),
                     show_col_types = FALSE) |> select(year, n_ministerial = n_scandal)

# Lords - final 12-case list (Rennard, Steel excluded; Lester included), PJ 14 Sep
lords_events <- c(`1980`=1, `2001`=1, `2005`=1, `2009`=2, `2010`=2, `2011`=2,
                   `2015`=1, `2018`=1, `2020`=1)

# Local government - 21 cases (updated 14 Sep 2026: added 3 devolved-nation
# cases found once PJ caught that the original search was England-only by
# omission, not by checked absence - see 73_gender_benchmark_localgov.R
# header for full sourcing). Section 114 notice years for 2020-25 are the
# least certain (Croydon's exact 3 dates not all confirmed) - distributed
# across 2020-23 to match the researched annual pattern; treat individual
# years in that cluster as approximate.
localgov_events <- c(
  `1985`=1, `1986`=1,                     # Liverpool, Lambeth (rate-capping)
  `1996`=1,                               # Westminster/Porter
  `1998`=1,                               # Anglesey/Roberts (Wales)
  `2002`=1,                               # Donnygate
  `2014`=1, `2015`=1, `2018`=2,           # Rotherham, Rahman, Northants x2
  `2020`=2, `2021`=3, `2022`=2, `2023`=4, # Liverpool CC + s.114 wave (9) + Bunting (NI)
  `2025`=1                                # McAveety (Scotland)
)
stopifnot(sum(lords_events) == 12, sum(localgov_events) == 21)

to_annual <- function(events) {
  v <- setNames(rep(0, length(YEARS)), YEARS)
  v[names(events)] <- events
  as.numeric(v)
}
# Ministerial resignations kept loaded but NOT pooled in - see header. Set
# INCLUDE_MINISTERIAL <- TRUE to reproduce the 4-list robustness comparison.
INCLUDE_MINISTERIAL <- FALSE

d <- tibble(year = YEARS) |>
  left_join(commons, by = "year") |>
  left_join(ministerial, by = "year") |>
  mutate(n_ministerial = coalesce(n_ministerial, 0),
         n_lords    = to_annual(lords_events),
         n_localgov = to_annual(localgov_events),
         n_combined = n_commons + n_lords + n_localgov +
                      (if (INCLUDE_MINISTERIAL) n_ministerial else 0)) |>
  left_join(d_prof |> select(year, prof_pc1), by = "year")

cat(sprintf("Combined total: %d events (Commons %d, Lords %d, local govt %d%s) over %d years\n",
            sum(d$n_combined), sum(d$n_commons), sum(d$n_lords), sum(d$n_localgov),
            if (INCLUDE_MINISTERIAL) sprintf(", Ministerial %d", sum(d$n_ministerial)) else "",
            nrow(d)))
cat(sprintf("Zero-event years: %d of %d (%.0f%%)\n",
            sum(d$n_combined == 0), nrow(d), 100*mean(d$n_combined==0)))

# ============================================================
# 3. POISSON REGRESSION — combined count ~ professionalisation PC1
#    (contemporaneous and lagged 1-2 years, matching the chapter's existing
#    lag convention for the profess->turbulence test)
# ============================================================
run_poisson <- function(d, lag) {
  dd <- d |> mutate(prof_lag = dplyr::lag(prof_pc1, lag)) |> filter(!is.na(prof_lag))
  m  <- glm(n_combined ~ prof_lag, family = poisson, data = dd)
  s  <- summary(m)$coefficients["prof_lag", ]
  irr <- exp(s["Estimate"])
  cat(sprintf("Lag %d: coef=%.3f (IRR=%.3f), SE=%.3f, z=%.3f, p=%.4f, N=%d, McFadden R2=%.3f\n",
              lag, s["Estimate"], irr, s["Std. Error"], s["z value"], s["Pr(>|z|)"], nrow(dd),
              1 - logLik(m)/logLik(glm(n_combined ~ 1, family=poisson, data=dd))))
}
cat("\n=== Poisson GLM: combined scandal count ~ professionalisation PC1 ===\n")
for (L in 0:2) run_poisson(d, L)

cat("\nNote: local government's 2018-23 section 114 cluster has approximate\n")
cat("within-year assignment (see script header) - a real but soft input to\n")
cat("this model, unlike the Commons/Lords components.\n")

# ============================================================
# 4. ROBUSTNESS — same spurious-common-trend check as footnote 15's
#    first-differencing test for professionalisation->turbulence. Both
#    professionalisation PC1 and the combined count trend upward over the
#    same 47 years; a raw-levels Poisson association could be mechanical,
#    not behavioural. Two checks: (a) add a linear year trend to the model
#    and see if professionalisation survives; (b) first-difference
#    professionalisation and refit.
# ============================================================
cat("\n=== Robustness: does professionalisation survive controlling for time? ===\n")
d2 <- d |> mutate(year_c = year - mean(year))
m_trend <- glm(n_combined ~ prof_pc1 + year_c, family = poisson, data = d2)
print(summary(m_trend)$coefficients)

cat("\n=== Robustness: first-differenced professionalisation ===\n")
d3 <- d |> arrange(year) |> mutate(prof_diff = prof_pc1 - dplyr::lag(prof_pc1)) |>
  filter(!is.na(prof_diff))
m_diff <- glm(n_combined ~ prof_diff, family = poisson, data = d3)
print(summary(m_diff)$coefficients)

cat("\n=== Non-linearity check: quadratic + GAM, matching footnote 13's method ===\n")
pacman::p_load(mgcv)
m_quad <- glm(n_combined ~ prof_pc1 + I(prof_pc1^2), family = poisson, data = d)
cat("Quadratic Poisson:\n"); print(summary(m_quad)$coefficients)
m_gam  <- gam(n_combined ~ s(prof_pc1, k = 5), family = poisson, data = d)
cat(sprintf("GAM: edf=%.2f, s(prof_pc1) p=%.4f, deviance explained=%.3f\n",
            summary(m_gam)$edf, summary(m_gam)$s.table[1,"p-value"], summary(m_gam)$dev.expl))

# ============================================================
# 5. REVERSE DIRECTION — does the scandal count predict professionalisation?
#    PJ 14 Sep: "does scandal predict the PCA" (the reverse-causation /
#    selection check, red-team objection #13). prof_pc1 is continuous
#    (PCA-derived), so this is OLS, not Poisson - the count variable is now
#    the predictor, not the outcome. Same trend-robustness discipline
#    applied: raw levels, then controlling for year, then first-differenced.
# ============================================================
cat("\n=== Reverse direction: professionalisation PC1 ~ combined scandal count ===\n")
run_ols_reverse <- function(d, lag) {
  dd <- d |> mutate(scandal_lag = dplyr::lag(n_combined, lag)) |> filter(!is.na(scandal_lag))
  m  <- lm(prof_pc1 ~ scandal_lag, data = dd)
  s  <- summary(m)$coefficients["scandal_lag", ]
  cat(sprintf("Lag %d: coef=%.3f, SE=%.3f, t=%.3f, p=%.4f, N=%d, R2=%.3f\n",
              lag, s["Estimate"], s["Std. Error"], s["t value"], s["Pr(>|t|)"],
              nrow(dd), summary(m)$r.squared))
}
for (L in 0:2) run_ols_reverse(d, L)

cat("\n=== Reverse direction robustness: controlling for year ===\n")
m_rev_trend <- lm(prof_pc1 ~ n_combined + year_c, data = d2)
print(summary(m_rev_trend)$coefficients)

cat("\n=== Reverse direction robustness: first-differenced professionalisation ===\n")
m_rev_diff <- lm(prof_diff ~ n_combined, data = d3)
print(summary(m_rev_diff)$coefficients)

cat("\n=== Reverse direction non-linearity check: quadratic + GAM ===\n")
m_rev_quad <- lm(prof_pc1 ~ n_combined + I(n_combined^2), data = d)
cat("Quadratic OLS:\n"); print(summary(m_rev_quad)$coefficients)
m_rev_gam  <- gam(prof_pc1 ~ s(n_combined, k = 5), data = d)
cat(sprintf("GAM: edf=%.2f, s(n_combined) p=%.4f, deviance explained=%.3f\n",
            summary(m_rev_gam)$edf, summary(m_rev_gam)$s.table[1,"p-value"], summary(m_rev_gam)$dev.expl))

# ============================================================
# 6. THE ACTUAL Ch2 TURBULENCE DV, not professionalisation — PJ 14 Sep:
#    "having the chapter two PCA as the dv with scandal as the predictor."
#    turbulence_pc1 is continuous (canonical composite PCA), so OLS, same
#    trend-robustness treatment as everything else here. NOT circular in the
#    objection-#3 sense: the combined scandal count (Commons seats-forfeited
#    + Lords + local government) is not one of the composite's 6 input
#    components (exec_instab, pedersen, defeats_py, nao_serious,
#    spending_churn, + 1 more) - a different construct from all of them.
# ============================================================
turb <- read_csv(file.path(PROJECT, "../composite_canonical/canonical_pc1_1979_2025.csv"),
                  show_col_types = FALSE) |> select(year, turb_pc1 = PC1_index)
d4 <- d |> left_join(turb, by = "year")

cat("\n=== Ch2 turbulence PC1 ~ combined scandal count ===\n")
run_ols_turb <- function(d, lag) {
  dd <- d |> mutate(scandal_lag = dplyr::lag(n_combined, lag)) |> filter(!is.na(scandal_lag), !is.na(turb_pc1))
  m  <- lm(turb_pc1 ~ scandal_lag, data = dd)
  s  <- summary(m)$coefficients["scandal_lag", ]
  cat(sprintf("Lag %d: coef=%.3f, SE=%.3f, t=%.3f, p=%.4f, N=%d, R2=%.3f\n",
              lag, s["Estimate"], s["Std. Error"], s["t value"], s["Pr(>|t|)"],
              nrow(dd), summary(m)$r.squared))
}
for (L in 0:2) run_ols_turb(d4, L)

cat("\n=== Robustness: controlling for year ===\n")
d4c <- d4 |> mutate(year_c = year - mean(year))
m_turb_trend <- lm(turb_pc1 ~ n_combined + year_c, data = d4c)
print(summary(m_turb_trend)$coefficients)

cat("\n=== Robustness: first-differenced turbulence ===\n")
d4d <- d4 |> arrange(year) |> mutate(turb_diff = turb_pc1 - dplyr::lag(turb_pc1)) |>
  filter(!is.na(turb_diff))
m_turb_diff <- lm(turb_diff ~ n_combined, data = d4d)
print(summary(m_turb_diff)$coefficients)

cat("\n=== Turbulence-DV non-linearity check: quadratic + GAM ===\n")
m_turb_quad <- lm(turb_pc1 ~ n_combined + I(n_combined^2), data = d4)
cat("Quadratic OLS:\n"); print(summary(m_turb_quad)$coefficients)
m_turb_gam  <- gam(turb_pc1 ~ s(n_combined, k = 5), data = d4)
cat(sprintf("GAM: edf=%.2f, s(n_combined) p=%.4f, deviance explained=%.3f\n",
            summary(m_turb_gam)$edf, summary(m_turb_gam)$s.table[1,"p-value"], summary(m_turb_gam)$dev.expl))

cat("\n=== Does the turbulence curvature survive detrending? (PJ follow-up, 14 Sep) ===\n")
d4c2 <- d4 |> mutate(year_c = year - mean(year))
m_turb_quad_trend <- lm(turb_pc1 ~ n_combined + I(n_combined^2) + year_c, data = d4c2)
cat("Quadratic + year control:\n"); print(summary(m_turb_quad_trend)$coefficients)

m_turb_gam_trend <- gam(turb_pc1 ~ s(n_combined, k=5) + year_c, data = d4c2)
cat(sprintf("GAM + year control: s(n_combined) p=%.4f, year_c p=%.4f, dev.expl=%.3f\n",
            summary(m_turb_gam_trend)$s.table[1,"p-value"],
            summary(m_turb_gam_trend)$p.table["year_c","Pr(>|t|)"],
            summary(m_turb_gam_trend)$dev.expl))

d4d2 <- d4 |> arrange(year) |> mutate(turb_diff = turb_pc1 - dplyr::lag(turb_pc1),
                                        n_diff = n_combined - dplyr::lag(n_combined)) |>
  filter(!is.na(turb_diff))
m_turb_quad_diff <- lm(turb_diff ~ n_combined + I(n_combined^2), data = d4d2)
cat("First-differenced turbulence, quadratic on LEVELS scandal count:\n")
print(summary(m_turb_quad_diff)$coefficients)

cat("\n=== Turbulence-DV quadratic + GAM at EACH lag (0/1/2), matching chapter convention ===\n")
for (L in 0:2) {
  dd <- d4 |> mutate(scandal_lag = dplyr::lag(n_combined, L)) |>
    filter(!is.na(scandal_lag), !is.na(turb_pc1))
  m_q <- lm(turb_pc1 ~ scandal_lag + I(scandal_lag^2), data = dd)
  cq  <- summary(m_q)$coefficients
  m_g <- gam(turb_pc1 ~ s(scandal_lag, k = 5), data = dd)
  cat(sprintf("\n-- Lag %d (N=%d) --\n", L, nrow(dd)))
  print(cq)
  cat(sprintf("GAM: edf=%.2f, s(scandal_lag) p=%.4f, dev.expl=%.3f\n",
              summary(m_g)$edf, summary(m_g)$s.table[1,"p-value"], summary(m_g)$dev.expl))
}

cat("\n=== Does curvature at lags 1-2 survive year control + first-differencing? ===\n")
for (L in 1:2) {
  dd <- d4 |> arrange(year) |> mutate(scandal_lag = dplyr::lag(n_combined, L),
                                        year_c = year - mean(year, na.rm=TRUE)) |>
    filter(!is.na(scandal_lag), !is.na(turb_pc1))
  cat(sprintf("\n-- Lag %d, quadratic + year control (N=%d) --\n", L, nrow(dd)))
  m_qy <- lm(turb_pc1 ~ scandal_lag + I(scandal_lag^2) + year_c, data = dd)
  print(summary(m_qy)$coefficients)
  m_gy <- gam(turb_pc1 ~ s(scandal_lag, k=5) + year_c, data = dd)
  cat(sprintf("GAM+year: s() p=%.4f, year_c p=%.4f, dev.expl=%.3f\n",
              summary(m_gy)$s.table[1,"p-value"], summary(m_gy)$p.table["year_c","Pr(>|t|)"],
              summary(m_gy)$dev.expl))

  dd_diff <- dd |> mutate(turb_diff = turb_pc1 - dplyr::lag(turb_pc1)) |> filter(!is.na(turb_diff))
  cat(sprintf("-- Lag %d, first-differenced turbulence, quadratic on LEVELS scandal_lag (N=%d) --\n", L, nrow(dd_diff)))
  m_qd <- lm(turb_diff ~ scandal_lag + I(scandal_lag^2), data = dd_diff)
  print(summary(m_qd)$coefficients)
}
