# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/allparty_review/build_fig_2_7_comparative_volatility.R
# ⭐ RENUMBERED 2.9 -> 2.8, 17 Aug 2026 (old Fig 2.3 dropped; everything after shifts down one).
# ⭐ Panel labels changed from "A · " to "A. " — this figure was the only one using a middle dot.
# ⚠ NO Chow content here, so the original script is edited IN PLACE rather than forked into a
#   _NOCHOW variant. Backup: build_fig_2_7_comparative_volatility.R.bak_17aug.
# ⚠ FOR THE AUDIT: this script writes THREE files — the numbered figure, a two-panel alt
#   (fig_volatility_two_pane.png) and an alias (fig_volatility_comparative.png). Decide before
#   upload which of them ships.
# ⚠ FOR THE AUDIT: `SUB` is defined ("Not the most volatile face in the room...") but never
#   used. It is a conclusion, and house style keeps conclusions off figures. Dead code — leave
#   unused or delete deliberately, do not wire it in.

# Two-pane comparative electoral-volatility figure — COMMON raw/angular style in both panels.
# No LOESS anywhere: election points connected by straight lines throughout.
# Panel A: peer field = faint grey raw lines (one per democracy) + UK bold + Germany dashed.
# Panel B: UK / Canada / Australia raw lines. Drops "cousins"; hard-boiled frame per PJ steer.
suppressMessages({library(ggplot2); library(patchwork)})
BASE <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
HERE <- file.path(BASE, "max_burn_2607/comparative/electoral_volatility")
DAT  <- file.path(HERE, "data"); FIG <- file.path(HERE, "figures")

em  <- read.csv(file.path(DAT, "emanuele_tv_western_europe_1945_2025.csv"))
can <- read.csv(file.path(DAT, "canada_volatility_computed.csv"))
aus <- read.csv(file.path(DAT, "australia_volatility_computed.csv"))
ukp <- read.csv(file.path(BASE, "easy_win_proposals/robust_ge_pedersen_8v4_FIXED.csv"))
em  <- em[order(em$country, em$xyear), ]
uk  <- em[em$country=="UK", ]; ger <- em[em$country=="Germany", ]; oth <- em[em$country!="UK", ]

era <- function(x,yr,cut=2015) c(pre=mean(x[yr<cut],na.rm=TRUE), post=mean(x[yr>=cut],na.rm=TRUE))
uk_e<-era(uk$tv,uk$election_year); oth_e<-era(oth$tv,oth$election_year)
rk <- aggregate(tv~country, em[em$election_year>=2015,], mean); rk<-rk[order(-rk$tv),]; uk_rank<-which(rk$country=="UK")

# ---- one house style for BOTH panels ----
house <- theme_minimal(base_size=10) + theme(panel.grid.minor=element_blank(), panel.grid.major.x=element_blank(),
  legend.position="none",
  # 17 Aug: this was the last figure still labelling panels with a bold "A. " PREFIX inside the
  # subtitle. House style is a bold labs(tag=) letter with an ITALIC grey30 subtitle beside it
  # (FIGURE_STYLE_GUIDE.md). Converted so 2.7 matches 2.1 and 2.6-2.16.
  plot.subtitle=element_text(face="italic", size=9, colour="grey30"),
  plot.tag=element_text(face="bold", size=11),
  axis.title=element_text(size=9, colour="grey20"))
XB <- scale_x_continuous(breaks=seq(1950,2020,10), expand=expansion(add=c(0.5,16)))
YB <- scale_y_continuous(limits=c(0,NA), expand=expansion(mult=c(0,.08)))
lastv <- function(d,xcol,ycol){ d<-d[!is.na(d[[ycol]]),]; d[[ycol]][which.max(d[[xcol]])] }

# ---- Panel A: UK vs four representative European democracies (raw lines) ----
it <- em[em$country=="Italy",]; nl <- em[em$country=="Netherlands",]; ch <- em[em$country=="Switzerland",]
# manual label-y nudges to avoid collisions at the right edge (UK/NL cluster ~mid-20s)
LY <- c(uk=lastv(uk,"xyear","tv")+1.2, nl=lastv(nl,"xyear","tv")-1.4,
        it=lastv(it,"xyear","tv"), ger=lastv(ger,"xyear","tv"), ch=lastv(ch,"xyear","tv"))
pA <- ggplot() +
  geom_line(data=it,  aes(xyear, tv), colour="grey45", linetype="solid",    linewidth=0.7) +
  geom_line(data=ger, aes(xyear, tv), colour="grey40", linetype="longdash", linewidth=0.7) +
  geom_line(data=nl,  aes(xyear, tv), colour="grey55", linetype="dashed",   linewidth=0.7) +
  geom_line(data=ch,  aes(xyear, tv), colour="grey60", linetype="dotted",   linewidth=0.85) +
  geom_line(data=uk,  aes(xyear, tv), colour="black", linewidth=1.3) +
  geom_point(data=uk, aes(xyear, tv), colour="black", size=1.2) +
  annotate("text", x=2026.5, y=LY["uk"],  label="UK", fontface="bold", size=3.2, hjust=0) +
  annotate("text", x=2026.5, y=LY["it"],  label="Italy", colour="grey45", size=2.7, hjust=0) +
  annotate("text", x=2026.5, y=LY["ger"], label="Germany", colour="grey40", size=2.7, hjust=0) +
  annotate("text", x=2026.5, y=LY["nl"],  label="Netherlands", colour="grey50", size=2.7, hjust=0) +
  annotate("text", x=2026.5, y=LY["ch"],  label="Switzerland", colour="grey55", size=2.7, hjust=0) +
  XB + YB +
  labs(tag="A", subtitle="Compared with four representative European democracies (Emanuele total volatility)",
       x=NULL, y="Total volatility") + house

# ---- UK 4-category volatility EXTENDED back to 1950 (pre-1979 from sourced GE shares) ----
ukv <- read.csv(file.path(HERE,"raw","uk_ge_voteshare_1945_1979.csv"), comment.char="#")
ukv <- ukv[order(ukv$xyear), ]
M <- as.matrix(ukv[,c("con","lab","lib")]); M <- cbind(M, oth = 100 - rowSums(M))
pv <- c(NA, sapply(2:nrow(ukv), function(i) 0.5*sum(abs(M[i,]-M[i-1,]))))
uk_pre <- data.frame(year=ukv$xyear, v=round(pv,2))
cat(sprintf("UK continuity check: computed 1979 = %.2f vs book ped_4cat 1979 = %.2f\n",
            uk_pre$v[ukv$xyear==1979], ukp$ped_4cat[ukp$year==1979]))
uk_pre <- uk_pre[!is.na(uk_pre$v) & uk_pre$year < 1979, ]     # 1950..Oct-1974; book supplies 1979+
uk_all <- rbind(uk_pre, data.frame(year=ukp$year, v=ukp$ped_4cat))

# ---- Panel B: raw lines, UK (1950+) / Canada / Australia (matched major-party basis) ----
ang <- rbind(data.frame(year=uk$xyear,v=uk$tv,who="UK"),  # ALL-PARTY (Emanuele TV) for consistency
             data.frame(year=can$year,v=can$volatility,who="Canada"),
             data.frame(year=aus$year,v=aus$volatility,who="Australia"))
ang <- ang[!is.na(ang$v), ]; ang$who<-factor(ang$who, levels=c("UK","Canada","Australia"))
pB <- ggplot(ang, aes(year,v,group=who)) +
  geom_line(aes(colour=who, linewidth=who)) + geom_point(aes(colour=who), size=1.2) +
  scale_colour_manual(values=c("black","grey35","grey65")) + scale_linewidth_manual(values=c(1.3,0.8,0.8)) +
  annotate("text", x=2026, y=lastv(uk,"xyear","tv"), label="UK", fontface="bold", size=3.2, hjust=0) +
  annotate("text", x=2026, y=lastv(can,"year","volatility"), label="Canada", colour="grey35", size=2.8, hjust=0) +
  annotate("text", x=2026, y=lastv(aus,"year","volatility"), label="Australia", colour="grey60", size=2.8, hjust=0) +
  XB + YB +
  # ⛔ The previous subtitle overran the canvas and printed clipped as "...read tr". It also told
  #    the reader how to read the panel ("read trends, not levels") and what the comparators are
  #    measured on — both belong in the footnote. Shortened 17 Aug.
  labs(tag="B", subtitle="Compared with the plurality systems, Canada and Australia",
       x=NULL, y="Volatility (main parties)") + house

# ---- Panel C: three AVERAGE trajectories, indexed to 1950s–60s = 100 ----
# Bases differ (European total volatility vs major-party for the Westminster peers), so each group
# is indexed to its own 1950–69 mean and we compare RATES OF CHANGE, not levels. 5-year bins.
b5 <- function(yr) floor(yr/5)*5 + 2.5
euA <- aggregate(tv ~ b, transform(em, b=b5(election_year)), mean); names(euA)[2]<-"val"; euA$grp<-"Europe"
ukA <- aggregate(tv ~ b, transform(uk, b=b5(election_year)), mean); names(ukA)[2]<-"val"; ukA$grp<-"UK"
wm  <- transform(rbind(data.frame(y=can$year,v=can$volatility), data.frame(y=aus$year,v=aus$volatility)), b=b5(y))
wm  <- wm[!is.na(wm$v), ]
wmA <- aggregate(v ~ b, wm, mean); names(wmA)[2]<-"val"; wmA$grp<-"Westminster"
idx <- function(d){ d<-d[order(d$b),]; d$ix <- 100*d$val/mean(d$val[d$b<1970]); d }
pcd <- rbind(idx(euA), idx(ukA), idx(wmA))
pcd$grp <- factor(pcd$grp, levels=c("UK","Europe","Westminster"))
end <- function(g){ z<-pcd[pcd$grp==g,]; z$ix[which.max(z$b)] }
xend <- max(pcd$b)
cat(sprintf("Panel C index endpoints (1950s-60s=100): UK %.0f, Europe %.0f, Westminster %.0f\n",
            end("UK"), end("Europe"), end("Westminster")))
pC <- ggplot(pcd, aes(b, ix, group=grp)) +
  geom_hline(yintercept=100, colour="grey80", linetype="dashed", linewidth=0.4) +
  geom_line(aes(colour=grp, linewidth=grp)) + geom_point(aes(colour=grp), size=1.1) +
  scale_colour_manual(values=c("black","grey40","grey62")) + scale_linewidth_manual(values=c(1.3,0.8,0.8)) +
  annotate("text", x=1951, y=118, label="1950s–60s average = 100", colour="grey55", size=2.5, hjust=0) +
  annotate("text", x=xend+1.2, y=end("UK"),          label="UK", fontface="bold", colour="black", size=3.0, hjust=0) +
  annotate("text", x=xend+1.2, y=end("Europe"),      label="Europe (all 20)", colour="grey40", size=2.7, hjust=0) +
  annotate("text", x=xend+1.2, y=end("Westminster"), label="Westminster peers\n(Canada, Australia)", colour="grey55", size=2.6, hjust=0, vjust=0.7, lineheight=0.85) +
  scale_x_continuous(breaks=seq(1950,2020,10), expand=expansion(add=c(0.5,17))) +
  scale_y_continuous(expand=expansion(mult=c(.05,.10))) +
  labs(tag="C", subtitle="Average trajectories, indexed to each group's 1950s–60s mean (=100)",
       x=NULL, y="Volatility index (1950s–60s = 100)") + house

TITLE <- "Comparative electoral volatility, 1950–2025"
SUB   <- "Not the most volatile face in the room — just the one that changed its story fastest."
# 17 Aug, PJ: "some of the titles are too small typface". Title size was a raw pt value while
# canvases run 6.5-10 in, so the SAME pt looked large on a narrow figure and small on a wide
# one - a 68% spread in apparent size. Titles are now set at ~1.75 pt per inch of canvas
# (this figure is 8.6 in wide, so 15 pt), which is the ratio the narrow figures already had.
THM   <- theme(plot.title=element_text(face="bold", size=15),
      plot.subtitle=element_text(face="italic", colour="grey30", size=10),
      plot.caption=element_text(size=6.8, colour="grey40", hjust=0, lineheight=1.2),
      plot.margin=margin(10,14,10,14))
cap2 <- paste0(
  "Pedersen total volatility; raw election points joined by straight lines. Panel A: four representative democracies (Italy, Germany, Netherlands, Switzerland) from\n",
  "Emanuele's 20-country dataset — one method, levels & trends comparable. Panel B: the UK 4-category series (pre-1979 from House of Commons Library GE shares) vs Canada &\n",
  "Australia, each country's main parties + Other (trends, not levels). Source: Emanuele, V. (2015), Dataset of Electoral Volatility... Western Europe (1945–2015), Italian Center\n",
  "for Electoral Studies, DOI 10.7802/1112, + 2015–25 update. UK 1983 corrected from Emanuele's 3.1 (apparent data-entry error; SDP–Alliance surge ≈ 11.8). Japan omitted.")
cap3 <- paste0(
  "Pedersen volatility, raw election points joined by straight lines. The UK is on TWO rulers — Emanuele TOTAL volatility in Panels A & C, the book's 4-CATEGORY Pedersen in\n",
  "Panel B (they track closely). Panel A: four representative democracies (Italy, Germany, Netherlands, Switzerland). Panel B: each country's main parties + Other (UK & Canada\n",
  "three, Australia two; trends, not levels). Panel C: UK, all 20 European democracies, and the Westminster peers (Canada, Australia), indexed to each group's 1950s–60s mean = 100.\n",
  "Source: Emanuele, V. (2015), Dataset of Electoral Volatility and its internal components in Western Europe (1945–2015), Rome: Italian Center for Electoral Studies, DOI 10.7802/1112\n",
  "(20 countries, 347 elections), with the author's 2015–25 update. UK 1983 corrected from Emanuele's 3.1 — an apparent data-entry error (SDP–Alliance surge ≈ 11.8). Japan omitted (1994 reform).")

# Provenance/method text (cap2/cap3) moved OFF the figure to the printed footnote (24 Jul edit).
# Title + panel subtitles (A/B/C) + series labels retained as legibility labels.
fig2 <- (pA / pB) + plot_layout(heights=c(1,1)) +
  plot_annotation(title=TITLE, theme=THM)
ggsave(file.path(FIG, "fig_volatility_two_pane.png"), fig2, width=8.6, height=8.8, dpi=200)

fig3 <- (pA / pB / pC) + plot_layout(heights=c(1,1,1)) +
  plot_annotation(title="Figure 2.7: Comparative electoral volatility, 1950–2025",
                  theme=THM)
ggsave(file.path(BASE, "allparty_review/figures/fig_2_7_comparative_volatility.png"), fig3, width=8.6, height=11.6, dpi=200)
ggsave(file.path(FIG, "fig_volatility_comparative.png"), fig3, width=8.6, height=11.6, dpi=200)  # alias
cat("DONE -> fig_2_7_comparative_volatility.png (Fig 2.8) + fig_volatility_two_pane.png (alt)\n")
