# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/build_fig_3_4_ministerial_departures.R
# build_fig_3_4_ministerial_departures.R
#
# Figure 3.4 — ministerial departure rate while government continued,
# 1979-2025. RENUMBERED 12 Sep 2026 from Figure 3.5 to 3.4 (values-evidence
# figures moved ahead of the professionalisation composite — see chapter-order
# discussion). PROMOTED to the (then) Figure 3.5 slot 8 Sep 2026 — PJ: "good work, so
# label the figure, get rid of subtiotle and create the footnote notes."
# Previously exploratory only (44_ministerial_departures_figure.R).
#
# CONSTRUCT: two lines, both descriptive (see circularity note below) -
# RESHUFFLES = ministers who left government the same day as 5+ others (an
# administratively-clustered move, government continuing - excludes reshuffle
# lateral moves and mechanical government-ended exits); STANDALONE = the
# narrower subset with no same-day clustering, government continuing.
# Plotted as a RATE per 100 active ministers, not raw counts - PJ asked
# directly whether the raw-count rise was just tracking a bigger government;
# checked and it is not (see rate note below).
#
# ⚠ RELABELLED 10 Sep 2026 - originally this panel showed TOTAL (reshuffles +
# standalone) vs STANDALONE overlaid, which reads visually as if the grey gap
# between the two bars were its own series. PJ noticed an apparent "downtick"
# in standalone around 2015 that a formal split (t-test, pre/post-2015) showed
# was NOT there - standalone actually rose significantly (p=0.012); the
# visual impression was an artefact of the overlay. PJ's fix: keep the exact
# same line-graph/overlay style, but swap the first series from TOTAL to its
# other real component, RESHUFFLES (reshuffle-cluster, threshold 5), so both
# plotted quantities are labelled, mutually exclusive, real categories -
# "reshuffles" not "forced departures" since the classification is purely
# about same-day clustering, not a determination that anyone was pushed out.
# TOTAL remains in the processed data/footnote for reference, just no longer
# plotted as its own line.
#
# Full construction, bug fixes, and the circularity resolution with Ch2's
# exec_instab are documented in 43_ministerial_departures_reshuffle_split.R's
# header - this script only builds the figure from its output.
#
# House style: same theme file as fig_3_1-3_4, greyscale, sources off the
# figure. FIG34_FOOTNOTE_NOTES.md generated below (computed, not typed).
#
# OUTPUT: figures/fig_3_4_ministerial_departures.png
#         FIG34_FOOTNOTE_NOTES.md

suppressMessages({library(dplyr); library(readr); library(ggplot2); library(tidyr); library(patchwork)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
source(file.path(WKBD_ROOT, "data_workspace_2026-07", "figure_house_theme.R"))

d <- read_csv(file.path(PROJECT, "data/processed/ministerial_departures_annual_1979_2025.csv"),
              show_col_types = FALSE) |>
  arrange(year) |>
  mutate(reshuffle_rate_pct = total_rate_pct - standalone_rate_pct)

scandal <- read_csv(file.path(PROJECT, "data/processed/scandal_resignations_annual_1979_2025.csv"),
                     show_col_types = FALSE)
n_scandal_total <- sum(scandal$n_scandal)
n_scandal_pre2008 <- sum(scandal$n_scandal[scandal$year <= 2007])
n_scandal_post2008 <- sum(scandal$n_scandal[scandal$year >= 2008])
d <- d |> left_join(scandal |> select(year, scandal_rate_pct), by = "year")

scandal_events <- read_csv(file.path(PROJECT, "data/raw/scandal_departures_event_list.csv"),
                            show_col_types = FALSE) |>
  arrange(date)

periods <- c(1979, 1989, 1998, 2010, 2020, 2026)
plabels <- c("1979-88", "1989-97", "1998-2009", "2010-19", "2020-25")
d <- d |> mutate(period = cut(year, breaks = periods, labels = plabels, right = FALSE))

period_means <- d |>
  group_by(period) |>
  summarise(reshuffle_rate_mean = mean(reshuffle_rate_pct), standalone_rate_mean = mean(standalone_rate_pct),
            scandal_rate_mean = mean(scandal_rate_pct),
            total_rate_mean = mean(total_rate_pct), year_mid = mean(year), .groups = "drop")

# ============================================================
# FIGURE — house style: ONE figure-level title via plot_annotation, each
# panel gets labs(tag=) for its letter + a short factual subtitle (italic
# grey30 per house), NOT title text - matches the professionalisation figure's working pattern
# exactly (see figure_house_theme.R's own rule: "PANEL LETTERS USE
# labs(tag = 'A'), NOT an 'A. ' prefix on the subtitle. ... One mechanism
# only, and it is the tag.").
# ⚠ RESTRUCTURED 10 Sep 2026, PJ: "the title with Ministerial Departures, no
# rate. Also get rid of the Dowding coding in brackets in panel C. We need
# three consistently labeled panels with their own paired down title, so
# panel A, B etc" - this also FIXED an existing house-style violation (this
# script had been putting "Figure 3.5: ..." text directly in Panel A's own
# ggplot title, and "Panel C: ..." text in Panel C's title, instead of using
# tag+subtitle like every other multi-panel Ch3 figure).
# ============================================================
CANVAS_W <- house_width_in()

p1 <- ggplot(d, aes(x = year)) +
  geom_col(aes(y = reshuffle_rate_pct), fill = "grey75", width = 0.8) +
  geom_col(aes(y = standalone_rate_pct), fill = "grey15", width = 0.8) +
  scale_x_continuous(limits = c(1978, 2026), breaks = seq(1980, 2025, 5)) +
  labs(tag = "A", subtitle = "Annual departure rate", x = NULL, y = "Departures per 100 ministers") +
  house_print(CANVAS_W)

trend_long <- period_means |>
  select(period, year_mid, reshuffle_rate_mean, standalone_rate_mean) |>
  pivot_longer(c(reshuffle_rate_mean, standalone_rate_mean),
               names_to = "series", values_to = "mean_rate") |>
  mutate(series = recode(series, reshuffle_rate_mean = "Reshuffles",
                          standalone_rate_mean = "Standalone"))

# Anchor point at 1979 - PJ, 10 Sep: extend the line back to 1979 with zeros
# rather than trimming the axis. Unlike every other point on this line (a
# period mean), this one is the REAL annual value for 1979 specifically
# (n_total_departures = 0 that year, so both series are genuinely 0, not an
# average standing in for 0) - included because it's true, not to pad the
# chart. Flagged in the footnote so the annual-vs-period-mean seam is visible.
anchor_1979 <- tibble(period = factor(NA, levels = levels(trend_long$period)),
                       year_mid = 1979, series = c("Reshuffles", "Standalone"), mean_rate = 0)
trend_long <- bind_rows(anchor_1979, trend_long)

p2 <- ggplot(trend_long, aes(x = year_mid, y = mean_rate, linetype = series)) +
  geom_line(colour = "black", linewidth = 0.8) +
  geom_point(colour = "black", size = 1.2) +
  scale_linetype_manual(values = c("Reshuffles" = "solid", "Standalone" = "dashed")) +
  scale_x_continuous(limits = c(1978, 2026), breaks = seq(1980, 2025, 5)) +
  labs(tag = "B", subtitle = "Period means", x = NULL, y = "Mean rate/year (%)", linetype = NULL) +
  house_print(CANVAS_W) +
  theme(legend.position = "bottom")

# ============================================================
# PANEL C - Financial scandal, own scale, 10 Sep 2026
# PJ, having seen the figure with scandal squeezed onto the shared Panel B
# scale: "it needs a panel C as the scale destroys it." Financial scandal
# (12 events/47 years, annual rate 0-1.8%) is ~10x smaller than Standalone and
# ~20x smaller than Reshuffles at their peaks - unreadable sharing an axis
# with either. Plotted here as ANNUAL bars (not period means, unlike Panel B)
# because these are rare, punctate events - averaging into 5 period buckets
# would smear the individual spike-years (1994, 1998, 2009, etc.) back into
# near-invisibility even on a rescaled axis. Own y-axis, autoscaled to this
# series' own range so the real pattern (clustered mid-1990s/2000s/2009, a
# gap through the 2010s, resuming 2023/2025) is actually visible.
# ============================================================
p3 <- ggplot(d, aes(x = year, y = scandal_rate_pct)) +
  geom_col(fill = "grey15", width = 0.8) +
  scale_x_continuous(limits = c(1978, 2026), breaks = seq(1980, 2025, 5)) +
  labs(tag = "C", subtitle = "Financial scandal", x = NULL, y = "Departures per\n100 ministers") +
  house_print(CANVAS_W)

fig <- (p1 / p2 / p3) +
  patchwork::plot_layout(heights = c(1.2, 1, 0.7)) +
  plot_annotation(
    title = "Figure 3.4: Ministerial Departures, 1979-2025",
    theme = theme(plot.title = element_text(face = "bold", size = pt_for(PRINTED$title, CANVAS_W)),
                  plot.margin = margin(12, 18, 12, 18))
  )
OUT <- file.path(PROJECT, "figures/fig_3_4_ministerial_departures.png")
ggsave(OUT, fig, width = CANVAS_W, height = CANVAS_W * 1.3, dpi = HOUSE_DPI, bg = "white")
cat("Figure saved:", OUT, "\n")

# ============================================================
# FOOTNOTE NOTES — generated so numbers cannot drift from the figure
# ============================================================
notes <- c(
"# Figure 3.4 - footnote notes",
"",
"⚠ GENERATED by build_fig_3_4_ministerial_departures.R. Every number below is computed from",
"data/processed/ministerial_departures_annual_1979_2025.csv at build time - nothing here is",
"hand-typed.",
"",
sprintf("Built %s. N = %d years, %d-%d, zero gaps.", Sys.Date(), nrow(d), min(d$year), max(d$year)),
"",
"## PROMOTED to Figure 3.5, 8 Sep 2026",
"PJ: \"good work, so label the figure, get rid of subtiotle and create the footnote notes.\"",
"Previously exploratory only (44_ministerial_departures_figure.R).",
"",
"## Source and construct",
"Institute for Government Ministers Database (CC-BY-4.0, since 1979),",
"data/raw/ifg_ministers/appointment.csv (already in the project, pulled 28 Aug 2026). Fully",
"scripted classification (no hand-coding), built in 43_ministerial_departures_reshuffle_split.R:",
"- Excludes LATERAL MOVES: same person reappointed to a different post within 14 days (reshuffle",
"  promotions/demotions/sideways moves) - these are not departures from government at all.",
"- Excludes GOVERNMENT-ENDED exits: within +-3 days of a verified true handover date (general",
"  election or PM change) - mechanical turnover, not an individual or political-class choice.",
"- The remainder splits into RESHUFFLES (5+ other appointments end the same day - an",
"  administratively coordinated move even without a PM change) vs STANDALONE (a lone departure,",
"  government continuing) - robustness checked at 3/5/10-same-day thresholds, all saved as",
"  separate columns; 5 is the headline threshold used here.",
"- TOTAL = departures while government continued (reshuffles + standalone) - kept in the",
"  processed data and below for reference, no longer plotted as its own line (see relabelling",
"  note).",
"",
"## ⚠ RELABELLED 10 Sep 2026 - was TOTAL vs STANDALONE, now RESHUFFLES vs STANDALONE",
"Original panel overlaid TOTAL (reshuffles + standalone) against STANDALONE, which visually reads",
"as if the gap between the two bars were a labelled series in its own right. PJ spotted an",
"apparent downtick in standalone around 2015; a formal pre/post-2015 split (Welch t-test) showed",
"standalone actually ROSE significantly (3.4% -> 8.1%, t=3.01, p=0.012) and its SHARE of total",
"departures rose too (30.5% -> 40.6%, chi-sq p=0.004) - the visual impression was an overlay",
"artefact, not a real pattern. Fix, PJ's call: keep the identical line-graph/overlay style, but",
"plot RESHUFFLES (the other real, mutually-exclusive component) instead of TOTAL, so both series",
"are labelled, real categories rather than one nesting the other. Named 'Reshuffles', not 'forced",
"departures' - the classification is purely same-day clustering (5+), not a determination that",
"anyone was pushed out (see cause-coding caveat below).",
"",
"## Why a RATE, not a raw count",
"PJ asked directly, 8 Sep: is the raw-count rise just tracking a bigger government over time?",
"Checked: the active-minister headcount (1 July snapshot each year) only grew ~33% across the",
"full span (108 to 144), while raw departures grew roughly 3x - so this figure shows the RATE per",
"100 active ministers, which still rises after controlling for headcount growth (see period means",
"below). That is the honest, stronger version of the claim.",
"",
"## Period means (rate per 100 active ministers/year)",
apply(period_means, 1, function(r) sprintf("- %s: reshuffles %.1f%%  standalone %.1f%%  (total %.1f%%)",
                                            r["period"], as.numeric(r["reshuffle_rate_mean"]),
                                            as.numeric(r["standalone_rate_mean"]),
                                            as.numeric(r["total_rate_mean"]))),
sprintf("- Reshuffles rate: %.1fx from 1979-88 to 2020-25 (%.1f%% -> %.1f%%)",
        period_means$reshuffle_rate_mean[5]/period_means$reshuffle_rate_mean[1],
        period_means$reshuffle_rate_mean[1], period_means$reshuffle_rate_mean[5]),
sprintf("- Standalone rate: %.1fx from 1979-88 to 2020-25 (%.1f%% -> %.1f%%)",
        period_means$standalone_rate_mean[5]/period_means$standalone_rate_mean[1],
        period_means$standalone_rate_mean[1], period_means$standalone_rate_mean[5]),
"",
"## ⚠⚠ THIRD LINE ADDED, 10 Sep 2026 - Financial scandal (Dowding coding)",
"PJ: \"can we pull out departures from scandal as per dowding\" -> \"create a third line in the",
"figure of resignations from scandal\" -> \"so you build the dataset\" -> \"yes do dilegency no model",
"creations.\" Source: Berlinski, Dewan & Dowding (2012) Accounting for Ministers, Ch.6",
"(literature/performance_measures_and_forced_exits.pdf) - their own coded category, not a re-",
"derivation. Built in 46_scandal_resignations_annual.R from",
"data/raw/scandal_departures_event_list.csv (every row individually sourced, see that file's",
"source_note column).",
sprintf("- Total events, 1979-2025: %d (%d from BDD's 1979-2007 list, %d from this session's",
        n_scandal_total, n_scandal_pre2008, n_scandal_post2008),
"  2008-2025 research, in two passes - see below).",
"- 1979-2007 (6 events - Tim Smith Oct 1994, Neil Hamilton Dec 1994, Peter Mandelson & Geoffrey",
"  Robinson Dec 1998, David Blunkett Oct 2005, Lord Sainsbury Nov 2006): taken VERBATIM from BDD's",
"  own text, which they built via a systematic method (cross-referencing every minister's name",
"  against 'Resign*' in The Times archive, 1996-2007, plus secondary sources for earlier years) -",
"  an audited census within their own category definition, not this project's own coding.",
"- 2008-2025, PASS 1 (opportunistic, 10 Sep): Peter Hain Jan 2008, David Laws May 2010, Nadhim",
"  Zahawi Jan 2023 - started from well-known scandals and verified each against real news sources",
"  (every date from a live web search, none from model memory, per PJ's 'no model creations'",
"  instruction), but not a systematic sweep.",
"- 2008-2025, PASS 2 (Times-style sweep, 10 Sep, PJ: 'do the sweep'): approximated a systematic",
"  search using Wikipedia's per-government 'List of departures from the X ministry' pages (Brown,",
"  Cameron-Clegg, second Cameron, first/second May, first/second Johnson, Truss, Sunak, Starmer) -",
"  the closest available substitute for BDD's own Times-archive method, since The Times archive",
"  itself is paywalled. Found TWO genuine misses from pass 1, both added:",
"  - Shahid Malik, 15 May 2009 (Justice minister, forced out over his own second-home expenses",
"    claim - reported as 'the first government member forced out by the expenses scandal'; later",
"    cleared by the inquiry, but the departure itself is what BDD's own method counts, same as",
"    their treatment of Mellor/Fairbairn regardless of eventual exoneration).",
"  - Angela Rayner, 5 Sep 2025 (Deputy PM, resigned after the independent ethics adviser found she",
"    underpaid GBP40,000 of stamp duty on a GBP800,000 flat - a breach of the ministerial code).",
"    This is a high-profile case pass 1 missed, itself evidence the sweep was worth doing.",
"- Two BORDERLINE cases checked and deliberately NOT included, pending PJ's own judgement call:",
"  - Liam Fox (14 Oct 2011, Adam Werritty conflict-of-interest affair) - resembles BDD's own",
"    Maudling/Brayley financial-scandal exemplars (undisclosed business-adjacent conflict of",
"    interest) about as much as their personal-error examples.",
"  - Tulip Siddiq (14 Jan 2025, Economic Secretary to the Treasury) - resigned over reputational",
"    risk from her family's alleged financial impropriety in Bangladesh (a GBP3.9bn embezzlement",
"    probe implicating her aunt, the deposed Bangladeshi PM), but the UK ethics adviser explicitly",
"    found she had NOT breached the ministerial code herself - a weaker case than Rayner's since no",
"    personal wrongdoing was established, closer to 'other controversy' by BDD's own scheme.",
"- PASS 3 (10 Sep, PJ: 'search outside wiki on government pages or an open access media record'):",
"  cross-checked against the IfG's own explainer page and open BBC/AP/Al Jazeera-style news search",
"  (not just Wikipedia). Surfaced THREE more real financial-impropriety cases from the same May-June",
"  2009 expenses crisis:",
"  - Hazel Blears (unpaid capital gains tax on a second-home sale) and Tony McNulty (parents living",
"    in a taxpayer-funded house) - BOTH EXCLUDED on a PRINCIPLED basis, not a judgement call: both",
"    left government on 5 June 2009, which this project's own IfG data confirms was a genuine",
"    reshuffle day (25 appointment-endings that day, five times the 5+ reshuffle-cluster threshold",
"    used throughout this figure) - Brown's post-European-elections reshuffle. BDD's own definition",
"    of 'forced exit' explicitly excludes departures that are part of a PM's planned reshuffle,",
"    regardless of what scandal made the minister vulnerable to being dropped.",
"  - Kitty Ussher (Exchequer Secretary to the Treasury, resigned 17 June 2009, hours before a story",
"    broke on her temporarily redesignating her home as a 'second home' to avoid ~GBP17,000 capital",
"    gains tax) - INCLUDED: checked against IfG data, only 2 appointment-endings on 17 June (not a",
"    reshuffle day, 12 days clear of the 5 June cluster) - genuinely standalone, same basis as",
"    Malik. She had been in the post only 8 days, appointed in the same 9 June reshuffle that",
"    replaced Blears/McNulty - so the post churned twice in one month, but her OWN exit was an",
"    isolated event, not part of that churn.",
"- ⚠⚠ STRUCTURAL LIMITATION, PJ 10 Sep: 'these reshuffles make it muddy as they may have seen it as",
"  time to go, disgraced' - a PM can neutralise a scandal by simply waiting for the next reshuffle",
"  to quietly drop the minister, which makes the departure look administratively routine in this",
"  data even though the underlying cause was disgrace. This is NOT a flaw specific to this",
"  project's coding - it is a structural blind spot in the 'forced exit vs reshuffle' concept",
"  itself, one BDD's own method inherits too (any PM who used a reshuffle to launder a scandal-",
"  driven removal would be invisible to their coding as much as to ours). No principled fix exists",
"  without insider knowledge of the PM's actual motive for each reshuffle-day drop, so this is left",
"  as a documented caveat rather than an attempted correction: the FINANCIAL SCANDAL line should be",
"  read as 'scandals visible enough to force an UNSCHEDULED individual departure,' a real but",
"  narrower thing than 'all departures where scandal was a contributing cause.'",
"- ✅ STANDING RULE, PJ 10 Sep 'also keep to dowding practice': any future addition to this line",
"  applies the SAME test used for Malik/Rayner/Blears/McNulty here - same-day-endings count against",
"  the project's own 5+ reshuffle-cluster threshold decides in/out, mirroring BDD's own 'forced",
"  exit excludes reshuffle' definition exactly, not a new ad hoc criterion invented per case.",
"- ⚠ Even after three passes, this remains a best-effort systematic search of the AVAILABLE public",
"  record (Wikipedia + IfG + open news search), not literal access to The Times archive BDD used",
"  (paywalled) - a genuinely obscure case that never reached any summary source could still be",
"  missing. Confidence is much higher than pass 1 alone, not absolute.",
"- ✅ SCALE FIX, 10 Sep, PJ: 'it needs a panel C as the scale destroys it.' Financial scandal",
sprintf("  (%d events/47 years, annual rate 0-1.8%%) is ~10x smaller than Standalone and ~20x",
        n_scandal_total),
"  smaller than Reshuffles at their peaks - unreadable sharing an axis with either, and unreadable",
"  even on its OWN axis as a period-mean line (5 buckets would smear individual spike-years back",
"  into near-invisibility). Moved OFF Panel B entirely and given its own PANEL C: annual bars (not",
"  period means), own y-axis, autoscaled to the series' own range - the real pattern (clustered",
"  mid-1990s/2000s/2009, a gap through the 2010s, resuming 2023/2025) is now actually visible.",
"  Panel B is back to just Reshuffles vs Standalone, its original two-series design.",
"",
"## ⚠ Panel C break-point test, 10 Sep 2026 (47_scandal_break_test.R)",
"PJ: \"can you do a breakpoint and statistical test for panel C\" - ran the SAME mean-shift Chow",
"(df1=1) + permutation test (10,000 draws) already used for Reshuffles/Standalone in",
"45_ministerial_departures_break_test.R, reused verbatim for a like-for-like method, not a new ad",
"hoc test.",
"- Peak candidate break year: 1993 (F=4.57), permutation p=0.235 - NOT significant at any",
"  conventional threshold.",
"- Mean rate before 1993: 0.000% (15 years, zero events) vs 0.288% from 1993 (32 years) - a real",
"  difference in the raw numbers, but not one the formal test can distinguish from chance given how",
"  few and clustered the 12 events are.",
"- ⚠⚠ CAVEAT, flagged BEFORE running the test, not after seeing a null result: financial scandal is",
"  a rare, zero-inflated count series (12 events/47 years, 38 years at exactly zero) - a much",
"  rougher fit for this method than the smoother Reshuffles/Standalone rates it was built for. The",
"  '1993' peak is an artefact of the search finding the latest point before the first real cluster",
"  (Smith/Hamilton, 1994), not evidence of a structural shift in scandal risk around that year.",
"- Read this as: NO DETECTABLE SINGLE-YEAR BREAK in financial scandal - the visible clustering in",
"  Panel C (mid-1990s, 1998, 2005-2009, then a decade-plus gap before 2023/2025) is a real pattern",
"  in the data but does not rise to a statistically identifiable structural break, unlike",
"  Reshuffles/Standalone which this same method WAS able to test meaningfully.",
"",
"## ⚠ Panel C rare-events test, 10 Sep 2026 (48_scandal_rare_event_test.R)",
"PJ: \"on the break could do a rare events test\" - ran a Poisson change-point/likelihood-ratio test",
"(the standard tool for a sparse COUNT series, as flagged as the right follow-up in the break-test",
"note above) instead of forcing the continuous-rate Chow method onto count data. Same sup-statistic",
"+ permutation architecture as the Chow test, different underlying model.",
"- Peak break year: 1993 (same as the Chow test), LR=7.83, permutation p=0.1323 (10,000 draws) -",
"  STILL not significant at any conventional threshold, but the count-appropriate method gives a",
"  p-value roughly HALF the Chow test's 0.235 - directionally consistent, correctly the stronger of",
"  the two tests for this kind of data, but the result doesn't flip to significant either way.",
"- Pooled rate before 1993: 0.000 events/100 minister-years (0 events, 15 years) vs 0.284 from 1993",
"  (12 events, 32 years) - same raw pattern as the Chow test's supplementary numbers, now expressed",
"  as a proper rate-per-exposure rather than a mean of already-computed rates.",
"- Bottom line, using BOTH the appropriate and the naive method: NO DETECTABLE SINGLE-YEAR BREAK in",
"  financial scandal, though the rare-events method leaves it somewhat less clear-cut than the Chow",
"  test alone suggested.",
"",
"## Panel C source citations, one per event (12 total)",
"Every event below is individually sourced - see data/raw/scandal_departures_event_list.csv for the",
"full reasoning behind each (why it's coded financial scandal, why it's in/out of the reshuffle",
"test). This list gives just the citation.",
apply(scandal_events, 1, function(r) sprintf("- %s (%s): %s", r["name"], r["date"], r["citation"])),
"",
"## ⚠⚠ CIRCULARITY CHECK - belongs in the chapter text",
"PJ, 8 Sep: \"another issue - resignations are part of the dependent chapter two variable now",
"they are here.\" Checked directly: Ch2's exec_instab (a canonical turbulence-composite/DV",
"component) is built from the SAME appointment.csv (WKBD_repo/scripts/03_cabinet_turnover.R),",
"counting RAW full-cabinet appointment-endings unfiltered for lateral moves. Of the 629 raw",
"cabinet-rank endings feeding exec_instab, only 59 (9.4%) would qualify as STANDALONE here - the",
"other 90.6% is exactly the routine reshuffle/mechanical churn this series filters out. PJ's own",
"resolution: \"agree - not using this for the statistical analysis, we have professionalism for",
"that.\" BOTH lines here are DESCRIPTIVE ONLY, part of Ch3's 'building the case' narrative (same",
"role as Figure 3.3) - never regressed or correlated against Ch2's turbulence index or",
"exec_instab. The professionalisation index (41e_professionalisation_pca.R) remains the one IV",
"doing statistical work in this chapter.",
"",
"## ⚠ No data at the start of the figure, 10 Sep 2026 - both real, not a gap",
"PJ asked why the figure looks empty near the start. Two separate reasons, neither a data gap:",
"- Top (bar) panel: 1979 is a genuine zero (n_total_departures=0 that year) - no minister left a",
"  continuing government in Thatcher's first year in office, before there had been time for one;",
"  1980 is likewise near-zero (0.9%, standalone only, no reshuffle-cluster). Left as-is, since it's",
"  a real value and the panel's x-axis matches the bottom panel's span for comparability.",
"- Bottom (line) panel: this plots PERIOD MEANS (5 points, one per period, 1979-88/1989-97/",
"  1998-2009/2010-19/2020-25), not annual values, each placed at its period's midpoint year - the",
"  first point sits at 1983.5, so a 1978-start axis left an empty margin before it with nothing to",
"  do with missing data.",
"- ✅ FIXED 10 Sep, PJ's call: rather than trimming the axis, added a real anchor point at 1979 -",
"  n_total_departures = 0 that year (Thatcher's first year in office, no time yet for a non-",
"  election departure), so both Reshuffles and Standalone are genuinely 0 in 1979, not an average",
"  standing in for 0. ⚠ Note this makes the line's FIRST point an actual annual value while every",
"  other point on it is a period mean (1979-88/89-97/98-2009/2010-19/2020-25) - a real methodological",
"  seam, flagged here rather than left silent, though the anchor value itself is not invented.",
"  Both panels' x-axes are back to matching (1978-2026).",
"",
"## ⚠ Method caveats",
"- Two bugs were caught and fixed during construction (full detail in",
"  43_ministerial_departures_reshuffle_split.R's header): a same-day post-to-post move boundary",
"  error, and an event.csv date-offset error that misclassified 2010, 2019 and 2022's real",
"  government-transition clusters as personal departures before being fixed. The July 2022 mass-",
"  resignation crisis (Sunak/Javid resigning, forcing Johnson's departure) correctly remains IN",
"  the series - that was real political-class behaviour, Johnson's government continued for",
"  another two months after it.",
"- ✅ UPDATED 10 Sep: STANDALONE itself still isn't fully cause-coded (cannot distinguish personal/",
"  ill-health or policy-disagreement departures from each other), but the FINANCIAL SCANDAL subset",
"  now is (Panel C, above) - built from Berlinski, Dewan & Dowding (2012)'s own coding for 1979-2007",
"  plus this session's sourced extension to 2025. Sexual scandal remains uncoded past the single",
"  named 1998 case (Ron Davies) - BDD's text doesn't name the other ~8 Conservative cases",
"  individually, and this project has not attempted its own sexual-scandal sweep.",
"- The reshuffle-cluster threshold (5+ same-day endings) is a judgement call, checked for",
"  robustness at 3/5/10 in the underlying data but not exhaustively tested against every",
"  alternative definition."
)
writeLines(unlist(notes), file.path(PROJECT, "FIG34_FOOTNOTE_NOTES.md"))
cat("notes  :", file.path(PROJECT, "FIG34_FOOTNOTE_NOTES.md"), "\n")
