# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/build_fig_3_6_three_series.R
# build_fig_3_6_three_series.R
#
# Figure 3.6 — the three series behind the path analysis: professionalisation,
# political trust, and turbulence, standardised and plotted together, 1979-
# 2025. PJ, 12 Sep: a precursor figure before the path analysis section, so
# the reader sees the raw series before Figure 3.7 (renumbered from 3.6, see
# build_fig_3_7_mediation.R) gives the actual test and numbers. Deliberately
# descriptive only — no correlation coefficients, stars, or fitted lines on
# this figure; that evidence stays on 3.7 and in the surrounding text.
#
# SPEC CHOICE: full-sample trust (N=47, includes BSA-observed + TrustGov/
# Ipsos-calibrated years) — PJ's explicit call, matching Figure 3.7's headline
# spec so the two figures describe the same sample.
#
# Professionalisation PC1 rebuilt identically to 41e/41f (career politicians,
# SPADs, staffing spend, 3-component PCA) rather than reading a saved output,
# since no such file exists — same pattern 41f already uses.
#
# House style: same theme file as fig_3_1-3_5, greyscale, sources off the
# figure.
#
# OUTPUT: figures/fig_3_6_three_series.png

suppressMessages({library(dplyr); library(readr); library(ggplot2); library(tidyr)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
source(file.path(WKBD_ROOT, "data_workspace_2026-07", "figure_house_theme.R"))

CANVAS_W <- house_width_in()
norm01 <- function(x) (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
zscore <- function(x) (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
YEARS  <- 1979:2025

# ============================================================
# 1. PROFESSIONALISATION PC1 — rebuilt identically to 41e/41f
# ============================================================
career_obs <- bind_rows(
  tribble(~year,~pct, 1979,3.0, 1983,4.5, 2010,14.0, 2015,17.0, 2019,21.0),
  tribble(~year,~pct, 1987,5.4, 1992,7.3, 1997,9.5, 2001,10.5, 2005,14.1)
) |> arrange(year)

career_annual <- tibble(year = YEARS) |>
  mutate(obs_yr     = sapply(year, function(y) max(career_obs$year[career_obs$year <= y])),
         career_pct = career_obs$pct[match(obs_yr, career_obs$year)])

spads <- read_csv(file.path(PROJECT, "data/raw/spads_DATA_ENTRY.csv"),
                  show_col_types = FALSE) |> filter(year <= 2025)
spads_annual <- tibble(year = YEARS,
  n_spads = approx(spads$year, spads$n_spads, xout = YEARS, rule = 2)$y)

ipsa  <- read_csv(file.path(PROJECT,"data/processed/ipsa_staffing_annual.csv"),
                  show_col_types=FALSE) |> select(cal_year, staffing_real=mean_staffing_real_2015)
pre10 <- read_csv(file.path(PROJECT,"data/processed/staffing_pre2010_calibrated_butler.csv"),
                  show_col_types=FALSE) |> filter(!is.na(real_2015_mean)) |>
  select(cal_year=year, staffing_real=real_2015_mean)
staffing_obs <- bind_rows(pre10, ipsa) |> arrange(cal_year) |> filter(cal_year <= 2025)
staffing_annual <- tibble(year = YEARS) |>
  mutate(obs_yr        = sapply(year, function(y) max(staffing_obs$cal_year[staffing_obs$cal_year <= y])),
         staffing_real = staffing_obs$staffing_real[match(obs_yr, staffing_obs$cal_year)])

d_prof <- tibble(year = YEARS) |>
  left_join(career_annual  |> select(year, career_pct),    by="year") |>
  left_join(spads_annual   |> select(year, n_spads),       by="year") |>
  left_join(staffing_annual|> select(year, staffing_real), by="year") |>
  mutate(career_norm   = norm01(career_pct),
         spads_norm    = norm01(n_spads),
         staffing_norm = norm01(staffing_real))

pca_res <- prcomp(d_prof |> select(career_norm, spads_norm, staffing_norm),
                   scale. = TRUE, center = TRUE)
d_prof  <- d_prof |> mutate(prof_pc1 = pca_res$x[, 1])

# ============================================================
# 2. TRUST — full sample (BSA-observed + calibrated years)
# ============================================================
trust <- read_csv(file.path(PROJECT, "data/processed/trust_extended_1979_2025.csv"),
                   show_col_types = FALSE) |> select(year, trust_pct)

# ============================================================
# 3. TURBULENCE — canonical composite
# ============================================================
turb <- read_csv(file.path(PROJECT, "../composite_canonical/canonical_pc1_1979_2025.csv"),
                  show_col_types = FALSE) |> select(year, turb_pc1 = PC1_index)

# ============================================================
# 4. MERGE, Z-SCORE, PLOT
# ============================================================
d <- tibble(year = YEARS) |>
  left_join(d_prof |> select(year, prof_pc1), by="year") |>
  left_join(trust,                            by="year") |>
  left_join(turb,                             by="year") |>
  mutate(Professionalisation = zscore(prof_pc1),
         `Political trust`   = zscore(trust_pct),
         Turbulence          = zscore(turb_pc1)) |>
  select(year, Professionalisation, `Political trust`, Turbulence) |>
  pivot_longer(-year, names_to = "series", values_to = "val_z")

d$series <- factor(d$series, levels = c("Professionalisation", "Political trust", "Turbulence"))

p <- ggplot(d, aes(x = year, y = val_z, linetype = series)) +
  geom_line(colour = "black", linewidth = 0.8) +
  scale_linetype_manual(values = c("Professionalisation" = "solid",
                                    "Political trust"     = "dashed",
                                    "Turbulence"           = "dotted")) +
  scale_x_continuous(limits = c(1978, 2026), breaks = seq(1980, 2025, 5)) +
  labs(
    title    = "Figure 3.6: Professionalisation, political trust,\nand turbulence, 1979-2025",
    subtitle = "Three series, standardised (mean 0, SD 1)",
    x = NULL, y = "Standardised score (SD)", linetype = NULL
  ) +
  house_print(CANVAS_W) +
  theme(legend.position = "bottom")

OUT <- file.path(PROJECT, "figures/fig_3_6_three_series.png")
ggsave(OUT, p, width = CANVAS_W, height = CANVAS_W * 0.62, dpi = HOUSE_DPI, bg = "white")
cat("Figure saved:", OUT, "\n")
