# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/composite_canonical/build_fig_2_16_turbulence_index.R
# build_fig_2_16_turbulence_index.R — Figure 2.18: the turbulence index, 1979-2024
#
# The chapter's payoff figure. v22 has NO index section and NO composite figure — it ends at
# U-turns (Fig 2.17) — so this is new, not a replacement. ⚠ PJ to confirm the number; 2.18 assumes
# it closes the chapter after the six dimensions have been introduced.
#
# ⛔ WHAT IS FITTED, AND WHY. PJ, 16 Aug: "go with the segmented bend as primary." The model
# selection run (nonlinear_modelling/NONLINEAR_MODEL_SELECTION.md) rejected BOTH a flat series and
# a linear trend decisively (delta-BIC 27.4 and 16.8). Break, spline and segmented fit equally well
# (delta-BIC 0.00 / 0.40 / 0.71) so the FORM is not identified; the segmented bend is primary
# because it is interpretable, it survives the pre-Covid window where the hard break does not, and
# it does not assert a discontinuity. ⛔ The alternative specifications are RELEGATED TO THE
# APPENDIX (PJ's instruction) and must NOT be drawn here — one fitted line only.
#
# ⭐ WHY A BAND AND NOT A LINE FOR THE TURNING POINT. PJ: "2013 is not needed and my prose indicates
# a range." The block bootstrap puts the knot's 90% CI at 2007-2017 (median 2013, modal year only
# 20.1% of draws). A vertical rule at 2013 would assert a precision the data does not have. The
# band IS the finding: a turn somewhere in the late 2000s / mid 2010s.
#
# ⭐ WHY PANEL B EXISTS. The single most important robustness fact about this index is that ALL SIX
# components shift the same way (+0.28 to +1.25 in mean z after 2013) — the index is not one series
# dragging the rest. Panel B carries the SAME band across all six so the reader can see each series
# sits lower to the left of it and higher to the right, without any statistic on the panel.
#
# ⭐ 17 Aug: pm_churn REPLACED by exec_instab (PC1 of PM + Great Officers + Cabinet departures),
# so Panel B's third small multiple is now 'Executive instability'. Ordered by loading throughout.
# ⛔ NO PERIOD-MEAN LINES on either panel. PJ, 16 Aug (on Fig 2.14): "don't add to the figure - mess
# it up". Same rule applies. The numbers live in the footnote notes.
# ⛔ NO stats, p-values or break dates on the panels — house style (figures inform, text concludes).
# ⛔ Sources go to the footnote, not the panel.

suppressPackageStartupMessages({library(ggplot2); library(dplyr); library(tidyr); library(patchwork)})

P  <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "../..")) else getwd()
})
WS <- file.path(P, "data_workspace_2026-07")
CC <- file.path(WS, "composite_canonical")

d <- read.csv(file.path(CC, "canonical_pc1_1979_2025.csv"), stringsAsFactors = FALSE)

# ---- CONTROL: the input must be the clean SEVEN, n = 45 --------------------
# ⭐ 17 Aug: `unexpected` (public opinion) added so all six theorised dimensions are represented.
# ⚠ 1981 has no unexpected-movements estimate, so the window 1979-2025 yields n = 46, not 47.
#   State the missing year; do not imply complete coverage.
# ⚠ 18 Aug: n is now 47 — 1981 is present, with its public-opinion component INTERPOLATED
#   (the Ipsos source has no 1981 observations at all). The point is drawn hollow, below.
stopifnot(nrow(d) == 47, min(d$year) == 1979, max(d$year) == 2025)

# ---- the BREAK fit (level + trend), re-derived here so the figure is self-contained ----
# ⭐ 18 Aug, PJ's decision: the figure now draws the model the CHAPTER REPORTS. It previously drew
#   the segmented bend while the text reported the break, so figure and claim described different
#   models. y = a + b1*t + shift*1{t>C} + b2*t*1{t>C}, break C chosen by min RSS over the
#   15%-trimmed interior — the same search the appendix and index_robustness/ use.
# ⚠ The bend is still computed below for the tripwire and the console line; it is no longer drawn.
int  <- function(n) { lo <- max(3, floor(0.15 * n)); lo:(n - lo) }
best <- NULL
for (C in d$year[int(nrow(d))]) {
  m <- lm(PC1_index ~ year + I(pmax(year - C, 0)), data = d)
  r <- sum(resid(m)^2)
  if (is.null(best) || r < best$r) best <- list(r = r, C = C, m = m)
}
co <- coef(best$m)

bestb <- NULL
for (C in d$year[int(nrow(d))]) {
  g <- as.numeric(d$year > C)
  m <- lm(PC1_index ~ year * g, data = d)
  r <- sum(resid(m)^2)
  if (is.null(bestb) || r < bestb$r) bestb <- list(r = r, C = C, m = m)
}
d$fit <- fitted(bestb$m)
# ⛔ The two segments must NOT be joined across the break — that would draw a continuous line and
#   undo the point of the model. Split the series so ggplot lifts the pen at the break.
d$seg <- ifelse(d$year > bestb$C, "post", "pre")
stopifnot(bestb$C == 2015)
cat(sprintf("break %d | RSS %.2f (bend at %d: RSS %.2f)\n", bestb$C, bestb$r, best$C, best$r))

# ⛔ TRIPWIRE — IT FIRED TWICE ON 17 Aug 2026, and was right both times.
#    (a) adding `unexpected` as the seventh component moved the knot 2013 -> 2012
#    (b) extending the window to 2025 moved it 2012 -> 2011
#    (c) dropping rebellions, 18 Aug, moved it back 2011 -> 2012
#    Each time the figure and the notes were rewritten to match; the assertion was never loosened.
#    ⚠ Note what this shows: the knot is NOT well identified. Three defensible specifications give
#    2011, 2012 and 2013. That is exactly why the figure draws a BAND and not a line, and the text
#    must say "the early 2010s", never a year.
# If the knot ever moves off 2012 the figure's band and the footnote notes are both
# stale. Fail rather than draw a fitted line the notes no longer describe.
stopifnot(best$C == 2012)   # unchanged by the interpolation
cat(sprintf("knot %d | slope before %+.4f/yr | slope after %+.4f/yr\n",
            best$C, co[2], co[2] + co[3]))

# ⛔ 18 Aug: the band used to be the KNOT bootstrap CI [2007, 2017], computed on a SUPERSEDED
#   specification. The figure was therefore drawing an interval for a quantity the chapter no
#   longer reports, from an index that no longer exists.
# ✅ It is now the Bai–Perron 90% confidence interval for the BREAK on the live specification —
#   the same interval quoted in the appendix and in index_robustness/R2. Recompute if the spec
#   moves; do not carry a stale interval forward.
CI <- c(2014, 2018)

# ---------------------------- house style ----------------------------------
base <- theme_minimal(base_size = 9) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey90", linewidth = 0.3),
        axis.title.y = element_text(size = 8))
ptitle <- function() theme(
  plot.subtitle = element_text(face = "italic", colour = "grey30", size = 9),
  plot.tag      = element_text(face = "bold", size = 11))
# ⛔ 17 Aug: the 2024.6 upper limit silently dropped the new 2025 point from ALL SIX component
#    panels (ggplot warns, it does not error). Extended with the window. Check this line whenever
#    the window moves — it is the second time clipping has bitten this chapter.
XS   <- scale_x_continuous(breaks = seq(1980, 2020, 10), limits = c(1978.4, 2025.6))
BAND <- annotate("rect", xmin = CI[1], xmax = CI[2], ymin = -Inf, ymax = Inf,
                 fill = "grey88", colour = NA)

# ------------------------------ Panel A ------------------------------------
pA <- ggplot(d, aes(year)) +
  BAND +
  geom_hline(yintercept = 0, colour = "grey75", linewidth = 0.3) +
  geom_line(aes(y = PC1_index), colour = "grey58", linewidth = 0.4) +
  geom_point(aes(y = PC1_index), colour = "grey45", size = 0.75) +
  geom_line(aes(y = fit, group = seg), colour = "grey10", linewidth = 0.85) +
  # ⛔ 19 Aug, PJ: "it needs a clearer key, and so the reader can see it applies to the whole
  #    figure". The in-panel label named the band for Panel A ONLY, leaving the six identical
  #    bands in Panel B unexplained unless the reader carried the label down. It is now a
  #    figure-level key in the caption, which is the only place that speaks for both panels.
  XS +
  # ⛔ Limits must contain the DATA (PC1 runs -2.120 to 3.342), not just the fitted line. An
  # earlier pass clipped the peak silently (twice: 16 Aug, and again after the 17 Aug component swap) — ggplot drops out-of-range points with only a
  # warning, so a too-tight limit deletes evidence from the panel.
  scale_y_continuous(breaks = seq(-2, 3, 1), limits = c(-2.40, 3.85), expand = c(0, 0)) +
  # ⛔ THE IMPUTED YEAR IS DRAWN HOLLOW so a reader can see it without reading the footnote.
  # 1981 has no Ipsos observations at all; its public-opinion component is interpolated from 1980
  # and 1982. Nothing rests on it (break year and CI are identical with it in, out, or imputed at
  # the mean) but it must not be presented as observed.
  geom_point(data = subset(d, year == 1981), aes(year, PC1_index),
             shape = 21, fill = "white", colour = "grey25", size = 2.1, stroke = 0.6) +
  # ⛔ NO TEXT NOTE ON THE FIGURE. PJ, 18 Aug: "don't write any text in the doc or add notes to
  #    figures." The imputed year is shown by the hollow point alone; it is explained in the
  #    footnote and the appendix, not on the panel.
  labs(tag = "A", subtitle = "The turbulence index", x = NULL, y = "Index (PC1)") +
  base + ptitle()

# ------------------------------ Panel B ------------------------------------
# Ordered by PC1 loading (strongest first), so the reader meets the components in the order
# they contribute. Fixed y across all six: they are z-scores and must be comparable.
# Ordered by PC1 loading on the SIX-component index (18 Aug, rebellions dropped):
#   elect_vol .479 | uturns .456 | dislocation .452 | unexpected .379 |
#   exec_instab .341 | dept_churn .313
lab <- c(elect_vol_z      = "Electoral volatility",
         uturns_z         = "U-turns",
         dislocation_z    = "Parliamentary dislocation",
         # ⛔ 18 Aug: the full name overran a one-third-width facet and printed clipped as
         #    "...in public attenti". Shortened; the full construct is named in the text.
         unexpected_z     = "Unexpected public attention",
         exec_instab_z    = "Executive instability",
         dept_churn_z     = "Machinery of government")

long <- d |>
  select(year, all_of(names(lab))) |>
  pivot_longer(-year, names_to = "k", values_to = "z") |>
  mutate(component = factor(lab[k], levels = unname(lab)))

pB <- ggplot(long, aes(year, z)) +
  BAND +
  geom_hline(yintercept = 0, colour = "grey75", linewidth = 0.3) +
  geom_line(colour = "grey20", linewidth = 0.4) +
  facet_wrap(~ component, ncol = 3) +
  XS +
  # Component z-scores run -1.786 to 4.174 — limits contain all six series (see Panel A note).
  scale_y_continuous(breaks = c(-2, 0, 2), limits = c(-2.2, 4.4), expand = c(0, 0)) +
  labs(tag = "B", subtitle = "The six components", x = NULL, y = "Standard deviations") +
  base + ptitle() +
  theme(strip.text = element_text(size = 7.6, face = "plain", hjust = 0,
                                  margin = margin(b = 2)),
        panel.spacing.x = unit(9, "pt"), panel.spacing.y = unit(7, "pt"),
        axis.text = element_text(size = 7))

# ------------------------------ THE FIGURE ---------------------------------
# ⛔ TWO PANELS. PJ, 17 Aug: "yes I want the two panel version." (A single-panel version was built
# and rejected.) Panel B stays in the CHAPTER because it carries the single most important
# robustness fact about the index — all six components shift the same way — and because the
# adjacent figures (2.12, 2.13, 2.14, 2.15) all carry a second panel.
# ⛔ "Rest in the appendix" therefore means the ALTERNATIVE SPECIFICATIONS (break, spline,
# quadratic, the horse race, the controls), NOT the components. One fitted line here, always.
fig <- (pA / pB) +
  plot_layout(heights = c(1, 1.25)) +
  plot_annotation(
    title = "Figure 2.16: The turbulence index and its components, 1979\u20132025",
    # ⛔ 19 Aug, PJ: "there is too much text for the bottom note. it can just give a key as
    #    the circle: interpolated". A KEY, not a note — two entries, no sentences, no statistics
    #    and no conclusion (house style). The band entry is here rather than on Panel A because
    #    the caption is the only element that speaks for both panels at once.
    # ⚠ "90 per cent" is the Bai–Perron asymptotic level for the interval actually drawn
    #    (2014–2018). The block bootstrap puts that band's coverage at 73.5%; that discrepancy
    #    belongs in the appendix, not in a key. Do not silently change the number here.
    caption = paste("Shaded area: 90 per cent confidence interval for the break.",
                    "Hollow circle: interpolated value."),
    theme = theme(plot.title = element_text(face = "bold", size = 11.5,
                                            margin = margin(b = 10)),
                  plot.caption = element_text(size = 7, colour = "grey35", hjust = 0,
                                              margin = margin(t = 8))))

dir.create(file.path(CC, "figures"), showWarnings = FALSE)
out <- file.path(CC, "figures/fig_2_16_turbulence_index_1979_2025.png")
ggsave(out, fig, width = 6.5, height = 6.7, dpi = 300, bg = "white")   # single-line key at the foot
cat("wrote", out, "\n")
