# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/ch3_pipeline_restored/scripts/build_fig_3_7_mediation.R
# build_fig_3_7_mediation.R
#
# Figure 3.7 — the mediation test result: professionalisation, political
# trust, and turbulence, with the actual path coefficients on it. PJ, 8 Sep:
# "now moving ont pthe mediation analusis to finish up chapter - can you do
# me a figure wiuth the numbers on it?" Redrawn in house greyscale style from
# the existing "talk" version (41i_mediation_test.R's ch3_mediation_talk.png,
# navy/grey/red, Manchester-slide colours) using the same box/arrow grammar
# as Figure 3.1's hypothesis schematic.
#
# SPEC CHOICE: full sample, PJ's explicit call when asked directly, 8 Sep —
# over BSA-observed-only (N=24). Rationale given: larger N, matches the rest
# of the chapter's headline series (the trust series' other figures already
# show both specs; this is the one place a single number is needed).
#
# ⚠⚠ QUADRATIC RESPEC, 10 Sep 2026 - c and c' are no longer single linear
# slopes. PJ asked whether the 2015 break/sign-flip found in
# 49_mediation_breakpoint_test.R was really just non-linearity in the
# Prof->Turbulence relationship - checked directly (41o_mediation_quadratic.R):
# a quadratic term alone (no discrete break) lifts R² substantially,
# matching 41n_profess_turb_gam_check.R's already-standing non-linearity
# finding. PJ: "rebuild with the quadratic spec as we did flag this earlier
# so feels like we are going backwards otherwise." Both c and c' are now
# reported as (linear coefficient, quadratic coefficient) pairs.
#
# ⚠⚠⚠ LAGGED RESPEC, 14 Sep 2026 - PJ caught that the model above was
# CONTEMPORANEOUS (all three series joined on the same year, no lag
# anywhere) - "should be lagged - please re do" - then specified the actual
# structure: "need to work out the structure of the lags -2 for prof and -1
# for trust". This is now a genuine SEQUENTIAL chain, not three same-year
# series glued together:
#
#     Professionalisation(t-2) --a--> Political Trust(t-1) --b--> Turbulence(t)
#                              \_____________ c / c' ______________/
#
# Professionalisation moves, trust has shifted 2 years later (path a), and
# trust's level exactly 1 year before turbulence is what predicts turbulence
# (path b) - so the mediator sits genuinely between treatment and outcome in
# time, not contemporaneous with both. c and c' (Prof->Turbulence, with/
# without trust) use the same 2-year gap as path a. N drops from 47 to 45
# (two years lost to the t-2 lag). Path a (Prof->Trust) stays linear - no
# non-linearity evidence exists for that leg specifically; c/c' stay
# quadratic per the 10 Sep respec above. Numbers pulled directly from
# 41p_mediation_quadratic_lagged.R's console output, not retyped from memory.
#
# House style: same theme file as fig_3_1-3_5, greyscale, sources off the
# figure. FIG37_FOOTNOTE_NOTES.md generated below.
#
# OUTPUT: figures/fig_3_7_mediation.png

suppressMessages({library(ggplot2)})

.ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), ".."))
  else getwd()
})
PROJECT   <- .ROOT
WKBD_ROOT <- normalizePath(file.path(PROJECT, "..", ".."))
source(file.path(WKBD_ROOT, "data_workspace_2026-07", "figure_house_theme.R"))

CANVAS_W <- house_width_in()
mm <- function(pt) mm_for(pt, CANVAS_W)

# ============================================================
# NUMBERS — sequential-lag spec, N=45, from 41p_mediation_quadratic_lagged.R
# (14 Sep 2026 rerun): Prof(t-2) -> Trust(t-1) -> Turbulence(t)
# ============================================================
a_coef  <- -1.12; a_star  <- " (n.s.)" # p=0.061, marginal
b_coef  <- 0.00;  b_star  <- " (n.s.)" # p=0.879, n.s.
# c and c' are QUADRATIC: (linear term, quadratic term), both significant
cp_lin  <- 0.48; cp_lin_star  <- "***" # p=0.000118
cp_quad <- 0.28; cp_quad_star <- "***" # p=0.000680
c_lin   <- 0.48; c_lin_star   <- "***" # p=5.06e-05
c_quad  <- 0.28; c_quad_star  <- "***" # p=3.37e-04
indirect_est <- -0.005; indirect_p <- 0.875
indirect_star <- " (n.s.)"  # p=0.875, n.s. - no CI shown, for consistency with the c'/c box below

box_w <- 3.0; box_h <- 1.4

# NOTE 11 Sep: full vertical layout rebalanced - PJ flagged the top box as
# "too high" (too much dead space above it, under-centred between the
# Indirect label and the bottom row) and the bottom annotation box as "too
# close to other bits" (the 3-line Direct(c') label's true height reached
# up to ~y=1.5, overlapping the bottom boxes' own bottom edge at y=1.3).
# Named y-positions below replace the old scattered hardcoded 6.0/8.4/0.75
# so the whole triangle can be re-spaced consistently in one place.
y_bot    <- 2.0   # Professionalisation / Turbulence boxes
y_top    <- 5.3   # Political Trust box - lowered from 6.0, closer to the
                   # true vertical midpoint between y_bot and y_indirect
y_indirect <- 7.6  # Indirect label - lowered from 8.4 to keep a steady gap
                     # above the (also-lowered) Trust box
y_direct   <- -0.35 # Direct(c') label - lowered from 0.75 so its 3-line
                     # height clears the bottom boxes' edge (y_bot - box_h/2
                     # = 1.3) with real daylight, not an overlap
y_ab       <- (y_bot + y_top) / 2  # a/b coefficient labels, exact midpoint

nodes <- data.frame(
  x     = c(1.5, 5.0, 8.5),
  y     = c(y_bot, y_top, y_bot),
  label = c("Professionalisation\nIndex (t-2)", "Political\nTrust (t-1)", "Turbulence\nIndex (t)"),
  fill  = c("#000000", "grey55", "grey25")
)

p <- ggplot() +
  # Direct path (solid, black), labelled c'
  annotate("segment", x = 1.5 + box_w / 2, y = y_bot, xend = 8.5 - box_w / 2, yend = y_bot,
           colour = "#000000", linewidth = 1.4,
           arrow = arrow(length = unit(0.3, "cm"), type = "closed")) +
  annotate("label", x = 5.0, y = y_direct,
           label = sprintf("Direct (c')\nLinear: %.2f%s\nQuadratic: %.2f%s",
                            cp_lin, cp_lin_star, cp_quad, cp_quad_star),
           colour = "#000000", fill = "white", label.size = 0.4, size = mm(8.5), fontface = "bold",
           lineheight = 1.1) +
  # Indirect path — Prof -> Trust (a), labelled
  # Endpoints inset slightly INTO each box (rather than sitting exactly on
  # the mathematical edge) so the dashed line visibly connects regardless
  # of where its dash pattern happens to start/end.
  annotate("segment", x = 1.5 + box_w / 2 - 0.12, y = y_bot + box_h / 2 - 0.12,
           xend = 5.0 - box_w / 2 + 0.12, yend = y_top - box_h / 2 + 0.12,
           colour = "grey55", linewidth = 0.9, linetype = "dashed",
           arrow = arrow(length = unit(0.22, "cm"), type = "closed")) +
  annotate("label", x = 2.35, y = y_ab, label = sprintf("a = %.2f%s", a_coef, a_star),
           colour = "grey20", fill = "white", label.size = 0.3, size = mm(8)) +
  # Indirect path — Trust -> Turbulence (b), labelled
  annotate("segment", x = 5.0 + box_w / 2 - 0.12, y = y_top - box_h / 2 + 0.12,
           xend = 8.5 - box_w / 2 + 0.12, yend = y_bot + box_h / 2 - 0.12,
           colour = "grey55", linewidth = 0.9, linetype = "dashed",
           arrow = arrow(length = unit(0.22, "cm"), type = "closed")) +
  annotate("label", x = 7.65, y = y_ab, label = sprintf("b = %.2f%s", b_coef, b_star),
           colour = "grey20", fill = "white", label.size = 0.3, size = mm(8)) +
  # Indirect box, top
  annotate("label", x = 5.0, y = y_indirect,
           label = sprintf("Indirect (a x b): %.3f%s", indirect_est, indirect_star),
           colour = "#000000", fill = "white", label.size = 0.4, size = mm(8), fontface = "bold") +
  # Node boxes
  geom_rect(data = nodes,
            aes(xmin = x - box_w / 2, xmax = x + box_w / 2, ymin = y - box_h / 2, ymax = y + box_h / 2),
            fill = nodes$fill, colour = "white", linewidth = 0.8) +
  geom_text(data = nodes, aes(x = x, y = y, label = label),
            colour = "white", fontface = "bold", size = mm(5.2), lineheight = 0.9) +
  coord_fixed(xlim = c(-1.0, 11.0), ylim = c(-1.6, 8.6), expand = FALSE) +
  labs(
    title    = paste0(
      "Figure 3.7: The relationship between professionalisation,\n",
      "political trust, and turbulence"
    )
  ) +
  theme_void(base_size = pt_for(PRINTED$axis_text, CANVAS_W)) +
  theme(
    plot.title  = element_text(face = "bold", size = pt_for(PRINTED$title, CANVAS_W), hjust = 0),
    plot.margin = margin(10, 10, 5, 10)
  )

OUT <- file.path(PROJECT, "figures/fig_3_7_mediation.png")
ggsave(OUT, p, width = CANVAS_W, height = CANVAS_W * 0.66, dpi = HOUSE_DPI, bg = "white")
cat("Figure saved:", OUT, "\n")

# ============================================================
# FOOTNOTE NOTES
# ============================================================
notes <- c(
"# Figure 3.7 - footnote notes",
"",
"## Construction",
"Baron & Kenny (1986) mediation test: does political trust carry professionalisation's effect on",
"turbulence? SEQUENTIAL LAG structure (respec'd 14 Sep 2026 - the model was contemporaneous",
"before, which PJ caught as wrong for a mediation claim): Professionalisation(t-2) -> Political",
"Trust(t-1) -> Turbulence(t), N=45 (1981-2025, two years lost to the t-2 lag). Professionalisation",
"= 3-component PCA (career politicians, SPADs, MP staffing spend). Turbulence = the canonical",
"6-component composite. Trust = BSA/TrustGov/Ipsos-blended series. Direct and total effects (c, c')",
"use a quadratic term on professionalisation (linear + quadratic coefficients both shown) - a",
"straight line fits this relationship poorly (R²=0.22 linear vs 0.43 with the quadratic term), so",
"both are reported rather than a single misleading slope. Path a (Prof->Trust) stays linear - no",
"non-linearity evidence exists for that leg specifically. Indirect effect (a x b) via trust",
"estimated with the Imai et al. (2010) mediation package, 5,000 simulations.",
"",
"## Reading the figure",
"- a, b: the two legs of the indirect path (Prof[t-2]->Trust[t-1]->Turbulence[t]).",
"- c' (linear/quadratic): the direct path, Prof(t-2)->Turbulence(t) controlling for trust(t-1).",
"- Indirect effect (a x b): not significant (p=0.88) - trust does not carry the effect.",
"- Stars: * p<0.05, ** p<0.01, *** p<0.001.",
"",
"## Exact p-values (figure shows stars only, for consistency across WKBD's figures)",
"- a (Prof[t-2] -> Trust[t-1]): p = 0.061 (marginal)",
"- b (Trust[t-1] -> Turbulence[t]): p = 0.879",
"- c' linear: p = 0.000118; c' quadratic: p = 0.000680",
"- c (total effect) linear: p = 0.0000506; c (total effect) quadratic: p = 0.000337",
"- Indirect effect (a x b), mediate() ACME: p = 0.875",
"",
"⚠ Numbers from 41p_mediation_quadratic_lagged.R's console output (14 Sep 2026); if that script",
"is rerun, re-check these figures before republishing. The prior contemporaneous spec's numbers",
"(41o_mediation_quadratic.R, 10 Sep 2026) are superseded, not deleted - see that script and",
"FIG37_ANALYSIS_LOG.md for the full spec-choice/robustness/break-test/lag history."
)
writeLines(unlist(notes), file.path(PROJECT, "FIG37_FOOTNOTE_NOTES.md"))
cat("notes  :", file.path(PROJECT, "FIG37_FOOTNOTE_NOTES.md"), "\n")
