# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/policy_failure/vdem_wgi/build_fig_2_14_external_validation.R
# ⭐ RENUMBERED 2.16 -> 2.15, 17 Aug 2026 (old Fig 2.3 dropped; everything after shifts
#   down one). Backup of the pre-renumber script: build_fig_2_14_external_validation.R.bak_17aug
# ⚠ NO Chow panel here — this is a validation figure, not a break test.

# build_fig_2_14_external_validation.R — Figure 2.16: the NAO delivery-failure series against an external measure
#
# ⚠ PJ, 15 Aug: moved from the appendix into the chapter. One panel, both series on a standardised
# scale, hard-boiled title, no comment on the figure.
#
# ⚠ WHICH NAO MEASURE, AND WHY IT MATTERS. This uses `est_count` from nao_final.csv — the COUNT
# measure on the sufficient-extract series, which is PJ's 10 Aug decision and exactly what Figure
# 2.14 plots. The proportion measure correlates more strongly with the external series (-0.674
# against -0.391), so using it HERE while Figure 2.15 uses the count would be choosing the
# flattering measure for the validation figure only. Consistency with 2.14 is the point.
#
# ⚠ THE WORLD BANK SERIES IS REVERSE CODED SO BOTH LINES POINT THE SAME WAY. PJ, 15 Aug: "let's put
# them on the same signed scale so the eye can see them trending together." Audit Office failure
# rising is deterioration; World Bank effectiveness rising is improvement, so the Bank's series is
# reverse coded and both now read "up = worse". ("Reverse coded", not "inverted" — PJ, 15 Aug: the
# standard term, and clearer to a reader who knows reverse-coded scale items.)
#
# ⚠ I ARGUED AGAINST THIS AND WAS OVERRULED, SO THE GUARD IS TRANSPARENCY. Two mirrored lines shown
# climbing together look like stronger agreement than r = -0.55 supports, and a reader who misses
# the flip will over-read it. The inversion is therefore stated in the SUBTITLE and carried in the
# series label on the panel — it must never be silent. If either is ever edited out, the figure
# becomes misleading rather than merely simplified.
#
# ⚠ Standardised over the SHARED window only. Standardising each series over its own full extent
# would compare a 1996-2023 slice of one z-scale against a 1984-2025 slice of another.
#
# ⚠ HOUSE STYLE, CORRECTED 15 Aug. "Hard-boiled" in this project means SPARE AND FACTUAL — plain
# declarative naming, no ornament — not a clever hook. The first attempt titled this "A second
# opinion", which is arch and reads as doctor-speak; PJ: "I hate title - where is hard boiled?".
# Figure 2.15 sets the pattern and this now follows it exactly:
#   "Figure 2.NN  <plain description of what is plotted>, <years>"
# with the FIGURE NUMBER IN THE TITLE LINE, source and method in the grey subtitle beneath, and no
# separate bottom caption block. Greyscale (BUP). No statistics on the panel; no result stated.

suppressPackageStartupMessages({library(ggplot2); library(dplyr); library(readr)})

WS  <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "../../..")) else getwd()
})
DW  <- file.path(WS, "data_workspace_2026-07")

YMIN <- 1996; YMAX <- 2023          # the span the World Bank series covers, single vintage

nao <- read_csv(file.path(DW, "nao_extension/pdf_era/nao_final.csv"), show_col_types = FALSE) |>
  transmute(year, value = est_count) |> filter(year >= YMIN, year <= YMAX)

wgi <- read_csv(file.path(DW, "policy_failure/vdem_wgi/wgi_goveff_uk.csv"),
                show_col_types = FALSE) |>
  transmute(year, value = estimate) |> filter(year >= YMIN, year <= YMAX)

z <- function(x) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)

d <- bind_rows(
  nao |> mutate(series = "Delivery failure recorded by the National Audit Office", value =  z(value)),
  wgi |> mutate(series = "Government effectiveness assessed by the World Bank",   value = -z(value)))

# ⚠ Direct labels rather than a legend: in greyscale a key forces the reader to match line types
# against a box.
# ⚠ PLACED BY HAND, NOT AT THE LAST POINT. Anchoring each label to its series' final value put the
# "World Bank" text directly on top of its own line, which rises into the label in the closing
# years — legible in the data frame, unreadable in the image. The two labels now sit in the empty
# quadrants each series vacates: the Bank's line is high in the late 1990s, the Audit Office's is
# low, so the labels go top-left and bottom-left respectively. Re-check the rendered PNG if either
# series changes shape.
labs_pos <- data.frame(
  x     = c(1996.4, 2004.0),
  y     = c(-1.85,  1.55),
  # PJ, 17 Aug: "no need to repeat reverse coded in the figure, get rid of the bottom one."
  # The subtitle already says it; saying it again on the line label was the repetition.
  lab   = c("World Bank", "National Audit Office"),
  series = sort(unique(d$series)))

fig <- ggplot(d, aes(year, value, linetype = series)) +
  geom_hline(yintercept = 0, colour = "grey80", linewidth = 0.3) +
  geom_line(colour = "grey20", linewidth = 0.65) +
  geom_point(colour = "grey20", size = 1.1) +
  geom_text(data = labs_pos, aes(x = x, y = y, label = lab),
            hjust = 0, size = 3.0, colour = "grey20", inherit.aes = FALSE) +
  scale_linetype_manual(values = c("solid", "22")) +
  scale_x_continuous(breaks = seq(1996, 2023, 4), limits = c(YMIN, YMAX + 0.4)) +
  scale_y_continuous(limits = c(-2.35, 2.55)) +
  labs(title = paste0("Figure 2.14: Serious delivery failures and government effectiveness, ",
                      YMIN, "\u2013", YMAX),
       # ⚠ THE SUBTITLE IS ONE SENTENCE AND STOPS. PJ, 15 Aug: "all the text in the figure
       # needs to say is the World Bank series is reverse coded. Nothing after that." Source,
       # vintage, the missing 1997/1999/2001 estimates and the standardisation are all explained
       # in the chapter text and the footnote — relocated, not lost. DO NOT re-add them here.
       subtitle = "The World Bank series is reverse coded.",
       x = NULL, y = "Standard deviations from series mean") +
  theme_minimal(base_size = 9) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(colour = "grey90", linewidth = 0.3),
        plot.title = element_text(face = "bold", size = 11.5, margin = margin(b = 4)),
        plot.subtitle = element_text(size = 7.8, colour = "grey30", margin = margin(b = 10)),
        axis.title.y = element_text(size = 8))

out <- file.path(WS, "figures/fig_2_14_external_validation.png")
ggsave(out, fig, width = 6.5, height = 4.2, dpi = 300, bg = "white")
cat("written", out, "\n")

m <- inner_join(nao, wgi, by = "year")
cat(sprintf("\nfor the text, not the panel: n=%d, r=%+.3f over %d-%d\n",
            nrow(m), cor(m$value.x, m$value.y), YMIN, YMAX))
