# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/allparty_review/build_fig_2_6_electoral_volatility.R
# ⭐ PROMOTED TO CANONICAL, 17 Aug 2026. This file WAS the _NOCHOW variant; PJ, 17 Aug:
#   "do it, need to sort out file mess!". The pre-Chow-removal original is preserved at
#   _superseded_17aug/data_workspace_2026-07/allparty_review/build_fig_2_6_electoral_volatility.R
# ✅ This is now the live script for the printed figure and IT IS FINE TO HAND-EDIT.
#   (The 'AUTO-DERIVED / DO NOT HAND-EDIT' lines below described the old derived copy and
#   no longer apply — there is no generator to re-run over this file.)
# build_fig_2_6_electoral_volatility.R — AUTO-DERIVED 17 Aug 2026. ⛔ DO NOT EDIT BY HAND.
# ⭐ RENUMBERED 2.8 -> 2.7 (old Fig 2.3 dropped; everything after shifts down one).
# ⭐ DIFFERENT KIND OF EDIT from the other _nochow variants. Panel 4 here is a DATA panel
# (the observed annual index), not a test panel, so it is KEPT and only the break furniture
# is stripped: the CI rectangle, the break vline, the break point, and the break label.
# Dropping the panel would have deleted the series itself.
# ⚠ The break is still COMPUTED above (brkyr, supF) and printed to the console; only the
# drawing of it is removed. Electoral volatility prefers a SPLINE, not a break (ΔBIC 2.25).

# Figure 2.8 — ELECTORAL VOLATILITY ONLY (four panels). The old Panel 4 (composite
# turbulence PC1) is REMOVED — it was not electoral volatility. New Panel 4 = a
# Chow / sup-F structural-break test run on the electoral-volatility latent itself.
#   1 Net aggregate (GE Pedersen + poll volatility, reliability-weighted MARSS)   -> 2026
#   2 Individual vote-switching (BES recall, Wilson CI)                            -> 2024 (last GE)
#   3 Combined individual-anchored latent                                          -> 2026
#   4 Structural-break test on the NET electoral-volatility latent (Chow/sup-F)
# Writes to a WORKSPACE copy for review (NOT the live figures/ folder).
suppressMessages({library(ggplot2); library(patchwork); library(strucchange)})
PROJ <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "../..")) else getwd()
})
WS <- file.path(PROJ,"data_workspace_2026-07"); M <- file.path(WS,"allparty_review/marss")

net  <- read.csv(file.path(M,"aggregate_volatility_index.csv"))[,c("year","v","lo","hi")]   # GE + polls
comb <- read.csv(file.path(M,"volatility_index_pca_input.csv"))
cc   <- comb[!is.na(comb$v), c("year","v","lo","hi")]
sw   <- read.csv(file.path(WS,"switching_series","switching_recall_1979_2024.csv"))
z<-1.96; p<-sw$switching_rate/100; n<-sw$n; den<-1+z^2/n
sw$lo <- 100*(p+z^2/(2*n)-z*sqrt(p*(1-p)/n+z^2/(4*n^2)))/den
sw$hi <- 100*(p+z^2/(2*n)+z*sqrt(p*(1-p)/n+z^2/(4*n^2)))/den

# ===== STRUCTURAL-BREAK TEST — on the OBSERVED (un-smoothed) electoral-volatility index =====
# The MARSS latent is near-deterministic (rho~0.94) so a break test on it is invalid (F explodes).
# Test instead on the observed annual indicators the MARSS fuses, standardized and averaged:
#   GE Pedersen (election years) + poll volatility (annual). Real year-to-year noise -> valid test.
ge <- read.csv(file.path(M,"marss_ge_pedersen.csv"))
pv <- read.csv(file.path(M,"marss_poll_volatility.csv"))
YRS <- 1979:2026
zof <- function(vals, years){ z<-setNames(rep(NA_real_,length(YRS)),YRS); z[as.character(years)]<-as.numeric(scale(vals)); z }
obs <- data.frame(year=YRS, v=rowMeans(cbind(zof(ge$pedersen_ge,ge$year), zof(pv$poll_volatility,pv$year)), na.rm=TRUE))
obs <- obs[is.finite(obs$v), ]
d  <- obs
fs <- Fstats(v ~ year, data=d, from=0.15)
supF <- max(fs$Fstats); pval <- sctest(fs)$p.value
bpf   <- breakpoints(v ~ year, data=d, h=0.15)            # full RSS/BIC object
nbic  <- if (all(is.na(bpf$breakpoints))) 0L else length(bpf$breakpoints)
ci    <- confint(bpf, breaks=1, level=0.90)$confint       # best SINGLE break + 90% CI
brkyr <- d$year[ci[1,2]]
ci_lo <- ifelse(is.na(ci[1,1]), min(d$year), d$year[ci[1,1]])
ci_hi <- ifelse(is.na(ci[1,3]), max(d$year), d$year[ci[1,3]])
# AR(1)-null guard (a smoothed latent is persistent -> inflates sup-F; test against AR(1))
ar1 <- ar(d$v, order.max=1, aic=FALSE, method="yule-walker"); rho <- ar1$ar; sdi <- sqrt(ar1$var.pred)
set.seed(1)
nullF <- replicate(3000, { x <- as.numeric(arima.sim(n=nrow(d), list(ar=max(min(rho,.99),-.99)), sd=sdi))
  max(Fstats(x ~ d$year, from=0.15)$Fstats) })
p_ar1 <- mean(nullF >= supF)
cat(sprintf("ELECTORAL-VOL break: %d  (90%% CI %d-%d)  sup-F=%.1f  asym p=%.4f  AR(1)-null p=%.3f  [rho=%.2f]\n",
            brkyr, ci_lo, ci_hi, supF, pval, p_ar1, rho))

BRKlab <- sprintf("Chow / sup-F break: %d\nsup-F=%.1f, p=%s\n90%% CI %d–%d", brkyr, supF,
                  ifelse(pval<0.001,"<.001",sprintf("%.3f",pval)), ci_lo, ci_hi)

YL <- c(min(c(net$lo,cc$lo)), max(c(net$hi,cc$hi)))
XB <- scale_x_continuous(breaks=seq(1980,2020,10), limits=c(1979,2026))
# ⏸ PRINT-RELATIVE TYPE REVERTED 17 Aug. PJ: "feel this is a mess - maybe live with what I have
# got?" Piloting it here left 2.6 with big type and the other fifteen figures at size 9, which is
# the one state worse than either option. Back to house size 9, consistent with the rest.
# ⭐ THE WORK IS NOT LOST: house_print() / pt_for() / mm_for() and the PRINTED size table are in
# figure_house_theme.R, tested on this figure, ready for stage (c). CANVAS_W here was 8.6.
# ⚠ What the pilot proved, and what stage (c) must budget for: enlarging type does NOT create
# space. Panel B's subtitle overran and printed clipped as "...2024 elec". Subtitles written for a
# 9 in canvas do not fit a 120 mm column, so the print pass is subtitle surgery, not a size switch.
base <- theme_minimal(base_size=12) + theme(legend.position="none",
  plot.subtitle=element_text(face="italic",hjust=0,colour="grey30",size=9),
  plot.tag=element_text(face="bold", size=11),
  panel.grid.minor=element_blank(), axis.title=element_text(size=10,colour="grey15"),
  plot.title=element_text(face="bold",size=14.5), plot.caption=element_text(size=7,colour="grey40",hjust=0))
vpanel <- function(df,lab){ ggplot(df,aes(year,v))+geom_hline(yintercept=0,colour="grey85")+
  geom_ribbon(aes(ymin=lo,ymax=hi),fill="grey70",alpha=.30)+geom_line(colour="#000000",linewidth=1.1)+
  coord_cartesian(ylim=YL)+XB+labs(subtitle=lab,x=NULL,y="z")+base+theme(axis.text.x=element_blank()) }

# ⭐ PANEL 1 REPLACED 17 Aug, PJ: "good to start with the basic index as this is where everyone
# starts, eg Fieldhouse book - so a good way to build the argument and all leads to panel four
# which then feeds PCA."
# ⛔ WHAT WAS THERE: the reliability-weighted MARSS *latent*. That is the opposite of "the basic
# index" — it is the most heavily modelled series in the figure, its uncertainty band spans about
# ±7z, and the project's own files flag it as a near-unit-root smoothing artefact (rho ~ 0.94),
# which is why the break test was deliberately run on the OBSERVED index instead.
# ⭐ WHAT IS THERE NOW: the RAW Pedersen index at general elections, in percentage points. The
# familiar measure, no model, no band. It is also an INPUT to panel 4, so the build now reads:
# standard measure -> individual-level counterpart -> modelled synthesis -> the operational annual
# series that feeds the PCA.
loc <- read.csv(file.path(M,"marss_local_pedersen.csv"))
loc <- loc[is.finite(loc$pedersen_local), ]
# ⭐ PJ, 17 Aug: "put in the raw series and we can add local elections in there unweighted."
# UNWEIGHTED means exactly that: both series are raw Pedersen in percentage points, drawn as they
# are. No reliability weighting, no standardisation, no model.
# ⚠ Locals earn their place by COVERAGE, not corroboration: they are annual, so they fill the gaps
#   between general elections. On the 12 shared election years r(local, GE) = -0.09 — the two do
#   NOT track each other. Do not let the panel imply they agree.
p1 <- ggplot() +
  geom_line(data=loc, aes(year, pedersen_local), colour="grey60", linewidth=.55) +
  geom_point(data=loc, aes(year, pedersen_local), colour="grey60", size=.9) +
  geom_line(data=ge,  aes(year, pedersen_ge), colour="grey30", linewidth=.4, linetype="22") +
  geom_point(data=ge, aes(year, pedersen_ge), colour="#000000", size=2.4) +
  annotate("text", x=1980.5, y=22.4, label="general elections", hjust=0, size=3, colour="grey10") +
  annotate("text", x=1980.5, y=19.6, label="local elections",   hjust=0, size=3, colour="grey45") +
  XB + scale_y_continuous(limits=c(0, 24.5), expand=c(0,0)) +
  labs(tag="A", subtitle="Net — Pedersen index of electoral volatility, raw and unweighted",
       x=NULL, y="volatility (% points)") +
  base + theme(axis.text.x=element_blank())

lab24 <- sw[sw$election_year==2024,]   # restored: lost when panel 1 was replaced
p2 <- ggplot(sw,aes(election_year,switching_rate)) +
  geom_ribbon(aes(ymin=lo,ymax=hi),fill="grey70",alpha=.28) +
  geom_line(colour="#000000",linewidth=1.0)+geom_point(colour="#000000",size=1.9)+
  geom_point(data=lab24,size=3.2,shape=21,fill="white",colour="#000000",stroke=1.1)+
  annotate("text",x=2024,y=lab24$switching_rate,label="2024\n37%",hjust=1.25,vjust=.35,size=2.8,fontface="bold",colour="grey10",lineheight=.85)+
  scale_y_continuous(limits=c(13,42))+XB+
  # ⛔ At print-relative type this subtitle overran the canvas and printed clipped as "...2024 elec".
  #    The parenthetical was method detail (recall instrument, interval type, end point) - footnote
  #    material, not panel material. The band and the end point are both visible in the panel.
  labs(tag="B", subtitle="Gross — individual vote-switching, BES recall",x=NULL,y="switchers (%)")+base+theme(axis.text.x=element_blank())

p3 <- vpanel(cc,"Combined index (individual-anchored latent)") + theme(axis.text.x=element_blank())

YL4 <- c(min(d$v)*1.05, max(d$v)*1.12)
p4 <- ggplot(d,aes(year,v)) +
  geom_hline(yintercept=0,colour="grey85")+geom_line(colour="#000000",linewidth=1.1)+
  coord_cartesian(ylim=YL4)+XB+
  # ⛔ House rule: subtitles DESCRIBE, they do not explain or conclude. The trailing clause
  # "— the series that enters the turbulence index" told the reader what the panel was for;
  # that is PJ's job in the text, not the panel's. Removed 17 Aug at his request.
  labs(tag="C", subtitle="Observed annual index, general elections and polls",x=NULL,y="z (observed)")+base

# Provenance/method text moved OFF the figure to the printed footnote (24 Jul edit). Title +
# panel subtitles + the in-panel break marker (panel 4) retained as legibility labels.
# ⛔ PANEL 3 (combined individual-anchored latent) DROPPED 17 Aug, PJ: "could drop panel 3
# or C". It was the last modelled series in the figure, it ran much flatter than either raw
# series, and it read as damping the finding rather than supporting it. p3 is still built
# above but is no longer drawn.
fig <- (p1/p2/p4)+plot_layout(heights=c(1,1,1.05))+
  plot_annotation(title="Figure 2.6: Electoral volatility, 1979–2026",
    theme=theme(plot.title=element_text(face="bold",size=15), plot.margin=margin(12,18,12,18)))
LIVE <- file.path(WS, "allparty_review/figures/fig_2_6_electoral_volatility.png")
ggsave(LIVE, fig, width=8.6, height=10.4, dpi=150)
cat("DONE -> LIVE:", LIVE, "\n")
