# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/composite_canonical/build_canonical_composite.R
# ============================================================
# build_canonical_composite.R
# THE canonical, frozen "clean-SIX" turbulence-PCA composite for
# ⭐ 17 Aug 2026: SIX components. `unexpected` added so every one of the chapter's six
#    theorised dimensions has a measure in the index. See the block at COMPS below.
# "Who Killed British Democracy?" (Chapter 2).
#
# ➕ RE-FROZEN 16 Aug 2026. The 24 Jul clean-five version is in _ARCHIVE/data_and_indices/composite_cleanfive_24jul/.
# TWO changes, and the first is a correction rather than a choice:
#
#  1. ⛔ THE 24 JUL FREEZE HAD GONE STALE. Two of its five inputs changed on 4 Aug — the Cowley
#     1987-97 transposition fix (rebellions_annual.csv) and the rebuild of the dislocation index on
#     the official parliament.uk series — and the frozen numbers were never regenerated, so Ch2 was
#     quoting pre-fix statistics. Caught by running the clean five as a REFERENCE alongside new
#     variants and finding it no longer reproduced.
#     ⚠ dept_churn ALSO changed, on 16 Aug: 3 of its 40 events were wrong on verification against
#     White & Dunleavy (2010) and the gov.uk organisations register (machinery_churn/
#     EVENT_VERIFICATION.md). 40 events -> 39. All three corrections fall pre-2002.
#
#  2. ➕ U-TURNS ADDED as a sixth component (PJ, 16 Aug). Agenda churn was tested and rejected.
#     ⚠ Adding U-turns LOWERS PC1 variance: it brings independent variation rather than
#     corroboration (r = -0.15 with rebellions). That is a real property of the index, not a
#     defect, and the write-up must not present the sixth component as confirming the other five.
#
# One authoritative run. Fixed seed. 1979-2024. ONE set of numbers.
# This SUPERSEDES the old defeats-based live composite in pca_rebuild/.
#
# Clean six = elect_vol + exec_instab + rebellion_pct + dislocation + dept_churn + uturns
# (exec_instab replaced pm_churn on 17 Aug 2026 — see the block below.)
#   (this is composite_candidates candidate C/D). It removes the two known
#   defects of the old composite: the near-inverted RAW defeats series (replaced
#   by the parliamentary DISLOCATION index) and the inert spending_churn (dropped),
#   and adds departmental machinery churn (the co-moving DEPARTMENTAL component,
#   NOT the counter-cyclical quango series).
#
# READ-ONLY on all inputs. WRITES ONLY to composite_canonical/. Does NOT touch
# the live pipeline (pca_rebuild/, scripts/, data/processed/, data_may2026/).
#
# PCA convention: z-score each component, prcomp(center=TRUE, scale.=TRUE) on
# complete cases, sign-flip PC1 so mean loading > 0 ("higher = more turbulent").
# Identical to the harness run_pca() in pca_rebuild/turbulence_pca_FINAL.R.
#
# Break test: the CANONICAL regression-based Quandt-Andrews sup-F,
# chow_standardized/chow_test.R :: chow_sweep. This is the LEVEL+TREND test
# (df1 = 2: intercept AND slope may break) -> the ~10-17-type F statistic.
# It is NOT the mean-shift (df1 = 1) Chow that the old live FINAL script used,
# which returns the much larger ~86-100 statistic. We report BOTH and label
# which is which, but the LEVEL+TREND sup-F is the canonical headline number.
#
# ============================================================================
# TWO CONVENTIONS FOR THE SAME STATISTIC -- RESOLVED 18 Aug 2026
# ============================================================================
# .chow_F_reg returns an F statistic: it divides the explained sum of squares
# by df1. strucchange::Fstats / sctest(type="supF") return the WALD form, which
# is df1 * F. For the level+trend test df1 = 2, so the two differ by EXACTLY a
# factor of two; for the mean-shift test df1 = 1 they are identical. This was
# verified pointwise across the whole 15%-trim sweep on the canonical series:
# ratio = 2.000000 at all 33 shared points, sd 1.5e-15, both peaking at 2015.
#
# NOTHING IS WRONG WITH EITHER. But the chapter must not mix them, because a
# referee re-running sctest() gets a number twice the size of the one in this
# file. DECISION (PJ, 18 Aug): QUOTE THE WALD FORM -- it is what strucchange
# returns, so it is what the replication package reproduces.
#
#   supF_level_trend_WALD  <- QUOTE THIS in the chapter and appendix (38.26)
#   supF_level_trend_df2   <- the same test in F form (19.13); kept because
#                             every internal comparison, permutation null and
#                             bootstrap in this project is built on it, and
#                             all of those are invariant to the scaling.
#
# DO NOT "fix" .chow_F_reg to match. Six other scripts read it
# (break_sensitivity, composite_variants, the stress tests) and rescaling it
# would silently change their stored outputs without changing any conclusion.
# ============================================================================
# ============================================================

PROJECT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "../..")) else getwd()
})
WS   <- file.path(PROJECT, "data_workspace_2026-07")
OUT  <- file.path(WS, "composite_canonical")
DP   <- file.path(PROJECT, "data", "processed")
ADP  <- file.path(PROJECT, "data_may2026", "data", "processed")
DIS  <- file.path(WS, "parliamentary_dislocation")
MCH  <- file.path(WS, "machinery_churn", "data")
PCR  <- file.path(WS, "_exploratory_ch3-10", "pca_rebuild")
POL  <- file.path(WS, "policy_instability")     # ➕ 16 Aug: U-turns series lives here

dir.create(OUT, showWarnings = FALSE, recursive = TRUE)
sink(file.path(OUT, "run.log"), split = TRUE)      # tee console -> run.log
cat("=== build_canonical_composite.R ===\n")
cat("Run at:", format(Sys.time()), "\n")
cat("R version:", R.version.string, "\n\n")

suppressMessages(library(strucchange))
source(file.path(WS, "chow_standardized", "chow_test.R"))  # canonical chow_sweep + .chow_F_reg

# ---- ONE fixed seed for the whole run --------------------------------------
SEED  <- 42                              # book convention (exec-instability figure)
# ⭐ 17 Aug 2026: window extended to 2025. `dept_churn` was the ONLY component ending in 2024 —
# every other one already reached 2025 or 2026 — so one series was capping the whole index.
# 2025 was checked against gov.uk / IfG / the ministerial-responsibilities list: NO ministerial
# department was created, abolished, merged, split or renamed in calendar 2025, so dept_churn
# 2025 = 0. See machinery_churn/VERIFICATION_2025.md.
# ⚠ 2026 deliberately NOT added — PJ: "2026 is not done yet so we leave, but update when year
# ends at review stage." A part-year would truncate every count series.
# ⭐ WINDOW STARTS 1980, NOT 1979 — PJ, 18 Aug: "there is a case for taking [out] 1979 for
# modelling reasons so start in 1980 - need to be clear that this is the back end of the
# disruption of the 1970s - was thinking anyway of running the series from start of Thatcher."
# ⭐ THE REASON IS SUBSTANTIVE FIRST: 1979 is the tail of the 1970s crisis (Winter of Discontent,
#   the May election), not part of the period the chapter is about. Thatcher takes office in May
#   1979, so 1980 is the first full year of the era under study.
# ⛔ THE MODELLING REASON, STATED PLAINLY BECAUSE IT MUST NOT LOOK LIKE THE ONLY ONE: 1979 was the
#   4th most turbulent year of 46, and that rested almost entirely on `unexpected` = +4.04 z — the
#   largest single value anywhere in the data, 5.1 SD from the mean of the rest of its own series,
#   the FIRST year of an expectations-based measure and built on only 3 items. Retaining it let a
#   thin-plate spline beat the segmented model by fitting one probably-artefactual point.
# ⚠ Disclose both reasons in the appendix. Dropping a boundary year that happens to favour the
#   preferred model is exactly the move a referee will look for.
YEARS <- 1979:2025   # reverted 18 Aug pending the variant battery; see unexpected_variants/
NPERM <- 10000                           # iid permutation draws (chow_sweep)
NSIM  <- 10000                           # AR(1)-null Monte-Carlo draws
BOOT  <- 3000                            # block-bootstrap break-date draws
BLKL  <- 4                               # moving-block length (~sqrt(n)); matches live script
set.seed(SEED)

zscore <- function(x){ m<-mean(x,na.rm=TRUE); s<-sd(x,na.rm=TRUE)
  if(is.na(s)||s==0) return(rep(0,length(x))); (x-m)/s }

run_pca <- function(df, zc){
  cc  <- df[complete.cases(df[,zc,drop=FALSE]),]
  fit <- prcomp(cc[,zc,drop=FALSE], center=TRUE, scale.=TRUE)
  l1  <- fit$rotation[,1]; flip <- if(mean(l1) < 0) -1 else 1
  list(fit=fit, years=cc$year, pc1=fit$x[,1]*flip, loadings=l1*flip,
       var_exp=fit$sdev^2/sum(fit$sdev^2), n=nrow(cc))
}

# sup-F helpers that reuse the CANONICAL .chow_F_reg (level+trend, df1=2) with
# the SAME interior/trim as chow_sweep, so nulls & bootstraps are like-for-like.
.ks_interior <- function(n, trim=0.15, min_seg=3){
  lo <- max(min_seg, floor(trim*n)); hi <- min(n-min_seg, n-floor(trim*n)); lo:hi
}
supF_max <- function(y, trim=0.15, min_seg=3){
  n<-length(y); t<-seq_len(n); ks<-.ks_interior(n,trim,min_seg)
  max(vapply(ks, function(k) .chow_F_reg(y,t,k,min_seg), numeric(1)), na.rm=TRUE)
}
supF_peakyear <- function(y, year, trim=0.15, min_seg=3){
  n<-length(y); t<-seq_len(n); ks<-.ks_interior(n,trim,min_seg)
  f<-vapply(ks, function(k) .chow_F_reg(y,t,k,min_seg), numeric(1))
  year[ks[which.max(f)]]
}

# mean-shift Chow (df1=1) — ONLY to show the contrasting ~86-100 statistic.
.rss_mean <- function(y){ s<-sum((y-mean(y))^2); if(is.na(s)) 0 else s }
chow_F_meanshift <- function(y, k, min_seg=3){
  n<-length(y); if(k<min_seg||k>n-min_seg) return(NA_real_)
  rss_pool <- .rss_mean(y); rss_split <- .rss_mean(y[1:k])+.rss_mean(y[(k+1):n])
  if(rss_split<=0) return(NA_real_)
  ((rss_pool-rss_split)/1)/(rss_split/(n-2))
}
supF_meanshift <- function(y, year, trim=0.15, min_seg=3){
  n<-length(y); ks<-.ks_interior(n,trim,min_seg)
  f<-vapply(ks, function(k) chow_F_meanshift(y,k,min_seg), numeric(1))
  list(peak_year=year[ks[which.max(f)]], peak_F=max(f,na.rm=TRUE), curve=data.frame(year=year[ks],F=f))
}

# ============================================================================
# 1. COMPONENTS (annual 1979-2024) — same read-only ingest as the live script
# ============================================================================
# ⭐ EXECUTIVE INSTABILITY (replaces the narrower pm_churn, PJ 17 Aug).
# Was: pm_churn = number of PMs active in the year, minus 1 (a handover count).
# Now: PC1 of THREE annual departure counts — PM, Great Officers, Cabinet — the same construct
# Figures 2.1-2.5 build. Reasons: it makes those figures load-bearing rather than decorative, it
# strengthens the executive loading (0.366 -> 0.438) by averaging out noise, and it keeps ONE
# method (PCA) at both levels, per PJ's rule of 17 Aug.
# ⚠ On this data PC1 is numerically identical to the simple mean (loadings 0.584/0.585/0.563,
#   r = 1.0000). The PCA is the consistent choice, NOT a more accurate one. Do not claim otherwise.
# ⚠ r(exec PC1, old pm_churn) = 0.916 and r(new index, old index) = 0.993 — the finding does not
#   move. This is a tidiness gain, not a result.
pm <- read.csv(file.path(DP,"pm_tenure.csv"), stringsAsFactors=FALSE)
pm$end_year <- as.numeric(format(as.Date(pm$end), "%Y"))
pm_dep <- sapply(YEARS, function(yr) sum(pm$end_year == yr, na.rm=TRUE))
go_raw  <- read.csv(file.path(DP,"great_officers_annual_departures.csv"), stringsAsFactors=FALSE)
cab_raw <- read.csv(file.path(DP,"cabinet_annual_departures.csv"), stringsAsFactors=FALSE)
go_dep  <- go_raw$total[match(YEARS, go_raw$end_year)];      go_dep[is.na(go_dep)]   <- 0
cab_dep <- cab_raw$departures[match(YEARS, cab_raw$year)];   cab_dep[is.na(cab_dep)] <- 0
.exz <- scale(cbind(pm_dep, go_dep, cab_dep))
.exp <- prcomp(.exz, center=FALSE, scale.=FALSE)
.exs <- if (mean(.exp$rotation[,1]) < 0) -1 else 1
exec_instab <- as.numeric(.exp$x[,1]) * .exs
cat(sprintf("exec instability PC1: %.1f%% var; loadings pm %.3f go %.3f cab %.3f\n",
    100*.exp$sdev[1]^2/sum(.exp$sdev^2), (.exp$rotation[,1]*.exs)[1],
    (.exp$rotation[,1]*.exs)[2], (.exp$rotation[,1]*.exs)[3]))

reb <- read.csv(file.path(ADP,"rebellions_annual.csv"), stringsAsFactors=FALSE)
rebellion_pct <- reb$rebellion_pct[match(YEARS, reb$year)]

mar <- read.csv(file.path(WS,"allparty_review","marss","volatility_index_pca_input.csv"), stringsAsFactors=FALSE)
elect_vol <- mar$v[match(YEARS, mar$year)]

dis <- read.csv(file.path(DIS,"parliamentary_dislocation_index.csv"), stringsAsFactors=FALSE)
dislocation <- dis$dislocation_index[match(YEARS, dis$year)]

dc  <- read.csv(file.path(MCH,"departmental_churn_1979_2025.csv"), stringsAsFactors=FALSE)
dept_churn <- dc$dept_churn[match(YEARS, dc$year)]

# ➕ 16 Aug 2026 — SIXTH COMPONENT: U-turns (PJ's decision, "u turns are in, agenda churn out").
# Raw annual count, the measure PJ settled on 16 Aug (commitment-failure framing).
# ⚠ It covers 1979-2025 in full, so adding it costs NO years: n stays at 46.
# ⛔ Agenda churn was tested and EXCLUDED — PC1 loading -0.075, and it correlates with nothing in
#    the index (max |r| = 0.14). See composite_variants/.
ut <- read.csv(file.path(POL,"uturns","series","uturns_series.csv"), stringsAsFactors=FALSE)
uturns <- ut$n[match(YEARS, ut$year)]

# ➕ 17 Aug 2026 — SEVENTH COMPONENT: unexpected movements in public attention.
# ⭐ PJ: "I think I always intended to have public opinion in, just got neglected... it does mean
#    that all the six dimensions are in there as theorised, even if not all the measures within
#    each category are."
# ⛔ THE ARGUMENT IS STRUCTURAL, NOT EMPIRICAL, and that is the defensible order. The chapter
#    theorises SIX dimensions; before this, dimension three (public opinion churn) was the only
#    one with NO measure in the index at all:
#      1 executive turnover      -> exec_instab
#      2 electoral volatility    -> elect_vol
#      3 public opinion churn    -> (nothing)   <- the gap this closes
#      4 parliamentary           -> dislocation + rebellion_pct
#      5 policy instability      -> dept_churn
#      6 policy failures         -> uturns
# ⚠ COSTS, to be stated in the appendix and NOT buried:
#    - n falls 46 -> 45 (1981 has no estimate)
#    - PC1 variance falls 35.8% -> 33.3%: it brings INDEPENDENT variation, so it must not be
#      read as corroboration of the other six
#    - flat is rejected LESS decisively, 27.6 -> 23.1 BIC. It does not strengthen the headline.
#    - knot moves 2013 -> 2012; r with the six-component index = 0.971
# ⚠ It was tested on 17 Aug, AFTER the index had been frozen twice. Describe it as what it is:
#    a design correction on theoretical grounds, not a discovery.
# ⚠ [[wkbd-ch2-public-opinion-revisit]] records PJ's own view that this series rests on stacked
#    assumptions. It should therefore lead the leave-one-out disclosure.
une <- read.csv(file.path(WS,"ch2_public_opinion","composite_unexpected_index.csv"), stringsAsFactors=FALSE)
unexpected <- une$composite_z[match(YEARS, une$year)]

# ⛔ 1981 IS INTERPOLATED, AND IT IS THE ONLY IMPUTED VALUE IN THE INDEX.
# PJ, 18 Aug 2026: "keep unexpected in, interpolate - declare".
# WHY THE GAP EXISTS: the Ipsos issues series has **no observations at all** for 1981 — 1980 has
#   88 monthly readings, 1982 has 132, 1981 has zero. It is a hole in the source, not a failure of
#   computation, and it is the ONLY year missing from any component in the whole index.
# ⚠ WHAT THIS VALUE IS AND IS NOT: `unexpected` is a RESIDUAL — how far public worry departed from
#   what conditions predicted. A linear interpolation does not estimate 1981's surprise; it assumes
#   1981 was unsurprising in proportion to its neighbours. 1981 was in fact an eventful year (the
#   SDP split, the March budget, the riots, unemployment through 2.5m), so treat this as a
#   PLACEHOLDER, not an estimate.
# ✅ NOTHING RESTS ON IT. Break year 2015 and its 90% CI are identical whether 1981 is linearly
#   interpolated, imputed at the series mean, or left out entirely (n=46). sup-F is marginally
#   HIGHER with it in (38.3 vs 36.0). Tested in nonlinear_modelling/; reported in the robustness set.
# ⚠ The choice of convention moves the 1981 POINT a long way even though it moves no conclusion:
#   linear gives +1.22, series-mean +0.01. That is why the figure marks the year as imputed.
.i81 <- which(YEARS == 1981)
if (length(.i81) == 1 && is.na(unexpected[.i81])) {
  unexpected[.i81] <- mean(c(unexpected[.i81 - 1], unexpected[.i81 + 1]))
  cat(sprintf("⚠ 1981 unexpected INTERPOLATED = %+.3f (mean of %+.3f and %+.3f)\n",
              unexpected[.i81], unexpected[.i81 - 1], unexpected[.i81 + 1]))
}
IMPUTED_YEARS <- 1981L   # read by build_fig_2_16_turbulence_index.R to mark the point

# ⛔ REBELLIONS DROPPED 18 Aug 2026. PJ: "we keep one dimension of parliament, whereas rebellions
# could be seen to be helpful for democracy."
# ⭐ NOT A NEW JUDGEMENT — the same test already removed raw government defeats from this composite
#   ("near-inverted for the thesis; high defeats can mean Parliament working"). Backbench rebellions
#   carries the identical valence problem and had simply never been re-tested against it.
# ⚠ The data agreed with the theory: rebellions correlated NEGATIVELY with electoral volatility
#   (-0.066), U-turns (-0.151) and unexpected movements (-0.034) — it pulled against half the index.
# Measurement case, independently: loading 0.150, r = 0.205 with its own index, only 11 distinct
#   values across 46 years (a per-parliament step function), and 2024 AND 2025 both carrying the
#   8.7 stub from a parliament that was months old when compiled.
# ✅ Costs NO years. PC1 variance 31.9% -> 36.9%; r with the seven-component index = 0.9945.
# 📄 PENDING_REBELLIONS_DECISION.md (now closed).
# ⛔ 29 Aug 2026 — CONSIDERED removing `unexpected`, REVERTED same day. The circularity concern
#   (danger of "expected MIP" feeding both the composite AND the Zucco/volatility-curse
#   attribution test's DV — see attribution_test/ZUCCO_INTERACTION_NOTES.md) is real, but it is
#   already correctly handled WHERE IT MATTERS: the attribution test rebuilds its own clean PC1
#   excluding `unexpected` before testing. A fresh 5-component rebuild of THIS composite (dropping
#   `unexpected` here too) was tried and reverted: the leave-one-out estimate (canonical_
#   leave_one_out.csv, row "unexpected") had suggested the break year would hold at 2015, but an
#   actual fresh 5-component build gave an unstable result instead (sup-F peak 2010, mean-shift
#   2017, Bai-Perron 2017) — the two disagree because z-scoring each component against a
#   5-component common sample differs from dropping one column out of the six-component panel's
#   z-scores. PJ, 29 Aug: keep the six-component composite as the canonical one; the Zucco test's
#   own separate clean-PC1 rebuild is the correct and sufficient fix for the circularity.
COMPS <- c("elect_vol","exec_instab","dislocation","dept_churn","uturns","unexpected")
panel <- data.frame(year=YEARS, elect_vol, exec_instab, dislocation, dept_churn, uturns, unexpected)
for(c in COMPS) panel[[paste0(c,"_z")]] <- zscore(panel[[c]])

cat("Component coverage (non-NA of", length(YEARS), "years):\n")
print(sapply(panel[,COMPS], function(x) sum(!is.na(x))))

# ============================================================================
# 2. CANONICAL PCA
# ============================================================================
zc <- paste0(COMPS,"_z")
P  <- run_pca(panel, zc)
cat(sprintf("\nPCA complete-case n = %d (years %d-%d)\n", P$n, min(P$years), max(P$years)))
cat(sprintf("PC1 variance explained = %.2f%%\n", 100*P$var_exp[1]))

# ---- PC1 series CSV (raw + z inputs) ---------------------------------------
series <- data.frame(year=P$years, PC1_index=P$pc1)
for(c in COMPS){ series[[c]] <- panel[[c]][match(P$years,panel$year)]
                 series[[paste0(c,"_z")]] <- panel[[paste0(c,"_z")]][match(P$years,panel$year)] }
write.csv(series, file.path(OUT,"canonical_pc1_1979_2025.csv"), row.names=FALSE)

# ---- loadings + variance explained -----------------------------------------
load_tab <- data.frame(component=COMPS,
                       loading_PC1=round(as.numeric(P$loadings),4),
                       var_explained_PCn=round(100*P$var_exp[seq_along(COMPS)],2))
write.csv(load_tab, file.path(OUT,"canonical_loadings.csv"), row.names=FALSE)
var_tab <- data.frame(PC=paste0("PC",seq_along(P$var_exp)),
                      sdev=round(P$fit$sdev,4),
                      var_pct=round(100*P$var_exp,2),
                      cum_pct=round(100*cumsum(P$var_exp),2))
write.csv(var_tab, file.path(OUT,"canonical_variance_explained.csv"), row.names=FALSE)
cat("\n=== LOADINGS ===\n"); print(load_tab, row.names=FALSE)
cat("\n=== VARIANCE EXPLAINED ===\n"); print(var_tab, row.names=FALSE)

# ============================================================================
# 3. THE SINGLE CANONICAL BREAK RESULT
# ============================================================================
# 3a. Canonical LEVEL+TREND sup-F (df1=2) with iid permutation p
CS <- chow_sweep(year=P$years, y=P$pc1, trim=0.15, nperm=NPERM, seed=SEED)
cat(sprintf("\n=== CANONICAL LEVEL+TREND sup-F (df1=2) ===\n"))
cat(sprintf("Break year        = %d\n", CS$peak_year))
cat(sprintf("sup-F(2,%d)        = %.2f   [F form; the ~10-17-type figure, LEVEL+TREND]\n", CS$n-4, CS$peak_F))
cat(sprintf("sup-F WALD         = %.2f   [<- QUOTE THIS: df1 * F, what sctest() returns]\n", 2*CS$peak_F))
cat(sprintf("5%% pointwise crit = %.2f\n", CS$crit_5pct))
cat(sprintf("perm p (iid)      = %.4f  (%d draws)\n", CS$perm_p, NPERM))
cat(sprintf("slope before/after= %.4f / %.4f\n", CS$slope_before, CS$slope_after))
write.csv(CS$curve, file.path(OUT,"canonical_fsweep_leveltrend.csv"), row.names=FALSE)

# 3b. Mean-shift (df1=1) contrast — the ~86-100 statistic (NOT canonical)
MS <- supF_meanshift(P$pc1, P$years)
cat(sprintf("\n[contrast] MEAN-SHIFT sup-F (df1=1) break %d, F = %.2f  <- the ~86-100-type figure; NOT canonical\n",
            MS$peak_year, MS$peak_F))
write.csv(MS$curve, file.path(OUT,"contrast_fsweep_meanshift.csv"), row.names=FALSE)

# --- segmented (two-regime linear-trend) fit at the canonical break ---------
# Used both by the block-bootstrap CI (3d) and by the "fair" AR(1) null (3c).
yy <- P$pc1[order(P$years)]; yr <- sort(P$years); n <- length(yy); t <- seq_len(n)
kk <- CS$peak_k
fit1 <- lm(yy[1:kk] ~ t[1:kk]); fit2 <- lm(yy[(kk+1):n] ~ t[(kk+1):n])
fitted_seg <- c(fitted(fit1), fitted(fit2)); resid_seg <- yy - fitted_seg

# 3c. AR(1)-NULL p — autocorrelation-robust Monte-Carlo null.
#   The sup-F NULL hypothesis is a SINGLE regime: y = a + b*t + e. So the null
#   DGP is the pooled single-trend fit plus AR(1) innovations; we simulate NSIM
#   paths, recompute the canonical sup-F max on each, p = Pr(sim sup-F >= obs).
#   Two ways to estimate the nuisance AR(1) persistence, reported as a range:
#     (i) POOLED-residual phi  = AR(1) of residuals from ONE trend line. The
#         break is still in those residuals, so phi is inflated -> this null is
#         DELIBERATELY CONSERVATIVE (an upper bound on p).
#    (ii) SEGMENTED-residual phi = AR(1) of residuals NET of the break (two-
#         regime fit). This isolates genuine short-run autocorrelation from
#         break-induced persistence -> a FAIRER, more powerful null.
m_pool   <- lm(yy ~ t); fit_pool <- fitted(m_pool); res_pool <- residuals(m_pool)
phi_pool <- as.numeric(ar(res_pool,  order.max=1, aic=FALSE, method="yule-walker")$ar)
phi_seg  <- as.numeric(ar(resid_seg, order.max=1, aic=FALSE, method="yule-walker")$ar)
sd_pool  <- sd(res_pool)  * sqrt(max(1e-6, 1 - phi_pool^2))   # AR(1) innovation sd
sd_seg   <- sd(resid_seg) * sqrt(max(1e-6, 1 - phi_seg^2))
ar1_null_p <- function(phi, sdi){
  sim <- replicate(NSIM, supF_max(fit_pool + as.numeric(arima.sim(list(ar=phi), n=n, sd=sdi))))
  mean(sim >= CS$peak_F)
}
set.seed(SEED); p_ar1_pooled <- ar1_null_p(phi_pool, sd_pool)   # conservative
set.seed(SEED); p_ar1_seg    <- ar1_null_p(phi_seg,  sd_seg)    # fair
cat(sprintf("\n=== AR(1)-NULL sup-F test (single-trend-line null + AR(1) innovations) ===\n"))
cat(sprintf("pooled-residual  phi = %.3f  -> AR(1)-null p = %.4f  [conservative; break inflates phi]\n",
            phi_pool, p_ar1_pooled))
cat(sprintf("segmented-resid  phi = %.3f  -> AR(1)-null p = %.4f  [fair; autocorr net of break]\n",
            phi_seg,  p_ar1_seg))

# 3d. BLOCK-BOOTSTRAP break-date CI.
#     DGP = two-segment LINEAR-TREND fit at the canonical break (level+trend
#     model, matching the test); moving-block residual resample (L=4) preserves
#     short-run autocorrelation; re-find the canonical sup-F peak year each draw.
mb_resample <- function(res, n, L){                  # moving-block bootstrap
  nb <- ceiling(n/L); starts <- sample(seq_len(length(res)-L+1), nb, replace=TRUE)
  as.numeric(unlist(lapply(starts, function(s) res[s:(s+L-1)])))[1:n]
}
set.seed(SEED)
boot_block <- integer(BOOT)
for(b in seq_len(BOOT)){ ystar <- fitted_seg + mb_resample(resid_seg, n, BLKL)
  boot_block[b] <- supF_peakyear(ystar, yr) }
set.seed(SEED)                                        # iid residual bootstrap (comparison)
boot_iid <- integer(BOOT)
for(b in seq_len(BOOT)){ ystar <- fitted_seg + sample(resid_seg, n, replace=TRUE)
  boot_iid[b] <- supF_peakyear(ystar, yr) }
ci_block <- quantile(boot_block, c(0.05,0.95), type=1)
ci_iid   <- quantile(boot_iid,   c(0.05,0.95), type=1)
tb <- as.data.frame(table(boot_year=boot_block)); tb$boot_year<-as.integer(as.character(tb$boot_year))
tb$prop <- round(tb$Freq/BOOT,4)
mode_year <- tb$boot_year[which.max(tb$Freq)]
p_2016 <- mean(boot_block==2016); p_1517 <- mean(boot_block %in% 2015:2017)

# --- 18 Aug: CONCENTRATION, not just a percentile interval --------------------
# ⛔ The percentile CI is the WRONG summary for this distribution and it was making
#   the break look far worse located than it is. The draws are strongly UNIMODAL at
#   2015 with a long thin left tail: 23% of resamples scatter across 26 distinct
#   years, none holding more than 4%. A 5th-percentile cut therefore lands in the
#   tail (2000) and reports a 17-year "interval" across a region with almost no mass.
#   There is no secondary mode -- this is noise, not a rival break date.
# ⭐ Report the mode and the concentration instead. Both are computed here so the
#   chapter never has to retype them.
p_2015    <- mean(boot_block == 2015)
p_1416    <- mean(boot_block %in% 2014:2016)
p_1318    <- mean(boot_block %in% 2013:2018)
p_asympt  <- mean(boot_block %in% 2014:2018)   # coverage of the band the FIGURE draws
tail_pre13 <- mean(boot_block < 2013)
# narrowest CONTIGUOUS window that genuinely reaches 90%
.yy <- sort(unique(boot_block)); .best <- NULL
for (i in seq_along(.yy)) for (j in i:length(.yy)) {
  cv <- mean(boot_block >= .yy[i] & boot_block <= .yy[j])
  if (cv >= 0.90) { w <- .yy[j]-.yy[i]
    if (is.null(.best) || w < .best$w) .best <- list(w=w, lo=.yy[i], hi=.yy[j], cov=cv) } }
cat(sprintf("\n=== BOOTSTRAP CONCENTRATION (the honest summary) ===\n"))
cat(sprintf("P(2015)      = %.3f   <- modal by a factor of %.1f over the next year\n",
            p_2015, p_2015/sort(tb$Freq/BOOT, decreasing=TRUE)[2]))
cat(sprintf("P(2014-2016) = %.3f\nP(2013-2018) = %.3f\n", p_1416, p_1318))
cat(sprintf("P(2014-2018) = %.3f   <- ACTUAL coverage of the band Figure 2.16 draws\n", p_asympt))
cat(sprintf("left tail <2013 = %.3f over %d distinct years, max any one year %.3f\n",
            tail_pre13, length(unique(boot_block[boot_block<2013])),
            max(tb$Freq[tb$boot_year<2013])/BOOT))
cat(sprintf("narrowest genuine 90%% contiguous band = [%d, %d] (%d years, cov %.3f)\n",
            .best$lo, .best$hi, .best$w+1, .best$cov))
write.csv(tb[order(tb$boot_year),c("boot_year","Freq","prop")],
          file.path(OUT,"canonical_bootstrap_distribution.csv"), row.names=FALSE)
cat(sprintf("\n=== BLOCK-BOOTSTRAP break-date CI (L=%d, B=%d) ===\n", BLKL, BOOT))
cat(sprintf("point estimate = %d; bootstrap mode = %d\n", CS$peak_year, mode_year))
cat(sprintf("90%% CI (block) = [%d, %d];  (iid) = [%d, %d]\n", ci_block[1],ci_block[2],ci_iid[1],ci_iid[2]))
cat(sprintf("P(break=2016) = %.3f; P(break in 2015-2017) = %.3f\n", p_2016, p_1517))

# 3e. BAI-PERRON multiple-break selection (BIC), mean-shift model, h=0.15
ts_pc1 <- ts(yy, start=min(yr))
bp <- breakpoints(ts_pc1 ~ 1, h=0.15)
bp_years <- if(all(is.na(bp$breakpoints))) integer(0) else yr[bp$breakpoints]
bp_bic <- summary(bp)$RSS["BIC",]
cat(sprintf("\n=== BAI-PERRON (breakpoints ~1, h=0.15, BIC) ===\n"))
cat("BIC-selected break year(s):", if(length(bp_years)) paste(bp_years,collapse=", ") else "none", "\n")
cat("BIC by #breaks:\n"); print(round(bp_bic,2))

# 3f. SECONDARY (~2000) break?  Largest local peak of the canonical F-sweep in
#     the pre-2010 region, plus the 2-break Bai-Perron solution.
pre <- CS$curve[CS$curve$year <= 2010,]
sec_year <- pre$year[which.max(pre$F)]; sec_F <- max(pre$F)
bp2 <- yr[breakpoints(bp, breaks=2)$breakpoints]
cat(sprintf("\n=== SECONDARY break scan ===\n"))
cat(sprintf("Largest pre-2010 sup-F peak: %d (F = %.2f)\n", sec_year, sec_F))
cat("Bai-Perron 2-break solution:", paste(bp2, collapse=", "), "\n")

# ---- one machine-readable break-result table -------------------------------
break_res <- data.frame(
  metric = c("break_year_canonical","supF_level_trend_WALD","supF_level_trend_df2","supF_5pct_crit_df2",
             "perm_p_iid","perm_p_ar1_pooled_conservative","perm_p_ar1_seg_fair",
             "ar1_phi_pooled","ar1_phi_seg","meanshift_break_year","meanshift_supF_df1",
             "boot_ci90_lo_block","boot_ci90_hi_block","boot_ci90_lo_iid","boot_ci90_hi_iid",
             "boot_mode","P_break_2016","P_break_2015_2017",
             "P_break_2015","P_break_2014_2016","P_break_2013_2018",
             "coverage_of_figure_band_2014_2018","boot_tailmass_pre2013",
             "genuine90_band_lo","genuine90_band_hi",
             "baiperron_breaks","baiperron_2break_sol","secondary_pre2010_year","secondary_pre2010_F",
             "n","seed","nperm","nsim","boot_B","block_len"),
  value  = c(CS$peak_year, round(2*CS$peak_F,3), round(CS$peak_F,3), round(CS$crit_5pct,3),
             round(CS$perm_p,4), round(p_ar1_pooled,4), round(p_ar1_seg,4),
             round(phi_pool,3), round(phi_seg,3), MS$peak_year, round(MS$peak_F,3),
             ci_block[1], ci_block[2], ci_iid[1], ci_iid[2],
             mode_year, round(p_2016,4), round(p_1517,4),
             round(p_2015,4), round(p_1416,4), round(p_1318,4),
             round(p_asympt,4), round(tail_pre13,4), .best$lo, .best$hi,
             if(length(bp_years)) paste(bp_years,collapse=";") else "none",
             paste(bp2,collapse=";"), sec_year, round(sec_F,3),
             CS$n, SEED, NPERM, NSIM, BOOT, BLKL),
  stringsAsFactors=FALSE)
write.csv(break_res, file.path(OUT,"canonical_break_result.csv"), row.names=FALSE)

# ============================================================================
# 4. LEAVE-ONE-OUT across the six components
# ============================================================================
loo <- do.call(rbind, lapply(COMPS, function(drop){
  keep <- setdiff(COMPS, drop)
  p <- run_pca(panel, paste0(keep,"_z"))
  m <- merge(data.frame(year=p$years,pc1=p$pc1), data.frame(year=P$years,full=P$pc1), by="year")
  cs <- chow_sweep(year=p$years, y=p$pc1, trim=0.15, nperm=2000, seed=SEED)
  data.frame(dropped=drop, n=p$n, cor_with_full=round(cor(m$pc1,m$full),4),
             pc1_var_pct=round(100*p$var_exp[1],2),
             break_year=cs$peak_year, supF=round(cs$peak_F,2), perm_p=round(cs$perm_p,4),
             stringsAsFactors=FALSE)
}))
write.csv(loo, file.path(OUT,"canonical_leave_one_out.csv"), row.names=FALSE)
cat("\n=== LEAVE-ONE-OUT (drop each of the six) ===\n"); print(loo, row.names=FALSE)

# ============================================================================
# 5. COMPARISON TO THE OLD DEFEATS-BASED LIVE COMPOSITE
# ============================================================================
old <- read.csv(file.path(PCR,"turbulence_pca_1979_2025_FINAL.csv"), stringsAsFactors=FALSE)
old <- old[!is.na(old$PC1_index), c("year","PC1_index")]
mrg <- merge(data.frame(year=P$years, new=P$pc1), old, by="year")
r_old <- cor(mrg$new, mrg$PC1_index)
old_cs <- chow_sweep(year=old$year, y=old$PC1_index, trim=0.15, nperm=NPERM, seed=SEED)  # same canonical test
old_ms <- supF_meanshift(old$PC1_index, old$year)
old_load <- read.csv(file.path(PCR,"pca_loadings_FINAL.csv"), stringsAsFactors=FALSE)
cmp <- data.frame(
  composite = c("OLD (live, defeats-based)","NEW (canonical clean-six)"),
  components = c("pm_churn+defeats_py+rebellion_pct+elect_vol+spending_churn",
                 "elect_vol+pm_churn+rebellion_pct+dislocation+dept_churn+uturns"),
  pc1_var_pct = c(old_load$var_explained_PCn[1], round(100*P$var_exp[1],2)),
  break_year_leveltrend = c(old_cs$peak_year, CS$peak_year),
  supF_leveltrend = c(round(old_cs$peak_F,2), round(CS$peak_F,2)),
  perm_p_iid = c(round(old_cs$perm_p,4), round(CS$perm_p,4)),
  supF_meanshift = c(round(old_ms$peak_F,2), round(MS$peak_F,2)),
  r_new_vs_old = c(NA, round(r_old,4)),
  stringsAsFactors=FALSE)
write.csv(cmp, file.path(OUT,"canonical_vs_old_comparison.csv"), row.names=FALSE)
cat("\n=== NEW vs OLD (same canonical test) ===\n"); print(cmp, row.names=FALSE)
cat(sprintf("\nPearson r(new PC1, old live PC1), %d common years = %.4f\n", nrow(mrg), r_old))

# ============================================================================
# 6. FIGURES (house style)
# ============================================================================
# 6a. canonical 2-panel Chow figure via the standardised helper
try(chow_panel_figure(CS, series_label="Canonical turbulence composite (clean six), 1979-2024",
      y_label="PC1 turbulence index (higher = more turbulent)",
      source_note="Level+trend sup-F (df1=2), canonical chow_sweep. Clean-five composite.",
      outfile=file.path(OUT,"fig_canonical_chow.png")), silent=TRUE)

# 6b. PC1 with break line + 90% bootstrap band, new vs old overlay
png(file.path(OUT,"fig_canonical_pc1.png"), width=1200, height=720, res=130)
par(mar=c(4.5,4.5,3.6,1))
plot(series$year, series$PC1_index, type="o", pch=19, col="#1F3864", lwd=2,
     xlab="Year", ylab="PC1 turbulence index (higher = more turbulent)",
     main="Canonical turbulence composite (clean six), PC1 1979-2024")
rect(ci_block[1], par("usr")[3], ci_block[2], par("usr")[4], col="#d7191c18", border=NA)
abline(v=CS$peak_year, lty=2, col="#d7191c", lwd=2)
lines(mrg$year, mrg$PC1_index, col="#999999", lwd=1.6, lty=3)
legend("topleft", bty="n", cex=0.85,
  legend=c("Canonical clean-six PC1", "OLD live composite PC1",
           paste0("Canonical break ",CS$peak_year),
           sprintf("90%% bootstrap band [%d-%d]",ci_block[1],ci_block[2])),
  col=c("#1F3864","#999999","#d7191c","#d7191c88"), lty=c(1,3,2,1), lwd=c(2,1.6,2,6))
dev.off()

# ============================================================================
# 7. FREEZE — save full run object
# ============================================================================
saveRDS(list(pca=P, chow=CS, meanshift=MS,
             p_ar1_pooled=p_ar1_pooled, p_ar1_seg=p_ar1_seg,
             ar1=list(phi_pool=phi_pool, phi_seg=phi_seg, sd_pool=sd_pool, sd_seg=sd_seg),
             boot_block=boot_block, boot_iid=boot_iid,
             ci_block=ci_block, ci_iid=ci_iid, mode_year=mode_year,
             p_2016=p_2016, p_1517=p_1517,
             baiperron=bp_years, baiperron_2=bp2, bp_bic=bp_bic,
             secondary=c(year=sec_year,F=sec_F),
             loo=loo, comparison=cmp, r_vs_old=r_old,
             seed=SEED, years=YEARS, comps=COMPS, load=load_tab, var=var_tab,
             break_result=break_res),
        file.path(OUT,"canonical_run_summary.rds"))

cat("\n=== DONE. Canonical composite frozen to", OUT, "===\n")
sink()
