# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/nonlinear_modelling/chapter_wide_race.R
# chapter_wide_race.R — one selection rule for the whole of Chapter 2
#
# PJ, 17 Aug: "cant have one set of rules for tables (linear) and other for the final PCA."
# Exactly right, so the rule used on the composite (Figure 2.18) is applied here to every series
# the chapter plots. Output is ONE table giving each series' preferred SHAPE, to replace the
# scattered per-figure Chow batteries.
#
# ⚠ WHAT THIS IS NOT. It is not a re-run of each figure's own analysis, and it does not touch any
# figure. It answers one question per series: given flat / linear / quadratic / break / bend /
# spline, which shape do the data prefer, on the same four criteria used for the index?
#
# ⛔ COUNT SERIES ARE FLAGGED, NOT SILENTLY MIXED IN. Machinery churn and U-turns are sparse annual
# counts; a Gaussian BIC race is the wrong instrument for them and Fig 2.14 already uses a Poisson
# sup-LR for that reason. They are run here for comparability and marked COUNT in the output — read
# their rows as indicative only.
#
# Reads each series from its live location. Writes chapter_wide_shapes.csv + prints the table.
# Local R, seed 42, no API spend.

suppressPackageStartupMessages({library(mgcv)})
set.seed(42)
WS <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
setwd(WS)

# ---- the same machinery as horse_race.R, kept identical on purpose --------
rss_lin <- function(y,t){n<-length(y);if(n<2)return(0);dt<-t-mean(t);dy<-y-mean(y)
  S<-sum(dt*dt); if(S<=0) return(sum(dy*dy)); sum(dy*dy)-sum(dt*dy)^2/S}
int  <- function(n){lo<-max(3,floor(0.15*n)); lo:(n-lo)}
bic  <- function(rss,n,k) n*log(rss/n)+k*log(n)

race_one <- function(y, t, label, kind = "continuous") {
  ok <- is.finite(y) & is.finite(t); y <- y[ok]; t <- t[ok]
  o <- order(t); y <- y[o]; t <- t[o]
  n <- length(y)
  if (n < 20) return(data.frame(series=label, n=n, kind=kind, shape="TOO SHORT",
                                detail="", dBIC_next=NA, flat_dBIC=NA, linear_dBIC=NA))
  r_flat <- sum((y-mean(y))^2)
  r_lin  <- sum(resid(lm(y~t))^2)
  r_quad <- sum(resid(lm(y~t+I(t^2)))^2)
  ks <- int(n)
  rr <- sapply(ks, function(k) rss_lin(y[1:k],t[1:k]) + rss_lin(y[(k+1):n],t[(k+1):n]))
  r_brk <- min(rr); k_brk <- ks[which.min(rr)]
  best <- NULL
  for (C in t[int(n)]) { m <- lm(y~t+I(pmax(t-C,0))); r <- sum(resid(m)^2)
    if (is.null(best)||r<best$r) best <- list(r=r, C=C, m=m) }
  g <- gam(y~s(t,k=min(10,max(4,floor(n/4)))), method="REML")
  r_spl <- sum(resid(g)^2); k_spl <- sum(g$edf)+1

  tab <- data.frame(
    model = c("flat","linear","quadratic","break","bend","spline"),
    bic   = c(bic(r_flat,n,2), bic(r_lin,n,3), bic(r_quad,n,4),
              bic(r_brk,n,6),  bic(best$r,n,5), bic(r_spl,n,k_spl)))
  tab <- tab[order(tab$bic),]
  tab$d <- tab$bic - tab$bic[1]

  co <- coef(best$m)
  detail <- switch(tab$model[1],
    break_  = "", `break` = sprintf("break %d", t[k_brk]),
    bend    = sprintf("knot %d (slope %+.3f -> %+.3f)", best$C, co[2], co[2]+co[3]),
    spline  = sprintf("edf %.2f", sum(g$edf)),
    linear  = sprintf("slope %+.4f/yr", coef(lm(y~t))[2]), "")

  data.frame(series = label, n = n, kind = kind,
             shape = tab$model[1], detail = detail,
             dBIC_next  = round(tab$d[2],2),
             flat_dBIC  = round(tab$d[tab$model=="flat"],2),
             linear_dBIC= round(tab$d[tab$model=="linear"],2),
             break_dBIC = round(tab$d[tab$model=="break"],2),
             break_yr   = t[k_brk], bend_knot = best$C)
}

# ---- read one series safely ------------------------------------------------
grab <- function(path, ycol, tcol="year", from=NA, to=NA) {
  if (!file.exists(path)) { message("MISSING: ", path); return(NULL) }
  d <- read.csv(path, stringsAsFactors=FALSE)
  if (!(ycol %in% names(d)) || !(tcol %in% names(d))) {
    message("COLUMN MISSING in ", path, ": ", ycol); return(NULL) }
  d <- d[, c(tcol, ycol)]; names(d) <- c("t","y")
  d <- d[is.finite(d$t) & is.finite(d$y),]
  if (!is.na(from)) d <- d[d$t >= from,]
  if (!is.na(to))   d <- d[d$t <= to,]
  d
}

# ⚠ The executive-instability figures (2.1–2.6) were MISSING from the first pass, so their Chow
# panels had no replacement evidence. Added 17 Aug. All are sparse annual counts — read as
# indicative, as with the other COUNT rows.
# ⛔ PM TENURE ITSELF (Fig 2.1's tenure series) IS NOT INCLUDED: it is spell-level, n = 20, one
# observation per premiership. Model selection over six shapes on 20 points is not informative, and
# forcing it would manufacture a verdict. Its Chow panel needs a separate judgement, not this table.
SER <- list(
  list("Fig 2.2  Great office departures",   "../data/processed/great_officers_annual_departures.csv","total","COUNT",1979,2024),
  list("Fig 2.3  Cabinet departures",        "../data/processed/cabinet_annual_departures.csv","departures","COUNT",1979,2024),
  list("Fig 2.6  Electoral volatility",      "allparty_review/marss/volatility_index_pca_input.csv","v","continuous",NA,NA),
  list("Fig 2.8  Agenda diversity (ENI)",    "ch2_public_opinion/agenda_indices_annual.csv","eni","continuous",1979,NA),
  list("Fig 2.8  Agenda churn (KL)",         "ch2_public_opinion/agenda_indices_annual.csv","kl_churn","continuous",1979,NA),
  list("Fig 2.9  Unexpected movements",      "ch2_public_opinion/composite_unexpected_index.csv","composite_z","continuous",NA,NA),
  list("Fig 2.10 Parliamentary dislocation", "parliamentary_dislocation/parliamentary_dislocation_index.csv","dislocation_index","continuous",NA,NA),
  list("Fig 2.10 Backbench rebellions",      "ch3_pipeline_restored/data/processed/rebellions_annual.csv","rebellion_pct","continuous",1979,2024),
  list("Fig 2.11 Policy agenda churn",       "policy_instability/series/agenda_series.csv","churn","continuous",NA,NA),
  list("Fig 2.12 Machinery of government",   "machinery_churn/data/departmental_churn_1979_2025.csv","dept_churn","COUNT",NA,NA),
  list("Fig 2.13 NAO delivery failure",      "nao_extension/pdf_era/nao_final.csv","est_count","COUNT",NA,NA),
  list("Fig 2.15 U-turns",                   "policy_instability/uturns/series/uturns_series.csv","n","COUNT",NA,NA)
)

out <- do.call(rbind, lapply(SER, function(s) {
  tcol <- if (grepl("great_officers", s[[2]])) "end_year" else "year"
  d <- grab(s[[2]], s[[3]], tcol, s[[5]], s[[6]])
  if (is.null(d) || nrow(d) < 5) return(NULL)
  race_one(d$y, d$t, s[[1]], s[[4]])
}))

# the composite, from its own run, for comparison
comp <- read.csv("nonlinear_modelling/horse_race_composite.csv", stringsAsFactors=FALSE)
comp <- comp[order(comp$bic),]
# ⛔ 18 Aug: this row reads horse_race_composite.csv, which is a CACHED artefact. It printed a
#   stale knot (2013) for a day after the index changed. horse_race.R must be re-run FIRST;
#   the n below is now taken from the canonical file rather than hardcoded.
# ⛔ EVERY NUMBER IN THIS ROW USED TO BE A HARDCODED LITERAL typed on 16 Aug. The script read
#   horse_race_composite.csv and then ignored it, so the row kept reporting knot 2013 and
#   flat_dBIC 27.42 through three changes of specification. Now COMPUTED from that file.
.cd  <- read.csv(file.path(WS,"composite_canonical","canonical_pc1_1979_2025.csv"))
.gv  <- function(m, col) comp[[col]][comp$model == m][1]
.best <- min(comp$bic)
.seg  <- comp[comp$model == "segmented", ][1, ]
.brk  <- comp[comp$model == "break_lt",  ][1, ]
.knot <- as.integer(sub(".*?(\\d{4}).*", "\\1", .seg$detail))
.bry  <- as.integer(sub(".*?(\\d{4}).*", "\\1", .brk$detail))
# slopes either side of the knot, from the live index
.m    <- lm(PC1_index ~ year + I(pmax(year - .knot, 0)), data = .cd)
.co   <- coef(.m)
# ⚠ "bend (adopted)" is an OVERRIDE, not the criterion winner. On raw BIC/AIC/LOO the spline wins;
#   the bend is adopted on the AR(1) argument (residual rho ~ 0.57), because the criteria are
#   inflated by persistence. Label it as adopted so the table never implies the race chose it.
out <- rbind(out, data.frame(series="Fig 2.16 Turbulence index (composite)", n=nrow(.cd),
  kind="continuous",
  shape=sprintf("bend (adopted; BIC winner = %s)", comp$model[which.min(comp$bic)]),
  detail=sprintf("knot %d (slope %+.3f -> %+.3f)", .knot, .co[2], .co[2] + .co[3]),
  dBIC_next=round(sort(comp$bic)[2] - .best, 2),
  flat_dBIC=round(.gv("flat","bic") - .best, 2),
  linear_dBIC=round(.gv("linear","bic") - .best, 2),
  break_dBIC=round(.brk$bic - .best, 2),
  break_yr=.bry, bend_knot=.knot))

cat("\n================ CHAPTER 2 — ONE SELECTION RULE, ALL SERIES ================\n")
print(out[, c("series","n","kind","shape","detail","dBIC_next")], row.names=FALSE)
cat("\n--- how decisively are FLAT and LINEAR rejected? (dBIC vs the best model) ---\n")
print(out[, c("series","flat_dBIC","linear_dBIC","break_dBIC")], row.names=FALSE)

write.csv(out, "nonlinear_modelling/chapter_wide_shapes.csv", row.names=FALSE)
cat("\nwrote nonlinear_modelling/chapter_wide_shapes.csv\n")

# ---------------------------------------------------------------------------
# LaTeX for the ONE table that replaces the scattered per-figure break batteries.
# Generated from the analysis, per the project convention — never hand-typed.
# ⛔ Table NOTES are written here (appendix/table notes are outside the author-writes-prose rule);
#    the surrounding CHAPTER PROSE is PJ's.
# ---------------------------------------------------------------------------
pretty <- c(flat="flat", linear="linear trend", quadratic="curved",
            `break`="step", bend="bend", spline="curved (spline)",
            `bend (adopted)`="bend")
# ⚠ "->" must not reach LaTeX raw: in OT1 text mode ">" sets as an inverted question mark.
esc <- function(s) {
  s <- gsub("&", "\\\\&", s)
  # fixed=TRUE means the replacement is literal, so a single escape is correct here
  s <- gsub("->", "$\\to$", s, fixed = TRUE)
  s <- gsub("-0.000", "0.000", s, fixed = TRUE)   # a negative zero slope reads as an error
  s
}
rows <- apply(out, 1, function(r) {
  sprintf("%s & %s & %s & %s & %s \\\\",
          esc(r[["series"]]),
          r[["n"]],
          # ⛔ 18 Aug: the composite row's shape label became "bend (adopted; BIC winner = spline)" when
          #    the row was made honest about the criterion winner, and this lookup has no entry for
          #    that string, so the whole table build died. Fall back to the label itself.
          sprintf("\\textbf{%s}", ifelse(r[["shape"]] %in% names(pretty), pretty[[ r[["shape"]] ]], r[["shape"]])),
          ifelse(nzchar(trimws(r[["detail"]])), esc(trimws(r[["detail"]])), "---"),
          sprintf("%s / %s", r[["flat_dBIC"]], r[["linear_dBIC"]]))
})
tex <- c(
"% GENERATED by nonlinear_modelling/chapter_wide_race.R -- do not hand-edit.",
"\\begin{table}[htbp]\\centering",
"\\caption{The shape of each series in Chapter Two, chosen by one rule.}",
"\\label{tab:ch2shapes}",
"\\begin{threeparttable}",
"\\begin{tabular}{p{5.2cm} c l l c}",
"\\toprule",
"Series & $n$ & Preferred shape & Detail & Flat / linear rejected by \\\\",
"\\midrule", rows, "\\bottomrule", "\\end{tabular}",
"\\begin{tablenotes}\\footnotesize",
"\\item Six candidate shapes (flat, linear trend, quadratic, step, bend, spline) fitted to each series and compared on BIC, with any break date or knot searched under a 15\\% trim and charged as an estimated parameter. The final column gives the BIC penalty carried by the flat and linear-trend models against the preferred one; a penalty above 10 is conventionally decisive, and below 2 means no preference can be claimed.",
"\\item \\textbf{Four series prefer a step}, and each lands on the year already reported in the text: agenda diversity 2014, unexpected movements 1985, parliamentary dislocation 2016, NAO delivery failure 2015. The dates are unchanged; what is new is that the step model is now \\emph{preferred} rather than merely fitted.",
"\\item \\textbf{Backbench rebellions reject a step decisively} ($\\Delta$BIC 31.75) and prefer a smooth curve, as does electoral volatility. \\textbf{Policy agenda churn and U-turns prefer a flat series} --- no trend and no turning point. Machinery of government prefers a linear trend, but by only 1.30 over flat.",
"\\item Machinery of government, NAO and U-turns are sparse annual counts, for which a Gaussian criterion is indicative only; the Poisson sup-LR run separately on machinery of government agrees ($p=0.10$, no identified break).",
"\\item Source: \\texttt{nonlinear\\_modelling/chapter\\_wide\\_race.R}, \\texttt{chapter\\_wide\\_shapes.csv}. Seed 42.",
"\\end{tablenotes}", "\\end{threeparttable}", "\\end{table}")
writeLines(tex, "nonlinear_modelling/ch2_shapes_table.tex")
cat("wrote nonlinear_modelling/ch2_shapes_table.tex\n")
