# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/nonlinear_modelling/full_model_comparison.R
# full_model_comparison.R — the "everything" index, for the appendix only.
#
# PJ, 17 Aug: "dropping variables out is fine and we will have the lasso at the end... I'd prefer
# to work with a leaner index and I want to lock down the specification we have as it is closer to
# theory and works for the book... But report in appendix a full model for comparison."
#
# ⛔ THIS IS NOT A CANDIDATE SPECIFICATION. It exists so the appendix can answer the selection
# question with a number instead of a paragraph: if the lean index and the everything index agree,
# the exclusions did not manufacture the finding.
#
# The lean six (LOCKED): elect_vol, exec_instab, dislocation, dept_churn, uturns, unexpected
# ⚠ CORRECTED 14 Sep 2026: this list previously said "rebellion_pct" in place of "unexpected" —
# stale since the 1 Sep composite re-freeze superseded rebellion_pct with dislocation and promoted
# unexpected into the locked six (see [[wkbd-composite-stale-canonical]]). A 1 Sep session already
# found and fixed this exact bug once, but the fix evidently never persisted to this file — it was
# broken again (rebellion_pct doesn't exist in canonical_pc1_1979_2025.csv's current schema) when
# checked today. Fixed properly this time: LEAN now matches the CSV's actual six columns exactly.
# Added here, and ONLY here (now that unexpected is IN the locked six, it's no longer a FULL-only
# addition — removed from this list accordingly, see FULL below):
#   eni         — tested 17 Aug, loads +0.455, never tested before
#   churn       — TESTED AND REJECTED 16 Aug (loading -0.075). Included deliberately: it is the
#                 component whose exclusion the selection worry is actually about.
set.seed(42)
WS <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
d  <- read.csv(file.path(WS,"composite_canonical/canonical_pc1_1979_2025.csv"))
ag <- read.csv(file.path(WS,"policy_instability/series/agenda_series.csv"))
ux <- read.csv(file.path(WS,"ch2_public_opinion/composite_unexpected_index.csv"))

d$eni        <- ag$eni[match(d$year, ag$year)]
d$churn      <- ag$churn[match(d$year, ag$year)]
d$unexpected <- ux$composite_z[match(d$year, ux$year)]

LEAN <- c("elect_vol","exec_instab","dislocation","dept_churn","uturns","unexpected")
FULL <- c(LEAN, "eni","churn")

fit <- function(cols, label) {
  ok <- complete.cases(d[, cols]); m <- as.matrix(d[ok, cols]); t <- d$year[ok]
  p <- prcomp(m, center=TRUE, scale.=TRUE); s <- if (mean(p$rotation[,1])<0) -1 else 1
  y <- as.numeric(p$x[,1])*s
  int <- function(n){lo<-max(3,floor(.15*n)); lo:(n-lo)}
  best <- NULL
  for (C in t[int(length(y))]) { mm <- lm(y~t+I(pmax(t-C,0))); r <- sum(resid(mm)^2)
    if (is.null(best)||r<best$r) best <- list(r=r,C=C,m=mm) }
  co <- coef(best$m); n <- length(y)
  bic <- function(rss,k) n*log(rss/n)+k*log(n)
  cat(sprintf("\n=== %s ===\n", label))
  cat(sprintf("  k = %d components, n = %d (%d-%d), PC1 var %.1f%%\n",
              length(cols), n, min(t), max(t), 100*p$sdev[1]^2/sum(p$sdev^2)))
  cat(sprintf("  knot %d | slope %+.4f -> %+.4f | flat worse by %.1f BIC | linear worse by %.1f BIC\n",
              best$C, co[2], co[2]+co[3],
              bic(sum((y-mean(y))^2),2)-bic(best$r,5), bic(sum(resid(lm(y~t))^2),3)-bic(best$r,5)))
  print(round(sort(p$rotation[,1]*s, decreasing=TRUE), 3))
  list(y=y, t=t, C=best$C)
}

a <- fit(LEAN, "LEAN SIX — the locked specification (main text)")
b <- fit(FULL, "FULL MODEL — everything tested, nothing excluded (appendix only)")

sh <- intersect(a$t, b$t)
cat(sprintf("\n⭐ r(lean index, full index) on the %d shared years = %.4f\n",
            length(sh), cor(a$y[a$t %in% sh], b$y[b$t %in% sh])))
cat(sprintf("   knot: lean %d, full %d\n", a$C, b$C))
