# COPY — generated by build_repo_mirror.R. Do not edit here. Working copy: data_workspace_2026-07/nonlinear_modelling/horse_race.R
# ============================================================
# horse_race.R — model comparison for the turbulence composite
#
# QUESTION (PJ, 16 Aug): the break/Chow apparatus assumes the series takes a
# STEPPED form. Does the data prefer a step, or a smooth rise? Decide it on a
# criterion rather than on argument.
#
# FIVE MODELS, same response, same n, same estimator family:
#   M0 flat        y = a                                    k = 2
#   M1 linear      y = a + b t                              k = 3
#   M2 quadratic   y = a + b t + c t^2                      k = 4
#   M3 break       y = a1 + b1 t (t<=K); a2 + b2 t (t>K)    k = 6   (K searched)
#   M4 segmented   y = a + b1 t + b2 (t-C)+                 k = 5   (C searched)
#   M5 spline      y = a + s(t), thin-plate, mgcv           k = edf + 1
#
# k counts EVERY estimated quantity including sigma and the searched break
# date / knot. BIC = n*log(RSS/n) + k*log(n), computed identically for all five
# so the numbers are comparable.
#
# FOUR CRITERIA, because no single one settles it:
#   (a) AIC          — lenient, favours flexibility
#   (b) BIC          — the criterion PJ asked for
#   (c) LOO-CV RMSE  — the break date / knot is RE-SEARCHED INSIDE EACH FOLD, so
#                      the break model is charged honestly for its search. This
#                      is the criterion that does not depend on a parameter-
#                      counting convention, and is the tie-breaker.
#   (d) AR(1)-error BIC — annual series are autocorrelated; the whole
#                      break-vs-trend literature (Perron vs its critics) turns
#                      on whether the "break" is serial correlation in disguise.
#
# The break model follows chow_standardized/chow_test.R exactly: level+trend
# split (p = 2), 15% interior trim, min 3 obs per segment.
#
# Also runs the same race on each of the six COMPONENT z-series, to test
# whether any verdict is general or specific to the composite.
#
# Reads : composite_canonical/canonical_pc1_1979_2025.csv  (clean six, 18 Aug; window now 1979-2025 -
#         the FILENAME is a legacy misnomer and is deliberately left alone until the whole
#         chapter is renamed, so that references do not break mid-lockdown)
# Writes: nonlinear_modelling/{horse_race_composite,horse_race_components,
#         fit_predictions}.csv, fig_horse_race.png, run.log
# NO API SPEND. Seed 42.
# ============================================================

suppressPackageStartupMessages({
  library(mgcv); library(nlme); library(ggplot2); library(patchwork)
})
set.seed(42)

WS <- local({
  a <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", a, value = TRUE)
  if (length(m) == 1) normalizePath(file.path(dirname(sub("^--file=", "", m)), "..")) else getwd()
})
OUT  <- file.path(WS, "nonlinear_modelling")
TRIM <- 0.15
MINSEG <- 3

d <- read.csv(file.path(WS, "composite_canonical", "canonical_pc1_1979_2025.csv"),
              stringsAsFactors = FALSE)

# ---- CONTROL: the input must be the clean six, n = 46, 1979-2025 -----------
# ⚠ 18 Aug: window extended to 2025 (dept_churn 2025 = 0, verified) and rebellions dropped.
stopifnot(nrow(d) == 47, min(d$year) == 1979, max(d$year) == 2025)   # 18 Aug: n=47, 1981 interpolated
cat(sprintf("INPUT: canonical PC1, n = %d, %d-%d\n", nrow(d), min(d$year), max(d$year)))

# ---------- helpers ---------------------------------------------------------
rss_lin <- function(y, t) {                     # closed-form RSS of y ~ t
  n <- length(y); if (n < 2) return(0)
  dt <- t - mean(t); dy <- y - mean(y)
  Sxx <- sum(dt * dt); if (Sxx <= 0) return(sum(dy * dy))
  sum(dy * dy) - sum(dt * dy)^2 / Sxx
}

interior <- function(n) {                        # candidate split indices
  lo <- max(MINSEG, floor(TRIM * n)); hi <- n - lo
  lo:hi
}

# --- M3: discontinuous level+trend break, K searched by min RSS -------------
fit_break <- function(y, t) {
  ks <- interior(length(y))
  r  <- sapply(ks, function(k) rss_lin(y[1:k], t[1:k]) +
                               rss_lin(y[(k+1):length(y)], t[(k+1):length(y)]))
  k  <- ks[which.min(r)]
  n  <- length(y)
  f1 <- lm(y[1:k] ~ t[1:k]); f2 <- lm(y[(k+1):n] ~ t[(k+1):n])
  fitted <- c(predict(f1), predict(f2))
  list(rss = min(r), k = 6L, split = k, fitted = fitted)
}

# --- M4: CONTINUOUS piecewise linear (a bend, not a jump), C searched -------
fit_segmented <- function(y, t) {
  cs <- t[interior(length(y))]
  best <- NULL
  for (C in cs) {
    m <- lm(y ~ t + I(pmax(t - C, 0)))
    r <- sum(resid(m)^2)
    if (is.null(best) || r < best$rss) best <- list(rss = r, C = C, fit = m)
  }
  list(rss = best$rss, k = 5L, knot = best$C, fitted = fitted(best$fit))
}

fit_gam <- function(y, t) {
  g <- gam(y ~ s(t, k = 10), method = "REML")
  list(rss = sum(resid(g)^2), k = sum(g$edf) + 1, fitted = fitted(g), obj = g)
}

# --- criteria ---------------------------------------------------------------
bic <- function(rss, n, k) n * log(rss / n) + k * log(n)
aic <- function(rss, n, k) n * log(rss / n) + 2 * k

# --- LOO-CV: the search happens INSIDE the fold -----------------------------
loo_rmse <- function(y, t, which_model) {
  n <- length(y); err <- numeric(n)
  for (i in seq_len(n)) {
    yi <- y[-i]; ti <- t[-i]
    p <- switch(which_model,
      flat      = mean(yi),
      linear    = { m <- lm(yi ~ ti);              predict(m, data.frame(ti = t[i])) },
      quadratic = { m <- lm(yi ~ ti + I(ti^2));    predict(m, data.frame(ti = t[i])) },
      break_lt  = {
        ks <- interior(length(yi))
        r  <- sapply(ks, function(k) rss_lin(yi[1:k], ti[1:k]) +
                                     rss_lin(yi[(k+1):length(yi)], ti[(k+1):length(yi)]))
        k  <- ks[which.min(r)]
        if (t[i] <= ti[k]) { m <- lm(yi[1:k] ~ ti[1:k]) } else {
          m <- lm(yi[(k+1):length(yi)] ~ ti[(k+1):length(yi)]) }
        as.numeric(coef(m)[1] + coef(m)[2] * t[i])
      },
      segmented = {
        cs <- ti[interior(length(yi))]; best <- NULL
        for (C in cs) { m <- lm(yi ~ ti + I(pmax(ti - C, 0))); r <- sum(resid(m)^2)
          if (is.null(best) || r < best$rss) best <- list(rss = r, C = C, fit = m) }
        as.numeric(predict(best$fit, data.frame(ti = t[i])))
      },
      spline    = { g <- gam(yi ~ s(ti, k = 10), method = "REML")
                    as.numeric(predict(g, data.frame(ti = t[i]))) })
    err[i] <- y[i] - p
  }
  sqrt(mean(err^2))
}

# --- AR(1)-error refit (does the preference survive serial correlation?) ----
ar1_bic <- function(y, t, which_model, split = NULL, knot = NULL) {
  df <- data.frame(y = y, t = t)
  f <- switch(which_model,
    flat      = y ~ 1,
    linear    = y ~ t,
    quadratic = y ~ t + I(t^2),
    break_lt  = { df$post <- as.integer(seq_along(y) > split); y ~ post * t },
    segmented = { df$seg <- pmax(t - knot, 0); y ~ t + seg },
    spline    = NULL)
  if (is.null(f)) return(NA_real_)
  m <- tryCatch(gls(f, data = df, correlation = corAR1(form = ~ t), method = "ML"),
                error = function(e) NULL)
  if (is.null(m)) return(NA_real_)
  as.numeric(BIC(m))
}

# ---------- run the race on one series --------------------------------------
race <- function(y, t, label, keep_fits = FALSE) {
  n <- length(y)
  m0 <- list(rss = sum((y - mean(y))^2), k = 2L, fitted = rep(mean(y), n))
  l1 <- lm(y ~ t);            m1 <- list(rss = sum(resid(l1)^2), k = 3L, fitted = fitted(l1))
  l2 <- lm(y ~ t + I(t^2));   m2 <- list(rss = sum(resid(l2)^2), k = 4L, fitted = fitted(l2))
  m3 <- fit_break(y, t)
  m4 <- fit_segmented(y, t)
  m5 <- fit_gam(y, t)

  ms   <- list(flat = m0, linear = m1, quadratic = m2,
               break_lt = m3, segmented = m4, spline = m5)
  keys <- names(ms)

  res <- data.frame(
    series = label,
    model  = keys,
    k      = sapply(ms, function(m) round(m$k, 2)),
    rss    = sapply(ms, function(m) m$rss),
    aic    = sapply(ms, function(m) aic(m$rss, n, m$k)),
    bic    = sapply(ms, function(m) bic(m$rss, n, m$k)),
    loo    = sapply(keys, function(kk) loo_rmse(y, t, kk)),
    ar1bic = sapply(keys, function(kk)
               ar1_bic(y, t, kk, split = m3$split, knot = m4$knot)),
    detail = c("", "", "",
               sprintf("break at %d", t[m3$split]),
               sprintf("knot at %d",  m4$knot),
               sprintf("edf %.2f", sum(m5$obj$edf))),
    stringsAsFactors = FALSE, row.names = NULL)

  res$dBIC <- round(res$bic - min(res$bic), 2)
  res$dAIC <- round(res$aic - min(res$aic), 2)
  res$dLOO <- round(res$loo - min(res$loo), 4)

  if (keep_fits) attr(res, "fits") <- ms
  res
}

# ============================== COMPOSITE ==================================
y <- d$PC1_index; t <- d$year
comp <- race(y, t, "PC1 composite (clean six)", keep_fits = TRUE)
fits <- attr(comp, "fits")

cat("\n================ HORSE RACE — CANONICAL PC1 ================\n")
print(comp[, c("model","k","rss","aic","bic","loo","ar1bic","detail","dBIC","dLOO")],
      row.names = FALSE, digits = 5)
cat(sprintf("\nBIC winner : %s\n", comp$model[which.min(comp$bic)]))
cat(sprintf("AIC winner : %s\n", comp$model[which.min(comp$aic)]))
cat(sprintf("LOO winner : %s\n", comp$model[which.min(comp$loo)]))
cat(sprintf("AR(1) BIC winner : %s\n",
            comp$model[which.min(replace(comp$ar1bic, is.na(comp$ar1bic), Inf))]))

# --- residual autocorrelation of the trend fit ------------------------------
r1 <- resid(lm(y ~ t))
cat(sprintf("\nAR(1) rho in linear-trend residuals: %.3f  (Box-Ljung p = %.3f)\n",
            as.numeric(acf(r1, plot = FALSE)$acf[2]),
            Box.test(r1, lag = 1, type = "Ljung-Box")$p.value))

# --- how much does the break buy over the bend? -----------------------------
cat(sprintf("\nRSS: linear %.2f -> segmented %.2f (%.1f%%) -> break %.2f (%.1f%%)\n",
            fits$linear$rss, fits$segmented$rss,
            100*(1 - fits$segmented$rss/fits$linear$rss),
            fits$break_lt$rss, 100*(1 - fits$break_lt$rss/fits$linear$rss)))

# ============================== COMPONENTS =================================
# ⛔ WAS A HARDCODED LIST, AND IT WENT STALE TWICE. On 17 Aug it still named `pm_churn_z` after
#   that component was swapped out, and the script died silently while printing an earlier run's
#   CSV that looked perfectly fine. On 18 Aug it still named `rebellion_pct_z` after rebellions was
#   dropped, and omitted `unexpected_z` entirely.
# ✅ Now DERIVED from the canonical file, so the component set cannot drift from the index again.
zc <- grep("_z$", names(d), value = TRUE)
stopifnot(length(zc) >= 3)
cat("components read from the canonical index:", paste(sub("_z$","",zc), collapse=", "), "\n")
comps <- do.call(rbind, lapply(zc, function(v) race(d[[v]], t, v)))

cat("\n================ SAME RACE, SIX COMPONENTS ================\n")
win <- do.call(rbind, lapply(split(comps, comps$series), function(s) data.frame(
  series = s$series[1],
  BIC    = s$model[which.min(s$bic)],
  LOO    = s$model[which.min(s$loo)],
  break_date = s$detail[s$model == "break_lt"],
  dBIC_break_vs_best = round(s$bic[s$model=="break_lt"] - min(s$bic), 2),
  stringsAsFactors = FALSE)))
print(win, row.names = FALSE)

# ============================== OUTPUTS ====================================
write.csv(comp[, setdiff(names(comp), "")], file.path(OUT, "horse_race_composite.csv"),
          row.names = FALSE)
write.csv(comps, file.path(OUT, "horse_race_components.csv"), row.names = FALSE)

pred <- data.frame(year = t, observed = y,
                   linear = fits$linear$fitted, quadratic = fits$quadratic$fitted,
                   break_lt = fits$break_lt$fitted, segmented = fits$segmented$fitted,
                   spline = fits$spline$fitted)
write.csv(pred, file.path(OUT, "fit_predictions.csv"), row.names = FALSE)

# ---------- figure: greyscale house style, DIAGNOSTIC not for the book ------
base <- theme_minimal(base_size = 9) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(colour = "grey90", linewidth = 0.3),
        plot.title = element_text(face = "bold", size = 9.5, hjust = 0))

long <- reshape(pred[, c("year","linear","break_lt","segmented","spline")],
                direction = "long", varying = list(2:5), v.names = "fit",
                timevar = "model", times = c("linear","break","segmented","spline"),
                idvar = "year")

pA <- ggplot() +
  geom_hline(yintercept = 0, colour = "grey85", linewidth = 0.3) +
  geom_line(data = pred, aes(year, observed), colour = "grey65", linewidth = 0.4) +
  geom_point(data = pred, aes(year, observed), colour = "grey55", size = 0.7) +
  geom_line(data = long, aes(year, fit, linetype = model), colour = "grey10",
            linewidth = 0.6) +
  scale_linetype_manual(values = c(linear = "solid", break_ = "42",
                                   `break` = "42", segmented = "22", spline = "1343"),
                        name = NULL) +
  labs(title = "A. The four candidate fits on the same series",
       x = NULL, y = "PC1 index") + base + theme(legend.position = "bottom")

cw <- comp[comp$model != "flat", ]
cw$model <- factor(cw$model, levels = cw$model[order(cw$bic)])
pB <- ggplot(cw, aes(model, dBIC)) +
  geom_col(width = 0.6, fill = "grey30") +
  geom_hline(yintercept = 2, colour = "grey55", linetype = "22", linewidth = 0.35) +
  labs(title = "B. BIC penalty relative to the best model (lower is better)",
       x = NULL, y = "delta BIC") + base

ggsave(file.path(OUT, "fig_horse_race.png"), (pA / pB) + plot_layout(heights = c(1.6, 1)),
       width = 6.8, height = 6.2, dpi = 300, bg = "white")

cat("\nWritten to nonlinear_modelling/: horse_race_composite.csv, horse_race_components.csv, fit_predictions.csv, fig_horse_race.png\n")
